C; model_eva_score=0.084, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_compro4.pdb1
structureX:meta_compro4.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C; model_eva_score=0.084, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C; model_eva_score=0.084, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C; model_eva_score=0.083, tm_score=0.8349, gdt_score=0.7247, maxsub=0.6859.
>P1;meta_msaprobs4.pdb1
structureX:meta_msaprobs4.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C; model_eva_score=0.083, tm_score=0.8349, gdt_score=0.7247, maxsub=0.6859.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C; model_eva_score=0.083, tm_score=0.8349, gdt_score=0.7247, maxsub=0.6859.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C;total number of template models = 6
>P1;C00452
 : : : : : : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*
