C; model_eva_score=0.092, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_super5.pdb1
structureX:meta_super5.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C;total number of template models = 1
>P1;C00452
 : : : : : : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*
