C; model_eva_score=0.091, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_muster3.pdb1
structureX:meta_muster3.pdb: 1: : 217: : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*

C;total number of template models = 1
>P1;C00452
 : : : : : : : : : 
MAVNDYEPGSMVITHVQGGGRDIIQYIPARSSYGTPPFVPPGPSPYVGTGMQEYRKLRSTLDKSHSELKKNLKNETLKEVDELKSEAGLPGKAVSANDIRDEKSIVDALMDAKAKSLKAIEDRPANLYTASDFPQKSESMYQSQLLASRKFYGEFLDRHMSELAKAYSADIYKAQIAILKQTSQELENKARSLEAEAQRAAAEVEADYKLEHHHHHH*
