C;cover size:262; local alignment length=262 (original info = e2q1sA1	336	396.36	1.6e-55	255	23	100.00)
>P1;e2q1sA1
structureX:e2q1sA1: 3: : 282: : : : : 
-----------------------SKL-ANTNVMVVGGA---GFVGSNLVKRLLELGVNQVHVVDNLLSAEK---IN-V-PDHPAVRFSETSITDDALLASLQDE---YDYVFHLATYHGNQSSIHDPLADHENNTLTTLKLYERLKHF-----KRLKKVVYSAAGEE------------------TDIVSLH---------------NNDSPYSMSKIFGEFYSVYYHKQ--------------HQLPTVRARFQNVYGPGEILGAGRWRGTPATVWRNVTPTFIYKALK-GMPLPLE------NGGVATRDFIFVEDVANGLIACAAD----GT---PGGVYNIASGK-ETSIADLATKINEITGN-NTELDRLPKRPWDNS----------------------------------------------------------------------------------*

C;cover size:137; local alignment length=137 (original info = d2d59a1	139	40.22	1.1e-05	98	15	94.91)
>P1;d2d59a1
structureX:d2d59a1: 7: : 108: : : : : 
----------------LTDEDIREILTRYKKIALVGASPKPERDANIVMKYLLEHG-YDVYPVNPKYEEVL------------GRKC-YPSVL------DIP--D-KIEVVDLFVK------------------PKLTMEYVEQAIKK-----G-AKVVWFQYNT------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:319; local alignment length=319 (original info = e4lisA1	364	388.17	8.8e-54	294	22	100.00)
>P1;e4lisA1
structureX:e4lisA1: 2: : 355: : : : : 
----------------------------SGSVLVTGGT---GYIGSFTTLALLEAG-YKVVVADNLYNSSAEALNRIELISGKKAEFAQLDVTDEAAFDKVFEAHPDIDSVIHFAALKAVGESGEKPLDYYHVNVYGTICLLRSMVRH-----N-VTNIVFSSSATVYGDATRFPDMIPIPEHCPL---------------------GPTNPYGNTKFAIELAITDVINAQRNNAKKAGNETEAAKWNGALLRYFNPAGAHPSGIMGEDPQGVPY---NLLPLLAQVATGKREKLLVFGDDYASHDGTAIRDYIHILDLADGHLKALNYLRANNP---GVRAWNLGTGR-GSTVYEMIRAFSKAVGR-DLPYEVAPRRAGDVLN--L---------------------TSNPTRANTELGW-KAQRTLEQACEDLWLWTKNNPQG--------------------*

C;cover size:284; local alignment length=284 (original info = e4tqgA1	297	474.40	1.1e-67	256	27	100.00)
>P1;e4tqgA1
structureX:e4tqgA1: 2: : 265: : : : : 
------------------------QI-NDKTIMIFGGS---GSLGNRLIETYINNN--IIVNYSRDESKHWSMELK-Y--KSDKLKNIIGDIRDFEKVQQSIMRI-NPDIIIIAAALKHIDRCEYEINECLDTNIKGLQNVLKVTEINRSNLSN-LKAVCFVSTDKA------------------C---------------------SPVNSYGMSKAICETLVVEKSKYI-------------KDIKYVCVRYGNVLNF-----------------------------------TL-------THTSMTRFIMTLDDSVKLIEYAIIN----GN---SGEIVIPKLN--SMYIKDMIELF----A-DKYPIVITGLRSGERMYESLINDTQSMKTVPKGDYYHILP----------------------------------------------------------*

C;cover size:318; local alignment length=318 (original info = e4wkgA3	336	373.88	2.4e-52	295	15	100.00)
>P1;e4wkgA3
structureX:e4wkgA3: 1: : 333: : : : : 
---------------------------RRTRVLILGVN---GFIGNHLTERLLREDHYEVYGLDIGSDAISRF------LNHPHFHFVEGDISIHSEWIEYHVK--KCDVVLPLVAIATPIEYTRNPLRVFELDFEENLRIIRYCVKY-----R--KRIIFPSTSEV------------------YGMCSDKYFDEDHSNLIVGPVNKPRWIYSVSKQLLDRVIWAYGEK--------------EGLQFTLFRPFNWMGPRLDNLNAARIGSS-----RAITQLILNLVE-GSPIKLI------DGGKQKRCFTDIRDGIEALYRIIEN----AGNRCDGEIINIGNPENEASIEELGEMLLASFEKHPLRH-HFPPFAGFRVVE----------SSSDVE-----HRKPSIRNAHRCLDWE-PKIDMQETIDETLDFFLRTV----------------------*

C;query_length:366 num_of_temps:1 cover_ratio:0.72 cover:262 not_cover:104
>P1;2017-11-04_00000004_1_72
 : : : : : : : : : 
ARDISIEDLLARKPKDLDDSAVAAFL-KDKVVLVSGAG---GTIGSELCKQCIKFGAKHLIMVDHSEYNLYKINDD-LNLYKEKITPILLSILDKQSLDEVLKTY-KPELILHAAAYKHVPLCEQNPHSAVINNILGTKILCDSAKEN-----K-VAKFVMISTDKA------------------V---------------------RPTNIYGCTKRVCELYTLSMSD---------------ENFEVACVRFGNVLGSSG----------------SVIPKFKAQIAN-NEPLTL-------THPDIVRYFMLVAEAVQLVLQAGAI----AK---GGELFVLDMGK-PVKIIDLAKKMLLLSNRNDLEIKITGLRKGEKLYEELLIDEND-AKTQYESIFVAKNEKVDLDWLNKEIENLQICEDISEALLKIVPEFKHNKEGIAAGFNRIPAAALEHHHHHH*
