C;cover size:247; local alignment length=247 (original info = e2ydxA1	312	314.23	2.8e-44	228	19	100.00)
>P1;e2ydxA1
structureX:e2ydxA1: 2: : 250: : : : : 
----------------------------NRRVLVTGAT---GLLGRAVHKEFQQNN-WHAVGCGFRRA---------------RPKFEQVNLLDSNAVHHIIHDF-QPHVIVHCAAERRPDVVENQPDAASQLNVDASGNLAKEAAAV-----GA-FLIYISSDYVFDGTNPPYREEDI-----P---------------------APLNLYGKTKLDGEKAVLEN------------------NLGAAVLRIPILYGEVE-------------KLEESAVTVMFDKVQF-SNKSAN-------MDHWQQRFPTHVKDVATVCRQLAEK----RMLDPS---IKGTFHWSGNE-QMTKYEMACAIADAFNLPSSHL---------------------------------------------------------------------------------------------*

C;cover size:137; local alignment length=137 (original info = d2d59a1	139	40.22	1.1e-05	98	15	94.91)
>P1;d2d59a1
structureX:d2d59a1: 7: : 108: : : : : 
----------------LTDEDIREILTRYKKIALVGASPKPERDANIVMKYLLEHG-YDVYPVNPKYEEVL------------GRKC-YPSVL------DIP--D-KIEVVDLFVK------------------PKLTMEYVEQAIKK-----GAKVVWFQYNT-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:319; local alignment length=319 (original info = e4lisA1	364	388.17	8.8e-54	294	22	100.00)
>P1;e4lisA1
structureX:e4lisA1: 2: : 355: : : : : 
----------------------------SGSVLVTGGT---GYIGSFTTLALLEAG-YKVVVADNLYNSSAEALNRIELISGKKAEFAQLDVTDEAAFDKVFEAHPDIDSVIHFAALKAVGESGEKPLDYYHVNVYGTICLLRSMVRH-----NVTNIVFSSSATVYGDATRFPDMIPIPEHCPL---------------------GPTNPYGNTKFAIELAITDVINAQRNNAKKAGNETEAAKWNGALLRYFNPAGAHPSGIMGEDPQGVPYN----LLPLLAQVATGKREKLLVFGDDYASHDGTAIRDYIHILDLADGHLKALNYLRANN----P---GVRAWNLGTGR-GSTVYEMIRAFSKAVGR-DLPYEVAPRRAGDVLN--L---------------------TSNPTRANTELGW-KAQRTLEQACEDLWLWTKNNPQG--------------------*

C;cover size:284; local alignment length=284 (original info = e4tqgA1	297	474.40	1.1e-67	256	27	100.00)
>P1;e4tqgA1
structureX:e4tqgA1: 2: : 265: : : : : 
------------------------QI-NDKTIMIFGGS---GSLGNRLIETYINNN--IIVNYSRDESKHWSMELK-Y--KSDKLKNIIGDIRDFEKVQQSIMRI-NPDIIIIAAALKHIDRCEYEINECLDTNIKGLQNVLKVTEINRSNLSNLKAVCFVSTDKA------------------C---------------------SPVNSYGMSKAICETLVVEKSKYI-------------KDIKYVCVRYGNVLNF------------------------------------TL-------THTSMTRFIMTLDDSVKLIEYAIIN----G----N---SGEIVIPKLN--SMYIKDMIELF----A-DKYPIVITGLRSGERMYESLINDTQSMKTVPKGDYYHILP----------------------------------------------------------*

C;cover size:318; local alignment length=318 (original info = e4wkgA3	336	373.88	2.4e-52	295	15	100.00)
>P1;e4wkgA3
structureX:e4wkgA3: 1: : 333: : : : : 
---------------------------RRTRVLILGVN---GFIGNHLTERLLREDHYEVYGLDIGSDAISRF------LNHPHFHFVEGDISIHSEWIEYHVK--KCDVVLPLVAIATPIEYTRNPLRVFELDFEENLRIIRYCVKY-----R-KRIIFPSTSEV------------------YGMCSDKYFDEDHSNLIVGPVNKPRWIYSVSKQLLDRVIWAYGEK--------------EGLQFTLFRPFNWMGPRLDNLNAARIGSS--R----AITQLILNLVE-GSPIKLI------DGGKQKRCFTDIRDGIEALYRIIEN----A----GNRCDGEIINIGNPENEASIEELGEMLLASFEKHPLRH-HFPPFAGFRVVE----------SSSDVE-----HRKPSIRNAHRCLDWE-PKIDMQETIDETLDFFLRTV----------------------*

C;query_length:366 num_of_temps:1 cover_ratio:0.67 cover:247 not_cover:119
>P1;2017-11-04_00000004_1_72
 : : : : : : : : : 
ARDISIEDLLARKPKDLDDSAVAAFL-KDKVVLVSGAG---GTIGSELCKQCIKFGAKHLIMVDHSEYNLYKINDD-LNLYKEKITPILLSILDKQSLDEVLKTY-KPELILHAAAYKHVPLCEQNPHSAVINNILGTKILCDSAKEN-----KVAKFVMISTDKA------------------V---------------------RPTNIYGCTKRVCELYTLSMSD---------------ENFEVACVRFGNVLGSSG-------------S----VIPKFKAQIAN-NEPLTL-------THPDIVRYFMLVAEAVQLVLQAGAI----A----K---GGELFVLDMGK-PVKIIDLAKKMLLLSNRNDLEIKITGLRKGEKLYEELLIDEND-AKTQYESIFVAKNEKVDLDWLNKEIENLQICEDISEALLKIVPEFKHNKEGIAAGFNRIPAAALEHHHHHH*
