C;cover size:243; local alignment length=243 (original info = e3slgF1	301	352.82	4.6e-50	232	19	100.00)
>P1;e3slgF1
structureX:e3slgF1: 1: : 258: : : : : 
---------------------------KAKKVLILGVN---GFIGHHLSKRILETTDW-----EVFGMDMQTDRLGDL-----VKHERMHFFEGDITINKEWVEYHV-KKCDVILPLVAIATPATYVKQPLRVFELDFEANLPIVRSAVKY-----G-KHLVFPSTSEV--------------YGMCADEQFDPDASALTYGPINKPRWIYACSKQLMDRVIWGYGM--EGLNFTLFRPFNWIGPGL---D--SIYT--PKEGSSRVVTQFGSQKRAFTYVDDGISALMKIIENSNGVATGKIYNIGNPNNNFSVRELANKMLELAAE--------------------------------------------------------------------------------------------------*

C;cover size:137; local alignment length=137 (original info = d2d59a1	139	40.22	1.1e-05	98	15	94.91)
>P1;d2d59a1
structureX:d2d59a1: 7: : 108: : : : : 
----------------LTDEDIREILTRYKKIALVGASPKPERDANIVMKYLLEHG-Y-----DVYPVNPKYEEVL-----------GRKC-YPSVL------DIP--DKIEVVDLFVK------------------PKLTMEYVEQAIKK-----GAKVVWFQYNT-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:317; local alignment length=317 (original info = e1r6dA1	322	362.95	4.2e-51	292	21	100.00)
>P1;e1r6dA1
structureX:e1r6dA1: 2: : 317: : : : : 
------------------------------RLLVTGGA---GFIGSHFVRQLLAGAYPDVPADEVIVLDSLTYAGNRANLAPVDADPRLRFVHGDIRDAGLLARELRG--VDAIVHFAAESHVDRSIAGASVFTETNVQGTQTLLQCAVDA-----GVGRVVHVSTNQVYGSIDSGSWTESSPL---------------------EPNSPYAASKAGSDLVARAYHRT-YGLDVRITRCCNNYGPYQHPEKLIPLFVTNLLDGGTLPLYGDGANVREWVHTDDHCRGIALVLAGGR---AGEIYHIGG-GLELTNRELTGILLDSLGADWSSVRKVADRKGHDLR-----------------------YSLDGGKIERELGYRP-QVSFADGLARTVRWYRENRGW--------------------*

C;cover size:284; local alignment length=284 (original info = e4tqgA1	297	474.40	1.1e-67	256	27	100.00)
>P1;e4tqgA1
structureX:e4tqgA1: 2: : 265: : : : : 
------------------------QI-NDKTIMIFGGS---GSLGNRLIETYINNN-------IIVNYSRDESKHWSMELKY--KSDKLKNIIGDIRDFEKVQQSIMRINPDIIIIAAALKHIDRCEYEINECLDTNIKGLQNVLKVTEINRSNLSNLKAVCFVSTDKA--------------C---------------------SPVNSYGMSKAICETLVVEKSKYIKDIKYVCVRYGNVLNF---------------------TL-THTSMTRFIMTLDDSVKLIEYAIINGN---SGEIVIPKL-N-SMYIKDMIELF----A-DKYPIVITGLRSGERMYESLINDTQSMKTVPKGDYYHILP----------------------------------------------------------*

C;query_length:366 num_of_temps:1 cover_ratio:0.66 cover:243 not_cover:123
>P1;2017-11-04_00000004_1_72
 : : : : : : : : : 
ARDISIEDLLARKPKDLDDSAVAAFL-KDKVVLVSGAG---GTIGSELCKQCIKFGAK-----HLIMVDHSEYNLYKINDDLNLYKEKITPILLSILDKQSLDEVLKTYKPELILHAAAYKHVPLCEQNPHSAVINNILGTKILCDSAKEN-----KVAKFVMISTDKA--------------V---------------------RPTNIYGCTKRVCELYTLSMSD--ENFEVACVRFGNVLGSSG---SVIPKFKAQIANNEPLTL-THPDIVRYFMLVAEAVQLVLQAGAIAK---GGELFVLDM-GKPVKIIDLAKKMLLLSNRNDLEIKITGLRKGEKLYEELLIDEND-AKTQYESIFVAKNEKVDLDWLNKEIENLQICEDISEALLKIVPEFKHNKEGIAAGFNRIPAAALEHHHHHH*
