C; model_eva_score=0.732, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.731, tm_score=0.8723, gdt_score=0.8569, maxsub=0.8199.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.728, tm_score=0.8470, gdt_score=0.8428, maxsub=0.8045.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.729, tm_score=0.8607, gdt_score=0.8491, maxsub=0.8187.
>P1;meta_hh10.pdb1
structureX:meta_hh10.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.726, tm_score=0.8911, gdt_score=0.8648, maxsub=0.8324.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.727, tm_score=0.8693, gdt_score=0.8538, maxsub=0.8148.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C;total number of template models = 6
>P1;C00552
 : : : : : : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*
