C; model_eva_score=0.728, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.732, tm_score=0.8470, gdt_score=0.8428, maxsub=0.8045.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.726, tm_score=0.8549, gdt_score=0.8491, maxsub=0.8041.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.725, tm_score=0.8582, gdt_score=0.8726, maxsub=0.8197.
>P1;meta_hh9.pdb1
structureX:meta_hh9.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.727, tm_score=0.8371, gdt_score=0.8491, maxsub=0.8014.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C;total number of template models = 5
>P1;C00552
 : : : : : : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*
