C; model_eva_score=0.731, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.732, tm_score=0.8723, gdt_score=0.8569, maxsub=0.8199.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.727, tm_score=0.8547, gdt_score=0.8443, maxsub=0.7931.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.726, tm_score=0.8552, gdt_score=0.8428, maxsub=0.7802.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C;total number of template models = 4
>P1;C00552
 : : : : : : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*
