C; model_eva_score=0.731, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C; model_eva_score=0.728, tm_score=0.9001, gdt_score=0.8868, maxsub=0.8569.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 159: : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*

C;total number of template models = 2
>P1;C00552
 : : : : : : : : : 
MKYLLPTAAAGLLLLAAQPAMAQMQLVESGGGLVQPGGSLRLSCAAPESTLDDYAIGWFRQAPGKEREGVSCIGSSGDSTNYADSVKGRFTVSRDNAKNTVYLQMNDLRPEDTAVYYCAAAHRIFGGCLVIHSSGYVSWGQGTPVTVSSHHHHHHEPEA*
