C; model_eva_score=0.275, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_star3.pdb1
structureX:meta_star3.pdb: 1: : 341: : : : : 
MGSSHHHHHHSSGLVPRGSHMIVGGSTIQPERVDAAALRQLGDAMRKVVGSADPTPLADLLSGTPVDPDELTREVGADGRQALLDSGMAVDDGTTFSSPLRGHQLHGVVVLSDPDVEEEVQHRWYVDPLWEADLLIRLMLRRGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMNDYPGDPFRERLADWLGLTENGLRVQIFTSQRRATESGGEWKRGWLVVAPGPVGLTEVEWPYHDRYEEDPDALLDGTDRLLRG*

C; model_eva_score=0.273, tm_score=0.7974, gdt_score=0.7067, maxsub=0.6664.
>P1;meta_center3.pdb1
structureX:meta_center3.pdb: 145: : 218: : : : : 
------------------------------------------------------------------------------------------------------------------------------------------------ARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTN---------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C01191
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMIVGGSTIQPERVDAAALRQLGDAMRKVVGSADPTPLADLLSGTPVDPDELTREVGADGRQALLDSGMAVDDGTTFSSPLRGHQLHGVVVLSDPDVEEEVQHRWYVDPLWEADLLIRLMLRRGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMNDYPGDPFRERLADWLGLTENGLRVQIFTSQRRATESGGEWKRGWLVVAPGPVGLTEVEWPYHDRYEEDPDALLDGTDRLLRG*
