C; model_eva_score=0.27, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 341: : : : : 
MGSSHHHHHHSSGLVPRGSHMIVGGSTIQPERVDAAALRQLGDAMRKVVGSADPTPLADLLSGTPVDPDELTREVGADGRQALLDSGMAVDDGTTFSSPLRGHQLHGVVVLSDPDVEEEVQHRWYVDPLWEADLLIRLMLRRGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMNDYPGDPFRERLADWLGLTENGLRVQIFTSQRRATESGGEWKRGWLVVAPGPVGLTEVEWPYHDRYEEDPDALLDGTDRLLRG*

C; model_eva_score=0.267, tm_score=0.5724, gdt_score=0.5073, maxsub=0.5027.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 142: : 261: : : : : 
---------------------------------------------------------------------------------------------------------------------------------------------RGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMNDY--------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C01191
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMIVGGSTIQPERVDAAALRQLGDAMRKVVGSADPTPLADLLSGTPVDPDELTREVGADGRQALLDSGMAVDDGTTFSSPLRGHQLHGVVVLSDPDVEEEVQHRWYVDPLWEADLLIRLMLRRGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMNDYPGDPFRERLADWLGLTENGLRVQIFTSQRRATESGGEWKRGWLVVAPGPVGLTEVEWPYHDRYEEDPDALLDGTDRLLRG*
