C; model_eva_score=0.271, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_muster1.pdb1
structureX:meta_muster1.pdb: 1: : 341: : : : : 
MGSSHHHHHHSSGLVPRGSHMIVGGSTIQPERVDAAALRQLGDAMRKVVGSADPTPLADLLSGTPVDPDELTREVGADGRQALLDSGMAVDDGTTFSSPLRGHQLHGVVVLSDPDVEEEVQHRWYVDPLWEADLLIRLMLRRGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMNDYPGDPFRERLADWLGLTENGLRVQIFTSQRRATESGGEWKRGWLVVAPGPVGLTEVEWPYHDRYEEDPDALLDGTDRLLRG*

C; model_eva_score=0.27, tm_score=0.5986, gdt_score=0.5799, maxsub=0.5680.
>P1;meta_muster3.pdb1
structureX:meta_muster3.pdb: 103: : 260: : : : : 
------------------------------------------------------------------------------------------------------HQLHGVVVLSDPDVEEEVQHRWYVDPLWEADLLIRLMLRRGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMND---------------------------------------------------------------------------------*

C; model_eva_score=0.246, tm_score=0.6922, gdt_score=0.5601, maxsub=0.5345.
>P1;meta_muster2.pdb1
structureX:meta_muster2.pdb: 167: : 241: : : : : 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------SVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRN----------------------------------------------------------------------------------------------------*

C;total number of template models = 3
>P1;C01191
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMIVGGSTIQPERVDAAALRQLGDAMRKVVGSADPTPLADLLSGTPVDPDELTREVGADGRQALLDSGMAVDDGTTFSSPLRGHQLHGVVVLSDPDVEEEVQHRWYVDPLWEADLLIRLMLRRGGARALDMGCGSGVLSLVLADRYESVLGVDVNPRAVALSRLNAALNGLTNVTFREGDMFEPAEGRFSRIVFNSPTNEEGNEFVDLLEAGEPILETFFRNVPRKLESGGIVEVNLAMNDYPGDPFRERLADWLGLTENGLRVQIFTSQRRATESGGEWKRGWLVVAPGPVGLTEVEWPYHDRYEEDPDALLDGTDRLLRG*
