C; model_eva_score=0.891, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.894, tm_score=0.9753, gdt_score=0.9771, maxsub=0.9623.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9623, gdt_score=0.9580, maxsub=0.9442.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9743, gdt_score=0.9752, maxsub=0.9647.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9743, gdt_score=0.9752, maxsub=0.9647.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9777, gdt_score=0.9733, maxsub=0.9675.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9741, gdt_score=0.9676, maxsub=0.9609.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9795, gdt_score=0.9733, maxsub=0.9699.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9724, gdt_score=0.9695, maxsub=0.9558.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9672, gdt_score=0.9618, maxsub=0.9492.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.893, tm_score=0.9686, gdt_score=0.9561, maxsub=0.9549.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9624, gdt_score=0.9561, maxsub=0.9436.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9633, gdt_score=0.9561, maxsub=0.9480.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9705, gdt_score=0.9714, maxsub=0.9554.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.889, tm_score=0.9595, gdt_score=0.9542, maxsub=0.9356.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9789, gdt_score=0.9790, maxsub=0.9736.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.888, tm_score=0.9590, gdt_score=0.9523, maxsub=0.9393.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9746, gdt_score=0.9695, maxsub=0.9570.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9773, gdt_score=0.9695, maxsub=0.9664.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9753, gdt_score=0.9752, maxsub=0.9649.
>P1;meta_blits10.pdb1
structureX:meta_blits10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C;total number of template models = 20
>P1;C00242
 : : : : : : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*
