C; model_eva_score=0.892, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.894, tm_score=0.9714, gdt_score=0.9676, maxsub=0.9592.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9623, gdt_score=0.9580, maxsub=0.9442.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9572, gdt_score=0.9561, maxsub=0.9355.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9572, gdt_score=0.9561, maxsub=0.9355.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9659, gdt_score=0.9637, maxsub=0.9530.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9613, gdt_score=0.9561, maxsub=0.9416.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9643, gdt_score=0.9618, maxsub=0.9485.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9560, gdt_score=0.9561, maxsub=0.9312.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9703, gdt_score=0.9676, maxsub=0.9593.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.893, tm_score=0.9720, gdt_score=0.9676, maxsub=0.9603.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9694, gdt_score=0.9714, maxsub=0.9581.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9716, gdt_score=0.9656, maxsub=0.9593.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9653, gdt_score=0.9637, maxsub=0.9513.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.889, tm_score=0.9801, gdt_score=0.9790, maxsub=0.9656.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9618, gdt_score=0.9599, maxsub=0.9398.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.888, tm_score=0.9749, gdt_score=0.9695, maxsub=0.9644.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9565, gdt_score=0.9542, maxsub=0.9325.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9629, gdt_score=0.9561, maxsub=0.9452.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9602, gdt_score=0.9599, maxsub=0.9414.
>P1;meta_blits10.pdb1
structureX:meta_blits10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C;total number of template models = 20
>P1;C00242
 : : : : : : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*
