C; model_eva_score=0.892, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.894, tm_score=0.9701, gdt_score=0.9695, maxsub=0.9535.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9743, gdt_score=0.9752, maxsub=0.9647.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9572, gdt_score=0.9561, maxsub=0.9355.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9659, gdt_score=0.9656, maxsub=0.9484.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9584, gdt_score=0.9542, maxsub=0.9388.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9604, gdt_score=0.9542, maxsub=0.9377.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9779, gdt_score=0.9790, maxsub=0.9704.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9505, gdt_score=0.9485, maxsub=0.9276.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.893, tm_score=0.9584, gdt_score=0.9504, maxsub=0.9371.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9527, gdt_score=0.9523, maxsub=0.9339.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9578, gdt_score=0.9561, maxsub=0.9366.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9594, gdt_score=0.9599, maxsub=0.9442.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.889, tm_score=0.9551, gdt_score=0.9561, maxsub=0.9330.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9742, gdt_score=0.9695, maxsub=0.9628.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.888, tm_score=0.9488, gdt_score=0.9523, maxsub=0.9246.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9776, gdt_score=0.9752, maxsub=0.9681.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9697, gdt_score=0.9714, maxsub=0.9566.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9895, gdt_score=0.9885, maxsub=0.9853.
>P1;meta_blits10.pdb1
structureX:meta_blits10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C;total number of template models = 20
>P1;C00242
 : : : : : : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*
