C; model_eva_score=0.894, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9714, gdt_score=0.9676, maxsub=0.9592.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9753, gdt_score=0.9771, maxsub=0.9623.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9701, gdt_score=0.9695, maxsub=0.9535.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9701, gdt_score=0.9695, maxsub=0.9535.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9747, gdt_score=0.9733, maxsub=0.9673.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9711, gdt_score=0.9676, maxsub=0.9629.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9723, gdt_score=0.9676, maxsub=0.9602.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.89, tm_score=0.9653, gdt_score=0.9637, maxsub=0.9471.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9664, gdt_score=0.9618, maxsub=0.9539.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.893, tm_score=0.9698, gdt_score=0.9637, maxsub=0.9581.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9636, gdt_score=0.9618, maxsub=0.9475.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9748, gdt_score=0.9656, maxsub=0.9660.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9610, gdt_score=0.9580, maxsub=0.9445.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.889, tm_score=0.9655, gdt_score=0.9618, maxsub=0.9469.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9800, gdt_score=0.9752, maxsub=0.9706.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.888, tm_score=0.9595, gdt_score=0.9599, maxsub=0.9438.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9660, gdt_score=0.9599, maxsub=0.9524.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.892, tm_score=0.9637, gdt_score=0.9561, maxsub=0.9494.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C; model_eva_score=0.891, tm_score=0.9709, gdt_score=0.9656, maxsub=0.9540.
>P1;meta_blits10.pdb1
structureX:meta_blits10.pdb: 1: : 131: : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*

C;total number of template models = 20
>P1;C00242
 : : : : : : : : : 
QVQLQESGGGLVQAGGSLRLSCAASGRTFSNDHMGWFRKAPGKEREFVAAITPGTEKTYYADSVKGRFAFSRDNAKNTVYLQMNSLKPEDTAVYYCVATPYYRGSYYAASTYTYWGQGTQVTVSSHHHHHH*
