C; model_eva_score=0.658, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.653, tm_score=0.9592, gdt_score=0.9308, maxsub=0.9171.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.648, tm_score=0.9027, gdt_score=0.8590, maxsub=0.8303.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.643, tm_score=0.8706, gdt_score=0.8128, maxsub=0.7763.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.633, tm_score=0.8861, gdt_score=0.8333, maxsub=0.7971.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.636, tm_score=0.8898, gdt_score=0.8308, maxsub=0.7935.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.634, tm_score=0.9101, gdt_score=0.8615, maxsub=0.8403.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.624, tm_score=0.8713, gdt_score=0.7910, maxsub=0.7522.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.8663, gdt_score=0.7949, maxsub=0.7619.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.621, tm_score=0.8713, gdt_score=0.7949, maxsub=0.7554.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.8581, gdt_score=0.7641, maxsub=0.7480.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.607, tm_score=0.8473, gdt_score=0.7885, maxsub=0.7268.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.621, tm_score=0.8728, gdt_score=0.7949, maxsub=0.7587.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.622, tm_score=0.8819, gdt_score=0.8103, maxsub=0.7840.
>P1;meta_hp3.pdb1
structureX:meta_hp3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.601, tm_score=0.8708, gdt_score=0.7962, maxsub=0.7693.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.59, tm_score=0.8457, gdt_score=0.7769, maxsub=0.7106.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.604, tm_score=0.8546, gdt_score=0.7795, maxsub=0.7447.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.604, tm_score=0.8546, gdt_score=0.7795, maxsub=0.7447.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.601, tm_score=0.8322, gdt_score=0.7705, maxsub=0.6958.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.608, tm_score=0.8646, gdt_score=0.7846, maxsub=0.7611.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00671
 : : : : : : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*
