C; model_eva_score=0.647, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.649, tm_score=0.9704, gdt_score=0.9526, maxsub=0.9379.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.648, tm_score=0.8892, gdt_score=0.8397, maxsub=0.8197.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.641, tm_score=0.8777, gdt_score=0.8128, maxsub=0.7922.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.638, tm_score=0.8726, gdt_score=0.8077, maxsub=0.7935.
>P1;meta_msaprobs3.pdb1
structureX:meta_msaprobs3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.638, tm_score=0.9582, gdt_score=0.9231, maxsub=0.9091.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.634, tm_score=0.9281, gdt_score=0.8756, maxsub=0.8610.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.634, tm_score=0.9281, gdt_score=0.8756, maxsub=0.8610.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.628, tm_score=0.9406, gdt_score=0.8885, maxsub=0.8761.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.63, tm_score=0.8678, gdt_score=0.7949, maxsub=0.7874.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.625, tm_score=0.9411, gdt_score=0.8872, maxsub=0.8771.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.9261, gdt_score=0.8692, maxsub=0.8534.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.62, tm_score=0.8650, gdt_score=0.7846, maxsub=0.7538.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C;total number of template models = 13
>P1;C00671
 : : : : : : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*
