C; model_eva_score=0.648, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.653, tm_score=0.8934, gdt_score=0.8385, maxsub=0.8086.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.658, tm_score=0.9027, gdt_score=0.8590, maxsub=0.8303.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.643, tm_score=0.8570, gdt_score=0.7897, maxsub=0.7665.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.633, tm_score=0.9174, gdt_score=0.8756, maxsub=0.8467.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.636, tm_score=0.8813, gdt_score=0.8372, maxsub=0.8056.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.637, tm_score=0.8426, gdt_score=0.7679, maxsub=0.7293.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.634, tm_score=0.8975, gdt_score=0.8436, maxsub=0.8060.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.624, tm_score=0.8773, gdt_score=0.8218, maxsub=0.7764.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.8727, gdt_score=0.8167, maxsub=0.7938.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.621, tm_score=0.8759, gdt_score=0.8128, maxsub=0.7773.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.8642, gdt_score=0.7987, maxsub=0.7753.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.607, tm_score=0.8413, gdt_score=0.7744, maxsub=0.7171.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.621, tm_score=0.8810, gdt_score=0.8295, maxsub=0.7810.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.622, tm_score=0.8859, gdt_score=0.8321, maxsub=0.7877.
>P1;meta_hp3.pdb1
structureX:meta_hp3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.601, tm_score=0.8529, gdt_score=0.7846, maxsub=0.7228.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.59, tm_score=0.8576, gdt_score=0.7833, maxsub=0.7338.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.604, tm_score=0.8572, gdt_score=0.7705, maxsub=0.7403.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.604, tm_score=0.8572, gdt_score=0.7705, maxsub=0.7403.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.601, tm_score=0.8439, gdt_score=0.7654, maxsub=0.7153.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00671
 : : : : : : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*
