C; model_eva_score=0.649, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.647, tm_score=0.9704, gdt_score=0.9526, maxsub=0.9379.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.648, tm_score=0.8864, gdt_score=0.8385, maxsub=0.8110.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.641, tm_score=0.8929, gdt_score=0.8410, maxsub=0.8257.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.638, tm_score=0.8741, gdt_score=0.8167, maxsub=0.7850.
>P1;meta_msaprobs3.pdb1
structureX:meta_msaprobs3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.638, tm_score=0.9595, gdt_score=0.9321, maxsub=0.9169.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.634, tm_score=0.9422, gdt_score=0.8859, maxsub=0.8863.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.634, tm_score=0.9422, gdt_score=0.8859, maxsub=0.8863.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.628, tm_score=0.9425, gdt_score=0.8923, maxsub=0.8888.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.629, tm_score=0.8462, gdt_score=0.7705, maxsub=0.7444.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.63, tm_score=0.8667, gdt_score=0.7923, maxsub=0.7817.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.625, tm_score=0.9370, gdt_score=0.8910, maxsub=0.8685.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.9319, gdt_score=0.8769, maxsub=0.8674.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.62, tm_score=0.8753, gdt_score=0.7923, maxsub=0.7689.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C;total number of template models = 14
>P1;C00671
 : : : : : : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*
