C; model_eva_score=0.653, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.658, tm_score=0.9592, gdt_score=0.9308, maxsub=0.9171.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.648, tm_score=0.8934, gdt_score=0.8385, maxsub=0.8086.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.643, tm_score=0.8860, gdt_score=0.8346, maxsub=0.8046.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.633, tm_score=0.8701, gdt_score=0.8064, maxsub=0.7614.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.636, tm_score=0.8904, gdt_score=0.8295, maxsub=0.7938.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.634, tm_score=0.8997, gdt_score=0.8538, maxsub=0.8169.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.624, tm_score=0.8756, gdt_score=0.7936, maxsub=0.7623.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.8591, gdt_score=0.7833, maxsub=0.7499.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.621, tm_score=0.8710, gdt_score=0.7885, maxsub=0.7585.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.623, tm_score=0.8549, gdt_score=0.7692, maxsub=0.7457.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.607, tm_score=0.8388, gdt_score=0.7795, maxsub=0.7192.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.621, tm_score=0.8762, gdt_score=0.8064, maxsub=0.7646.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.622, tm_score=0.8686, gdt_score=0.8038, maxsub=0.7607.
>P1;meta_hp3.pdb1
structureX:meta_hp3.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.601, tm_score=0.8516, gdt_score=0.7833, maxsub=0.7281.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.59, tm_score=0.8392, gdt_score=0.7705, maxsub=0.7006.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.604, tm_score=0.8374, gdt_score=0.7538, maxsub=0.7080.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.604, tm_score=0.8374, gdt_score=0.7538, maxsub=0.7080.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.601, tm_score=0.8314, gdt_score=0.7641, maxsub=0.6969.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C; model_eva_score=0.608, tm_score=0.8509, gdt_score=0.7808, maxsub=0.7350.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 195: : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00671
 : : : : : : : : : 
SGGYAVDYSEPIIIKEKGEIKVVKIGELIDEIIKNSKNVRKDGILEIARCKDVEVIAFDSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTGSHSVFTVKDNEVVPIRVDDLRVGDILVLAKELPNIEENRKLEPNIEENRKLEKLINSDFIFLKIKKINKVEPTNGYAYDLTVPNAENFIAGFGGFVLHNA*
