C;cover size:314; local alignment length=314 (original info = d1aina_	314	757.54	4.6e-104	313	54	100.00)
>P1;d1aina_
structureX:d1aina_: 2: : 314: : : : : 
----------------------------------------------------------------------------------------------------------------SAV-S-PYPTFNPSSDVAALHKAIMVKGVDEATIIDILTKRNNAQRQQIKAAYLQETGKPLDETLKKALTGHLEEVVLALLKTPAQFDADELRAAMKGLGTDEDTLIEILASRTNKEIRDINRVYREELKRDLAKDITSDTSGDFRNALLSLAKGDRSEDF-GVNE----DLADSDARALYEAGERRKGTDVNVFNTILTTRSYPQLRRVFQKYTKYSKHDMNKVLDLE-LKGDIEKCLTAIVKCATSKPAFFAEKLHQAMKGVGTRHKALIRIMVSRSEIDMNDIKAFYQKMYGISLCQAILDETKGDYEKILVALCGGN-*

C;cover size:314; local alignment length=314 (original info = d1dk5a_	316	719.73	9.6e-99	310	27	100.00)
>P1;d1dk5a_
structureX:d1dk5a_: 6: : 316: : : : : 
----------------------------------------------------------------------------------------------------------------ASLTV-PAHVPSAAEDCEQLRSAFKGWGTNEKLIISILAHRTAAQRKLIRQTYAETFGEDLLKELDRELTHDFEKLVLVWTLDPSERDAHLAKEATKRWTKSNFVLVELACTRSPKELVLAREAYHARYKKSLEEDVAYHTTGDHRKLLVPLVSSYRYGG-EEVDL----RLAKAESKILHEKISDKAYSDD-EVIRILATRSKAQLNATLNHYKDEHGEDILKQLE---DGDEFVALLRATIKGLVYPEHYFVEVLRDAINRRGTEEDHLTRVIATRAEVDLKIIADEYQKRDSIPLGRAIAKDTRGDYESMLLALLGQE-*

C;cover size:315; local alignment length=315 (original info = d1n00a_	318	728.02	8.2e-100	313	27	100.00)
>P1;d1n00a_
structureX:d1n00a_: 3: : 316: : : : : 
---------------------------------------------------------------------------------------------------------------HATL-TVPTTVPSVSEDCEQLRKAFSGWGTNEGLIIDILGHRNAEQRNLIRKTYAETYGEDLLKALDKELSNDFERLVLLWALDPAERDALLANEATKRWTSSNQVLMEIACTRSANQLLHARQAYHARYKKSLEEDVAHHTTGDFHKLLLPLVSSYRYEGE-EVNM----TLAKTEAKLLHEKISNKAYSDDD-VIRVLATRSKAQINATLNHYKNEYGNDINKDLKAD-PKDEFLALLRSTVKCLVYPEKYFEKVLRLAINRRGTDEGALTRVVCTRAEVDLKVIADEYQRRNSVPLTRAIVKDTHGDYEKLLLVLAGHV-*

C;cover size:316; local alignment length=316 (original info = d1avca2	307	711.10	6.7e-98	306	46	100.00)
>P1;d1avca2
structureX:d1avca2: 2: : 307: : : : : 
-------------------------------------------------------------------------------------------------------------ELKGTV-R-PAGDFNPDADAKALRKAMKGLGTDEDTIIDIITHRSNAQRQQIRQTFKSHFGRDLMADLKSELSGDLARLILGLMMPPAHYDAKQLKKAMEGAGTDEKALIEILATRTNAEIQAINKAYKEDYHKTLEDALSSDTSGHFKRILISLATGNREEG--GEDR----ERAREDAQVAAEIL--------TRFMMILCTRSYPDLRRVFQEFVKMTNYDVEHTIKKE-MSGDVRDVFVAIVQSVKNKPLFFADKLYKSMKGAGTEEKTLTRIMVSRSEIDLLNIRREFIEKYDKSLHQAIEGDTSGHFLKALLAICGG--*

C;cover size:318; local alignment length=318 (original info = d1m9ia2	323	745.44	5.1e-102	318	46	100.00)
>P1;d1m9ia2
structureX:d1m9ia2: 2: : 323: : : : : 
-------------------------------------------------------------------------------------------------------------ELKGDV-R-PANDFNPDADAKALRKAMKGLGTDEDTIIDIITHRSNVQRQQIRQTFKSHFGRDLMTDLKSEISGDLARLILGLMMPPAHYDAKQLKKAMEGAGTDEKALIEILATRTNAEIRAINEAYKEDYHKSLEDALSSDTSGHFRRILISLATGHREEGGENLDQAREDAQVAAEILEIADTPSGDKTSLETRFMTILCTRSYPHLRRVFQEFIKMTNYDVEHTIKKE-MSGDVRDAFVAIVQSVKNKPLFFADKLYKSMKGAGTDDKTLTRIMVSRSEIDLLNIRREFIEKYDKSLHQAIEGDTSGDFLKALLALCGGED*

C;cover size:314; local alignment length=314 (original info = d1ycna_	312	699.64	4.1e-96	307	31	100.00)
>P1;d1ycna_
structureX:d1ycna_: 3: : 311: : : : : 
-----------------------------------------------------------------------------------------------------------------TL-KVSDSVPAPSDDAEQLRTAF-----EEDLIISILAHRSAEQRKVIRQAYHETYGEDLLKTLDKELSNDFERAILLWTLEPGERDALLANEATKRWTSSNQVLMEVACTRTSTQLLHARQAYHARYKKSLEEDVAHHTTGDFRKLLVSLVTSYRYEG-DEVNM----TLAKQEAKLVHEKIKDKHYNDE-DVIRILSTRSKAQINATFNRYQDDHGEEILKSLEEGDDDDKFLALLRSTIQCLTRPELYFVDVLRSAINKTGTDEGALTRIVTTRAEIDLKVIGEEYQRRNSIPLEKAITKDTRGDYEKMLVALLGEDD*

C;cover size:310; local alignment length=310 (original info = d1i4aa_	309	726.93	5.1e-100	309	50	100.00)
>P1;d1i4aa_
structureX:d1i4aa_: 1: : 309: : : : : 
-----------------------------------------------------------------------------------------------------------------------ASGFNAAEDAQTLRKAMKGLGTDEDAIINVLAYRSTAQRQEIRTAYKTTIGRDLMDDLKSELSGNFEQVILGMMTPTVLYDVQELRKAMKGAGTDEGCLIEILASRTPEEIRRINQTYQLQYGRSLEDDIRSDTSFMFQRVLVSLSAGGRDES-NYLDD----ALMRQDAQDLYEAGEKKWGTDEVKFLTVLCSRNRNHLLHVFDEYKRIAQKDIEQSIKSE-TSGSFEDALLAIVKCMRNKSAYFAERLYKSMKGLGTDDDTLIRVMVSRAEIDMLDIRANFKRLYGKSLYSFIKGDTSGDYRKVLLILCGGDD*

C;cover size:313; local alignment length=313 (original info = d1hvda_	313	747.36	1.1e-102	312	46	100.00)
>P1;d1hvda_
structureX:d1hvda_: 2: : 313: : : : : 
--------------------------------------------------------------------------------------------------------------LRGTV-T-DFPGFDGRADAETLRKAMKGLGTDEESILTLLTSRSNAQRQEISAAFKTLFGRDLLDDLKSELTGKFEKLIVALMKPSRLYDAYELKHALKGAGTNEKVLTEIIASRTPEELRAIKQVYEEEYGSSLEDDVVGDTSGYYQRMLVVLLQANRDPDA-GIDE----AQVEQDAQALFQAGELKWGTDEEKFITIFGTRSVSHLRKVFDKYMTISGFQIEETIDRE-TSGNLEQLLLAVVKSIRSIPAYLAETLYYAMKGAGTDDHTLIRVMVSRSEIDLFNIRKEFRKNFATSLYSMIKGDTSGDYKKALLLLC----*

C;cover size:317; local alignment length=317 (original info = d1m9ia1	341	766.38	2.9e-104	316	48	100.00)
>P1;d1m9ia1
structureX:d1m9ia1: 1: : 316: : : : : 
--------------------------------------------------------------------------------------------------------------YRGSI-H-DFPGFDPNQDAEALYTAMKGFGSDKEAILDIITSRSNRQRQEVCQSYKSLYGKDLIADLKYELTGKFERLIVGLMRPPAYCDAKEIKDAISGIGTDEKCLIEILASRTNEQMHQLVAAYKDAYERDLEADIIGDTSGHFQKMLVVLLQGTREED-DVVSE----DLVQQDVQDLYEAGELKWGTDEAQFIYILGNRSKQHLRLVFDEYLKTTGKPIEASIRGE-LSGDFEKLMLAVVKCIRSTPEYFAERLFKAMKGLGTRDNTLIRIMVSRSELDMLDIREIFRTKYEKSLYSMIKNDTSGEYKKTLLKLSGGDD*

C;query_length:427 num_of_temps:1 cover_ratio:0.74 cover:314 not_cover:113
>P1;2017-11-04_00000032_1_72
 : : : : : : : : : 
GSMGKPFFTRNPSELKGKFIHTKLRKSSRGFGFTVVGGDEPDEFLQIKSLVLDGPAALDGKMETGDVIVSVNDTCVLGHTHAQVVKIFQSIPIGASVDLELCRGYPLGSSAYGSV-K-AYTNFDAERDALNIETAIKTKGVDEVTIVNILTNRSNEQRQDIAFAYQRRTKKELASALKSALSGHLETVILGLLKTPAQYDASELKASMKGLGTDEDSLIEIICSRTNQELQEINRVYKEMYKTDLEKDIISDTSGDFRKLMVALAKGRRAEDGSVIDY----ELIDQDARDLYDAGVKRKGTDVPKWISIMTERSVPHLQKVFDRYKSYSPYDMLESIRKE-VKGDLENAFLNLVQCIQNKPLYFADRLYDSMKGKGTRDKVLIRIMVSRSEVDMLKIRSEFKRKYGKSLYYYIQQDTKGDYQKALLYLCGGDD*
