C;cover size:316; local alignment length=316 (original info = d1avca2	307	711.10	6.7e-98	306	46	100.00)
>P1;d1avca2
structureX:d1avca2: 2: : 307: : : : : 
-------------------------------------------------------------------------------------------------------------ELKGTVRPAGDFNPDADAKALRKAMKGLGTDEDTIIDIITHRSNAQRQQIRQTFKSHFGRDLMADLKSELSGDLARLILGLMMPPAHYDAKQLKKAMEGAGTDEKALIEILATRTNAEIQAINKAYKEDYHKTLEDALSSDTSGHFKRILISLATGNREEG--GEDR----ERAREDAQVAAEIL--------TRFMMILCTRSYPDLRRVFQEFVKMTNYDVEHTIKKEMSGDVRDVFVAIVQSVKNKPLFFADKLYKSMKGAGTEEKTLTRIMVSRSEIDLLNIRREFIEKYDKSLHQAIEGDTSGHFLKALLAICGG--*

C;cover size:318; local alignment length=318 (original info = d1m9ia2	323	745.44	5.1e-102	318	46	100.00)
>P1;d1m9ia2
structureX:d1m9ia2: 2: : 323: : : : : 
-------------------------------------------------------------------------------------------------------------ELKGDVRPANDFNPDADAKALRKAMKGLGTDEDTIIDIITHRSNVQRQQIRQTFKSHFGRDLMTDLKSEISGDLARLILGLMMPPAHYDAKQLKKAMEGAGTDEKALIEILATRTNAEIRAINEAYKEDYHKSLEDALSSDTSGHFRRILISLATGHREEGGENLDQAREDAQVAAEILEIADTPSGDKTSLETRFMTILCTRSYPHLRRVFQEFIKMTNYDVEHTIKKEMSGDVRDAFVAIVQSVKNKPLFFADKLYKSMKGAGTDDKTLTRIMVSRSEIDLLNIRREFIEKYDKSLHQAIEGDTSGDFLKALLALCGGED*

C;cover size:208; local alignment length=208 (original info = e4bm5A1	268	20.13	0.077	152	16	3.85)
>P1;e4bm5A1
structureX:e4bm5A1: 90: : 241: : : : : 
---------------------------------------------------------TNNRLEEKDIEFLRNIQNMLSMDEATCRTLLQETKEAR-----A-------GFLFDKI-----FMA-EAVAEFRRVCRELDVE-------------DRRV-------RAFRAEIEHAIENSL---LKESQEELGIS-----AEKA----------RQVLLDCIQDRCEALIVQAAASLRQRRQEGAARDLSRALRQELYLVYQAYALG----------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:427 num_of_temps:1 cover_ratio:0.74 cover:316 not_cover:111
>P1;2017-11-04_00000032_1_72
 : : : : : : : : : 
GSMGKPFFTRNPSELKGKFIHTKLRKSSRGFGFTVVGGDEPDEFLQIKSLVLDGPAALDGKMETGDVIVSVNDTCVLGHTHAQVVKIFQSIPIGASVDLELCRGYPLGSSAYGSVKAYTNFDAERDALNIETAIKTKGVDEVTIVNILTNRSNEQRQDIAFAYQRRTKKELASALKSALSGHLETVILGLLKTPAQYDASELKASMKGLGTDEDSLIEIICSRTNQELQEINRVYKEMYKTDLEKDIISDTSGDFRKLMVALAKGRRAEDGSVIDY----ELIDQDARDLYDAGVKRKGTDVPKWISIMTERSVPHLQKVFDRYKSYSPYDMLESIRKEVKGDLENAFLNLVQCIQNKPLYFADRLYDSMKGKGTRDKVLIRIMVSRSEVDMLKIRSEFKRKYGKSLYYYIQQDTKGDYQKALLYLCGGDD*
