C;cover size:317; local alignment length=317 (original info = d1m9ia1	341	766.38	2.9e-104	316	48	100.00)
>P1;d1m9ia1
structureX:d1m9ia1: 1: : 316: : : : : 
--------------------------------------------------------------------------------------------------------------YRGSIHDFPGFDPNQDAEALYTAMKGFGSDKEAILDIITSRSNRQRQEVCQSYKSLYGKDLIADLKYELTGKFERLIVGLMRPPAYCDAKEIKDAISGIGTDEKCLIEILASRTNEQMHQLVAAYKDAYERDLEADIIGDTSGHFQKMLVVLLQGTREED-DVVSEDLVQQDVQDLYEAGELKWGTDEAQFIYILGNRSKQHLRLVFDEYLKTTGKPIEASIRGELSGDFEKLMLAVVKCIRSTPEYFAERLFKAMKGLGTRDNTLIRIMVSRSELDMLDIREIFRTKYEKSLYSMIKNDTSGEYKKTLLKLSGGDD*

C;cover size:208; local alignment length=208 (original info = e4bm5A1	268	20.13	0.077	152	16	3.85)
>P1;e4bm5A1
structureX:e4bm5A1: 90: : 241: : : : : 
---------------------------------------------------------TNNRLEEKDIEFLRNIQNMLSMDEATCRTLLQETKEAR-----A-------GFLFDKI-----FMA-EAVAEFRRVCRELDVE-------------DRRV-------RAFRAEIEHAIENSL---LKESQEELGIS-----AEKA----------RQVLLDCIQDRCEALIVQAAASLRQRRQEGAARDLSRALRQELYLVYQAYALG------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:427 num_of_temps:1 cover_ratio:0.74 cover:317 not_cover:110
>P1;2017-11-04_00000032_1_72
 : : : : : : : : : 
GSMGKPFFTRNPSELKGKFIHTKLRKSSRGFGFTVVGGDEPDEFLQIKSLVLDGPAALDGKMETGDVIVSVNDTCVLGHTHAQVVKIFQSIPIGASVDLELCRGYPLGSSAYGSVKAYTNFDAERDALNIETAIKTKGVDEVTIVNILTNRSNEQRQDIAFAYQRRTKKELASALKSALSGHLETVILGLLKTPAQYDASELKASMKGLGTDEDSLIEIICSRTNQELQEINRVYKEMYKTDLEKDIISDTSGDFRKLMVALAKGRRAEDGSVIDYELIDQDARDLYDAGVKRKGTDVPKWISIMTERSVPHLQKVFDRYKSYSPYDMLESIRKEVKGDLENAFLNLVQCIQNKPLYFADRLYDSMKGKGTRDKVLIRIMVSRSEVDMLKIRSEFKRKYGKSLYYYIQQDTKGDYQKALLYLCGGDD*
