C; model_eva_score=0.09, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 337: : : : : 
MSELKTGHAGHNPWASVANSGPISILSYCGSSILMTVTNKFVVNLKDFNMNFVMLFVQSLVCTITLIILRILGYAKFRSLNKTDAKNWFPISFLLVLMIYTSSKALQYLAVPIYTIFKNLTIILIAYGEVLFFGGSVTSMELSSFLLMVLSSVVATWGDQQAVAAKAASLAEGAAGAVASFNPGYFWMFTNCITSALFVLIMRKRIKLTNFKDFDTMFYNNVLALPILLLFSFCVEDWSSVNLTNNFSNDSLTAMIISGVASVGISYCSGWCVRVTSSTTYSMVGALNKLPIALSGLIFFDAPRNFLSILSIFIGFLSGIIYAVAKQKKQQAQPLRK*

C; model_eva_score=0.092, tm_score=0.8362, gdt_score=0.7337, maxsub=0.6788.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 247: : 331: : : : : 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------FSNDSLTAMIISGVASVGISYCSGWCVRVTSSTTYSMVGALNKLPIALSGLIFFDAPRNFLSILSIFIGFLSGIIYAVAKQKKQQ------*

C; model_eva_score=0.089, tm_score=0.7876, gdt_score=0.6907, maxsub=0.6442.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 249: : 331: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------NDSLTAMIISGVASVGISYCSGWCVRVTSSTTYSMVGALNKLPIALSGLIFFDAPRNFLSILSIFIGFLSGIIYAVAKQKKQQ------*

C;total number of template models = 3
>P1;C00211
 : : : : : : : : : 
MSELKTGHAGHNPWASVANSGPISILSYCGSSILMTVTNKFVVNLKDFNMNFVMLFVQSLVCTITLIILRILGYAKFRSLNKTDAKNWFPISFLLVLMIYTSSKALQYLAVPIYTIFKNLTIILIAYGEVLFFGGSVTSMELSSFLLMVLSSVVATWGDQQAVAAKAASLAEGAAGAVASFNPGYFWMFTNCITSALFVLIMRKRIKLTNFKDFDTMFYNNVLALPILLLFSFCVEDWSSVNLTNNFSNDSLTAMIISGVASVGISYCSGWCVRVTSSTTYSMVGALNKLPIALSGLIFFDAPRNFLSILSIFIGFLSGIIYAVAKQKKQQAQPLRK*
