C; model_eva_score=0.084, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_super2.pdb1
structureX:meta_super2.pdb: 1: : 337: : : : : 
MSELKTGHAGHNPWASVANSGPISILSYCGSSILMTVTNKFVVNLKDFNMNFVMLFVQSLVCTITLIILRILGYAKFRSLNKTDAKNWFPISFLLVLMIYTSSKALQYLAVPIYTIFKNLTIILIAYGEVLFFGGSVTSMELSSFLLMVLSSVVATWGDQQAVAAKAASLAEGAAGAVASFNPGYFWMFTNCITSALFVLIMRKRIKLTNFKDFDTMFYNNVLALPILLLFSFCVEDWSSVNLTNNFSNDSLTAMIISGVASVGISYCSGWCVRVTSSTTYSMVGALNKLPIALSGLIFFDAPRNFLSILSIFIGFLSGIIYAVAKQKKQQAQPLRK*

C; model_eva_score=0.08, tm_score=0.7265, gdt_score=0.5979, maxsub=0.5666.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 255: : 295: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------MIISGVASVGISYCSGWCVRVTSSTTYSMVGALNKLPIALS------------------------------------------*

C;total number of template models = 2
>P1;C00211
 : : : : : : : : : 
MSELKTGHAGHNPWASVANSGPISILSYCGSSILMTVTNKFVVNLKDFNMNFVMLFVQSLVCTITLIILRILGYAKFRSLNKTDAKNWFPISFLLVLMIYTSSKALQYLAVPIYTIFKNLTIILIAYGEVLFFGGSVTSMELSSFLLMVLSSVVATWGDQQAVAAKAASLAEGAAGAVASFNPGYFWMFTNCITSALFVLIMRKRIKLTNFKDFDTMFYNNVLALPILLLFSFCVEDWSSVNLTNNFSNDSLTAMIISGVASVGISYCSGWCVRVTSSTTYSMVGALNKLPIALSGLIFFDAPRNFLSILSIFIGFLSGIIYAVAKQKKQQAQPLRK*
