C; model_eva_score=0.899, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9878, gdt_score=0.9863, maxsub=0.9811.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9760, gdt_score=0.9766, maxsub=0.9661.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.9, tm_score=0.9843, gdt_score=0.9844, maxsub=0.9749.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9816, gdt_score=0.9863, maxsub=0.9719.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9777, gdt_score=0.9766, maxsub=0.9712.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9775, gdt_score=0.9824, maxsub=0.9708.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9779, gdt_score=0.9805, maxsub=0.9699.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9790, gdt_score=0.9844, maxsub=0.9692.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9899, gdt_score=0.9902, maxsub=0.9865.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9899, gdt_score=0.9902, maxsub=0.9865.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9758, gdt_score=0.9727, maxsub=0.9675.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9757, gdt_score=0.9785, maxsub=0.9612.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9851, gdt_score=0.9805, maxsub=0.9799.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9734, gdt_score=0.9746, maxsub=0.9649.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9734, gdt_score=0.9746, maxsub=0.9649.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9777, gdt_score=0.9805, maxsub=0.9690.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9785, gdt_score=0.9785, maxsub=0.9683.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9765, gdt_score=0.9766, maxsub=0.9702.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00262
 : : : : : : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*
