C; model_eva_score=0.899, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9878, gdt_score=0.9863, maxsub=0.9811.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9878, gdt_score=0.9863, maxsub=0.9811.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9822, gdt_score=0.9883, maxsub=0.9736.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.9, tm_score=0.9931, gdt_score=0.9961, maxsub=0.9909.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9777, gdt_score=0.9766, maxsub=0.9645.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9816, gdt_score=0.9844, maxsub=0.9741.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9730, gdt_score=0.9727, maxsub=0.9619.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9807, gdt_score=0.9863, maxsub=0.9728.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9760, gdt_score=0.9766, maxsub=0.9639.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9897, gdt_score=0.9883, maxsub=0.9862.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9897, gdt_score=0.9883, maxsub=0.9862.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9813, gdt_score=0.9805, maxsub=0.9717.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9843, gdt_score=0.9863, maxsub=0.9784.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9806, gdt_score=0.9766, maxsub=0.9710.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9690, gdt_score=0.9727, maxsub=0.9557.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9690, gdt_score=0.9727, maxsub=0.9557.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9725, gdt_score=0.9707, maxsub=0.9572.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9859, gdt_score=0.9844, maxsub=0.9815.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9709, gdt_score=0.9707, maxsub=0.9600.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00262
 : : : : : : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*
