C; model_eva_score=0.898, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9760, gdt_score=0.9766, maxsub=0.9661.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9822, gdt_score=0.9883, maxsub=0.9736.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9760, gdt_score=0.9766, maxsub=0.9661.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.9, tm_score=0.9864, gdt_score=0.9883, maxsub=0.9807.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9750, gdt_score=0.9727, maxsub=0.9641.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9906, gdt_score=0.9883, maxsub=0.9871.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9759, gdt_score=0.9746, maxsub=0.9644.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9851, gdt_score=0.9805, maxsub=0.9801.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9743, gdt_score=0.9785, maxsub=0.9626.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9814, gdt_score=0.9824, maxsub=0.9688.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9814, gdt_score=0.9824, maxsub=0.9688.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9918, gdt_score=0.9922, maxsub=0.9890.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9842, gdt_score=0.9824, maxsub=0.9773.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9737, gdt_score=0.9727, maxsub=0.9590.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9798, gdt_score=0.9844, maxsub=0.9708.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9798, gdt_score=0.9844, maxsub=0.9708.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9730, gdt_score=0.9746, maxsub=0.9575.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9801, gdt_score=0.9805, maxsub=0.9704.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9713, gdt_score=0.9727, maxsub=0.9594.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00262
 : : : : : : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*
