C; model_eva_score=0.9, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9843, gdt_score=0.9844, maxsub=0.9749.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9931, gdt_score=0.9961, maxsub=0.9909.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9864, gdt_score=0.9883, maxsub=0.9807.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9843, gdt_score=0.9844, maxsub=0.9749.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9787, gdt_score=0.9824, maxsub=0.9633.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9866, gdt_score=0.9902, maxsub=0.9798.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9763, gdt_score=0.9766, maxsub=0.9672.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9871, gdt_score=0.9902, maxsub=0.9781.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9783, gdt_score=0.9785, maxsub=0.9656.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9869, gdt_score=0.9883, maxsub=0.9828.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9869, gdt_score=0.9883, maxsub=0.9828.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9842, gdt_score=0.9824, maxsub=0.9777.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9867, gdt_score=0.9863, maxsub=0.9811.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.899, tm_score=0.9821, gdt_score=0.9785, maxsub=0.9727.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9736, gdt_score=0.9766, maxsub=0.9599.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9736, gdt_score=0.9766, maxsub=0.9599.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9746, gdt_score=0.9746, maxsub=0.9611.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.898, tm_score=0.9830, gdt_score=0.9824, maxsub=0.9746.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.897, tm_score=0.9741, gdt_score=0.9727, maxsub=0.9626.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00262
 : : : : : : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGQIEHIGYLGWFRQAPGKEREGVAALITYTGHTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*
