C;cover size:156; local alignment length=156 (original info = e5kbaB1	160	237.96	7.6e-42	156	56	100.00)
>P1;e5kbaB1
structureX:e5kbaB1: 4: : 159: : : : : 
---SELGKRLI-EAAENGN--KDRV-KDLIENGAD-V-NASD-SDGRTPLHHAAENGHAEVVALLIEK----GADV---NAKDSDGRTPLHHAAENGHDEVVLILLLK-GADVNAKDSDGRTPLHHAAENGHKRVVLVLILAGAD-VNTSDSDGRTPLDLAREHGNEEVVKALEK-----------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:63; local alignment length=63 (original info = d1z3xa1	83	-0.52	0.99	59	15	0.02)
>P1;d1z3xa1
structureX:d1z3xa1: 15: : 83: : : : : 
GNEK--SQLAASTLSTAGTEGYHLLQEFLKDSATFSP-PPAPWIRGQ--AYRLLFHSPEASVQAFLQQHYPQGV----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:237; local alignment length=237 (original info = e1oy3D1	220	285.67	8.9e-48	210	34	100.00)
>P1;e1oy3D1
structureX:e1oy3D1: 3: : 217: : : : : 
--------------------------------------GYVT-EDGDTALHLAVIHQHEPFLDFLLGF----SAGHEYLDLQNDLGQTALHLAAILGEASTVEKLYAA-GAGVLVAERGGHTALHLACRVRAHTCACVLLQPRPS-HPRD-AD--------------------------EDWRLQLEAENYDGHTPLHVAVIH-KDAEMVRLLRDAG-ADLNKPEPTCGRTPLHLAVEAQAASVLELLLKAGADPTARMYGGRTPLGSALLRPNPILARLLRAHGAPEP-----------------------------*

C;cover size:290; local alignment length=290 (original info = e5et0A1	327	391.69	4.4e-62	284	36	100.00)
>P1;e5et0A1
structureX:e5et0A1: 33: : 322: : : : : 
------ALPVH-HAARSGK--LHCL-RYLVEEVAL-PAVSRA-RNGATPAHDAAATGYLSCLQWLLTQG---GCRV---QEKDNSGATVLHLAARFGHPDVVKWLLYQGGANSAITTDTGALPIHYAAAKGDLPSLKLLVGHYPEGVNAQTNNGATPLYLACQEGHLEVTKYLVQECS-----ADPHLRAQDGMTPLHAAA-QMGHNPVLVWLVSFADVSFSEQDHD-GATAMHFAASRGHTKVLSWLLLHGAEIS-QDLWGGTPLHDAAENGELECCQILAVNGAGLDVRDHDGYTAADLAEFNGHTHCSRYLRT--*

C;query_length:298 num_of_temps:1 cover_ratio:0.52 cover:156 not_cover:142
>P1;2017-11-04_00000023_2_72
 : : : : : : : : : 
GPGSDLGKKLL-EAARAGQ--DDEV-RILMANGAD-V-NAAD-DVGVTPLHLAAQRGHLEIVEVLLKY----GADV---NAADLWGQTPLHLAATAGHLEIVEVLLKN-GADVNARDNIGHTPLHLAAWAGHLEIVEVLLKYGAD-VNAQDKFGKTPFDLAIDNGNEDIAEVLQKAAGGGSGGGDVNAYDEVGWTPLHRAA-W-GHLELVEKLLKNG-ADVNAADID-GYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAA*
