C;cover size:157; local alignment length=157 (original info = e4f6rD1	159	248.93	8.1e-44	157	87	100.00)
>P1;e4f6rD1
structureX:e4f6rD1: 1: : 157: : : : : 
--GSDLGKKLLEAARAGQDDEVRILMANGADV-NAEDDSGKTPLHLAAIKGHLEIVEVLLKH-GADV---NAADKMGDTPLHLAALYGHLEIVEVLLKN-GADVNATDTYGFTPLHLAADAGHLEIVEVLLKYGAD-VNAQDKFGKTAFDISIDNGNEDLAEILQK-----------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:237; local alignment length=237 (original info = e1oy3D1	220	285.67	8.9e-48	210	34	100.00)
>P1;e1oy3D1
structureX:e1oy3D1: 3: : 217: : : : : 
---------------------------------GYVTEDGDTALHLAVIHQHEPFLDFLLGF-SAGHEYLDLQNDLGQTALHLAAILGEASTVEKLYAA-GAGVLVAERGGHTALHLACRVRAHTCACVLLQPRPS-HPRD-AD--------------------------EDWRLQLEAENYDGHTPLHVAVIH-KDAEMVRLLRDAG-ADLNKPEPTCGRTPLHLAVEAQAASVLELLLKAGADPTARMYGGRTPLGSALLRPNPILARLLRAHGAPEP-----------------------------*

C;cover size:290; local alignment length=290 (original info = e5et0A1	327	391.69	4.4e-62	284	36	100.00)
>P1;e5et0A1
structureX:e5et0A1: 33: : 322: : : : : 
------ALPVHHAARSGKLHCLRYLVEEVALPAVSRARNGATPAHDAAATGYLSCLQWLLTQGGCRV---QEKDNSGATVLHLAARFGHPDVVKWLLYQGGANSAITTDTGALPIHYAAAKGDLPSLKLLVGHYPEGVNAQTNNGATPLYLACQEGHLEVTKYLVQECS-----ADPHLRAQDGMTPLHAAA-QMGHNPVLVWLVSFADVSFSEQDHD-GATAMHFAASRGHTKVLSWLLLHGAEIS-QDLWGGTPLHDAAENGELECCQILAVNGAGLDVRDHDGYTAADLAEFNGHTHCSRYLRT--*

C;query_length:298 num_of_temps:1 cover_ratio:0.53 cover:157 not_cover:141
>P1;2017-11-04_00000023_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADV-NAADDVGVTPLHLAAQRGHLEIVEVLLKY-GADV---NAADLWGQTPLHLAATAGHLEIVEVLLKN-GADVNARDNIGHTPLHLAAWAGHLEIVEVLLKYGAD-VNAQDKFGKTPFDLAIDNGNEDIAEVLQKAAGGGSGGGDVNAYDEVGWTPLHRAA-W-GHLELVEKLLKNG-ADVNAADID-GYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAA*
