C;cover size:291; local alignment length=291 (original info = e3picB1	366	98.05	4.6e-18	245	14	99.45)
>P1;e3picB1
structureX:e3picB1: 82: : 366: : : : : 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SFTVTITYPSSG--TAPYPAIIG--YGGG--S-------------------------------------------------------------LPAPAGVAMINFNNDNIAAQVNTGSRGQGKFYDLYGSSHSAGAMTAWAWGVSRVIDALE---------------LVPGARIDTTKIGVTGCSRNGKGAMVAGAFE--KRIVLTLPQESGAGGSACWRISDYLKS---QGA---NIQTASEIIGED---------PWFSTTFNSY---VNQV------------------------------PVLPFDHHSLAALIA-PRGLFVIDNNIDWLGPQSCFGCMTAAHMAWQALGVSDH-MGY--SQI-GAHAHCAFPSN---QQSQLTAFVQKFLLGQS--T-NTAIFQS-------DFSANQSQWIDWTTPTLS---*

C;cover size:446; local alignment length=446 (original info = e2bklA2	411	663.21	1.9e-88	408	25	100.00)
>P1;e2bklA2
structureX:e2bklA2: 1: : 411: : : : : 
----------SYPA-TRAEQVVDTLHGVQ-----VADPYRWLEDEKAPEVQTWMTAQNAHAREALAKFPGREALAARFKELFYTDSVSTPSRRN-GRFFYVRTHKDKEKAILYWRQG---------ESGQEKVLLDPNGWSKDGTVSLGTWAVSWDGKKVAFAQKPNAADEAVLHVIDVDSGEWSKV----------DVIEGGKYATPKWTPDSKGFYYEWLPTDPSIKVDERPGYTTIRYHTLGTEPSKDTVVHERTGD--P-TTFLQSDLSRDGKYLFVYILR-GWSEN-DVYWKRPGEK--------DFRLLVKGV-GAKYEVHAWKDRFYVLTDEGA--------PRQRVFEVDPAKPARASWKEIVPEDSSASLLSVSIV-GGHLSLEYLKDATSEVRVATLKGKPVRT-VQLPG-VGAASNLMGLEDLDDAYYVFTSFTTPRQIYKTSVSTGKS---ELWAKVDVP-MNP-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:446; local alignment length=446 (original info = e2bklA2	411	663.21	1.9e-88	408	25	100.00)
>P1;e2bklA2
structureX:e2bklA2: 1: : 411: : : : : 
----------SYPA-TRAEQVVDTLHGVQ-----VADPYRWLEDEKAPEVQTWMTAQNAHAREALAKFPGREALAARFKELFYTDSVSTPSRRN-GRFFYVRTHKDKEKAILYWRQG---------ESGQEKVLLDPNGWSKDGTVSLGTWAVSWDGKKVAFAQKPNAADEAVLHVIDVDSGEWSKV----------DVIEGGKYATPKWTPDSKGFYYEWLPTDPSIKVDERPGYTTIRYHTLGTEPSKDTVVHERTGD--P-TTFLQSDLSRDGKYLFVYILR-GWSEN-DVYWKRPGEK--------DFRLLVKGV-GAKYEVHAWKDRFYVLTDEGA--------PRQRVFEVDPAKPARASWKEIVPEDSSASLLSVSIV-GGHLSLEYLKDATSEVRVATLKGKPVRT-VQLPG-VGAASNLMGLEDLDDAYYVFTSFTTPRQIYKTSVSTGKS---ELWAKVDVP-MNP-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:765 num_of_temps:1 cover_ratio:0.38 cover:291 not_cover:474
>P1;2017-10-28_00000021_1_72
 : : : : : : : : : 
MSSVT-WAPGNYPS-TRRSDHVDTYQSASKGEVPVPDPYQWLEE-STDEVDKWTTAQADLAQSYLDQNADIQKLAEKFRASRNYAKFSAPTLLDDGHWYWFYNRGLQSQSVLYRSKEPALPDFSKGDDNVGDVFFDPNVLAADGSAGMVLCKFSPDGKFFAYAVSHLGGDYSTIYVRSTSSPLSQASVAQGVDGRLSDEVKWFKFSTIIWTKDSKGFLYQRYPARERHEGTRSDRNAMMCYHKVGTTQEEDIIVYQDNEH--P-EWIYGADTSEDGKYLYLYQFK-DTSKKNLLWVAELDEDGV--KSGIHWRKVVNEYAADYNIITNHGSLVYIKTNLNA--------PQYKVITIDLSKDE-PEIRDFIPEEKDAKLAQVNCANEEYFVAIYKRNVKDEIYLYSKAGVQLTR-LAPDF-VG-AASIANRQKQTHFFLTLSGFNTPGTIARYDFTAPETQRFSILRTTKVNELDPDDFESTQVWYES-----KDGT--KIPMFIVRHKSTKFDGTAAAIQY--GYGG--FATSA-----------------------------------DPFF------------SPIILTFLQTYGAIFAVPSIRGG------GEFGE-EWHKG-G-RRETKVNTF--DDFIAAAQFLV---------------KNKY--AAPGKVAINGASNGGLLVMGSIVRAPEGTFGAAVPEGG----VADLL-----KF---HKF---T-------GGQ----------AWIS----EY---G-NP-SIPEEF-------------------DYIYPLSPVHN--VRTDKVMP-ATLITVNIGDGRVVPMHSFKFIAT--LQHNVPQNPHPLLIKIDKSWLGAGMGKPTDKNVKDAADKWGFIARALGLELKTVEMFDTNATRLPIWGIGCNPWTAEHVDQTLASGNDIC*
