C;cover size:270; local alignment length=270 (original info = e3zpxA1	382	133.25	4.9e-16	246	13	99.41)
>P1;e3zpxA1
structureX:e3zpxA1: 37: : 375: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------NKVEAFQLQYRTTNTQKEAQANVATVWIPNK--PASPPKIFSYQVYQDSTQLNCAPSYSFLKGLDKPNKATTILEAPIIIGWALQQ-GFYVVSSDHEGP------R---S-SF--------IAGYEEG--MAILDGIRALKNYAKL--PTDSAIGFYGYSGGAHATGWAANLAGSYAPEHNIIGAAYGGL----PASAR-----DTFNFLNKGAF-------AGFAIAGVSGLA-LAYPDVETYIQSRL-NAKGEKVFKQVRSRGFCIGQVVLTYPFVDAYSLINDTNLLNEEPVASTLKSETLVQAEASYT--VPVPKF---PRFIWHALLDEIVPFHSAATYVKE--QCSK----GADINWNVY-SFAEHISAE-----LFGLLPGLDWLNKAYKGQ----------------------------------------*

C;cover size:446; local alignment length=446 (original info = e2bklA2	411	663.21	1.9e-88	408	25	100.00)
>P1;e2bklA2
structureX:e2bklA2: 1: : 411: : : : : 
----------SYPA-TRAEQVVDTLHGVQ-----VADPYRWLEDEKAPEVQTWMTAQNAHAREALAKFPGREALAARFKELFYTDSVSTPSRRN-GRFFYVRTHKDKEKAILYWRQG---------ESGQEKVLLDPNGWSKDGTVSLGTWAVSWDGKKVAFAQKPNAADEAVLHVIDVDSGEWSKV----------DVIEGGKYATPKWTPDSKGFYYEWLPTDPSIKVDERPGYTTIRYHTLGTEPSKDTVVHERTGD--P-TTFLQSDLSRDGKYLFVYILR-GWSEN-DVYWKRPGEK--------DFRLLVKGV-GAKYEVHAWKDRFYVLTDEGA--------PRQRVFEVDPAKPARASWKEIVPEDSSASLLSVSIV-GGHLSLEYLKDATSEVRVATLKGKPVRT-VQLPG-VGAASNLMGLEDLDDAYYVFTSFTTPRQIYKTSVSTGKS---ELWAKVDVP-MNP-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:446; local alignment length=446 (original info = e2bklA2	411	663.21	1.9e-88	408	25	100.00)
>P1;e2bklA2
structureX:e2bklA2: 1: : 411: : : : : 
----------SYPA-TRAEQVVDTLHGVQ-----VADPYRWLEDEKAPEVQTWMTAQNAHAREALAKFPGREALAARFKELFYTDSVSTPSRRN-GRFFYVRTHKDKEKAILYWRQG---------ESGQEKVLLDPNGWSKDGTVSLGTWAVSWDGKKVAFAQKPNAADEAVLHVIDVDSGEWSKV----------DVIEGGKYATPKWTPDSKGFYYEWLPTDPSIKVDERPGYTTIRYHTLGTEPSKDTVVHERTGD--P-TTFLQSDLSRDGKYLFVYILR-GWSEN-DVYWKRPGEK--------DFRLLVKGV-GAKYEVHAWKDRFYVLTDEGA--------PRQRVFEVDPAKPARASWKEIVPEDSSASLLSVSIV-GGHLSLEYLKDATSEVRVATLKGKPVRT-VQLPG-VGAASNLMGLEDLDDAYYVFTSFTTPRQIYKTSVSTGKS---ELWAKVDVP-MNP-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:765 num_of_temps:1 cover_ratio:0.35 cover:270 not_cover:495
>P1;2017-10-28_00000021_1_72
 : : : : : : : : : 
MSSVT-WAPGNYPS-TRRSDHVDTYQSASKGEVPVPDPYQWLEE-STDEVDKWTTAQADLAQSYLDQNADIQKLAEKFRASRNYAKFSAPTLLDDGHWYWFYNRGLQSQSVLYRSKEPALPDFSKGDDNVGDVFFDPNVLAADGSAGMVLCKFSPDGKFFAYAVSHLGGDYSTIYVRSTSSPLSQASVAQGVDGRLSDEVKWFKFSTIIWTKDSKGFLYQRYPARERHEGTRSDRNAMMCYHKVGTTQEEDIIVYQDNEH--P-EWIYGADTSEDGKYLYLYQFK-DTSKKNLLWVAELDEDGV--KSGIHWRKVVNEYAADYNIITNHGSLVYIKTNLNA--------PQYKVITIDLSKDE-PEIRDFIPEEKDAKLAQVNCANEEYFVAIYKRNVKDEIYLYSKAGVQLTR-LAPDF-VG-AASIANRQKQTHFFLTLSGFNTPGTIARYDFTAPETQRFSILRTTKVNELDPDDFESTQVWYESKD--GTKIP--MFIVRHKSTKFDGTAAAIQYGYGGFATS--ADPFFS------------------PIILTFLQTYGAIFAVPSIRGG------GEFGE-EWHKG-G-RRETKVNTF--DDFIAAAQFLVK-NKY--AAPGKVAINGASNGGLLVMGSIVR----APEGTFGAAVPEGG----VADLL-----KFHK-----FT-------GG---------Q-AWIS-------EYG-NPS--------------------------------------IPEEFDYIYPLS-----PVHN--VRTDKVMP-ATLITVNIGDGRVVPMHSFKFIAT--LQHNVPQNPHPLLIKIDKSWLGAGMGKPTDKNVKDAADKWGFIARALGLELKTVEMFDTNATRLPIWGIGCNPWTAEHVDQTLASGNDIC*
