C;cover size:271; local alignment length=271 (original info = e1lnsA3	405	155.79	7.6e-19	250	19	99.60)
>P1;e1lnsA3
structureX:e1lnsA3: 16: : 377: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------FDSSLLEREVLWVESPVDSEQRGENDLIKIQIIRPKS---TEKLPVVMTASPYHLGINDKANDLALHDMNVELEEKTSHEIHVEQKLPQKLSAKAKELPIVDKAPYRFTHGWTYSLNDYFLTR-GFASIYVAGVG------T------RSSDG-FQT--------SGDYQQI--YSMTAVIDWLNGRARAYTSRKKTHEIKASW--AN-GKVAMTGKSYLGTMAYGAATTGVEG-LELILAEAG----ISS--WY-----NYYRENGLVRSP-------GGFPGEDLDVLAALTYS----RNLDGA-DFLKGNAEYEKRLAEMTAALDRKSGDYNQFWHDRNYLIN--TDKVKA---DVLIVHGLQDWNVTP--EQAYNFWKA--LPEG---HAKHAFLH---R-GAHIYMNS-WQSIDFSETINAYFVAKLL------------------------------------------*

C;cover size:271; local alignment length=271 (original info = e1lnsA3	405	155.79	7.6e-19	250	19	99.60)
>P1;e1lnsA3
structureX:e1lnsA3: 16: : 377: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------FDSSLLEREVLWVESPVDSEQRGENDLIKIQIIRPKS---TEKLPVVMTASPYHLGINDKANDLALHDMNVELEEKTSHEIHVEQKLPQKLSAKAKELPIVDKAPYRFTHGWTYSLNDYFLTR-GFASIYVAGVG------T------RSSDG-FQT--------SGDYQQI--YSMTAVIDWLNGRARAYTSRKKTHEIKASW--AN-GKVAMTGKSYLGTMAYGAATTGVEG-LELILAEAG----ISS--WY-----NYYRENGLVRSP-------GGFPGEDLDVLAALTYS----RNLDGA-DFLKGNAEYEKRLAEMTAALDRKSGDYNQFWHDRNYLIN--TDKVKA---DVLIVHGLQDWNVTP--EQAYNFWKA--LPEG---HAKHAFLH---R-GAHIYMNS-WQSIDFSETINAYFVAKLL------------------------------------------*

C;cover size:446; local alignment length=446 (original info = e2bklA2	411	663.21	1.9e-88	408	25	100.00)
>P1;e2bklA2
structureX:e2bklA2: 1: : 411: : : : : 
----------SYPA-TRAEQVVDTLHGVQ-----VADPYRWLEDEKAPEVQTWMTAQNAHAREALAKFPGREALAARFKELFYTDSVSTPSRRN-GRFFYVRTHKDKEKAILYWRQG---------ESGQEKVLLDPNGWSKDGTVSLGTWAVSWDGKKVAFAQKPNAADEAVLHVIDVDSGEWSKV----------DVIEGGKYATPKWTPDSKGFYYEWLPTDPSIKVDERPGYTTIRYHTLGTEPSKDTVVHERTGD--P-TTFLQSDLSRDGKYLFVYILR-GWSEN-DVYWKRPGEK--------DFRLLVKGV-GAKYEVHAWKDRFYVLTDEGA--------PRQRVFEVDPAKPARASWKEIVPEDSSASLLSVSIV-GGHLSLEYLKDATSEVRVATLKGKPVRT-VQLPG-VGAASNLMGLEDLDDAYYVFTSFTTPRQIYKTSVSTGKS---ELWAKVDVP-MNP----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:446; local alignment length=446 (original info = e2bklA2	411	663.21	1.9e-88	408	25	100.00)
>P1;e2bklA2
structureX:e2bklA2: 1: : 411: : : : : 
----------SYPA-TRAEQVVDTLHGVQ-----VADPYRWLEDEKAPEVQTWMTAQNAHAREALAKFPGREALAARFKELFYTDSVSTPSRRN-GRFFYVRTHKDKEKAILYWRQG---------ESGQEKVLLDPNGWSKDGTVSLGTWAVSWDGKKVAFAQKPNAADEAVLHVIDVDSGEWSKV----------DVIEGGKYATPKWTPDSKGFYYEWLPTDPSIKVDERPGYTTIRYHTLGTEPSKDTVVHERTGD--P-TTFLQSDLSRDGKYLFVYILR-GWSEN-DVYWKRPGEK--------DFRLLVKGV-GAKYEVHAWKDRFYVLTDEGA--------PRQRVFEVDPAKPARASWKEIVPEDSSASLLSVSIV-GGHLSLEYLKDATSEVRVATLKGKPVRT-VQLPG-VGAASNLMGLEDLDDAYYVFTSFTTPRQIYKTSVSTGKS---ELWAKVDVP-MNP----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:765 num_of_temps:1 cover_ratio:0.33 cover:256 not_cover:509
>P1;2017-10-28_00000021_1_72
 : : : : : : : : : 
MSSVT-WAPGNYPS-TRRSDHVDTYQSASKGEVPVPDPYQWLEE-STDEVDKWTTAQADLAQSYLDQNADIQKLAEKFRASRNYAKFSAPTLLDDGHWYWFYNRGLQSQSVLYRSKEPALPDFSKGDDNVGDVFFDPNVLAADGSAGMVLCKFSPDGKFFAYAVSHLGGDYSTIYVRSTSSPLSQASVAQGVDGRLSDEVKWFKFSTIIWTKDSKGFLYQRYPARERHEGTRSDRNAMMCYHKVGTTQEEDIIVYQDNEH--P-EWIYGADTSEDGKYLYLYQFK-DTSKKNLLWVAELDEDGV--KSGIHWRKVVNEYAADYNIITNHGSLVYIKTNLNA--------PQYKVITIDLSKDE-PEIRDFIPEEKDAKLAQVNCANEEYFVAIYKRNVKDEIYLYSKAGVQLTR-LAPDF-VG-AASIANRQKQTHFFLTLSGFNTPGTIARYDFTAPETQRFSILRTTKVNELDPDDFESTQVWYES-----KDGT--KIPMFIVRHKSTKFDGTAAAIQY--GYGG--FATSA-----------------------------------DPFF------------SPIILTFLQTYGAIFAVPSIRG------G------GEFGE-EWHKG-G--RRETKVNTF--DDFIAAAQFLV---------------KNKY--AAPGKVAINGASNGGLLVMGSIVRAPEGTFGAAVPEGG----VAD--LL-----KF---HKF---T-------GGQ----------AWIS----EY---G-NP-SIPEEF-------------------DYIYPLSPVHN--VRTDKVMP-ATLITVNIGDGRVVP--MHSFKFIAT--LQHNVPQNPHPLLIKIDKSWLGAGMGKPTDKNVKDAADKWGFIARALGLELKTVEMFDTNATRLPIWGIGCNPWTAEHVDQTLASGNDIC*
