C; model_eva_score=0.063, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 285: : : : : 
MVVNNALNFDSTPTNAKKHQPQKPDKTALEKIIQGIMPAHAAGAMTNPQDKDAAIWISNIRNGITGPIVITSYGVYAAGWTAPLIGTAGKLAISTCMANPSGCTVMVTQAAEAGAGIATGAVTVGNAWEAPVGALSKAKAAKQAIPTQTVKELDGLLQESKNIGAVNTRINIANSTTRYTPMRQTGQPVSAGFEHVLEGHFHRPIANNRSVFTISPNELKVILQSNKVVSSPVSMTPDGQYMRTVDVGKVIGTTSIKEGGQPTTTIKVFTDKSGNLITTYPVKGN*

C; model_eva_score=0.063, tm_score=0.7387, gdt_score=0.5965, maxsub=0.5659.
>P1;meta_super2.pdb1
structureX:meta_super2.pdb: 108: : 162: : : : : 
-----------------------------------------------------------------------------------------------------------TQAAEAGAGIATGAVTVGNAWEAPVGALSKAKAAKQAIPTQTVKELDGLLQESKN---------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;T9999s1
 : : : : : : : : : 
MVVNNALNFDSTPTNAKKHQPQKPDKTALEKIIQGIMPAHAAGAMTNPQDKDAAIWISNIRNGITGPIVITSYGVYAAGWTAPLIGTAGKLAISTCMANPSGCTVMVTQAAEAGAGIATGAVTVGNAWEAPVGALSKAKAAKQAIPTQTVKELDGLLQESKNIGAVNTRINIANSTTRYTPMRQTGQPVSAGFEHVLEGHFHRPIANNRSVFTISPNELKVILQSNKVVSSPVSMTPDGQYMRTVDVGKVIGTTSIKEGGQPTTTIKVFTDKSGNLITTYPVKGN*
