C;cover size:73; local alignment length=73 (original info = d3b2ua1	169	11.51	0.028	64	16	1.47)
>P1;d3b2ua1
structureX:d3b2ua1: 104: : 169: : : : : 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------AVVSLNITSLG---LRSLKEISDGDVIISGNKNLCYANTINWKK-LFGTSGQ-----KTK-IISNRGENSCKATGQ---------------*

C;cover size:228; local alignment length=228 (original info = e3m18A1	245	332.81	5.6e-53	227	43	100.00)
>P1;e3m18A1
structureX:e3m18A1: 13: : 241: : : : : 
---------------GKKEVDCQGKSLDSVPSGIPADTEKLDLQSTGLATLSDATFRGLTKLTWLNLDYNQLQTLSAGVFDDLTELGTLGLANNQLASLPLGVFDHLTQLDKLYLGGNQLKSLPSGVFDRLTKLKELRLNTNQLQSIPAGAFDKLTNLQTLSLSTNQLQSVPHGAFDRLGKLQ--TITLFGNQFDCSRCETLYLSQWIRENSNKVKDGTGQNLHESPDGVTCSD-GKVVRTVTNETL-----*

C;cover size:233; local alignment length=233 (original info = e3wo9A1	223	283.93	1.1e-45	202	50	100.00)
>P1;e3wo9A1
structureX:e3wo9A1: 22: : 223: : : : : 
---------------SPETVDCSSKKLTAVPTGIPANTEKLQLDFNQLANIPAEAFHGLTRLTYLALDYNQLQSLPVGVFDQLNNLNELRLQDNQLTSLPPGVFDSLTKLTYLTLSQNQLQSIPAGVFDKL------------------------TNLNRLELSTNQLQSVPHGAFDSLVNLE--TLHLELNPWDCACSDIIYLRTFIAKNTDK---------ISGMESAQCNGTSTAVKDVNTEKIKNVTC*

C;query_length:248 num_of_temps:1 cover_ratio:0.29 cover:73 not_cover:175
>P1;2017-10-14_00000088_1_71
 : : : : : : : : : 
HHHHHHGGCPSQCSCRGTYVDCDSRRLASVPAGIPTNVQILNLYNNQITNLEPGVFDRLVNLQKLYLSGNQLQALPVGVFDKLSQLTFLSLDENKLTALPNGVFDKLTELTYLNLNTNQLTALPEGVFDRLVHLKELLMCCNKLTELPR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLT--HAYLFGNPWDCECRDIMYLRNWVADHTSIVMRWDGK-AVNDPDSAKCAGTNTPVRAVTEASTSPSKC*
