C;cover size:233; local alignment length=233 (original info = e3e6jA1	219	338.18	1e-54	209	85	100.00)
>P1;e3e6jA1
structureX:e3e6jA1: 10: : 218: : : : : 
---------------SGTTVDCRSKRHASVPAGIPTNAQILYLHDNQITKLEPG-VFDSLINLKELYLGSNQLGALPVGVFDSLTQLTVLDLGTNQLTVLPS------------------------AVFDRLVH------------------------LKELFMCCNKLTEL--PR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLT----HAYLFGNPWDCECRDIMYLRNWVADHTSIAMRWDGK-AVNDPDSAKCAG----TNTPVRAVTEAS--TSPSKC*

C;cover size:233; local alignment length=233 (original info = e2r9uA1	174	262.74	6.6e-44	162	77	100.00)
>P1;e2r9uA1
structureX:e2r9uA1: 13: : 174: : : : : 
---------------DQTLVNCQNIRLASVPAGIPTDKQRLWLNNNQITKLEPG-VFDHLVNLQQLYFNSNKLTAIPTGVFDKLTQLTQLDLNDNHLKSIPR------------------------GAF--------------------------------------------------------------------------DNLKSLT----HIYLYNNPWDCECRDIMYLRNWVADHTSIVMRWDGK-AVNDPDSAKCAG----TNTPVRAVTEAS--TSPSKC*

C;cover size:233; local alignment length=233 (original info = e4k5uB1	218	332.94	6.8e-54	209	63	100.00)
>P1;e4k5uB1
structureX:e4k5uB1: 9: : 217: : : : : 
---------------SGTEVNCAGKSLASVPAGIPTTTRVLYLNSNQITKLEPG-VFDRLANLRELHLWGNQLVSLPPGVFDNLANLEKLWLNSNQLTSLPA------------------------GLFDRLVNLEHLGLCCMKLTELPSGAFDKLT--------------------------RLKQLGLDQNQLKSIPDGAFARLPSLT----HVWLHTNPWDCQCTDILYLSGWVAQHSSIVG-EGWP-WRHSPDSAKCSG----TNTPVRAVTEAS--TSPSKC*

C;cover size:228; local alignment length=228 (original info = e2o6qA1	270	306.44	4.4e-48	221	43	100.00)
>P1;e2o6qA1
structureX:e2o6qA1: 17: : 262: : : : : 
---------------NKNSVDCSSKKLTAIPSNIPADTKKLDLQSNKLSSLPSK-AFHRLTKLRLLYLNDNKLQTLPAGIFKELKNLETLWVTDNKLQALPIGVFDQLVNLAELRLDRNQLKSLPPRVFDSLTKLTYLSLGYNELQSLPKGVFDKLTSLKELRLYNNQLKRV--PEGAFDKLTELKTLKLDNNQLKRVPEGAFDSLEKLK----MLQLQENPWDCTCNGIIYMAKWLKKKADE--------GLGGVDTAGCEK----GGKAVLEITEKD--A-----*

C;cover size:233; local alignment length=233 (original info = e1w8aA1	189	228.52	1.5e-37	174	31	100.00)
>P1;e1w8aA1
structureX:e1w8aA1: 9: : 189: : : : : 
---------------EGTTVDCTGRGLKEIPRDIPLHTTELLLNDNELGRISSDGLFGRLPHLVKLELKRNQLTGIEPNAFEGASHIQELQLGENKIKEISN------------------------KMFLGLH--------------------------------------------------QLKTLNLYDNQISCVMPGSFEHLNSLT----SLNLASNPFNCNCH-LAWFAEWLRKKSLN------------GGAARCGAPSKVRDVQIKDLPHSEFKCSSEGC*

C;cover size:228; local alignment length=228 (original info = e3m18A1	245	332.81	5.6e-53	227	43	100.00)
>P1;e3m18A1
structureX:e3m18A1: 13: : 241: : : : : 
---------------GKKEVDCQGKSLDSVPSGIPADTEKLDLQSTGLATLSDA-TFRGLTKLTWLNLDYNQLQTLSAGVFDDLTELGTLGLANNQLASLPL------------------------GVFDHLTQLDKLYLGGNQLKSLPSGVFDRLTKLKELRLNTNQLQSI--PAGAFDKLTNLQTLSLSTNQLQSVPHGAFDRLGKLQ----TITLFGNQFDCSRCETLYLSQWIRENSNKVKDGTGQNLHESPDGVTCSD-----GKVVRTVTNET--L-----*

C;cover size:194; local alignment length=194 (original info = e2v9tB1	210	264.46	6.9e-43	170	31	100.00)
>P1;e2v9tB1
structureX:e2v9tB1: 12: : 181: : : : : 
---------------SNNIVDCRGKGLTEIPTNLPETITEIRLEQNTIKVIPPG-AFSPYKKLRRIDLSNNQISELAPDAFQGLRSLNSLVLYGNKITELPK------------------------SLFEGLFSLQLLLLNANKINCLRVDAFQDL--------------------------HNLNLLSLYDNKLQTIAKGTFSPLRAIQ----TMHLAQNPFICDCH-LKWLADYLHTNP----------------------------------------------*

C;cover size:223; local alignment length=223 (original info = e2o6sA1	208	297.08	2.5e-48	198	54	100.00)
>P1;e2o6sA1
structureX:e2o6sA1: 8: : 205: : : : : 
---------------SGTTVECYSQGRTSVPTGIPAQTTYLDLETNSLKSLPNG-VFDELTSLTQLYLGGNKLQSLPNGVFNKLTSLTYLNLSTNQLQSLPN------------------------GVFDKLTQLKELALNTNQLQSLPDGVFDKLT--------------------------QLKDLRLYQNQLKSVPDGVFDRLTSLQ----YIWLHDNPWDCTCPGIRYLSEWINKHSGVVRN--SA-GSVAPDSAKCSG----SGKPVRSI------------*

C;cover size:177; local alignment length=177 (original info = e2z64A1	264	230.32	3.1e-36	177	25	99.97)
>P1;e2z64A1
structureX:e2z64A1: 7: : 189: : : : : 
---------------PNITYQCMDQKLSKVPDDIPSSTKNIDLSFNPLKILKSY-SFSNFSELQWLDLSRCEIETIEDKAWHGLHHLSNLILTGNPIQSFSP------------------------GSFSGLTSLENLVAVETKLASLESFPIGQLITLKKLNVAHNFIHSCKLPA-YFSNLTNLVHVDLSYNYIQTITVNDLQFLRENPQVNLSLDMSLNPID---------------------------------------------------------------*

C;query_length:248 num_of_temps:1 cover_ratio:0.94 cover:233 not_cover:15
>P1;2017-10-14_00000088_1_71
 : : : : : : : : : 
HHHHHHGGCPSQCSCRGTYVDCDSRRLASVPAGIPTNVQILNLYNNQITNLEPG-VFDRLVNLQKLYLSGNQLQALPVGVFDKLSQLTFLSLDENKLTALPN------------------------GVFDKLTELTYLNLNTNQLTALPEGVFDRLVHLKELLMCCNKLTEL--PR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLT----HAYLFGNPWDCECRDIMYLRNWVADHTSIVMRWDGK-AVNDPDSAKCAG----TNTPVRAVTEAS--TSPSKC*
