C; model_eva_score=0.875, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.878, tm_score=0.9775, gdt_score=0.9753, maxsub=0.9645.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9978, gdt_score=0.9985, maxsub=0.9959.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.877, tm_score=0.9747, gdt_score=0.9753, maxsub=0.9609.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9787, gdt_score=0.9782, maxsub=0.9648.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9774, gdt_score=0.9738, maxsub=0.9623.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9774, gdt_score=0.9738, maxsub=0.9623.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9952, gdt_score=0.9971, maxsub=0.9910.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.875, tm_score=0.9791, gdt_score=0.9797, maxsub=0.9667.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9826, gdt_score=0.9797, maxsub=0.9689.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9938, gdt_score=0.9971, maxsub=0.9889.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9925, gdt_score=0.9927, maxsub=0.9860.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9927, gdt_score=0.9956, maxsub=0.9850.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9909, gdt_score=0.9913, maxsub=0.9818.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9806, gdt_score=0.9797, maxsub=0.9669.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9734, gdt_score=0.9680, maxsub=0.9533.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9734, gdt_score=0.9680, maxsub=0.9533.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9756, gdt_score=0.9738, maxsub=0.9594.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9821, gdt_score=0.9840, maxsub=0.9711.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9810, gdt_score=0.9826, maxsub=0.9698.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C;total number of template models = 20
>P1;C00231
 : : : : : : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*
