C; model_eva_score=0.876, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.878, tm_score=0.9774, gdt_score=0.9767, maxsub=0.9647.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9787, gdt_score=0.9767, maxsub=0.9630.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.877, tm_score=0.9753, gdt_score=0.9753, maxsub=0.9618.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.875, tm_score=0.9978, gdt_score=0.9985, maxsub=0.9959.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9784, gdt_score=0.9738, maxsub=0.9643.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9784, gdt_score=0.9738, maxsub=0.9643.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9958, gdt_score=0.9971, maxsub=0.9920.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.875, tm_score=0.9809, gdt_score=0.9811, maxsub=0.9700.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9834, gdt_score=0.9811, maxsub=0.9702.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9953, gdt_score=0.9985, maxsub=0.9913.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9936, gdt_score=0.9942, maxsub=0.9883.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9948, gdt_score=0.9971, maxsub=0.9908.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9927, gdt_score=0.9927, maxsub=0.9846.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9806, gdt_score=0.9811, maxsub=0.9671.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9747, gdt_score=0.9709, maxsub=0.9555.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9747, gdt_score=0.9709, maxsub=0.9555.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9758, gdt_score=0.9738, maxsub=0.9625.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9811, gdt_score=0.9826, maxsub=0.9695.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9803, gdt_score=0.9797, maxsub=0.9688.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C;total number of template models = 20
>P1;C00231
 : : : : : : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*
