C; model_eva_score=0.876, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.878, tm_score=0.9899, gdt_score=0.9898, maxsub=0.9844.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9787, gdt_score=0.9767, maxsub=0.9630.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.877, tm_score=0.9839, gdt_score=0.9840, maxsub=0.9729.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.875, tm_score=0.9787, gdt_score=0.9782, maxsub=0.9648.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9837, gdt_score=0.9797, maxsub=0.9705.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9837, gdt_score=0.9797, maxsub=0.9705.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9786, gdt_score=0.9753, maxsub=0.9627.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.875, tm_score=0.9851, gdt_score=0.9811, maxsub=0.9720.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9864, gdt_score=0.9840, maxsub=0.9755.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9778, gdt_score=0.9767, maxsub=0.9622.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9792, gdt_score=0.9753, maxsub=0.9657.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9768, gdt_score=0.9738, maxsub=0.9617.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9748, gdt_score=0.9738, maxsub=0.9590.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9844, gdt_score=0.9869, maxsub=0.9740.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9756, gdt_score=0.9753, maxsub=0.9543.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9756, gdt_score=0.9753, maxsub=0.9543.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9786, gdt_score=0.9782, maxsub=0.9651.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9826, gdt_score=0.9797, maxsub=0.9683.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9826, gdt_score=0.9826, maxsub=0.9672.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C;total number of template models = 20
>P1;C00231
 : : : : : : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*
