C; model_eva_score=0.878, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9899, gdt_score=0.9898, maxsub=0.9844.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9774, gdt_score=0.9767, maxsub=0.9647.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.877, tm_score=0.9903, gdt_score=0.9855, maxsub=0.9810.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.875, tm_score=0.9775, gdt_score=0.9753, maxsub=0.9645.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9893, gdt_score=0.9826, maxsub=0.9818.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.876, tm_score=0.9893, gdt_score=0.9826, maxsub=0.9818.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9776, gdt_score=0.9753, maxsub=0.9652.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.875, tm_score=0.9858, gdt_score=0.9855, maxsub=0.9721.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9843, gdt_score=0.9840, maxsub=0.9716.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9775, gdt_score=0.9767, maxsub=0.9642.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9772, gdt_score=0.9738, maxsub=0.9640.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9765, gdt_score=0.9767, maxsub=0.9620.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9739, gdt_score=0.9709, maxsub=0.9581.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.874, tm_score=0.9878, gdt_score=0.9869, maxsub=0.9789.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9806, gdt_score=0.9782, maxsub=0.9618.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9806, gdt_score=0.9782, maxsub=0.9618.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9846, gdt_score=0.9840, maxsub=0.9699.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.873, tm_score=0.9830, gdt_score=0.9826, maxsub=0.9683.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C; model_eva_score=0.872, tm_score=0.9854, gdt_score=0.9826, maxsub=0.9718.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 172: : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*

C;total number of template models = 20
>P1;C00231
 : : : : : : : : : 
HGFIEKPGSRAALCSEAFGFLNLNCGSVMYEPQSLEAKKGFPHSGPADGQIASAGGLFGGILDQQSENRWFKHIMTGGEHTFTWTYTAPHNTSQWHYYITKKGWDPDKPLKRADFELIGAVPHDGSPASRNLSHHIYIPEDRLGYHVILAVWDVADTENAFYQVIDVDLVNK*
