C; model_eva_score=0.082, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 618: : : : : 
MNDTLLNAYSGIKTHQFGIDSLSNNIANVNTLGYRSNDPEFKTLFSSHLDALNAKSVVTNDRNYGVTGSGNVLSNKDGEYMPSEGEFHMAYQGKGWFVIGPNKNGEMTINKDGFSKKQDNFLTRAGNFARDADGYLVTPEGYYVYGIDLKKIKDGTLNSTARDEDIEKLHGNTLSPLQIPQDLTYQPVLSTKVGISVNLNPKDHLKGVQDFFLNDKGEIIKERFLNQDINALANDDNEPIDAITNRKLNVSIQKENGKKEDFVFTYGDAEKGENQFKTLGDLQKLLKEKTGLDLNLIKSEKDAKSPPLLLEIANPSQTPITFSLSGGIADKLGLNANGMELKKGISRDSVAIKIPYYSTEVDIYDKAGDKYLLQSEYYMTNSNDPTSSPTSKRKNQTWEVKSYIVDPKNKTPINDPTWEIVGFDSATHKMKSAPMTLDFKGNKLTYSLDKSENHDSSDLSYQDSKLLEASQDGKPRGIFRDMRIEENGVISLAFSNGVVEPVARIGILAFTNDQGLRKIGGNLYEMQEGTINGENRPLSGNPILGWDEEGKLKFGKIRHKYLETSNVNAGNALTNLILMQRGYSMNARAFGAGDDMIKEAISLKKENLYFQSHHHHHH*

C; model_eva_score=0.084, tm_score=0.6896, gdt_score=0.4640, maxsub=0.3879.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 549: : 595: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------EGKLKFGKIRHKYLETSNVNAGNALTNLILMQRGYSMNARAFGAGDD-----------------------*

C;total number of template models = 2
>P1;C00771
 : : : : : : : : : 
MNDTLLNAYSGIKTHQFGIDSLSNNIANVNTLGYRSNDPEFKTLFSSHLDALNAKSVVTNDRNYGVTGSGNVLSNKDGEYMPSEGEFHMAYQGKGWFVIGPNKNGEMTINKDGFSKKQDNFLTRAGNFARDADGYLVTPEGYYVYGIDLKKIKDGTLNSTARDEDIEKLHGNTLSPLQIPQDLTYQPVLSTKVGISVNLNPKDHLKGVQDFFLNDKGEIIKERFLNQDINALANDDNEPIDAITNRKLNVSIQKENGKKEDFVFTYGDAEKGENQFKTLGDLQKLLKEKTGLDLNLIKSEKDAKSPPLLLEIANPSQTPITFSLSGGIADKLGLNANGMELKKGISRDSVAIKIPYYSTEVDIYDKAGDKYLLQSEYYMTNSNDPTSSPTSKRKNQTWEVKSYIVDPKNKTPINDPTWEIVGFDSATHKMKSAPMTLDFKGNKLTYSLDKSENHDSSDLSYQDSKLLEASQDGKPRGIFRDMRIEENGVISLAFSNGVVEPVARIGILAFTNDQGLRKIGGNLYEMQEGTINGENRPLSGNPILGWDEEGKLKFGKIRHKYLETSNVNAGNALTNLILMQRGYSMNARAFGAGDDMIKEAISLKKENLYFQSHHHHHH*
