C; model_eva_score=0.158, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 196: : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*

C; model_eva_score=0.154, tm_score=0.8477, gdt_score=0.7168, maxsub=0.7097.
>P1;meta_csiblast7.pdb1
structureX:meta_csiblast7.pdb: 1: : 196: : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*

C;total number of template models = 2
>P1;T042120
 : : : : : : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*
