C; model_eva_score=0.157, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_csiblast5.pdb1
structureX:meta_csiblast5.pdb: 1: : 196: : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*

C; model_eva_score=0.154, tm_score=0.8306, gdt_score=0.7028, maxsub=0.6718.
>P1;meta_csiblast7.pdb1
structureX:meta_csiblast7.pdb: 1: : 196: : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*

C;total number of template models = 2
>P1;T042120
 : : : : : : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*
