C;cover size:182; local alignment length=182 (original info = e2wz1A1	197	335.93	9.4e-54	181	39	100.00)
>P1;e2wz1A1
structureX:e2wz1A1: 2: : 194: : : : : 
--------------------------------------------------------------------PAKRYDNVTILFSGIVGFNAFCSKHASGAMKIVNLLNDLYTRFDTLTDSRKNPFVYKVETVGDKYMTVSGLPEPCIHHARSICHLALDMMEIAGQVQVD------GESVQITIGIHTGEVVTGVIGQ-RMPRYCLFGNTVNLTSRTETTGE--KGKINVSEYTYRCLMSPENSDPQFHLEHRGPVSMKGK--KEPMQVWFLSRK-----*

C;cover size:67; local alignment length=67 (original info = e1biaA3	182	6.11	0.24	52	8	0.17)
>P1;e1biaA3
structureX:e1biaA3: 20: : 73: : : : : 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------VLPVIDSTNQYLLDRIGELK--SGDACIAEYQQA-----------------G----SPFGANL-YLSMFWRLEQPAAA*

C;cover size:203; local alignment length=203 (original info = e5m2aA1	236	319.71	7e-50	198	20	100.00)
>P1;e5m2aA1
structureX:e5m2aA1: 4: : 210: : : : : 
--------------------------------------QTITQSHRVLEKYMPARVIYLINQGINPLTVEPQLVEKIIFFSDILAFSTLTEKLP--VNEVVILVNRYFSICTRIISAYG---GEVTKFIGDCVMASFTKE-----QGDAAIRTSLDIISELKQLRHHVEATNPLHLLYTGIGLSYGHVIEGNMGSSLKMDHTLLGDAVNVAARLEALTRQLPYALAFTAGVKKCCQA------QWTFINLGAHQVKEA--IE-V-------------*

C;query_length:254 num_of_temps:1 cover_ratio:0.72 cover:182 not_cover:72
>P1;2017-10-28_00000061_1_72
 : : : : : : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSV-IADKYDEVSVLFADIVGFTERASTTT--PADLVRFLNRLYGAFDELVDKHG---LEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPH-----GDPVPLRMGMACGPVVAGVVGS-RRFFYDVWGDAVNVASRMESTDS--VGRIQVPEAMYERLKN------EFVLQERGRIEVKGK--GV-MRTWYLIGRKADEE*
