C;cover size:175; local alignment length=175 (original info = e3uvjA1	191	338.27	2.3e-54	174	35	100.00)
>P1;e3uvjA1
structureX:e3uvjA1: 2: : 177: : : : : 
-----------------------------------------------------------------VV-QAKKFSNVTMLFSDIVGFTAICSQCSPLQVITMLNALYTRFDQQCGELDVYKVETIGDAYCVAGGLHKESDTHAVQIALMALKMMELSDEVMSPHG-----EPIKMRIGLHSGSVFAGVVGV--MPRYCLFGNNVTLANKFESCSV--PRKINVSPTTYRLLKDCPGFVFTPRSREELPPN--FP---------------*

C;cover size:67; local alignment length=67 (original info = e1biaA3	182	6.11	0.24	52	8	0.17)
>P1;e1biaA3
structureX:e1biaA3: 20: : 73: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------VLPVIDSTNQYLLDRIGELK--SGDACIAEYQQA-------------G----SPFGANL-YLSMFWRLEQPAAA*

C;cover size:211; local alignment length=211 (original info = e4yutB1	241	331.39	1.5e-51	206	23	100.00)
>P1;e4yutB1
structureX:e4yutB1: 5: : 220: : : : : 
---------------------------------------TLTESHRILEKYTQPSIFKIISQGTNPLNIRPKAVEKIVFFSDIVSFSTFAEKLPVEEVVSVVNSYFSVCTAIITRQGGEVTKFIGDCVMAYFDG-----DCADQAIQASLDILMELEILRNSAPEGSPLRVLYSGIGLAKGKVIEGNIGSELKRDYTILGDAVNVAARLEALTRQLSQALVFSSEVKNSATK--SWNFIWLTDSELKGK--SESIDIYSIDNEM----*

C;query_length:254 num_of_temps:1 cover_ratio:0.69 cover:175 not_cover:79
>P1;2017-10-28_00000061_1_72
 : : : : : : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSV-IADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHG-----DPVPLRMGMACGPVVAGVVGS-RRFFYDVWGDAVNVASRMESTDS--VGRIQVPEAMYERLKN--EFVLQERGRIEVKGK--GV-MRTWYLIGRKADEE*
