C;cover size:178; local alignment length=178 (original info = e1cjtB1	188	361.67	2.5e-58	178	37	100.00)
>P1;e1cjtB1
structureX:e1cjtB1: 2: : 187: : : : : 
----------------------------------------------------------------------QSYDCVCVMFASIPDFKEFYTESDVNKEGLECLRLLNEIIADFDDLLSKPKFSGVEKIKTIGSTYMAATGLSARQYMHIGTMVEFAYALVGKLDAINKHSF-----NDFKLRVGINHGPVIAGVIGA-QKPQYDIWGNTVNVASRMDSTGV--LDKIQVTEETSLILQTLGYTCTCRGIINVKGK--GD-LKTYFVN-------*

C;cover size:67; local alignment length=67 (original info = e1biaA3	182	6.11	0.24	52	8	0.17)
>P1;e1biaA3
structureX:e1biaA3: 20: : 73: : : : : 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------VLPVIDSTNQYLLDRIGELK--SGDACIAEYQQA------------G----SPFGANL-YLSMFWRLEQPAAA*

C;cover size:211; local alignment length=211 (original info = e4yutB1	241	331.39	1.5e-51	206	23	100.00)
>P1;e4yutB1
structureX:e4yutB1: 5: : 220: : : : : 
---------------------------------------TLTESHRILEKYTQPSIFKIISQGTNPLNIRPKAVEKIVFFSDIVSFSTFAEKLP----VEEVVSVVNSYFSVCTAIITR---QGGEVTKFIGDCVMAYFDG-----DCADQAIQASLDILMELEILRNSAPEGSPLRVLYSGIGLAKGKVIEGNIGSELKRDYTILGDAVNVAARLEALTRQLSQALVFSSEVKNSATK-SWNFIWLTDSELKGK--SESIDIYSIDNEM----*

C;query_length:254 num_of_temps:1 cover_ratio:0.7 cover:178 not_cover:76
>P1;2017-10-28_00000061_1_72
 : : : : : : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSV-IADKYDEVSVLFADIVGFTERASTTT----PADLVRFLNRLYGAFDELVDK---HGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHG-----DPVPLRMGMACGPVVAGVVGS-RRFFYDVWGDAVNVASRMESTDS--VGRIQVPEAMYERLKN-EFVLQERGRIEVKGK--GV-MRTWYLIGRKADEE*
