C;cover size:340; local alignment length=340 (original info = e5e5cA1	337	468.33	1.2e-61	337	46	100.00)
>P1;e5e5cA1
structureX:e5e5cA1: 1: : 337: : : : : 
--------------------------------------------------------------------GGIDPHTHMQLPFMGTVASEDFFSGTAAGLAGGTTSIIDFVIPNPRQSLLEAFHTWRGWAQ-KSAADYGFHVAITWWSDEVAREMGELVAQHGVNSFHFM-AYKNAIMAADDTLVASFERCLELGAVPTVHAENGELVFHLQQKLLAQGLTGPEAHPLSRPPQVEGEAASRAIRIAETLGTPLYLVHISSREALDEIAYARAKGQPVYGEVLAGHLLLDDSVYRHPDWATAAGYVMSPPFRP-VEHQEALWRGLQSGNLHTTATDHCCFCAEQKAMGRDDFSKIPNGTAGIEDRMALLWDAGVNSGRLSMHEFVALTSTNTAKIFNLFPRKGAIRVGADA---------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:573 num_of_temps:1 cover_ratio:0.59 cover:340 not_cover:233
>P1;2017-10-28_00000044_1_72
 : : : : : : : : : 
SMSFQGKKSIPRITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIHGVPRGLYDGPVHEVMVPAKPGSGAPARASCPGKISVPPVRNLHQSGFSLSGSQADDHIARRTAQKIMAPPGGRSNITSLS*
