C;cover size:334; local alignment length=334 (original info = e4bknB2	334	485.99	3.3e-64	334	73	100.00)
>P1;e4bknB2
structureX:e4bknB2: 1: : 334: : : : : 
-------------------------------------------------------------------PGGIDVHTHYQMPYKGMTTVDDFFQGTKAALAGGTTMIIDHVVPEPESSLTEAYEKWREWADGKSCCDYALHVDITHWNDSVKQEVQNLIKDKGVNSFMVYMAYKDLYQVSNTELYEIFTCLGELGAIAQVHAENGDIIAQEQTRMLEMGITGPEGHVLSRPEELEAEAVFRAITIASQTNCPLYVTKVMSKSAADLISQARKKGNVVFGEPITASLGIDGTHYWSKNWAKAAAFVTSPPLSPDPTTPDYINSLLASGDLQLSGSAHCTFSTAQKAIGKDNFTAIPEGTNGVEERMSVIWDKAVATGKMDENQFVAVTSTNAAKIFNLYPRKGR----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:340; local alignment length=340 (original info = e5e5cA1	337	468.33	1.2e-61	337	46	100.00)
>P1;e5e5cA1
structureX:e5e5cA1: 1: : 337: : : : : 
--------------------------------------------------------------------GGIDPHTHMQLPFMGTVASEDFFSGTAAGLAGGTTSIIDFVIPNPRQSLLEAFHTWRGWAQ-KSAADYGFHVAITWWSDEVAREMGELVAQHGVNSFHFM-AYKNAIMAADDTLVASFERCLELGAVPTVHAENGELVFHLQQKLLAQGLTGPEAHPLSRPPQVEGEAASRAIRIAETLGTPLYLVHISSREALDEIAYARAKGQPVYGEVLAGHLLLDDSVYRHPDWATAAGYVMSPPFRP-VEHQEALWRGLQSGNLHTTATDHCCFCAEQKAMGRDDFSKIPNGTAGIEDRMALLWDAGVNSGRLSMHEFVALTSTNTAKIFNLFPRKGAIRVGADA---------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:573 num_of_temps:1 cover_ratio:0.58 cover:334 not_cover:239
>P1;2017-10-28_00000044_1_72
 : : : : : : : : : 
SMSFQGKKSIPRITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIHGVPRGLYDGPVHEVMVPAKPGSGAPARASCPGKISVPPVRNLHQSGFSLSGSQADDHIARRTAQKIMAPPGGRSNITSLS*
