C; model_eva_score=0.16, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 230: : : : : 
MNGFERELQNNILGLMPQAILSSEHGSLNPQQLPETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLGVNRGDQIRVMVPSASQFTPMGRIPSQRLFNVIGTFAANSEVDGYEMLVNIEDASRLMRYPAGNITGWRLWLDEPLKVDSLSQQKLPEGSKWQDWRDRKGELFQAVRMEKNMAAALEHHHHHH*

C; model_eva_score=0.154, tm_score=0.7423, gdt_score=0.6663, maxsub=0.6190.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 34: : 108: : : : : 
---------------------------------PETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLG--------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00581
 : : : : : : : : : 
MNGFERELQNNILGLMPQAILSSEHGSLNPQQLPETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLGVNRGDQIRVMVPSASQFTPMGRIPSQRLFNVIGTFAANSEVDGYEMLVNIEDASRLMRYPAGNITGWRLWLDEPLKVDSLSQQKLPEGSKWQDWRDRKGELFQAVRMEKNMAAALEHHHHHH*
