C; model_eva_score=0.158, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 230: : : : : 
MNGFERELQNNILGLMPQAILSSEHGSLNPQQLPETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLGVNRGDQIRVMVPSASQFTPMGRIPSQRLFNVIGTFAANSEVDGYEMLVNIEDASRLMRYPAGNITGWRLWLDEPLKVDSLSQQKLPEGSKWQDWRDRKGELFQAVRMEKNMAAALEHHHHHH*

C; model_eva_score=0.154, tm_score=0.8249, gdt_score=0.7511, maxsub=0.7200.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 34: : 108: : : : : 
---------------------------------PETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLG--------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00581
 : : : : : : : : : 
MNGFERELQNNILGLMPQAILSSEHGSLNPQQLPETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLGVNRGDQIRVMVPSASQFTPMGRIPSQRLFNVIGTFAANSEVDGYEMLVNIEDASRLMRYPAGNITGWRLWLDEPLKVDSLSQQKLPEGSKWQDWRDRKGELFQAVRMEKNMAAALEHHHHHH*
