C; model_eva_score=0.154, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 230: : : : : 
MNGFERELQNNILGLMPQAILSSEHGSLNPQQLPETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLGVNRGDQIRVMVPSASQFTPMGRIPSQRLFNVIGTFAANSEVDGYEMLVNIEDASRLMRYPAGNITGWRLWLDEPLKVDSLSQQKLPEGSKWQDWRDRKGELFQAVRMEKNMAAALEHHHHHH*

C; model_eva_score=0.153, tm_score=0.8442, gdt_score=0.7815, maxsub=0.7651.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 11: : 122: : : : : 
----------NILGLMPQAILSSEHGSLNPQQLPETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLGVNRGDQIRVMVPSA------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00581
 : : : : : : : : : 
MNGFERELQNNILGLMPQAILSSEHGSLNPQQLPETAVKLDGVNRVAPITTGDVVLQSARSVAVGVMLGIDPAQKDPLTPYLVNVKQTDLEPGKYNVILGEQLASQLGVNRGDQIRVMVPSASQFTPMGRIPSQRLFNVIGTFAANSEVDGYEMLVNIEDASRLMRYPAGNITGWRLWLDEPLKVDSLSQQKLPEGSKWQDWRDRKGELFQAVRMEKNMAAALEHHHHHH*
