C;cover size:121; local alignment length=121 (original info = e3kvnX2	314	22.03	0.028	100	9	5.05)
>P1;e3kvnX2
structureX:e3kvnX2: 145: : 246: : : : : 
---------------------------------------------------------------------------------------------------------------------------------------LYYITGGGND-----FLQGRILND--VQAQQAAGRLVDSVQALQQAGARYIVVWLLPDLGLTPATFGGPLQPFASQLSGTFNAELTAQL--------------SQAGANVIPLNIPLLLKEGM-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:435; local alignment length=435 (original info = e4xkmA1	435	1766.68	2.2e-244	435	83	100.00)
>P1;e4xkmA1
structureX:e4xkmA1: 1: : 435: : : : : 
--KEFFPGIEKIKFEGKDSKNPMAFRYYDAEKVINGKKMKDWLRFAMAWWHTLCAEGGDQFGGGTKQFPWNGNADAIQAAKDKMDAGFEFMQKMGIEYYCFHDVDLVSEGASVEEYEANLKEIVAYAKQKQAETGIKLLWGTANVFGHARYMNGAATNPDFDVVARAAVQIKNAIDATIELGGENYVFWGGREGY--MSLLNTDQKREKEHLAQMLTIARDYARARGFKGTFLIEPKPMEPTKHQYDVDTETVIGFLKAHGLDKDFKVNIEVNHATLAGHTFEHELAVAVDNGMLGSIDANRGDYQNGWDTDQFPIDNYELTQAMMQIIRNGGLGTGGTNFDAKTRRNSTDLEDIFIAHIAGMDAMARALESAAALLDESPYKKMLADRYASFDGGKGKEFEDGKLTLEDVVAYAKTKGEPKQTSGKQELYEAILNMYC*

C;query_length:437 num_of_temps:1 cover_ratio:0.28 cover:121 not_cover:316
>P1;2017-10-28_00000041_1_72
 : : : : : : : : : 
MAKEYFPQIQKIKFEGKDSKNPLAFHYYDAEKEVMGKKMKDWLRFAMAWWHTLCAEGADQFGGGTKSFPWNEGTDAIEIAKQKVDAGFEIMQKLGIPYYCFHDVDLVSEGNSIEEYESNLKAVVAYLKEKQKETGIKLLWSTANVFGHKRYMNGASTNPDFDVVARAIVQIKNAIDAGIELGAENYVFWGGREGY--MSLLNTDQKREKEHMATMLTMARDYARSKGFKGTFLIEPKPMEPTKHQYDVDTETAIGFLKAHNLDKDFKVNIEVNHATLAGHTFEHELACAVDAGMLGSIDANRGDYQNGWDTDQFPIDQYELVQAWMEIIRGGGFVTGGTNFDAKTRRNSTDLEDIIIAHVSGMDAMARALENAAKLLQESPYTKMKKERYASFDSGIGKDFEDGKLTLEQVYEYGKKNGEPKQTSGKQELYEAIVAMYQ*
