C;cover size:98; local alignment length=98 (original info = e3cl6A1	302	19.29	0.087	70	19	2.10)
>P1;e3cl6A1
structureX:e3cl6A1: 80: : 149: : : : : 
----------------------------------------------------------------------------------------------------------------------GVWRILKLF----KAFDIPLTI----------FAVAMAAQRHP-------DVIRAMVAAGHEICSHGYR-------WIDYQYMDEAQEREHMLEAIRI-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:435; local alignment length=435 (original info = e4xkmA1	435	1766.68	2.2e-244	435	83	100.00)
>P1;e4xkmA1
structureX:e4xkmA1: 1: : 435: : : : : 
--KEFFPGIEKIKFEGKDSKNPMAFRYYDAEKVINGKKMKDWLRFAMAWWHTLCAEGGDQFGGGTKQFPWNGNADAIQAAKDKMDAGFEFMQKMGIEYYCFHDVDLVSEGASVEEYEANLKEIVAYAKQKQAETGIKLLWGTANVFGHARYMNGAATNPDFDVVARAAVQIKNAIDATIELGGENYVFWGGREGYMSLLNTDQKREKEHLAQMLTIARDYARARGFKGTFLIEPKPMEPTKHQYDVDTETVIGFLKAHGLDKDFKVNIEVNHATLAGHTFEHELAVAVDNGMLGSIDANRGDYQNGWDTDQFPIDNYELTQAMMQIIRNGGLGTGGTNFDAKTRRNSTDLEDIFIAHIAGMDAMARALESAAALLDESPYKKMLADRYASFDGGKGKEFEDGKLTLEDVVAYAKTKGEPKQTSGKQELYEAILNMYC*

C;query_length:437 num_of_temps:1 cover_ratio:0.22 cover:98 not_cover:339
>P1;2017-10-28_00000041_1_72
 : : : : : : : : : 
MAKEYFPQIQKIKFEGKDSKNPLAFHYYDAEKEVMGKKMKDWLRFAMAWWHTLCAEGADQFGGGTKSFPWNEGTDAIEIAKQKVDAGFEIMQKLGIPYYCFHDVDLVSEGNSIEEYESNLKAVVAYLKEKQKETGIKLLWSTANVFGHKRYMNGASTNPDFDVVARAIVQIKNAIDAGIELGAENYVFWGGREGYMSLLNTDQKREKEHMATMLTMARDYARSKGFKGTFLIEPKPMEPTKHQYDVDTETAIGFLKAHNLDKDFKVNIEVNHATLAGHTFEHELACAVDAGMLGSIDANRGDYQNGWDTDQFPIDQYELVQAWMEIIRGGGFVTGGTNFDAKTRRNSTDLEDIIIAHVSGMDAMARALENAAKLLQESPYTKMKKERYASFDSGIGKDFEDGKLTLEQVYEYGKKNGEPKQTSGKQELYEAIVAMYQ*
