C;cover size:177; local alignment length=177 (original info = e2iw0A1	220	20.40	0.041	130	15	6.71)
>P1;e2iw0A1
structureX:e2iw0A1: 14: : 143: : : : : 
----------------------------------------------------------------------------------------------GLVALTYDD---GPFTF--------TPQLLDIL----KQNDVR-----ATFFVNGNNWANIEAGSNP-------DTIRRMRADGHLVGSHTYAH----PDLNTLSSADRISQMRQLEEAT------RRIDGFAPKYMRAP-----YL-SC---DAGCQGDLGGLGYH-IIDTNLDTK----------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:435; local alignment length=435 (original info = e4xkmA1	435	1766.68	2.2e-244	435	83	100.00)
>P1;e4xkmA1
structureX:e4xkmA1: 1: : 435: : : : : 
--KEFFPGIEKIKFEGKDSKNPMAFRYYDAEKVINGKKMKDWLRFAMAWWHTLCAEGGDQFGGGTKQFPWNGNADAIQAAKDKMDAGFEFMQKMGIEYYCFHDVDLVSEGASVEEYEANLKEIVAYAKQKQAETGIKLLWGTANVFGHARYMNGAATNPDFDVVARAAVQIKNAIDATIELGGENYVFWGGREGYMSLLNTDQKREKEHLAQMLTIARDYARARGFKGTFLIEPKPMEPTKHQYDVDTETVIGFLKAHGLDKDFKVNIEVNHATLAGHTFEHELAVAVDNGMLGSIDANRGDYQNGWDTDQFPIDNYELTQAMMQIIRNGGLGTGGTNFDAKTRRNSTDLEDIFIAHIAGMDAMARALESAAALLDESPYKKMLADRYASFDGGKGKEFEDGKLTLEDVVAYAKTKGEPKQTSGKQELYEAILNMYC*

C;query_length:437 num_of_temps:1 cover_ratio:0.41 cover:177 not_cover:260
>P1;2017-10-28_00000041_1_72
 : : : : : : : : : 
MAKEYFPQIQKIKFEGKDSKNPLAFHYYDAEKEVMGKKMKDWLRFAMAWWHTLCAEGADQFGGGTKSFPWNEGTDAIEIAKQKVDAGFEIMQKLGIPYYCFHDVDLVSEGNSIEEYESNLKAVVAYLKEKQKETGIKLLWSTANVFGHKRYMNGASTNPDFDVVARAIVQIKNAIDAGIELGAENYVFWGGREGYMSLLNTDQKREKEHMATMLTMARDYARSKGFKGTFLIEPKPMEPTKHQYDVDTETAIGFLKAHNLDKDFKVNIEVNHATLAGHTFEHELACAVDAGMLGSIDANRGDYQNGWDTDQFPIDQYELVQAWMEIIRGGGFVTGGTNFDAKTRRNSTDLEDIIIAHVSGMDAMARALENAAKLLQESPYTKMKKERYASFDSGIGKDFEDGKLTLEQVYEYGKKNGEPKQTSGKQELYEAIVAMYQ*
