C;cover size:90; local alignment length=90 (original info = e3dcpA1	269	-2.07	1	76	11	0.01)
>P1;e3dcpA1
structureX:e3dcpA1: 190: : 269: : : : : 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SDFSEEVEKFRVILALVKKRDYE--LDFNTAGLFKPLCGETYPPKKIVTLASELQIPFVYGSDSH------------GVQDIGRGYSTYCQKLE-------------------------------------------------------------------------------------------------------------*

C;cover size:435; local alignment length=435 (original info = e4xkmA1	435	1766.68	2.2e-244	435	83	100.00)
>P1;e4xkmA1
structureX:e4xkmA1: 1: : 435: : : : : 
--KEFFPGIEKIKFEGKDSKNPMAFRYYDAEKVINGKKMKDWLRFAMAWWHTLCAEGGDQFGGGTKQFPWNGNADAIQAAKDKMDAGFEFMQKMGIEYYCFHDVDLVSEGASVEEYEANLKEIVAYAKQKQAETGIKLLWGTANVFGHARYMNGAATNPDFDVVARAAVQIKNAIDATIELGGENYVFWGGREGYMSLLNTDQKREKEHLAQMLTIARDYARARGFKGTFLIEPKPMEPTKHQYDVDTETVIGFLKAHGLDKDFKVNIEVNHATLAGHTF--EHELAVAVDNGMLGSI--DANRGDYQNGWDTDQFPIDNYELTQAMMQIIRNGGLGTGGTNFDAKTRRNSTDLEDIFIAHIAGMDAMARALESAAALLDESPYKKMLADRYASFDGGKGKEFEDGKLTLEDVVAYAKTKGEPKQTSGKQELYEAILNMYC*

C;query_length:437 num_of_temps:1 cover_ratio:0.21 cover:90 not_cover:347
>P1;2017-10-28_00000041_1_72
 : : : : : : : : : 
MAKEYFPQIQKIKFEGKDSKNPLAFHYYDAEKEVMGKKMKDWLRFAMAWWHTLCAEGADQFGGGTKSFPWNEGTDAIEIAKQKVDAGFEIMQKLGIPYYCFHDVDLVSEGNSIEEYESNLKAVVAYLKEKQKETGIKLLWSTANVFGHKRYMNGASTNPDFDVVARAIVQIKNAIDAGIELGAENYVFWGGREGYMSLLNTDQKREKEHMATMLTMARDYARSKGFKGTFLIEPKPMEPTKHQYDVDTETAIGFLKAHNLDKDFKVNIEVNHATLAGHTF--EHELACAVDAGMLGSI--DANRGDYQNGWDTDQFPIDQYELVQAWMEIIRGGGFVTGGTNFDAKTRRNSTDLEDIIIAHVSGMDAMARALENAAKLLQESPYTKMKKERYASFDSGIGKDFEDGKLTLEQVYEYGKKNGEPKQTSGKQELYEAIVAMYQ*
