C;cover size:180; local alignment length=180 (original info = e3gtxA1	332	21.10	0.067	141	15	1.07)
>P1;e3gtxA1
structureX:e3gtxA1: 58: : 206: : : : : 
----------------------------------------------------------------------------------SCTETARALLARGIQTVV----DATPNGCG-----RNP----AFLREVSEATGLQILCATGFYYEGGGATTYFKFRASLG--DAE-SEIYEMMRTEVTEGIAGTGIRA--GVI-LAS--SRDAI--TP------YEQLFFRAAARVQRETG--VPIITHTQEG--------QQGPQQAELLTSLGADP-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:435; local alignment length=435 (original info = e4xkmA1	435	1766.68	2.2e-244	435	83	100.00)
>P1;e4xkmA1
structureX:e4xkmA1: 1: : 435: : : : : 
--KEFFPGIEKIKFEGKDSKNPMAFRYYDAEKVINGKKMKDWLRFAMAWWHTLCAEGGDQFGGGTKQFPWNGNADAIQAAKDKMDAGFEFMQKMGIEYYCFHDVDLVSEGASVEEYEANLKEIVAYAKQKQAETGIKLLWGTA--------NVFGHARYMNGAATNPDFDVVARAAVQIKNAIDATIELGGENYVFWGGREGYMSLLNTDQKREKEHLAQMLTIARDYARARGFKGTFLIEPKPMEPTKHQYDVDTETVIGFLKAHGLDKDFKVNIEVNHATLAGHTFEHELAVAVDNGMLGSIDANRGDYQNGWDTDQFPIDNYELTQAMMQIIRNGGLGTGGTNFDAKTRRNSTDLEDIFIAHIAGMDAMARALESAAALLDESPYKKMLADRYASFDGGKGKEFEDGKLTLEDVVAYAKTKGEPKQTSGKQELYEAILNMYC*

C;query_length:437 num_of_temps:1 cover_ratio:0.41 cover:180 not_cover:257
>P1;2017-10-28_00000041_1_72
 : : : : : : : : : 
MAKEYFPQIQKIKFEGKDSKNPLAFHYYDAEKEVMGKKMKDWLRFAMAWWHTLCAEGADQFGGGTKSFPWNEGTDAIEIAKQKVDAGFEIMQKLGIPYYCFHDVDLVSEGNSIEEYESNLKAVVAYLKEKQKETGIKLLWSTA--------NVFGHKRYMNGASTNPDFDVVARAIVQIKNAIDAGIELGAENYVFWGGREGYMSLLNTDQKREKEHMATMLTMARDYARSKGFKGTFLIEPKPMEPTKHQYDVDTETAIGFLKAHNLDKDFKVNIEVNHATLAGHTFEHELACAVDAGMLGSIDANRGDYQNGWDTDQFPIDQYELVQAWMEIIRGGGFVTGGTNFDAKTRRNSTDLEDIIIAHVSGMDAMARALENAAKLLQESPYTKMKKERYASFDSGIGKDFEDGKLTLEQVYEYGKKNGEPKQTSGKQELYEAIVAMYQ*
