C;cover size:236; local alignment length=236 (original info = e5gykA1	227	528.20	7.4e-79	226	54	100.00)
>P1;e5gykA1
structureX:e5gykA1: 2: : 227: : : : : 
--------------------MSFDINWSTLESDNRLNDLIRKHLNSYLQNTQLPSYVSNLRVLDFDLGKVGPAITLKEITDPLDEFYDSI----------REESPNDIQFLLEVEYKGDLLVTIGADLVLNYPVEKFMTLPVKLSISDIGLHSLCIVACL--------SKQLFLSFLCDVSDPALDDNQTVLDPKGPILAATKPLERISIVRSMKIETEIGEQYQGQGSVLRSVGELEQFLFTIFKDFLRKELAWPSWINLDFN---------------------------------------------------------------------*

C;cover size:236; local alignment length=236 (original info = e5gydC1	191	317.95	4.4e-49	190	56	100.00)
>P1;e5gydC1
structureX:e5gydC1: 2: : 191: : : : : 
--------------------MSFDINWSTLESDNRLNDLIRKHLNSYLQNTQLPSYVSNLRVLDFDLGKVGPAITLKEITDP-------------------LDSPNDIQFLLEVEYKGDLLVTIGADLVLNYPVEKFMTLPVKLSISDIGLHSLCIVACL--------SKQLFLSFLCDVSD---------------------------PVRSMKIETEIGEQYQGQGSVLRSVGELEQFLFTIFKDFLRKELAWPSWINLDFN---------------------------------------------------------------------*

C;cover size:225; local alignment length=225 (original info = e4p42A1	190	133.16	4.6e-20	154	14	99.69)
>P1;e4p42A1
structureX:e4p42A1: 20: : 181: : : : : 
--------------------------------CQFIEKLFRETIEPAVRG--ANTHLSTFSFTKVDVGQQPLRINGVKVYT-------------------ENVDKRQIILDLQISFVGNCEIDLEIK-----------RYFCRAGVKSIQIHGTMRVILEPLIGDMPLVGALSIFFLRK------------------------------PLLEINWTGL-T-------N-LLDVPGLNGLSDTIILDIISNYLVLPNRITVPLVS--------------------------------------------------------------------*

C;query_length:325 num_of_temps:1 cover_ratio:0.73 cover:236 not_cover:89
>P1;2017-11-04_00000009_1_72
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMSVEIDWDNIRGDLSVNQGVKDFLNSRLQEFELPSYVNNLKVTNFDLGTMPPNVILKQMDDPLDEFYSYLLQEGDISKEAAKDKNTDVQLLVELDYKGDMSIELSADLVLNYPSPQFMILPVKLRISDIGMHCLCLLAYL--------KKQLFISFLCDVSDPLLENDKLQVDPSGPNFMGKRALERISLIRNIKIHTELGQLDQGEGSVLRSVGKLEEFLVDLFRNLIRKEAAWPSWIDLDFTPEDPEDPEEEGRENDLVADSSNDGKDIEMKSGTEETLGAGIQESVQHVSPAVTSIDQESRVNSNTSLEE*
