C;cover size:92; local alignment length=92 (original info = e5aoeA2	376	-3.81	1	86	9	0.01)
>P1;e5aoeA2
structureX:e5aoeA2: 274: : 376: : : : : 
-------------------------------------DEVEAAFEALIKGVKVAPQTEWKQILDNTEVKAVILGGDPS-SGARVVTGKVDMVEDLIQEGSRFTADHP-----GLPISYTTSFLRDNVVATFQNSTDYVETKVTAYR----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:236; local alignment length=236 (original info = e5gykA1	227	528.20	7.4e-79	226	54	100.00)
>P1;e5gykA1
structureX:e5gykA1: 2: : 227: : : : : 
--------------------MSFDINWSTLESDNRLNDLIRKHLNSYLQNTQ------LPSYVSNLRVLDFDLGKVGPAITLKEITDPLDEFYDSI----------REESPNDIQFLLEVEY-----------KGDLLVTIGADLVLNYPVEKFMTLPVKLSISDIGLHSLCIVACLSKQLFLSFLCDVSDPALDDNQTVLDPKGPILAATKPLERISIVRSMKIETEIGEQYQGQGSVLRSVGELEQFLFTIFKDFLRKELAWPSWINLDFN---------------------------------------------------------------------*

C;query_length:325 num_of_temps:1 cover_ratio:0.28 cover:92 not_cover:233
>P1;2017-11-04_00000009_1_72
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMSVEIDWDNIRGDLSVNQGVKDFLNSRLQEFE------LPSYVNNLKVTNFDLGTMPPNVILKQMDDPLDEFYSYLLQEGDISKEAAKDKNTDVQLLVELDY-----------KGDMSIELSADLVLNYPSPQFMILPVKLRISDIGMHCLCLLAYLKKQLFISFLCDVSDPLLENDKLQVDPSGPNFMGKRALERISLIRNIKIHTELGQLDQGEGSVLRSVGKLEEFLVDLFRNLIRKEAAWPSWIDLDFTPEDPEDPEEEGRENDLVADSSNDGKDIEMKSGTEETLGAGIQESVQHVSPAVTSIDQESRVNSNTSLEE*
