C;cover size:236; local alignment length=236 (original info = e5gykA1	227	528.20	7.4e-79	226	54	100.00)
>P1;e5gykA1
structureX:e5gykA1: 2: : 227: : : : : 
--------------------MSFDINWSTLESDNRLNDLIRKHLNSYLQNTQLPSYVSNLRVLDFDLGKVGPAITLKEITDPLDEFYDSI----------REESPNDIQFLLEVEYKGDLLVTIGADLVLNYPVEKFMTLPVKLSISDIGLHSLCIVACLSKQLFLSFLCDVSDPALDDNQTVLDPKGPILAATKPLERISIVRSMKIETEIGEQYQGQGSVLRSVGELEQFLFTIFKDFLRKELAWPSWINLDFN---------------------------------------------------------------------*

C;query_length:325 num_of_temps:1 cover_ratio:0.73 cover:236 not_cover:89
>P1;2017-11-04_00000009_1_72
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMSVEIDWDNIRGDLSVNQGVKDFLNSRLQEFELPSYVNNLKVTNFDLGTMPPNVILKQMDDPLDEFYSYLLQEGDISKEAAKDKNTDVQLLVELDYKGDMSIELSADLVLNYPSPQFMILPVKLRISDIGMHCLCLLAYLKKQLFISFLCDVSDPLLENDKLQVDPSGPNFMGKRALERISLIRNIKIHTELGQLDQGEGSVLRSVGKLEEFLVDLFRNLIRKEAAWPSWIDLDFTPEDPEDPEEEGRENDLVADSSNDGKDIEMKSGTEETLGAGIQESVQHVSPAVTSIDQESRVNSNTSLEE*
