C;template; converted from global alignment
>P1;1TH8B
structureX:1TH8B: 1: : 115: : : : : 
-----------SLAIDLEVKQDVLIVRLSGELDHHTAEELREQVTDVLENRAIRHIVLNLGQLTFMDSSGLGVILGRYKQIKNVGGQMVVCAVSPAVKRLFDMSGLFKIIRVEADEQFALQALGVA*

C;template; converted from global alignment
>P1;1VC1A
structureX:1VC1A: 1: : 99: : : : : 
-----------NLKLDIVE---KAIVRVQGDIDAYNSSELKEQLRNFIST----KIVLDLSSVSYMDSAGLGTLVVILKDAKIG--EFILSSLKESISRILKLTHLDKIFKITDTVEEA-------*

C;template; converted from global alignment
>P1;1AUZA
structureX:1AUZA: 1: : 100: : : : : 
-----------SLGIDMNVKESVLCIRLTGELDHHTAETLKQ-KV--S------HIVLNLEDLSFMDSSGLGVILGRYKQIKQI-GEMVVCAISPAVKRLFDMSGLFKIIRFEQS-QAL---GVA-*

C;template; converted from global alignment
>P1;2KA5A
structureX:2KA5A: 1: : 99: : : : : 
--------------PY-I-DD-VVILMPNK-L-I--A--FKKWVFDELN-KGYNKIFLVLSDVESIDSFSLGVIVNILKSISSSGGFFALVSPNEKVERVLSLTNLDRIVKIYDTISEAMEEV---*

C;template; converted from global alignment
>P1;4HYLA
structureX:4HYLA: 1: : 102: : : : : 
-----------NTDTQIRTE--IDIITLHGHLDTRSSPAVQAAVLPR------GK-ILDLREVSY-SSAGLRVLLSLYRHTSNQQGALVLVGVSEEIRDT-EITGFWNFFTACAS-DEALRILG-S*

C;template; converted from global alignment
>P1;3T6OA
structureX:3T6OA: 1: : 101: : : : : 
--------------IRVTHE--VTVISF-FRLRETEVEQIASTFLAAQ---A-RKVLIDLEGVEFFGSSFIELLVRGWKRIKEDQGVFALCSVSPYCVEVLQVTHI-EVWPRYSTKQEALLA-A--*

C;template; converted from global alignment
>P1;4QTPA
structureX:4QTPA: 1: : 105: : : : : 
-----------SITTLVED-G-VSVVSVSGEIDMVTAPALEQAIGAVVA-DSP-ALVIDLSAVEFLGSVGLKILAATYEKL--KET-FGVV-RGPATRRPIHLTGLDKTFPLYPTLDDALTAVR--*

C;template; converted from global alignment
>P1;1H4XA
structureX:1H4XA: 1: : 94: : : : : 
-------------AFQLEMTRETVVIRLFGE-----VEQIRAKIS--I---AVTTIIWNFERLSF---SGVGLVLGRMRELEAVAGRTILLNPSPTMRKVFQFSGLG--W-M-ATEEEAIDRV-R-*

C;template; converted from global alignment
>P1;3LLOA
structureX:3LLOA: 1: : 88: : : : : 
--------------YTV--IPGIKIFQIN--P----Y-YANSDL-------NI-TVILDFTQVN-MDSVGVKTLAGIVKEYGDVGIYVYLAGCSAQVVNDLT-RF--AL-LLFHSIHDAVLGSQ--*

C;template; converted from global alignment
>P1;1THNB
structureX:1THNB: 1: : 114: : : : : 
-----------SLAIDLEVKQDVLIVRLSGELDHHTAEELREQVTDVLENRAIRHIVLNLGQLTFMDSSGLGVILGRYKQIKNVGGQMVVCAVSPAVKRLFDMSGLFKIIRVEADEQFALQALGV-*

C;query; converted from global alignment
>P1;T0993s2
 : : : : : : : : : 
MHHHHHHENLYFQSESLSWMQTGDTLALSGELDQDVLLPLWEMREEAVK----GITCIDLSRVSRVDTGGLALLLHLIDLAKKQGNNVTLQGVNDKVYTLAKLYNLPADVLPR-------------*
