C;template; converted from global alignment
>P1;1VC1A
structureX:1VC1A: 1: : 110: : : : : 
---------MNNLKLDIVEQDDKAIVRVQGDIDAYNSSELKEQLRNFISTTSKKKIVLDLSSVSYMDSAGLGTLVVILKDAKINGKEFILSSLKESISRILKLTHLDKIFKITDTVEEA*

C;template; converted from global alignment
>P1;1TH8B
structureX:1TH8B: 1: : 99: : : : : 
-----------SLAIDLEV---VLIVRLSGELDHHTAEELREQVTDVLEN----HIVLNLGQLTFMDSSGLGVILGRYKQIKN-V-QMVVCAVSPAVKRLFDMSGLFKIIRVEADEQFA*

C;template; converted from global alignment
>P1;1AUZA
structureX:1AUZA: 1: : 96: : : : : 
------------LGIDMNVK--VLCIRLTGELDHHTAETLKQK-TQ-S------HIVLNLEDLSFMDSSGLGVILGRYKQIKQIGGEMVVCAISPAVKRLFDMSGLFKIIRFEQSQA-L*

C;template; converted from global alignment
>P1;2KA5A
structureX:2KA5A: 1: : 95: : : : : 
--------------PYKIVD--VVILMPNK-L-I-NAHLFKKWVFDFLNK----KIFLVLSDVESIDSFSLGVIVNILKSISSSGGFFALVSPNEKVERVLSLT-LDRIVKIYDTISEA*

C;template; converted from global alignment
>P1;4HYLA
structureX:4HYLA: 1: : 97: : : : : 
-----------ATDTQIRTE--IDIITLHGHLDTRSSPAVQAAVLPRV-----GK-ILDLREVSY-SSAGLRVLLSLYRHTSNQQGALVLVGVSEEIRDT-EITGFWNFFTACAS-DEA*

C;template; converted from global alignment
>P1;3T6OA
structureX:3T6OA: 1: : 91: : : : : 
-------------DIRVTHEAQVTVISFPFRLRETEVE-IASTFLAA-Q-----KVLIDLEGVEFFGSSFIELLVRGWKRIK----VFALCSVSPYCVEVLQVT---E-WPRYSTKQEA*

C;template; converted from global alignment
>P1;4QTPA
structureX:4QTPA: 1: : 99: : : : : 
-----------SITTLVEDHD-VSVVSVSGEIDMVTAPALEQAIGAVVAD---PALVIDLSAVEFLGSVGLKILAATYEKL----TGFGVV-ARGPTRRPIHLTGLDKTFPLYPTLDDA*

C;template; converted from global alignment
>P1;1H4XA
structureX:1H4XA: 1: : 74: : : : : 
-------------FQ-E-V-----VIRLF----H-AVEQIRAKIS--IGA----TIIWNFERLSFM--SGVGLVLGRMRELEAVAGRTILLNPSP-MR--F---FS-G--WMMDA-E--*

C;template; converted from global alignment
>P1;3LLOA
structureX:3LLOA: 1: : 81: : : : : 
-------------SYTVLEI--IKIFQINA------Y--AN-DL-------NIHTVILDFTQVNFMDSVGVKTLAGIVKEYGD-GIYVYLAGCSAQVVNDL----F-PL-LLFHSIHDA*

C;template; converted from global alignment
>P1;1THNB
structureX:1THNB: 1: : 96: : : : : 
-----------SLAIDLE-----LIVRLSGELDHHTAEELREQVTDVLEN----HIVLNLGQLTFMDSSGLGVILGRYKQIKN---QMVVCAVSPAVKRLFDMSGLFKIIRVEADEQFA*

C;query; converted from global alignment
>P1;T0993s2
 : : : : : : : : : 
MHHHHHHENLYFQSESLSWMQTGDTLALSGELDQDVLLPLWEMREEAVKG----ITCIDLSRVSRVDTGGLALLLHLIDLAKKQGNNVTLQGVNDKVYTLAKLYNLPADVLPR------*
