C;cover size:155; local alignment length=155 (original info = e4k5bA1	156	247.52	1.5e-44	155	86	100.00)
>P1;e4k5bA1
structureX:e4k5bA1: 1: : 155: : : : : 
----DLGKKLLEAARAGQ--DDEV-RILMAN--GADVNAK-DRFGWTPLHLAAMEGH-LEIVEVLLKT---GADVNAWADLGTTPLHLAAMKGHLEIVEVLLK---AGAD---VNAEA-IVGYTPLHLAAWEGHLEIVEVLLKHGADVNAQDKFGKTPFDLAID--NGNEDIAEVLQK-----------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:63; local alignment length=63 (original info = d1y6ia1	82	-0.59	0.99	59	14	0.02)
>P1;d1y6ia1
structureX:d1y6ia1: 15: : 82: : : : : 
ASEKKQLTAIAALAEMGEGGQGILLDYLAKNVPLEKPVLA-VGN----VYQTLRNLEQETITTQLQRNYPTGI--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:265; local alignment length=265 (original info = e3eu9A1	233	332.59	2.2e-56	227	34	100.00)
>P1;e3eu9A1
structureX:e3eu9A1: 2: : 231: : : : : 
-------------------------------------THI-DDYSTWDIVKATQYGI-YERCRELVEA---GYDVRQPDKENVTLLHWAAINNRIDLVKYYIS---KGAI---VDQLGGDLNSTPLHWATRQGHLSMVVQLMKYGADPSLIDGEGCSCIHLAAQ--FGHT---------------------------------------SIVAYLIAKGQDVDMM-DQNGMTPLMWAAYRTHSVDPTRLLLT-FNVSVNLGDKYHKNTALHWAVLAGNTTVISLLLEAGANVDAQNI-----KGESALDLAKQRKNVWMINHLQEA-*

C;cover size:280; local alignment length=280 (original info = e4ot9A1	298	309.27	2.3e-50	273	31	100.00)
>P1;e4ot9A1
structureX:e4ot9A1: 3: : 292: : : : : 
--------------------PEML-QRAREY--NARLFGLAQRSARALLDYGVT----ADARALLAGQ---RHLLTAQDENGDTPLHLAIIHGQTSVIEQIVYVIHHAQDLGVVNLTN-HLHQTPLHLAVITGQTSVVSFLLRVGADPALLDRHGDSAMHLALRAGAGAPELLRALLQSGAPAV-PQLLHMPDFEGLYPVHLAVRARSPECLDLLVDSGAEVEATERQGGRTALHLATEME-ELGLVTHLVTKLRANVNARTF-AGNTPLHLAAGLGYPTLTRLLLKAGADIHAENEEPSSFRGHTPLDLTCSTK---VKTLLLNAA*

C;query_length:298 num_of_temps:1 cover_ratio:0.52 cover:155 not_cover:143
>P1;2017-11-04_00000020_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQ--DDEV-RILMAN--GADVNAA-DDVGVTPLHLAAQRGH-LEIVEVLLKY---GADVNAADLWGQTPLHLAATAGHLEIVEVLLK---NGAD---VNARD-NIGHTPLHLAAWAGHLEIVEVLLKYGADVNAQDKFGKTPFDLAID--NGNEDIAEVLQKAAGGGSGGGDVNAYDEVGWTPLHKAAW-GHLEKVEDLLKNGADVNAA-DIDGYTPLHLAAFSG-HLEIVEVLLK-YGADVNADDQ-AGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDK-----FGKTPFDLAIDNGNEDIAEVLQKAA*
