C;cover size:158; local alignment length=158 (original info = e5kngB1	159	246.16	3.4e-44	158	84	100.00)
>P1;e5kngB1
structureX:e5kngB1: 1: : 158: : : : : 
--GSDLDKKLLEAARAGQDDEVRILMANGADVNAR-DSYGSTPLHLAAREGHLEIVEVLLKYGADVNAADFIGDTPLHLAAYRGHLEIVEVLLK---YGAD---VNASD-ITGETPLHLAAQIGHLEIVEVLLKHGADVNAQDKFGKTPADIAAD--NGHEDIAEVLQKL----------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:265; local alignment length=265 (original info = e3eu9A1	233	332.59	2.2e-56	227	34	100.00)
>P1;e3eu9A1
structureX:e3eu9A1: 2: : 231: : : : : 
--------------------------------THI-DDYSTWDIVKATQYGIYERCRELVEAGYDVRQPDKENVTLLHWAAINNRIDLVKYYIS---KGAI---VDQLGGDLNSTPLHWATRQGHLSMVVQLMKYGADPSLIDGEGCSCIHLAAQ--FGHT---------------------------------------SIVAYLIAKGQDVDMM-DQNGMTPLMWAAYRTHSVDPTRLLLT-FNVSVNLGDKYHKNTALHWAVLAGNTTVISLLLEAGANVDAQNI-----KGESALDLAKQRKNVWMINHLQEA-*

C;cover size:280; local alignment length=280 (original info = e4ot9A1	298	309.27	2.3e-50	273	31	100.00)
>P1;e4ot9A1
structureX:e4ot9A1: 3: : 292: : : : : 
------------------PEMLQRAREYNARLFGLAQRSARALLDYGVT---ADARALLAGQRHLLTAQDENGDTPLHLAIIHGQTSVIEQIVYVIHHAQDLGVVNLTN-HLHQTPLHLAVITGQTSVVSFLLRVGADPALLDRHGDSAMHLALRAGAGAPELLRALLQSGAPAV-PQLLHMPDFEGLYPVHLAVRARSPECLDLLVDSGAEVEATERQGGRTALHLATEME-ELGLVTHLVTKLRANVNARTF-AGNTPLHLAAGLGYPTLTRLLLKAGADIHAENEEPSSFRGHTPLDLTCSTK---VKTLLLNAA*

C;query_length:298 num_of_temps:1 cover_ratio:0.53 cover:158 not_cover:140
>P1;2017-11-04_00000020_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADVNAA-DDVGVTPLHLAAQRGHLEIVEVLLKYGADVNAADLWGQTPLHLAATAGHLEIVEVLLK---NGAD---VNARD-NIGHTPLHLAAWAGHLEIVEVLLKYGADVNAQDKFGKTPFDLAID--NGNEDIAEVLQKAAGGGSGGGDVNAYDEVGWTPLHKAAW-GHLEKVEDLLKNGADVNAA-DIDGYTPLHLAAFSG-HLEIVEVLLK-YGADVNADDQ-AGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDK-----FGKTPFDLAIDNGNEDIAEVLQKAA*
