C;cover size:153; local alignment length=153 (original info = d1awcb_	153	243.06	5.7e-44	152	64	100.00)
>P1;d1awcb_
structureX:d1awcb_: 1: : 152: : : : : 
----DLGKKLLEAARAGQ--DDEV-RILMAN--GAPFT-T-DWLGTSPLHLAAQYGH-FSTTEVLLRA---GVSRDARTKVDRTPLHMAASEGHANIVEVLLK---HGAD---VNAKD-MLKMTALHWATEHNHQEVVELLIKYGADVHTQSKFCKTAFDISID--NGNEDLAEIL-------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:63; local alignment length=63 (original info = d1y6ia1	82	-0.59	0.99	59	14	0.02)
>P1;d1y6ia1
structureX:d1y6ia1: 15: : 82: : : : : 
ASEKKQLTAIAALAEMGEGGQGILLDYLAKNVPLEKPVLA-VGN----VYQTLRNLEQETITTQLQRNYPTGI--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:265; local alignment length=265 (original info = e3eu9A1	233	332.59	2.2e-56	227	34	100.00)
>P1;e3eu9A1
structureX:e3eu9A1: 2: : 231: : : : : 
-------------------------------------THI-DDYSTWDIVKATQYGI-YERCRELVEA---GYDVRQPDKENVTLLHWAAINNRIDLVKYYIS---KGAI---VDQLGGDLNSTPLHWATRQGHLSMVVQLMKYGADPSLIDGEGCSCIHLAAQ--FGHT---------------------------------------SIVAYLIAKGQDVDMM-DQNGMTPLMWAAYRTHSVDPTRLLLT-FNVSVNLGDKYHKNTALHWAVLAGNTTVISLLLEAGANVDAQNI-----KGESALDLAKQRKNVWMINHLQEA-*

C;cover size:280; local alignment length=280 (original info = e4ot9A1	298	309.27	2.3e-50	273	31	100.00)
>P1;e4ot9A1
structureX:e4ot9A1: 3: : 292: : : : : 
--------------------PEML-QRAREY--NARLFGLAQRSARALLDYGVT----ADARALLAGQ---RHLLTAQDENGDTPLHLAIIHGQTSVIEQIVYVIHHAQDLGVVNLTN-HLHQTPLHLAVITGQTSVVSFLLRVGADPALLDRHGDSAMHLALRAGAGAPELLRALLQSGAPAV-PQLLHMPDFEGLYPVHLAVRARSPECLDLLVDSGAEVEATERQGGRTALHLATEME-ELGLVTHLVTKLRANVNARTF-AGNTPLHLAAGLGYPTLTRLLLKAGADIHAENEEPSSFRGHTPLDLTCSTK---VKTLLLNAA*

C;query_length:298 num_of_temps:1 cover_ratio:0.51 cover:153 not_cover:145
>P1;2017-11-04_00000020_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQ--DDEV-RILMAN--GADVNAA-DDVGVTPLHLAAQRGH-LEIVEVLLKY---GADVNAADLWGQTPLHLAATAGHLEIVEVLLK---NGAD---VNARD-NIGHTPLHLAAWAGHLEIVEVLLKYGADVNAQDKFGKTPFDLAID--NGNEDIAEVLQKAAGGGSGGGDVNAYDEVGWTPLHKAAW-GHLEKVEDLLKNGADVNAA-DIDGYTPLHLAAFSG-HLEIVEVLLK-YGADVNADDQ-AGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDK-----FGKTPFDLAIDNGNEDIAEVLQKAA*
