C; model_eva_score=0.772, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9855, gdt_score=0.9827, maxsub=0.9682.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9855, gdt_score=0.9827, maxsub=0.9682.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.773, tm_score=0.9854, gdt_score=0.9847, maxsub=0.9790.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9864, gdt_score=0.9857, maxsub=0.9773.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.774, tm_score=0.9758, gdt_score=0.9520, maxsub=0.9387.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9955, gdt_score=0.9959, maxsub=0.9895.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9859, gdt_score=0.9837, maxsub=0.9755.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9645, gdt_score=0.9347, maxsub=0.9276.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9811, gdt_score=0.9745, maxsub=0.9592.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9485, gdt_score=0.9082, maxsub=0.8942.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9672, gdt_score=0.9265, maxsub=0.9182.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9855, gdt_score=0.9857, maxsub=0.9730.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.769, tm_score=0.9608, gdt_score=0.9276, maxsub=0.9152.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.768, tm_score=0.9830, gdt_score=0.9765, maxsub=0.9573.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.765, tm_score=0.9821, gdt_score=0.9796, maxsub=0.9635.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.766, tm_score=0.9528, gdt_score=0.9051, maxsub=0.8983.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9617, gdt_score=0.9306, maxsub=0.9165.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.762, tm_score=0.9605, gdt_score=0.9337, maxsub=0.9062.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9620, gdt_score=0.9316, maxsub=0.9129.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C;total number of template models = 20
>P1;C00421
 : : : : : : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*
