C; model_eva_score=0.771, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9855, gdt_score=0.9827, maxsub=0.9682.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.773, tm_score=0.9812, gdt_score=0.9776, maxsub=0.9683.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9849, gdt_score=0.9827, maxsub=0.9730.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.774, tm_score=0.9703, gdt_score=0.9510, maxsub=0.9353.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9871, gdt_score=0.9857, maxsub=0.9718.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9842, gdt_score=0.9816, maxsub=0.9716.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9618, gdt_score=0.9316, maxsub=0.9226.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9844, gdt_score=0.9816, maxsub=0.9679.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9513, gdt_score=0.9153, maxsub=0.9025.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9606, gdt_score=0.9214, maxsub=0.9087.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9852, gdt_score=0.9755, maxsub=0.9641.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.769, tm_score=0.9600, gdt_score=0.9296, maxsub=0.9140.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.768, tm_score=0.9846, gdt_score=0.9847, maxsub=0.9679.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.765, tm_score=0.9779, gdt_score=0.9724, maxsub=0.9527.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.766, tm_score=0.9515, gdt_score=0.9071, maxsub=0.8970.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9605, gdt_score=0.9357, maxsub=0.9169.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.762, tm_score=0.9638, gdt_score=0.9357, maxsub=0.9159.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9615, gdt_score=0.9367, maxsub=0.9197.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C;total number of template models = 20
>P1;C00421
 : : : : : : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*
