C; model_eva_score=0.736, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 573: : : : : 
SMSFQGKKSIPRITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIHGVPRGLYDGPVHEVMVPAKPGSGAPARASCPGKISVPPVRNLHQSGFSLSGSQADDHIARRTAQKIMAPPGGRSNITSLS*

C; model_eva_score=0.736, tm_score=0.8891, gdt_score=0.8547, maxsub=0.8401.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 14: : 493: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIH--------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8658, gdt_score=0.8442, maxsub=0.8313.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 14: : 489: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8604, gdt_score=0.8473, maxsub=0.8332.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 16: : 491: : : : : 
---------------DRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8873, gdt_score=0.8586, maxsub=0.8441.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 16: : 489: : : : : 
---------------DRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.736, tm_score=0.8825, gdt_score=0.8630, maxsub=0.8397.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 14: : 491: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8935, gdt_score=0.8556, maxsub=0.8340.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 14: : 491: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8676, gdt_score=0.8512, maxsub=0.8346.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 15: : 491: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8800, gdt_score=0.8508, maxsub=0.8288.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 16: : 489: : : : : 
---------------DRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8559, gdt_score=0.8399, maxsub=0.8254.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 15: : 491: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.736, tm_score=0.8835, gdt_score=0.8517, maxsub=0.8365.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 13: : 492: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEI---------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8591, gdt_score=0.8451, maxsub=0.8352.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 14: : 492: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEI---------------------------------------------------------------------------------*

C; model_eva_score=0.736, tm_score=0.8726, gdt_score=0.8508, maxsub=0.8352.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 13: : 489: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8816, gdt_score=0.8508, maxsub=0.8302.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 15: : 489: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8763, gdt_score=0.8451, maxsub=0.8306.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 14: : 489: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.733, tm_score=0.8439, gdt_score=0.8351, maxsub=0.8259.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 14: : 491: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8603, gdt_score=0.8455, maxsub=0.8386.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 14: : 492: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEI---------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8561, gdt_score=0.8438, maxsub=0.8337.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 14: : 492: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEI---------------------------------------------------------------------------------*

C; model_eva_score=0.733, tm_score=0.8528, gdt_score=0.8447, maxsub=0.8282.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 16: : 489: : : : : 
---------------DRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8869, gdt_score=0.8547, maxsub=0.8364.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 13: : 492: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEI---------------------------------------------------------------------------------*

C;total number of template models = 20
>P1;C00441
 : : : : : : : : : 
SMSFQGKKSIPRITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIHGVPRGLYDGPVHEVMVPAKPGSGAPARASCPGKISVPPVRNLHQSGFSLSGSQADDHIARRTAQKIMAPPGGRSNITSLS*
