C; model_eva_score=0.735, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 573: : : : : 
SMSFQGKKSIPRITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIHGVPRGLYDGPVHEVMVPAKPGSGAPARASCPGKISVPPVRNLHQSGFSLSGSQADDHIARRTAQKIMAPPGGRSNITSLS*

C; model_eva_score=0.736, tm_score=0.8915, gdt_score=0.8591, maxsub=0.8311.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 14: : 489: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.736, tm_score=0.8658, gdt_score=0.8442, maxsub=0.8313.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 14: : 489: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8674, gdt_score=0.8495, maxsub=0.8389.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 13: : 489: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.9011, gdt_score=0.8613, maxsub=0.8376.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 13: : 491: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.736, tm_score=0.8633, gdt_score=0.8477, maxsub=0.8288.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 15: : 489: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8660, gdt_score=0.8464, maxsub=0.8327.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 13: : 489: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8749, gdt_score=0.8569, maxsub=0.8366.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 14: : 489: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8586, gdt_score=0.8451, maxsub=0.8295.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 16: : 491: : : : : 
---------------DRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8633, gdt_score=0.8447, maxsub=0.8335.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 12: : 489: : : : : 
-----------RITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.736, tm_score=0.8596, gdt_score=0.8421, maxsub=0.8293.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 14: : 491: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8609, gdt_score=0.8442, maxsub=0.8259.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 15: : 490: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLA-----------------------------------------------------------------------------------*

C; model_eva_score=0.736, tm_score=0.8544, gdt_score=0.8503, maxsub=0.8302.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 15: : 491: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.734, tm_score=0.8807, gdt_score=0.8569, maxsub=0.8331.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 13: : 494: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIHG-------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8689, gdt_score=0.8503, maxsub=0.8330.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 13: : 491: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAE----------------------------------------------------------------------------------*

C; model_eva_score=0.733, tm_score=0.8496, gdt_score=0.8403, maxsub=0.8321.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 13: : 489: : : : : 
------------ITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8570, gdt_score=0.8381, maxsub=0.8273.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 15: : 489: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8559, gdt_score=0.8386, maxsub=0.8233.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 15: : 489: : : : : 
--------------SDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C; model_eva_score=0.733, tm_score=0.8459, gdt_score=0.8377, maxsub=0.8269.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 16: : 490: : : : : 
---------------DRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLA-----------------------------------------------------------------------------------*

C; model_eva_score=0.735, tm_score=0.8505, gdt_score=0.8429, maxsub=0.8275.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 14: : 489: : : : : 
-------------TSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRL------------------------------------------------------------------------------------*

C;total number of template models = 20
>P1;C00441
 : : : : : : : : : 
SMSFQGKKSIPRITSDRLLIRGGRIVNDDQSFYADVHVEDGLIKQIGENLIVPGGIKTIDAHGLMVLPGGVDVHTRLQMPVLGMTPADDFCQGTKAALAGGTTMILDHVFPDTGVSLLAAYEQWRERADSAACCDYSLHVDITRWHESIKEELEALVKEKGVNSFLVFMAYKDRCQCSDSQMYEIFSIIRDLGALAQVHAENGDIVEEEQKRLLELGITGPEGHVLSHPEEVEAEAVYRAVTIAKQANCPLYVTKVMSKGAADAIAQAKRRGVVVFGEPITASLGTDGSHYWSKNWAKAAAFVTSPPVNPDPTTADHLTCLLSSGDLQVTGSAHCTFTTAQKAVGKDNFALIPEGTNGIEERMSMVWEKCVASGKMDENEFVAVTSTNAAKIFNFYPRKGRVAVGSDADLVIWNPKATKIISAKTHNLNVEYNIFEGVECRGAPAVVISQGRVALEDGKMFVTPGAGRFVPRKTFPDFVYKRIKARNRLAEIHGVPRGLYDGPVHEVMVPAKPGSGAPARASCPGKISVPPVRNLHQSGFSLSGSQADDHIARRTAQKIMAPPGGRSNITSLS*
