C; model_eva_score=0.922, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9956, gdt_score=0.9933, maxsub=0.9876.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9951, gdt_score=0.9933, maxsub=0.9886.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.922, tm_score=0.9911, gdt_score=0.9846, maxsub=0.9778.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9915, gdt_score=0.9885, maxsub=0.9806.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9902, gdt_score=0.9865, maxsub=0.9766.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9893, gdt_score=0.9817, maxsub=0.9776.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9889, gdt_score=0.9827, maxsub=0.9746.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9854, gdt_score=0.9760, maxsub=0.9664.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9896, gdt_score=0.9856, maxsub=0.9744.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9892, gdt_score=0.9856, maxsub=0.9765.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9881, gdt_score=0.9769, maxsub=0.9718.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9886, gdt_score=0.9817, maxsub=0.9745.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9874, gdt_score=0.9817, maxsub=0.9716.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9966, gdt_score=0.9942, maxsub=0.9908.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9870, gdt_score=0.9788, maxsub=0.9729.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9885, gdt_score=0.9798, maxsub=0.9739.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9877, gdt_score=0.9798, maxsub=0.9725.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9861, gdt_score=0.9769, maxsub=0.9689.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9883, gdt_score=0.9788, maxsub=0.9728.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C;total number of template models = 20
>P1;C00251
 : : : : : : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*
