C; model_eva_score=0.921, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9902, gdt_score=0.9846, maxsub=0.9782.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9943, gdt_score=0.9923, maxsub=0.9850.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.922, tm_score=0.9915, gdt_score=0.9885, maxsub=0.9806.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.922, tm_score=0.9914, gdt_score=0.9856, maxsub=0.9769.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9896, gdt_score=0.9846, maxsub=0.9742.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9893, gdt_score=0.9817, maxsub=0.9741.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9909, gdt_score=0.9837, maxsub=0.9758.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9903, gdt_score=0.9817, maxsub=0.9748.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9856, gdt_score=0.9769, maxsub=0.9694.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9901, gdt_score=0.9808, maxsub=0.9737.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9918, gdt_score=0.9846, maxsub=0.9789.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9896, gdt_score=0.9817, maxsub=0.9717.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9892, gdt_score=0.9817, maxsub=0.9713.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9903, gdt_score=0.9856, maxsub=0.9778.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9917, gdt_score=0.9856, maxsub=0.9776.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9909, gdt_score=0.9846, maxsub=0.9779.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9928, gdt_score=0.9865, maxsub=0.9826.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9906, gdt_score=0.9837, maxsub=0.9777.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9897, gdt_score=0.9788, maxsub=0.9725.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C;total number of template models = 20
>P1;C00251
 : : : : : : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*
