C; model_eva_score=0.921, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9927, gdt_score=0.9904, maxsub=0.9831.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.922, tm_score=0.9950, gdt_score=0.9913, maxsub=0.9866.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.922, tm_score=0.9951, gdt_score=0.9933, maxsub=0.9886.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9943, gdt_score=0.9923, maxsub=0.9850.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9921, gdt_score=0.9885, maxsub=0.9795.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9914, gdt_score=0.9846, maxsub=0.9768.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9928, gdt_score=0.9856, maxsub=0.9814.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9886, gdt_score=0.9798, maxsub=0.9702.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9879, gdt_score=0.9817, maxsub=0.9746.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9901, gdt_score=0.9827, maxsub=0.9762.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9891, gdt_score=0.9779, maxsub=0.9714.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9906, gdt_score=0.9856, maxsub=0.9753.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9910, gdt_score=0.9856, maxsub=0.9770.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9935, gdt_score=0.9894, maxsub=0.9844.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9890, gdt_score=0.9808, maxsub=0.9732.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9903, gdt_score=0.9808, maxsub=0.9767.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9906, gdt_score=0.9817, maxsub=0.9760.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9878, gdt_score=0.9788, maxsub=0.9704.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9893, gdt_score=0.9788, maxsub=0.9723.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C;total number of template models = 20
>P1;C00251
 : : : : : : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*
