C; model_eva_score=0.922, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9931, gdt_score=0.9904, maxsub=0.9837.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9950, gdt_score=0.9913, maxsub=0.9866.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.922, tm_score=0.9911, gdt_score=0.9846, maxsub=0.9778.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9914, gdt_score=0.9856, maxsub=0.9769.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9947, gdt_score=0.9942, maxsub=0.9879.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9945, gdt_score=0.9904, maxsub=0.9848.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9950, gdt_score=0.9904, maxsub=0.9875.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9898, gdt_score=0.9788, maxsub=0.9734.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9915, gdt_score=0.9894, maxsub=0.9834.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9880, gdt_score=0.9817, maxsub=0.9698.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9896, gdt_score=0.9779, maxsub=0.9722.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9941, gdt_score=0.9913, maxsub=0.9844.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9915, gdt_score=0.9837, maxsub=0.9790.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9927, gdt_score=0.9894, maxsub=0.9811.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9880, gdt_score=0.9769, maxsub=0.9706.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9886, gdt_score=0.9808, maxsub=0.9698.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.92, tm_score=0.9890, gdt_score=0.9798, maxsub=0.9717.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9887, gdt_score=0.9808, maxsub=0.9730.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C; model_eva_score=0.921, tm_score=0.9904, gdt_score=0.9827, maxsub=0.9769.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 260: : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*

C;total number of template models = 20
>P1;C00251
 : : : : : : : : : 
MPSNCRRFEGKVAIVTAATKGIGLAIAERLLDEGASVVIGSRNQKNVDEAIEYLKNKGLTKVAGIAGHIASTDDQKKLVDFTLQKFGKINILVNNHGINPAFGHILEVSDQVWDKLFEVNVKAGFQMTKLVHPHIAKEGGGAIIFNASYSAYKSPPGIAAYGVTKTTLVGLTRALAMGLAKDNIRVNGIAPGVIKTKMSQVLWDGGEDAEKELTDIQEIALGRLGVPDDCAGTVAYLASDDSSYITGEMIIIAGGVQARL*
