C;cover size:206; local alignment length=206 (original info = e1lj8A2	279	311.96	1.5e-43	205	20	100.00)
>P1;e1lj8A2
structureX:e1lj8A2: 9: : 279: : : : : 
-------------------QLAPEVKLPAYTLADTRQGIAHIGVGGFHRAHQAYYTDALNTGEGLDWSICGVGLRSEDRKARDDLAGQDYLFTLYELGDTDDTEVRVIGSISDLLAEDSAQALIDKLASPEIRIVSLTITEGGYCIDDSNGEFAHLPQIQHDLAHPSSPKTVFGFICAALTQRRAAGIPAFTVSCDNLPHNGAVTRKALLAFAALHNAELHDWIKAHVSFP-NAVDRITPTSTAHRLQLHDEHGIDDAWPVVCEPFVQWVLEDKFVNGRPAWEKVGVQFTD---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:402 num_of_temps:1 cover_ratio:0.51 cover:206 not_cover:196
>P1;2017-11-04_00000013_1_72
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMASGTTENLYFQGSMK--AVHFGAGNIGRGFIGYILADN------NVKVTFADV---NEEIINALA-HDHQYDVILADES--KTTTRVNNVDAINSMQPSEALKQAILEADI--IT---TAVGV-------------NI---------LPIIAKSFAPFLKEK---TNHVNIVACENAIMATDTLKKAVLD--------ITGPLGNNIHFANSAVDRIVPLQKN-----------ENILDVMVEPFYEWVVEKDAWYG-PELN--HIKYVDDLTPYIERKLLTVNTGHAYLAYAGKFAGKATVLDAVKDSSIEAGLRRVLAETSQYITNEFDFTEAEQAGYVEKIIDRFNNSYLSDEVTRVGRGTLRKIGPKDRIIKPLTYLYNKDLERTGLLNTAALLLKYDDTADQETVEKNNYIKEHGLKAFLSEYAKVDDGLADEIIEAYNSLS*
