C;template
>P1;2DYSU
structureX:2DYSU: : : : : : : : 
KIKNYQTAPFDSRFPNQNQTRNCWQNYLDFHRCEKAMTAKGGDVSVCEWYRRVYKSLCPISWVSTWDDRRAEGTFPGKI--------------*

C;query
>P1;domain1
 : : : : : : : : : 
-------IAVGMAAPSMKERQVCWGARDEYWKCLDENL---EDASQCKKLRSSFESSCPQQWIKYFDKRRDYLKFKEKFEAGQFEPSETTAKS*
