C;cover size:271; local alignment length=271 (original info = e2vy0A1	264	376.85	5e-60	242	23	100.00)
>P1;e2vy0A1
structureX:e2vy0A1: 8: : 262: : : : : 
---------------IDGKQWRLI--WHDEFEGSEV-NKEYWTFEKGNGIAYGIPGWGNGELEYY---TENNTYIVN-G-TLVIEARKEIITDPNEGTFLYTSSRLKTEGKVEFSPPVVVEARIKL-PK-GKGLWPAFWMLGSNIR--EVGWPNCGEIDIMEFLGHEPR--------TIHGTVHGPGYSGSKGI--------TRAYTLPEGVPDFTEDFHVFGIVWYPD--KIKWYVDGTFYHEVTKEQVEAMG-------YEWVF-DKPFYIILNLAVGGYWPGNP-DATTPFPAKMVVDYVRVYSFV*

C;cover size:268; local alignment length=268 (original info = e3azxA1	252	388.35	2.5e-62	239	23	100.00)
>P1;e3azxA1
structureX:e3azxA1: 2: : 251: : : : : 
------------------EDWQLV--WSQEFDDGVI-DPNIWNFEIGNGHAKGIPGWGNGELEYY---TDENAFVEN-G-CLVIEARKEQVS-DEYGTYDYTSARMTTEGKFEIKYG-KIEIRAKL-PK-GKGIWPALWMLGNNI--GEVGWPTCGEIDIMEMLGHDTR--------TVYGTAHGPGYSGGASI--------GVAYHLPEGVPDFSEDFHIFSIEWDED--EVEWYVDGQLYHVLSKDELAELG-------LEWVFDH-PFFLILNVAVGGYWPGYPD-ETTQFPQRMYIDYIRVYKDM*

C;cover size:262; local alignment length=262 (original info = e3wvjB1	220	313.37	4.7e-51	212	24	100.00)
>P1;e3wvjB1
structureX:e3wvjB1: 6: : 217: : : : : 
------------------------TPFVAVFS--NF-DSSQWEKAD--------WANGSVFNCVW---KPSQVTFSN-G-KMILTLDREY-----GGSYPYKSGEYRTKSF--FGYG-YYEVRMKAA-K-NVGIVSSFFTYTGPS-----DNNPWDEIDI-EFLGKDT--------TKVQFNWYKNGVGG--------------NEYLHNLGFDASQDFHTYGFEWRPD--YIDFYVDGKKVYRGTRN---------------IPV-T-PGKIMMNLWPGIGVDEWLGRYDGRTPLQAEYEYVKYYPNG*

C;cover size:90; local alignment length=90 (original info = e4m00A1	243	11.07	0.033	64	9	1.22)
>P1;e4m00A1
structureX:e4m00A1: 175: : 240: : : : : 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------NNTFQDFDINYNGDTKVMTVKYAGQTWTRNISDWI--------A--KSG-T-T-NFSLSMTASTGGA---------------TNLQQVQFGTFE*

C;cover size:266; local alignment length=266 (original info = e4crqA1	231	366.56	1.5e-59	224	25	100.00)
>P1;e4crqA1
structureX:e4crqA1: 1: : 231: : : : : 
-------------------DYNLV--WQDEFDDG---IGPDWVFETGMGY----NGWGNNELQYY---RRENAAVEN-G-NLVITAKHENF-----GGAQYTSARMKTQGRKSFKYG-KIEARIAL-PS-GQGLWPAFWMLGNNI--TSVSWPACGEIDIMSRINNAL---------QTHGTIHWSDQNGD------------HASYGDDVGVSDPGQYHIYSVEWDAN--SIKWFVDGQQFNEVDISNGVN---------GTGEFQN-EFFILLNMAVGGDWPGFDV-DQSKLPAQMLVDYVRVYQK-*

C;cover size:205; local alignment length=205 (original info = e1umzA1	267	188.56	1.8e-30	157	22	99.95)
>P1;e1umzA1
structureX:e1umzA1: 15: : 175: : : : : 
--------------------------------------------------------------------AFDHIKYFNGGNEIQLHLDK------------YTGTGFQSKGS--YLFG-HFSMQMKLVPGDSAGTVTAFYLSSQNS--------EHDEID-FEFLGNRTG-----QPYILQTNVFTGGK--------------GDREQRIYLWFDPTKEFHYYSVLWNMY--MIVFLVDDVPIRVFKNCKDL---------GVKFPFNQ-PMKIYSSLWNADDWA-------------------------*

C;cover size:266; local alignment length=266 (original info = e3ilnA1	251	379.41	6.6e-61	237	26	100.00)
>P1;e3ilnA1
structureX:e3ilnA1: 4: : 249: : : : : 
-------------------HWELV--WSDEFDYNGLPDPAKWDYDVGG------HGWGNQELQYYTRARIENARVGG-G-VLIIEARRESY-----EGREYTSARLVTRGKASWTYG-RFEIRARL-PS-GRGTWPAIWMLPDRQTYGSAYWPDNGEIDIAEHVGFNPD--------VVHGTVHTKAYNHLLG----------TQRGGSIRVPTARTDFHVYAIEWTPE--EIRWFVDDSLYYRFPNERLTNPEADW----RHWPF-DQPFHLIMNIAVGGTWGGQQGVDPEAFPAQLVVDYVRVYRW-*

C;query_length:286 num_of_temps:1 cover_ratio:0.95 cover:271 not_cover:15
>P1;2017-10-14_00000032_1_71
 : : : : : : : : : 
HHHHHHGSQQPTKTSNPNDQWTIKWSASDEFNKNDP-DWAKWIKTG--------NLPNTSAWKWN---NQKNVKISN-G-IAELTMRHNANN-TPDGGTYFTSGIFKSYQK--FTYG-YFEAKIQGADI-GEGVCPSFWLYSDFDYSVANGETVYSEIDVVELQQFDWYEGHQDDIYDMDLNLHAVVKENGQGVWKRPKMYPQEQLNKWRAPWDPSKDFHIYGCEVNQN--EIIWYVDGVEVARKPNKYWHRPMNVTLSLGLRKPF-V-KFFDNKNNAINPETDAKAREKLSDIPTSMYVDYVRVWEKS*
