C;cover size:268; local alignment length=268 (original info = e3azxA1	252	388.35	2.5e-62	239	23	100.00)
>P1;e3azxA1
structureX:e3azxA1: 2: : 251: : : : : 
------------------EDWQLV--WSQEFDDGVIDPNIWNFEIGNGHAKGIPGW--GNGELEY-----YTDENAFV-ENGCLVIEARKEQVSDE-----------YGTYDYTSARMTTEGKFEIKYGKIEIRAKL-PKG-KGIWPALWMLGNNI--GEVGWPTCGEIDIMEMLGHDTR--------TVYGTAHGPGY--SGGASI----------GVAYH-----LPEGVPD-FSEDFHIFSIEWDEDEVE-WYVDGQLY-HVLSKD-----ELAEL-G-------LEWVFDHPFFLILNVAVGGYWPGYPD-ETT------------------QFP-----QRMYIDYIRVYKDM*

C;cover size:272; local alignment length=272 (original info = e1dypA1	266	365.48	5e-58	250	37	100.00)
>P1;e1dypA1
structureX:e1dypA1: 5: : 265: : : : : 
-------------IAKPGETWILQAKRSDEFNV--KDATKWNFQ-----------T--ENYGVWS-----WKNENATV-SKGKLKLTTKRESHQRTFWDGCNQQQVANYPLYYTSGVAKSRAT--GNYGYYEARIKGASTF-PGVSPAFWYSTIDRSLTKEGDVQYSEIDVVELTQKSAVRESD-------HDLHNIVV--KNGKPTWR-PG-S-FPQTNHN-----GYHLPFD-PRNDFHTYGVNVTKDKIT-WYVDGEIV-GEKDNL-----YWHR--QNLTLSQGLR-------APHTQWKCNQFYPSANK-SAE-------------------GF-----PTSEVDYVRTWVK-*

C;cover size:263; local alignment length=263 (original info = e5jvvB1	297	266.71	3e-42	245	14	100.00)
>P1;e5jvvB1
structureX:e5jvvB1: 2: : 296: : : : : 
--------------------YTL----KDSLSGKDFL-DAFSFFA--------DRDPTNGFVHYVSREVAEGEGLVKVTSSGSVYLGVDHTNTL-S-----------LTDIGRKSVRLESTDK--IDHGLVIADIKHMPGSICGAWPAFWTVGD-------TWPDDGEIDIIEGVNTQSQN-----TMVLHTKGNCEITSDDDQTGTTTSNQCSLDAGPAGCVVQGTPGSYGSSFNEQGGGVYAMQWTDEFIKLWFFPRSAIPKSIESDSPDVSEFGTPMGNFKGTCDIGKEF-KPQKLVFDTTFCGDWAGSVYGQSDSCPLTKEDSLASCIDFVATKPEEFKEAYWEINYLKTY---*

C;query_length:286 num_of_temps:1 cover_ratio:0.94 cover:268 not_cover:18
>P1;2017-10-14_00000032_1_71
 : : : : : : : : : 
HHHHHHGSQQPTKTSNPNDQWTIKWSASDEFNKNDPDWAKWIKTG--------NLP--NTSAWKW-----NNQKNVKI-SNGIAELTMRHNANNTP-----------DGGTYFTSGIFKSYQK--FTYGYFEAKIQGADIG-EGVCPSFWLYSDFDYSVANGETVYSEIDVVELQQFDWYEGHQDDIYDMDLNLHAVVK--ENGQGVWKRPK-M-YPQEQLN-----KWRAPWD-PSKDFHIYGCEVNQNEII-WYVDGVEV-ARKPNK-----YWHRP-MNVTLSLGLRKPF-VKFFDNKNNAINPETDAKAREKLS------------------DIP-----TSMYVDYVRVWEKS*
