C;cover size:266; local alignment length=266 (original info = e3ilnA1	251	379.41	6.6e-61	237	26	100.00)
>P1;e3ilnA1
structureX:e3ilnA1: 4: : 249: : : : : 
-------------------HWELV--WSDEFDYNGLPDPAKWDYDVGGHGW--GNQELQY-----YTRARIENARV-GGGVLIIEARRESY---------------EGREYTSARLVTRGKASWTYGRFEIRARL-PSG-RGTWPAIWMLPDRQTYGSAYWPDNGEIDIAEHVGFNPD--------VVHGTVHTKAY--NHLLG------------TQRG-----GSIRVPT-ARTDFHVYAIEWTPEEIR-WFVDDSLY-YRFPNE-----RLTNP-EADW----RHWPFDQPFHLIMNIAVGGTWGGQQGVDPE------------------AFP-----AQLVVDYVRVYRW-*

C;cover size:272; local alignment length=272 (original info = e1dypA1	266	365.48	5e-58	250	37	100.00)
>P1;e1dypA1
structureX:e1dypA1: 5: : 265: : : : : 
-------------IAKPGETWILQAKRSDEFNV--K-DATKWNFQ-----T--ENYGVWS-----W---KNENATV-SKGKLKLTTKRESHQRTFWDGCNQQQVANYPLYYTSGVAKSRAT--GNYGYYEARIKGASTF-PGVSPAFWYSTIDRSLTKEGDVQYSEIDVVELTQKSAVRESD-------HDLHNIVV--KNGKPTWR-PG-S-FPQTNHN-----GYHLPFD-PRNDFHTYGVNVTKDKIT-WYVDGEIV-GEKDNL-----YWHR--QNLTLSQGLR-------APHTQWKCNQFYPSANK-SAE-------------------GF-----PTSEVDYVRTWVK-*

C;cover size:263; local alignment length=263 (original info = e5jvvB1	297	266.71	3e-42	245	14	100.00)
>P1;e5jvvB1
structureX:e5jvvB1: 2: : 296: : : : : 
--------------------YTL----KDSLSGKDF-L-DAFSFFA--DRDPTNGFVHYVSREVAE---GEGLVKVTSSGSVYLGVDHTNTL-S-----------LTDIGRKSVRLESTDK--IDHGLVIADIKHMPGSICGAWPAFWTVGD-------TWPDDGEIDIIEGVNTQSQN-----TMVLHTKGNCEITSDDDQTGTTTSNQCSLDAGPAGCVVQGTPGSYGSSFNEQGGGVYAMQWTDEFIKLWFFPRSAIPKSIESDSPDVSEFGTPMGNFKGTCDIGKEFK-PQKLVFDTTFCGDWAGSVYGQSDSCPLTKEDSLASCIDFVATKPEEFKEAYWEINYLKTY---*

C;query_length:286 num_of_temps:1 cover_ratio:0.93 cover:266 not_cover:20
>P1;2017-10-14_00000032_1_71
 : : : : : : : : : 
HHHHHHGSQQPTKTSNPNDQWTIKWSASDEFNKNDP-DWAKWIKTG--NLP--NTSAWKW-----N---NQKNVKI-SNGIAELTMRHNANNTP-----------DGGTYFTSGIFKSYQK--FTYGYFEAKIQGADIG-EGVCPSFWLYSDFDYSVANGETVYSEIDVVELQQFDWYEGHQDDIYDMDLNLHAVVK--ENGQGVWKRPK-M-YPQEQLN-----KWRAPWD-PSKDFHIYGCEVNQNEII-WYVDGVEV-ARKPNK-----YWHRP-MNVTLSLGLRKPFV-KFFDNKNNAINPETDAKAREKLS------------------DIP-----TSMYVDYVRVWEKS*
