C;cover size:271; local alignment length=271 (original info = e2vy0A1	264	376.85	5e-60	242	23	100.00)
>P1;e2vy0A1
structureX:e2vy0A1: 8: : 262: : : : : 
---------------IDGKQWRLI--WHDEFEGSEVNKEYWTFEKGNGIAYGIPGWGNGELEYYTENNTYIVNGTLVIEARKEIITDPNEGTFLYTSSRLKTEGKVEFSPPVVVEARIKL-PKGKGLWPAFWMLGSNIR--EVGWPNCGEIDIMEFLGHEPR--------TIHGTVHGPGYSGSKGI--------TRAYTLPEGVPDFTEDFHVFGIVWYPDKIKWYVDGTFYHEVTKEQVEAMG-------YEWVFDKPFYIILNLAVGGYWPGNP-DATTPFPAKMVVDYVRVYSFV*

C;query_length:286 num_of_temps:1 cover_ratio:0.95 cover:271 not_cover:15
>P1;2017-10-14_00000032_1_71
 : : : : : : : : : 
HHHHHHGSQQPTKTSNPNDQWTIKWSASDEFNKNDPDWAKWIKTG--------NLPNTSAWKWNNQKNVKISNGIAELTMRHNANN-TPDGGTYFTSGIFKSYQK--FTYG-YFEAKIQGADIGEGVCPSFWLYSDFDYSVANGETVYSEIDVVELQQFDWYEGHQDDIYDMDLNLHAVVKENGQGVWKRPKMYPQEQLNKWRAPWDPSKDFHIYGCEVNQNEIIWYVDGVEVARKPNKYWHRPMNVTLSLGLRKPFV-KFFDNKNNAINPETDAKAREKLSDIPTSMYVDYVRVWEKS*
