C;cover size:268; local alignment length=268 (original info = e3azxA1	252	388.35	2.5e-62	239	23	100.00)
>P1;e3azxA1
structureX:e3azxA1: 2: : 251: : : : : 
------------------EDWQLV--WSQEFDDGVIDPNIWNFEIGNGHAKGIPGWGNGELEYYTDENAFVENGCLVIEARKEQVSDEYGTYDYTSARMTTEGKFEIKYGKIEIRAKL-PKGKGIWPALWMLGNNI--GEVGWPTCGEIDIMEMLGHDTR--------TVYGTAHGPGYSGGASI--------GVAYHLPEGVPDFSEDFHIFSIEWDEDEVEWYVDGQLYHVLSKDELAELG-------LEWVFDHPFFLILNVAVGGYWPGYPD-ETTQFPQRMYIDYIRVYKDM*

C;query_length:286 num_of_temps:1 cover_ratio:0.94 cover:268 not_cover:18
>P1;2017-10-14_00000032_1_71
 : : : : : : : : : 
HHHHHHGSQQPTKTSNPNDQWTIKWSASDEFNKNDPDWAKWIKTG--------NLPNTSAWKWNNQKNVKISNGIAELTMRHNANNTPDGGTYFTSGIFKSYQK--FTYGYFEAKIQGADIGEGVCPSFWLYSDFDYSVANGETVYSEIDVVELQQFDWYEGHQDDIYDMDLNLHAVVKENGQGVWKRPKMYPQEQLNKWRAPWDPSKDFHIYGCEVNQNEIIWYVDGVEVARKPNKYWHRPMNVTLSLGLRKPF-VKFFDNKNNAINPETDAKAREKLSDIPTSMYVDYVRVWEKS*
