C; model_eva_score=0.749, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.756, tm_score=0.9377, gdt_score=0.9228, maxsub=0.9149.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.754, tm_score=0.9127, gdt_score=0.8821, maxsub=0.8797.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.745, tm_score=0.9592, gdt_score=0.9492, maxsub=0.9463.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.745, tm_score=0.9592, gdt_score=0.9492, maxsub=0.9463.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9616, gdt_score=0.9614, maxsub=0.9422.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9459, gdt_score=0.9350, maxsub=0.9283.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.748, tm_score=0.9383, gdt_score=0.9187, maxsub=0.9170.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9407, gdt_score=0.9350, maxsub=0.9182.
>P1;meta_hp4.pdb1
structureX:meta_hp4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.744, tm_score=0.9213, gdt_score=0.9065, maxsub=0.8936.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.74, tm_score=0.9609, gdt_score=0.9533, maxsub=0.9456.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.741, tm_score=0.9507, gdt_score=0.9451, maxsub=0.9334.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.737, tm_score=0.9257, gdt_score=0.9167, maxsub=0.8956.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.733, tm_score=0.9487, gdt_score=0.9512, maxsub=0.9276.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.735, tm_score=0.9314, gdt_score=0.9248, maxsub=0.9064.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.728, tm_score=0.9320, gdt_score=0.9207, maxsub=0.9006.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.738, tm_score=0.9465, gdt_score=0.9431, maxsub=0.9276.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.729, tm_score=0.9316, gdt_score=0.9268, maxsub=0.9033.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.731, tm_score=0.8995, gdt_score=0.8963, maxsub=0.8528.
>P1;meta_blits7.pdb1
structureX:meta_blits7.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C;total number of template models = 20
>P1;C00731
 : : : : : : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*
