C; model_eva_score=0.745, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9592, gdt_score=0.9492, maxsub=0.9463.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9592, gdt_score=0.9492, maxsub=0.9463.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.754, tm_score=0.8983, gdt_score=0.8638, maxsub=0.8543.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.756, tm_score=0.9197, gdt_score=0.8963, maxsub=0.8869.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.745, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9399, gdt_score=0.9309, maxsub=0.9116.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9380, gdt_score=0.9228, maxsub=0.9139.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.748, tm_score=0.9038, gdt_score=0.8740, maxsub=0.8642.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9111, gdt_score=0.8801, maxsub=0.8763.
>P1;meta_hp4.pdb1
structureX:meta_hp4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.744, tm_score=0.9020, gdt_score=0.8679, maxsub=0.8697.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.74, tm_score=0.9329, gdt_score=0.9228, maxsub=0.9000.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.741, tm_score=0.9162, gdt_score=0.8943, maxsub=0.8804.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.737, tm_score=0.9342, gdt_score=0.9207, maxsub=0.9055.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.733, tm_score=0.9146, gdt_score=0.8963, maxsub=0.8763.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.735, tm_score=0.8970, gdt_score=0.8699, maxsub=0.8548.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.728, tm_score=0.8864, gdt_score=0.8557, maxsub=0.8351.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.738, tm_score=0.9095, gdt_score=0.8923, maxsub=0.8735.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.729, tm_score=0.9010, gdt_score=0.8882, maxsub=0.8571.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.731, tm_score=0.8686, gdt_score=0.8394, maxsub=0.8079.
>P1;meta_blits7.pdb1
structureX:meta_blits7.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C;total number of template models = 20
>P1;C00731
 : : : : : : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*
