C; model_eva_score=0.756, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9377, gdt_score=0.9228, maxsub=0.9149.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9377, gdt_score=0.9228, maxsub=0.9149.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.754, tm_score=0.9752, gdt_score=0.9695, maxsub=0.9671.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.745, tm_score=0.9197, gdt_score=0.8963, maxsub=0.8869.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.745, tm_score=0.9197, gdt_score=0.8963, maxsub=0.8869.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9517, gdt_score=0.9390, maxsub=0.9341.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9293, gdt_score=0.9167, maxsub=0.9009.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.748, tm_score=0.9391, gdt_score=0.9268, maxsub=0.9178.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9224, gdt_score=0.9106, maxsub=0.8953.
>P1;meta_hp4.pdb1
structureX:meta_hp4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.744, tm_score=0.9468, gdt_score=0.9390, maxsub=0.9291.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.74, tm_score=0.9264, gdt_score=0.9024, maxsub=0.9027.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.741, tm_score=0.9280, gdt_score=0.9106, maxsub=0.9021.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.737, tm_score=0.9277, gdt_score=0.9248, maxsub=0.9028.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.733, tm_score=0.9210, gdt_score=0.8963, maxsub=0.8913.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.735, tm_score=0.9318, gdt_score=0.9065, maxsub=0.9051.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.728, tm_score=0.9439, gdt_score=0.9309, maxsub=0.9196.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.738, tm_score=0.9264, gdt_score=0.9045, maxsub=0.9010.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.729, tm_score=0.9209, gdt_score=0.9045, maxsub=0.8959.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.731, tm_score=0.9131, gdt_score=0.9004, maxsub=0.8689.
>P1;meta_blits7.pdb1
structureX:meta_blits7.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C;total number of template models = 20
>P1;C00731
 : : : : : : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*
