C; model_eva_score=0.754, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9127, gdt_score=0.8821, maxsub=0.8797.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9127, gdt_score=0.8821, maxsub=0.8797.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.756, tm_score=0.9752, gdt_score=0.9695, maxsub=0.9671.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.745, tm_score=0.8983, gdt_score=0.8638, maxsub=0.8543.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.745, tm_score=0.8983, gdt_score=0.8638, maxsub=0.8543.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9313, gdt_score=0.9085, maxsub=0.9043.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.749, tm_score=0.9164, gdt_score=0.8902, maxsub=0.8892.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.748, tm_score=0.9361, gdt_score=0.9228, maxsub=0.9130.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.746, tm_score=0.9106, gdt_score=0.8821, maxsub=0.8809.
>P1;meta_hp4.pdb1
structureX:meta_hp4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.744, tm_score=0.9460, gdt_score=0.9370, maxsub=0.9299.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.74, tm_score=0.9131, gdt_score=0.8760, maxsub=0.8861.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.741, tm_score=0.9201, gdt_score=0.8923, maxsub=0.8905.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.737, tm_score=0.9144, gdt_score=0.8984, maxsub=0.8827.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.733, tm_score=0.9088, gdt_score=0.8821, maxsub=0.8761.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.735, tm_score=0.9226, gdt_score=0.8882, maxsub=0.8940.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.728, tm_score=0.9304, gdt_score=0.9085, maxsub=0.9027.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.738, tm_score=0.9238, gdt_score=0.8984, maxsub=0.8969.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.729, tm_score=0.9160, gdt_score=0.8943, maxsub=0.8882.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C; model_eva_score=0.731, tm_score=0.9103, gdt_score=0.8841, maxsub=0.8771.
>P1;meta_blits7.pdb1
structureX:meta_blits7.pdb: 1: : 123: : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*

C;total number of template models = 20
>P1;C00731
 : : : : : : : : : 
PYVTISATEGLSAEKKKQLLERSSDAVVQSIGAPLASVRVMLHELPGGHYLNAGQFNTPGLMFVVDFIEGRTEEQRNALIAALSKTGTETTGIPESEVRVRLLDFPKANMGMAGGISAKAMGR*
