C; model_eva_score=0.564, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 162: : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*

C; model_eva_score=0.563, tm_score=0.8702, gdt_score=0.8225, maxsub=0.8037.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 162: : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*

C;total number of template models = 2
>P1;T041482
 : : : : : : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*
