C; model_eva_score=0.57, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_novel4.pdb1
structureX:meta_novel4.pdb: 1: : 162: : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*

C; model_eva_score=0.541, tm_score=0.7930, gdt_score=0.7716, maxsub=0.6988.
>P1;meta_novel1.pdb1
structureX:meta_novel1.pdb: 1: : 162: : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*

C;total number of template models = 2
>P1;T041482
 : : : : : : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*
