C; model_eva_score=0.57, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 162: : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*

C; model_eva_score=0.575, tm_score=0.9449, gdt_score=0.9105, maxsub=0.9034.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 162: : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*

C;total number of template models = 2
>P1;T041482
 : : : : : : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*
