C; model_eva_score=0.918, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9809, gdt_score=0.9805, maxsub=0.9730.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9903, gdt_score=0.9922, maxsub=0.9851.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9903, gdt_score=0.9922, maxsub=0.9851.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9920, gdt_score=0.9941, maxsub=0.9891.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9838, gdt_score=0.9824, maxsub=0.9736.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9799, gdt_score=0.9805, maxsub=0.9677.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.917, tm_score=0.9795, gdt_score=0.9824, maxsub=0.9700.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.917, tm_score=0.9811, gdt_score=0.9844, maxsub=0.9751.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9807, gdt_score=0.9785, maxsub=0.9740.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.917, tm_score=0.9830, gdt_score=0.9824, maxsub=0.9726.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9814, gdt_score=0.9805, maxsub=0.9709.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9863, gdt_score=0.9902, maxsub=0.9813.
>P1;meta_blits5.pdb1
structureX:meta_blits5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9863, gdt_score=0.9902, maxsub=0.9813.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9863, gdt_score=0.9902, maxsub=0.9813.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9798, gdt_score=0.9785, maxsub=0.9731.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9798, gdt_score=0.9785, maxsub=0.9731.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9744, gdt_score=0.9727, maxsub=0.9661.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9812, gdt_score=0.9824, maxsub=0.9743.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00272
 : : : : : : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*
