C; model_eva_score=0.918, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9809, gdt_score=0.9805, maxsub=0.9730.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9809, gdt_score=0.9805, maxsub=0.9730.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9817, gdt_score=0.9805, maxsub=0.9739.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9817, gdt_score=0.9805, maxsub=0.9739.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9811, gdt_score=0.9824, maxsub=0.9735.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9786, gdt_score=0.9805, maxsub=0.9696.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9837, gdt_score=0.9863, maxsub=0.9761.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.917, tm_score=0.9882, gdt_score=0.9883, maxsub=0.9842.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.917, tm_score=0.9878, gdt_score=0.9922, maxsub=0.9802.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.918, tm_score=0.9872, gdt_score=0.9883, maxsub=0.9836.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.917, tm_score=0.9837, gdt_score=0.9824, maxsub=0.9782.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9835, gdt_score=0.9824, maxsub=0.9764.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9805, gdt_score=0.9805, maxsub=0.9709.
>P1;meta_blits5.pdb1
structureX:meta_blits5.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9805, gdt_score=0.9805, maxsub=0.9709.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9805, gdt_score=0.9805, maxsub=0.9709.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9862, gdt_score=0.9883, maxsub=0.9809.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.915, tm_score=0.9862, gdt_score=0.9883, maxsub=0.9809.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9854, gdt_score=0.9883, maxsub=0.9803.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C; model_eva_score=0.916, tm_score=0.9793, gdt_score=0.9805, maxsub=0.9672.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 128: : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00272
 : : : : : : : : : 
GPSQVQLVESGGGSVQAGGSLRLSCAASGKIHEIGYLGWFRQAPGKEREGVAALMTFQGQTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAYWGKQSPLISWDYSYWGQGTQVTVSA*
