C; model_eva_score=0.387, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_novel1.pdb1
structureX:meta_novel1.pdb: 1: : 132: : : : : 
GSHMASAARLTMMWEEVTCPICLDPFVEPVSIECGHSFCQECISQVGKGGGSVCPVCRQRFLLKNLRPNRQLANMVNNLKEISQEAREGTQGERCAVHGERLHLFCEKDGKALCWVCAQSRKHRDHAMVPLE*

C; model_eva_score=0.384, tm_score=0.6775, gdt_score=0.6629, maxsub=0.6404.
>P1;meta_novel4.pdb1
structureX:meta_novel4.pdb: 12: : 93: : : : : 
-----------MMWEEVTCPICLDPFVEPVSIECGHSFCQECISQVGKGGGSVCPVCRQRFLLKNLRPNRQLANMVNNLKEISQEAREGTQGE---------------------------------------*

C;total number of template models = 2
>P1;T042112
 : : : : : : : : : 
GSHMASAARLTMMWEEVTCPICLDPFVEPVSIECGHSFCQECISQVGKGGGSVCPVCRQRFLLKNLRPNRQLANMVNNLKEISQEAREGTQGERCAVHGERLHLFCEKDGKALCWVCAQSRKHRDHAMVPLE*
