C; model_eva_score=0.39, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 132: : : : : 
GSHMASAARLTMMWEEVTCPICLDPFVEPVSIECGHSFCQECISQVGKGGGSVCPVCRQRFLLKNLRPNRQLANMVNNLKEISQEAREGTQGERCAVHGERLHLFCEKDGKALCWVCAQSRKHRDHAMVPLE*

C; model_eva_score=0.385, tm_score=0.9011, gdt_score=0.8996, maxsub=0.8713.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 132: : : : : 
GSHMASAARLTMMWEEVTCPICLDPFVEPVSIECGHSFCQECISQVGKGGGSVCPVCRQRFLLKNLRPNRQLANMVNNLKEISQEAREGTQGERCAVHGERLHLFCEKDGKALCWVCAQSRKHRDHAMVPLE*

C;total number of template models = 2
>P1;T042112
 : : : : : : : : : 
GSHMASAARLTMMWEEVTCPICLDPFVEPVSIECGHSFCQECISQVGKGGGSVCPVCRQRFLLKNLRPNRQLANMVNNLKEISQEAREGTQGERCAVHGERLHLFCEKDGKALCWVCAQSRKHRDHAMVPLE*
