C; model_eva_score=0.1, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 246: : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*

C; model_eva_score=0.097, tm_score=0.6554, gdt_score=0.5640, maxsub=0.5124.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 175: : 246: : : : : 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------TIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*

C;total number of template models = 2
>P1;C00031
 : : : : : : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*
