C; model_eva_score=0.097, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 246: : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*

C; model_eva_score=0.095, tm_score=0.5203, gdt_score=0.4319, maxsub=0.3731.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 180: : 244: : : : : 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTA--*

C;total number of template models = 2
>P1;C00031
 : : : : : : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*
