C; model_eva_score=0.098, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 246: : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*

C; model_eva_score=0.1, tm_score=0.6012, gdt_score=0.4675, maxsub=0.4256.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 184: : 246: : : : : 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------KEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*

C;total number of template models = 2
>P1;C00031
 : : : : : : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*
