C; model_eva_score=0.092, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_muster2.pdb1
structureX:meta_muster2.pdb: 1: : 246: : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*

C; model_eva_score=0.091, tm_score=0.5433, gdt_score=0.3943, maxsub=0.2946.
>P1;meta_muster3.pdb1
structureX:meta_muster3.pdb: 117: : 142: : : : : 
--------------------------------------------------------------------------------------------------------------------ANKVSQANIDMGFGITKLVIRILDPF--------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00031
 : : : : : : : : : 
GSPGISGGGGGILDSLADFADQVTTPQVVNHVNSNNQAQQMAQKLDQDSIQLRNIKDNVQGTDYEKPVNEAITSVEKLKTSLRANSETVYDLNSIGSRVEALTDVIEAITFSTQHLANKVSQANIDMGFGITKLVIRILDPFASVDSIKAQVNDVKALEQKVLTYPDLKPTDRATIYTKSKLDKEIWNTRFTRDKKVLNVKEFKVYNTLNKAITHAVGVQLNPNVTVQQVDQEIVTLQAALQTALK*
