C; model_eva_score=0.134, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsu6.pdb1
structureX:meta_hhsu6.pdb: 1: : 263: : : : : 
SATSLKQDADDMCMICFTEALSAAPAIQLDCSHIFHLQCCRRVLENRWLGPRITFGFISCPICKNKINHIVLKDLLDPIKELYEDVRRKALMRLEYEGLHKSEAITTPGVRFYNDPAGYAMNRYAYYVCYKCRKAYFGGEARCDAEAGRGDDYDPRELICGACSDVSRAQMCPKHGTDFLEYKCRYCCSVAVFFCFGTTHFCNACHDDFQRMTSIPKEELPHCPAGPKGKQLEGTECPLHVVHPPTGEEFALGCGVCRNAHTF*

C; model_eva_score=0.134, tm_score=0.6181, gdt_score=0.5067, maxsub=0.4684.
>P1;meta_hhsu5.pdb1
structureX:meta_hhsu5.pdb: 7: : 77: : : : : 
------QDADDMCMICFTEALSAAPAIQLDCSHIFHLQCCRRVLENRWLGPRITFGFISCPICKNKINHIVLKDLLD------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;T041400000013
 : : : : : : : : : 
SATSLKQDADDMCMICFTEALSAAPAIQLDCSHIFHLQCCRRVLENRWLGPRITFGFISCPICKNKINHIVLKDLLDPIKELYEDVRRKALMRLEYEGLHKSEAITTPGVRFYNDPAGYAMNRYAYYVCYKCRKAYFGGEARCDAEAGRGDDYDPRELICGACSDVSRAQMCPKHGTDFLEYKCRYCCSVAVFFCFGTTHFCNACHDDFQRMTSIPKEELPHCPAGPKGKQLEGTECPLHVVHPPTGEEFALGCGVCRNAHTF*
