C; model_eva_score=0.344, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_novel4.pdb1
structureX:meta_novel4.pdb: 1: : 183: : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*

C; model_eva_score=0.349, tm_score=0.7645, gdt_score=0.7268, maxsub=0.6979.
>P1;meta_novel2.pdb1
structureX:meta_novel2.pdb: 39: : 100: : : : : 
--------------------------------------QVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGF-----------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;T0949
 : : : : : : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*
