C; model_eva_score=0.139, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_Unicon3d-5.pdb1
structureX:meta_Unicon3d-5.pdb: 1: : 118: : : : : 
GPGSAPLPNPPMTPAQHYAQAIHHEGLARHHTTVAEDHRQTANLHDNRIKAAKARYNAGLDPNGLTSAQKHQIERDHHLSLAAQAERHAATHNREAAYHRLHSQTPAPGTKRSIDELD*

C; model_eva_score=0.139, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_Unicon3d-4.pdb1
structureX:meta_Unicon3d-4.pdb: 1: : 118: : : : : 
GPGSAPLPNPPMTPAQHYAQAIHHEGLARHHTTVAEDHRQTANLHDNRIKAAKARYNAGLDPNGLTSAQKHQIERDHHLSLAAQAERHAATHNREAAYHRLHSQTPAPGTKRSIDELD*

C;total number of template models = 2
>P1;T0428011
 : : : : : : : : : 
GPGSAPLPNPPMTPAQHYAQAIHHEGLARHHTTVAEDHRQTANLHDNRIKAAKARYNAGLDPNGLTSAQKHQIERDHHLSLAAQAERHAATHNREAAYHRLHSQTPAPGTKRSIDELD*
