C; model_eva_score=0.764, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9277, gdt_score=0.9036, maxsub=0.8981.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.772, tm_score=0.9393, gdt_score=0.9321, maxsub=0.9132.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.769, tm_score=0.9302, gdt_score=0.9143, maxsub=0.9017.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9358, gdt_score=0.9232, maxsub=0.9057.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9448, gdt_score=0.9411, maxsub=0.9175.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9342, gdt_score=0.9286, maxsub=0.8958.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9444, gdt_score=0.9321, maxsub=0.9140.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9430, gdt_score=0.9446, maxsub=0.9243.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9453, gdt_score=0.9429, maxsub=0.9174.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9270, gdt_score=0.9161, maxsub=0.9054.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9268, gdt_score=0.9161, maxsub=0.8903.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9316, gdt_score=0.9375, maxsub=0.9119.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9316, gdt_score=0.9107, maxsub=0.8856.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.756, tm_score=0.9239, gdt_score=0.9214, maxsub=0.9012.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.754, tm_score=0.9067, gdt_score=0.8911, maxsub=0.8671.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.753, tm_score=0.8943, gdt_score=0.8839, maxsub=0.8371.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.748, tm_score=0.9055, gdt_score=0.8911, maxsub=0.8579.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.752, tm_score=0.9012, gdt_score=0.8839, maxsub=0.8509.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.746, tm_score=0.8824, gdt_score=0.8750, maxsub=0.8467.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*
