C; model_eva_score=0.772, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9595, gdt_score=0.9607, maxsub=0.9422.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9731, gdt_score=0.9768, maxsub=0.9621.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.769, tm_score=0.9594, gdt_score=0.9536, maxsub=0.9385.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9393, gdt_score=0.9321, maxsub=0.9132.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9348, gdt_score=0.9286, maxsub=0.9108.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9314, gdt_score=0.9286, maxsub=0.9103.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9410, gdt_score=0.9339, maxsub=0.9192.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9272, gdt_score=0.9232, maxsub=0.9018.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9293, gdt_score=0.9250, maxsub=0.9043.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9268, gdt_score=0.9196, maxsub=0.9067.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9477, gdt_score=0.9429, maxsub=0.9254.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9134, gdt_score=0.9089, maxsub=0.8850.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9286, gdt_score=0.9161, maxsub=0.9016.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.756, tm_score=0.9231, gdt_score=0.9143, maxsub=0.9013.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.754, tm_score=0.9093, gdt_score=0.8964, maxsub=0.8731.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.753, tm_score=0.9058, gdt_score=0.8964, maxsub=0.8706.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.748, tm_score=0.9042, gdt_score=0.8893, maxsub=0.8680.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.752, tm_score=0.9021, gdt_score=0.8804, maxsub=0.8585.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.746, tm_score=0.8970, gdt_score=0.8946, maxsub=0.8650.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*
