C; model_eva_score=0.773, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9812, gdt_score=0.9839, maxsub=0.9703.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.772, tm_score=0.9731, gdt_score=0.9768, maxsub=0.9621.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.769, tm_score=0.9718, gdt_score=0.9661, maxsub=0.9541.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9358, gdt_score=0.9232, maxsub=0.9057.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9358, gdt_score=0.9304, maxsub=0.9121.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9310, gdt_score=0.9143, maxsub=0.9050.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9422, gdt_score=0.9375, maxsub=0.9178.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9235, gdt_score=0.9143, maxsub=0.8963.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9311, gdt_score=0.9268, maxsub=0.9064.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9287, gdt_score=0.9250, maxsub=0.9083.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9585, gdt_score=0.9536, maxsub=0.9345.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9267, gdt_score=0.9179, maxsub=0.8983.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.756, tm_score=0.9307, gdt_score=0.9268, maxsub=0.9107.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.754, tm_score=0.9118, gdt_score=0.9071, maxsub=0.8751.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.753, tm_score=0.9106, gdt_score=0.9018, maxsub=0.8650.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.748, tm_score=0.9051, gdt_score=0.8982, maxsub=0.8670.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.752, tm_score=0.9071, gdt_score=0.8929, maxsub=0.8634.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.746, tm_score=0.9014, gdt_score=0.9036, maxsub=0.8698.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.745, tm_score=0.8873, gdt_score=0.8732, maxsub=0.8360.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*
