C; model_eva_score=0.773, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9812, gdt_score=0.9839, maxsub=0.9703.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.772, tm_score=0.9595, gdt_score=0.9607, maxsub=0.9422.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.769, tm_score=0.9606, gdt_score=0.9571, maxsub=0.9382.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9277, gdt_score=0.9036, maxsub=0.8981.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9302, gdt_score=0.9250, maxsub=0.9028.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9229, gdt_score=0.9018, maxsub=0.8917.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9362, gdt_score=0.9304, maxsub=0.9110.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9182, gdt_score=0.9018, maxsub=0.8912.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9257, gdt_score=0.9196, maxsub=0.8988.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9258, gdt_score=0.9214, maxsub=0.9036.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9523, gdt_score=0.9357, maxsub=0.9271.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9316, gdt_score=0.9268, maxsub=0.9058.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.756, tm_score=0.9243, gdt_score=0.9232, maxsub=0.9022.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.754, tm_score=0.9078, gdt_score=0.9018, maxsub=0.8710.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.753, tm_score=0.9168, gdt_score=0.9107, maxsub=0.8783.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.748, tm_score=0.9128, gdt_score=0.9000, maxsub=0.8789.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.752, tm_score=0.9027, gdt_score=0.8875, maxsub=0.8647.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.746, tm_score=0.8915, gdt_score=0.8911, maxsub=0.8585.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.745, tm_score=0.8874, gdt_score=0.8732, maxsub=0.8400.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*
