C; model_eva_score=0.769, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9606, gdt_score=0.9571, maxsub=0.9382.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.772, tm_score=0.9594, gdt_score=0.9536, maxsub=0.9385.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.773, tm_score=0.9718, gdt_score=0.9661, maxsub=0.9541.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9302, gdt_score=0.9143, maxsub=0.9017.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9414, gdt_score=0.9429, maxsub=0.9218.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9290, gdt_score=0.9054, maxsub=0.9033.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.762, tm_score=0.9365, gdt_score=0.9339, maxsub=0.9110.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9251, gdt_score=0.9089, maxsub=0.9015.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9345, gdt_score=0.9321, maxsub=0.9147.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9281, gdt_score=0.9232, maxsub=0.9076.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.764, tm_score=0.9438, gdt_score=0.9321, maxsub=0.9134.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.759, tm_score=0.9016, gdt_score=0.8893, maxsub=0.8681.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.76, tm_score=0.9201, gdt_score=0.9089, maxsub=0.8904.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.756, tm_score=0.9271, gdt_score=0.9268, maxsub=0.9078.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.754, tm_score=0.9099, gdt_score=0.9071, maxsub=0.8764.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.753, tm_score=0.9023, gdt_score=0.8946, maxsub=0.8479.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.748, tm_score=0.8940, gdt_score=0.8786, maxsub=0.8523.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.752, tm_score=0.9083, gdt_score=0.8964, maxsub=0.8670.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C; model_eva_score=0.746, tm_score=0.9036, gdt_score=0.9036, maxsub=0.8729.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 140: : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
GSMEDDAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNLEKTV*
