C; model_eva_score=0.136, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 263: : : : : 
SATSLKQDADDMCMICFTEALSAAPAIQLDCSHIFHLQCCRRVLENRWLGPRITFGFISCPICKNKINHIVLKDLLDPIKELYEDVRRKALMRLEYEGLHKSEAITTPGVRFYNDPAGYAMNRYAYYVCYKCRKAYFGGEARCDAEAGRGDDYDPRELICGACSDVSRAQMCPKHGTDFLEYKCRYCCSVAVFFCFGTTHFCNACHDDFQRMTSIPKEELPHCPAGPKGKQLEGTECPLHVVHPPTGEEFALGCGVCRNAHTF*

C; model_eva_score=0.136, tm_score=0.7064, gdt_score=0.6065, maxsub=0.5400.
>P1;meta_super3.pdb1
structureX:meta_super3.pdb: 55: : 138: : : : : 
------------------------------------------------------FGFISCPICKNKINHIVLKDLLDPIKELYEDVRRKALMRLEYEGLHKSEAITTPGVRFYNDPAGYAMNRYAYYVCYKCRKAYFG-----------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;T041400000013
 : : : : : : : : : 
SATSLKQDADDMCMICFTEALSAAPAIQLDCSHIFHLQCCRRVLENRWLGPRITFGFISCPICKNKINHIVLKDLLDPIKELYEDVRRKALMRLEYEGLHKSEAITTPGVRFYNDPAGYAMNRYAYYVCYKCRKAYFGGEARCDAEAGRGDDYDPRELICGACSDVSRAQMCPKHGTDFLEYKCRYCCSVAVFFCFGTTHFCNACHDDFQRMTSIPKEELPHCPAGPKGKQLEGTECPLHVVHPPTGEEFALGCGVCRNAHTF*
