C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGV----EIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRFAGQAQVSLRDL----CLEP--ILL--DVQPSRTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGKKVVVDLAE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGV----EIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRFAGQAQVSLRDL----CLEP--ILL--DVQPSRTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGKKVVVDLAE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGV----EIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRFAGQAQVSLRDL----CLEP--ILL--DVQPSRTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGKKVVVDLAE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;query_length:334 num_of_temps:1 cover_ratio:0.24 cover:80 not_cover:254
>P1;2017-11-04_00000049_1_72
 : : : : : : : : : 
MGGSHHHHHHGMASMTGGQQMGRDLYDDDDKDPSSDWPTRQVTLVVPFTSGGTTDMLARLIAARLSEHYGQ----SFVIDNRSGESGNIAASYVAKVPADGYTFIIGTPGIHATNRLVYRTMGYDPATDFTPVIVIARVPNLLSVTKSLPVTS-----VADLISYARQRPRELFYGVSALGSTGHLSTE----LFKTMTGVEITAVP-YKGSAPMLRDLAEGRVHLTIDNLPASKPLLEAGEIRPLAVTTAKRWPPLSHLP----TIAEAGVPGYETASWFTVGAPRGTP-TEIVTSLNTTVAAFLGSDSGTVKLREIGAEPGGGSPQDMQRHVE----AEIARWEKVAKTAG-IAPL*
