C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGVEIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRFAGQAQVSLRDL----CLEP--ILL--DVQPSRTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGK--KVVVDL--AE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGVEIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRFAGQAQVSLRDL----CLEP--ILL--DVQPSRTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGK--KVVVDL--AE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGVEIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRFAGQAQVSLRDL----CLEP--ILL--DVQPSRTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGK--KVVVDL--AE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;query_length:334 num_of_temps:1 cover_ratio:0.37 cover:123 not_cover:211
>P1;2017-11-04_00000049_1_72
 : : : : : : : : : 
MGGSHHHHHHGMASMTGGQQMGRDLYDDDDKDPSSDWPTRQVTLVVPFTSGGTTDMLARLIAARLSEHYGQSFVIDNRSGESGNIAASYVAKVPADGYTFIIGTPGIHATNRLVYRTMGYDPATDFTPVIVIARVPNLLSVTKSLPVTS-----VADLISYARQRPRELFYGVSALGSTGHLSTE----LFKTMTGVEITAVP-YKGSAPMLRDLAEGRVHLTIDNLPASKPLLEAGE--IRPLAV--TTAKRWPPLSHLP----TIAEAGVPGYETASWFTVGAPRGTP-TEIVTSLNTTVAAFLGSDSGTVKLREIGAEPGGGSPQDMQRHVE----AEIARWEKVAKTAG-IAPL*
