C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGVEIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRF-AGQAQVSLRDL----CLEP--ILL---DV-QPS-RTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGKKVVVDLAE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGVEIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRF-AGQAQVSLRDL----CLEP--ILL---DV-QPS-RTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGKKVVVDLAE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;cover size:247; local alignment length=247 (original info = e3fzvA3	211	12.52	0.018	194	10	2.29)
>P1;e3fzvA3
structureX:e3fzvA3: 12: : 211: : : : : 
------------------------------------------QIDIGCFETVAPLYLPGLIAGFRQAYPGVEIRIRDGE---QQELVQGLTSGRFD---LAFLYEH------DLD--------STIETE-PLPPQRPHALLPEGHRF-AGQAQVSLRDL----CLEP--ILL---DV-QPS-RTYF--V----SLFEELGLTPNI-A-FSSPSIEVRGVGQGFG-FSLLVTRPHSECTYDGKKVVVDLAE------------------------PVSTSGLAAAWLKRAQLTKPARLFVDYCREQLGK--------------------------------------------------*

C;query_length:334 num_of_temps:1 cover_ratio:0.31 cover:102 not_cover:232
>P1;2017-11-04_00000049_1_72
 : : : : : : : : : 
MGGSHHHHHHGMASMTGGQQMGRDLYDDDDKDPSSDWPTRQVTLVVPFTSGGTTDMLARLIAARLSEHYGQSFVIDNRSGESGNIAASYVAKVPADGYTFIIGTPGIHATNRLVYRTMGYDPATDFTPVIVIARVPNLLSVTKSLPV-TS-----VADLISYARQRPRELFY-GVSA-LGS-TGHLSTE----LFKTMTGVEITAVP-YKGSAPMLRDLAEGRVHLTIDNLPASKPLLEAGEIRPLAVTTAKRWPPLSHLP----TIAEAGVPGYETASWFTVGAPRGTP-TEIVTSLNTTVAAFLGSDSGTVKLREIGAEPGGGSPQDMQRHVE----AEIARWEKVAKTAG-IAPL*
