C; model_eva_score=0.333, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 183: : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*

C; model_eva_score=0.319, tm_score=0.5841, gdt_score=0.5369, maxsub=0.4693.
>P1;meta_center4.pdb1
structureX:meta_center4.pdb: 128: : 179: : : : : 
-------------------------------------------------------------------------------------------------------------------------------PVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILP----*

C;total number of template models = 2
>P1;T0949
 : : : : : : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*
