C; model_eva_score=0.335, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 183: : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*

C; model_eva_score=0.332, tm_score=0.7216, gdt_score=0.6735, maxsub=0.6757.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 42: : 102: : : : : 
-----------------------------------------NGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPK---------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;T0949
 : : : : : : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*
