C; model_eva_score=0.334, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsu1.pdb1
structureX:meta_hhsu1.pdb: 1: : 183: : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*

C; model_eva_score=0.322, tm_score=0.6911, gdt_score=0.6721, maxsub=0.6564.
>P1;meta_hhsu5.pdb1
structureX:meta_hhsu5.pdb: 45: : 117: : : : : 
--------------------------------------------HHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDG------------------------------------------------------------------*

C;total number of template models = 2
>P1;T0949
 : : : : : : : : : 
MAAKKGMTTVLVSAVICAGVIIGALQWEKAVALPNPSGQVINGVHHYTIDEFNYYYKPDRMTWHVGEKVELTIDNRSQSAPPIAHQFSIGRTLVSRDNGFPKSQAIAVGWKDNFFDGVPITSGGQTGPVPAFSVSLNGGQKYTFSFVVPNKPGKWEYGCFLQTGQHFMNGMHGILDILPAQGS*
