C; model_eva_score=0.804, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.803, tm_score=0.9724, gdt_score=0.9764, maxsub=0.9623.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9896, gdt_score=0.9921, maxsub=0.9858.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.806, tm_score=0.9802, gdt_score=0.9803, maxsub=0.9728.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9898, gdt_score=0.9902, maxsub=0.9858.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9956, gdt_score=0.9980, maxsub=0.9938.
>P1;meta_multicom3.pdb1
structureX:meta_multicom3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9852, gdt_score=0.9862, maxsub=0.9796.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9690, gdt_score=0.9744, maxsub=0.9509.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9656, gdt_score=0.9685, maxsub=0.9490.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9632, gdt_score=0.9606, maxsub=0.9462.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9632, gdt_score=0.9606, maxsub=0.9462.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9652, gdt_score=0.9705, maxsub=0.9493.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9704, gdt_score=0.9744, maxsub=0.9562.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9555, gdt_score=0.9626, maxsub=0.9355.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9648, gdt_score=0.9685, maxsub=0.9466.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.794, tm_score=0.9581, gdt_score=0.9547, maxsub=0.9362.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9677, gdt_score=0.9685, maxsub=0.9463.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9807, gdt_score=0.9843, maxsub=0.9720.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9604, gdt_score=0.9587, maxsub=0.9421.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9812, gdt_score=0.9862, maxsub=0.9752.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C;total number of template models = 20
>P1;C00691
 : : : : : : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*
