C; model_eva_score=0.803, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.806, tm_score=0.9828, gdt_score=0.9882, maxsub=0.9766.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9808, gdt_score=0.9843, maxsub=0.9733.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.804, tm_score=0.9724, gdt_score=0.9764, maxsub=0.9623.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9774, gdt_score=0.9783, maxsub=0.9687.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9738, gdt_score=0.9764, maxsub=0.9638.
>P1;meta_multicom3.pdb1
structureX:meta_multicom3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9777, gdt_score=0.9823, maxsub=0.9678.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9576, gdt_score=0.9528, maxsub=0.9369.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9524, gdt_score=0.9547, maxsub=0.9302.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9523, gdt_score=0.9528, maxsub=0.9315.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9523, gdt_score=0.9528, maxsub=0.9315.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9539, gdt_score=0.9567, maxsub=0.9333.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9533, gdt_score=0.9587, maxsub=0.9296.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9658, gdt_score=0.9705, maxsub=0.9516.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9629, gdt_score=0.9685, maxsub=0.9435.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.794, tm_score=0.9676, gdt_score=0.9705, maxsub=0.9534.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9583, gdt_score=0.9587, maxsub=0.9360.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9724, gdt_score=0.9685, maxsub=0.9620.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9631, gdt_score=0.9665, maxsub=0.9481.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9734, gdt_score=0.9705, maxsub=0.9634.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C;total number of template models = 20
>P1;C00691
 : : : : : : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*
