C; model_eva_score=0.806, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.803, tm_score=0.9828, gdt_score=0.9882, maxsub=0.9766.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9849, gdt_score=0.9882, maxsub=0.9789.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.804, tm_score=0.9802, gdt_score=0.9803, maxsub=0.9728.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9816, gdt_score=0.9823, maxsub=0.9747.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9796, gdt_score=0.9823, maxsub=0.9720.
>P1;meta_multicom3.pdb1
structureX:meta_multicom3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9724, gdt_score=0.9685, maxsub=0.9623.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9643, gdt_score=0.9685, maxsub=0.9461.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9630, gdt_score=0.9665, maxsub=0.9458.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9564, gdt_score=0.9528, maxsub=0.9378.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9564, gdt_score=0.9528, maxsub=0.9378.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9606, gdt_score=0.9646, maxsub=0.9436.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9568, gdt_score=0.9508, maxsub=0.9377.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9607, gdt_score=0.9606, maxsub=0.9462.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9645, gdt_score=0.9665, maxsub=0.9459.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.794, tm_score=0.9756, gdt_score=0.9744, maxsub=0.9670.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9627, gdt_score=0.9665, maxsub=0.9417.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9730, gdt_score=0.9744, maxsub=0.9632.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9707, gdt_score=0.9744, maxsub=0.9578.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9746, gdt_score=0.9744, maxsub=0.9652.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C;total number of template models = 20
>P1;C00691
 : : : : : : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*
