C; model_eva_score=0.802, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.803, tm_score=0.9774, gdt_score=0.9783, maxsub=0.9687.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9938, gdt_score=0.9980, maxsub=0.9914.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.804, tm_score=0.9898, gdt_score=0.9902, maxsub=0.9858.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.806, tm_score=0.9816, gdt_score=0.9823, maxsub=0.9747.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.802, tm_score=0.9919, gdt_score=0.9980, maxsub=0.9887.
>P1;meta_multicom3.pdb1
structureX:meta_multicom3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9836, gdt_score=0.9823, maxsub=0.9776.
>P1;meta_csiblast2.pdb1
structureX:meta_csiblast2.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9690, gdt_score=0.9705, maxsub=0.9513.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9629, gdt_score=0.9705, maxsub=0.9453.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9546, gdt_score=0.9488, maxsub=0.9358.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.801, tm_score=0.9546, gdt_score=0.9488, maxsub=0.9358.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.799, tm_score=0.9588, gdt_score=0.9567, maxsub=0.9408.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9636, gdt_score=0.9626, maxsub=0.9470.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9621, gdt_score=0.9626, maxsub=0.9497.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9724, gdt_score=0.9744, maxsub=0.9527.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.794, tm_score=0.9540, gdt_score=0.9449, maxsub=0.9350.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.795, tm_score=0.9715, gdt_score=0.9744, maxsub=0.9517.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9904, gdt_score=0.9980, maxsub=0.9866.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.797, tm_score=0.9578, gdt_score=0.9547, maxsub=0.9422.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C; model_eva_score=0.793, tm_score=0.9898, gdt_score=0.9921, maxsub=0.9858.
>P1;meta_csiblast4.pdb1
structureX:meta_csiblast4.pdb: 1: : 127: : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*

C;total number of template models = 20
>P1;C00691
 : : : : : : : : : 
PLYECQTVKGTLSERQRQSLAESITSIHTRETGAPASYVHVLFKELEPGSAFTAGQVATPAIIRGQIRAGRPQATRHAILRAITDVYMAVTGADANAVVVAVVDIPASWAMEGGQIFPEPEQPPEVA*
