C;cover size:307; local alignment length=307 (original info = e4ntdA1	318	471.34	2.4e-70	296	24	100.00)
>P1;e4ntdA1
structureX:e4ntdA1: 5: : 304: : : : : 
---------------HEGGIDVVVIGAGAGGLNAALVLARARRRVVLVDSGAPRNAPSAHMQGFLSRD-GMAPSALLETGRAEVSGYGAEFIRGEVDDVEREGEDDAPRFTVRLVGG------VALSTRRVVVATGLRDELPDIP---GVRERWGKDLLHCPYCHGYEVSDQPLGVLGTSPGAVRHALLLRQWSDDVVLFRHGLEL-TDDDRRALSARQVPVIEGTVKRLVVEDDRLRGVELAEDSGVARSTVFVVPRMVPRDGLLTALGCERGADGWIATDRSGLTSVPGVWAVGNVVDPRALVVSSAGMGSAAAFALNHQLVDE--------*

C;query_length:330 num_of_temps:1 cover_ratio:0.93 cover:307 not_cover:23
>P1;2017-11-11_00000010_1_72
 : : : : : : : : : 
GSHMVKLSSKNLDARLDTVYDAIVLGGGMGGLSAAIYLARYGLKCLVVEKGRGRSFWMQDLRNYVGLDPDTPGRDIITHSTQQALHWGADLLRGYVEDVTDEGD----TLAVKVKVGKKDSLYPIFRTKYVIAATGIIDNLPQLEDMQNVYDYAGYTLHVCMICDGFDMWDQKAVLIAGTEGQINAAFVLNWFTPYITVLTHGLCTVGDEMKAKLADHGYPLHEAAITKFLGEDHKMSGVELVDGTVMEATTGLINMGSVYHNHYLKGIEGLEWDGENLVTNDMAQTSHPRIFALGDLKKGLNQVSVAVADGTLAATQIWRNIRRASEPRKWIH*
