C; model_eva_score=0.153, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_abi4_denovo1.pdb1
structureX:meta_abi4_denovo1.pdb: 1: : 196: : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*

C; model_eva_score=0.156, tm_score=0.4853, gdt_score=0.3827, maxsub=0.3155.
>P1;meta_abi5_denovo2.pdb1
structureX:meta_abi5_denovo2.pdb: 50: : 77: : : : : 
-------------------------------------------------NPEKKSVLQKILEDEEKHIELLETLQQT-----------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;T042120
 : : : : : : : : : 
GSPELRQEHQQLAQEFQQLLQEIQQLGRELLKGELQGIKQLREASEKARNPEKKSVLQKILEDEEKHIELLETLQQTGQEAQQLLQELQQTGQELWQLGGSGGPELRQKHQQLAQKIQQLLQKHQQLGAKILEDEEKHIELLETILGGSGGDELRELLKGELQGIKQYRELQQLGQKAQQLVQKLQQTGQKLWQLG*
