C; model_eva_score=0.697, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.9245, gdt_score=0.8927, maxsub=0.8799.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.693, tm_score=0.9188, gdt_score=0.8872, maxsub=0.8702.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.691, tm_score=0.9433, gdt_score=0.9090, maxsub=0.8960.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.686, tm_score=0.9098, gdt_score=0.8791, maxsub=0.8673.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.688, tm_score=0.9208, gdt_score=0.8981, maxsub=0.8876.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9149, gdt_score=0.8927, maxsub=0.8713.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.9186, gdt_score=0.8913, maxsub=0.8655.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.676, tm_score=0.9592, gdt_score=0.9307, maxsub=0.9171.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9126, gdt_score=0.8872, maxsub=0.8611.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8906, gdt_score=0.8478, maxsub=0.8359.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.9100, gdt_score=0.8709, maxsub=0.8479.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.672, tm_score=0.8860, gdt_score=0.8383, maxsub=0.8034.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.67, tm_score=0.8828, gdt_score=0.8397, maxsub=0.8055.
>P1;meta_star3.pdb1
structureX:meta_star3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.678, tm_score=0.9094, gdt_score=0.8845, maxsub=0.8659.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.671, tm_score=0.8862, gdt_score=0.8505, maxsub=0.8271.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.661, tm_score=0.8601, gdt_score=0.8220, maxsub=0.7656.
>P1;meta_center3.pdb1
structureX:meta_center3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.68, tm_score=0.9080, gdt_score=0.8655, maxsub=0.8648.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.9125, gdt_score=0.8859, maxsub=0.8693.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.672, tm_score=0.9164, gdt_score=0.8940, maxsub=0.8664.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00681
 : : : : : : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*
