C; model_eva_score=0.686, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.9098, gdt_score=0.8791, maxsub=0.8673.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.693, tm_score=0.8843, gdt_score=0.8560, maxsub=0.8346.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.691, tm_score=0.8966, gdt_score=0.8438, maxsub=0.8341.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.9030, gdt_score=0.8587, maxsub=0.8487.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.688, tm_score=0.9706, gdt_score=0.9457, maxsub=0.9457.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9446, gdt_score=0.9049, maxsub=0.8936.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.9128, gdt_score=0.8682, maxsub=0.8484.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.676, tm_score=0.8855, gdt_score=0.8397, maxsub=0.8160.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9356, gdt_score=0.8764, maxsub=0.8750.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8889, gdt_score=0.8288, maxsub=0.8166.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8910, gdt_score=0.8247, maxsub=0.8285.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.67, tm_score=0.8697, gdt_score=0.8125, maxsub=0.7840.
>P1;meta_star3.pdb1
structureX:meta_star3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.678, tm_score=0.9387, gdt_score=0.8832, maxsub=0.8817.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.671, tm_score=0.8863, gdt_score=0.8261, maxsub=0.8037.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.661, tm_score=0.8556, gdt_score=0.8016, maxsub=0.7634.
>P1;meta_center3.pdb1
structureX:meta_center3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.68, tm_score=0.9665, gdt_score=0.9307, maxsub=0.9350.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.9381, gdt_score=0.8791, maxsub=0.8800.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.9375, gdt_score=0.8940, maxsub=0.8792.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.672, tm_score=0.9075, gdt_score=0.8356, maxsub=0.8234.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00681
 : : : : : : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*
