C; model_eva_score=0.693, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.9188, gdt_score=0.8872, maxsub=0.8702.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.8890, gdt_score=0.8641, maxsub=0.8391.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.691, tm_score=0.8974, gdt_score=0.8533, maxsub=0.8277.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.686, tm_score=0.8843, gdt_score=0.8560, maxsub=0.8346.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.8728, gdt_score=0.8356, maxsub=0.8112.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8732, gdt_score=0.8383, maxsub=0.8063.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.676, tm_score=0.8910, gdt_score=0.8451, maxsub=0.8187.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.8717, gdt_score=0.8220, maxsub=0.8032.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8809, gdt_score=0.8410, maxsub=0.8093.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8830, gdt_score=0.8207, maxsub=0.8076.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.672, tm_score=0.9352, gdt_score=0.8981, maxsub=0.8733.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.67, tm_score=0.8769, gdt_score=0.8342, maxsub=0.7956.
>P1;meta_star3.pdb1
structureX:meta_star3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.678, tm_score=0.8638, gdt_score=0.8016, maxsub=0.7909.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.671, tm_score=0.8702, gdt_score=0.8274, maxsub=0.8028.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.661, tm_score=0.8605, gdt_score=0.8125, maxsub=0.7698.
>P1;meta_center3.pdb1
structureX:meta_center3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.8623, gdt_score=0.8003, maxsub=0.7881.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.672, tm_score=0.8581, gdt_score=0.7921, maxsub=0.7827.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.671, tm_score=0.8640, gdt_score=0.8166, maxsub=0.7734.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.673, tm_score=0.8872, gdt_score=0.8098, maxsub=0.8044.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00681
 : : : : : : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*
