C; model_eva_score=0.691, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.9433, gdt_score=0.9090, maxsub=0.8960.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.693, tm_score=0.8974, gdt_score=0.8533, maxsub=0.8277.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.9444, gdt_score=0.9348, maxsub=0.9130.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.686, tm_score=0.8966, gdt_score=0.8438, maxsub=0.8341.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.688, tm_score=0.9099, gdt_score=0.8818, maxsub=0.8626.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9075, gdt_score=0.8709, maxsub=0.8537.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.9142, gdt_score=0.8818, maxsub=0.8541.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.676, tm_score=0.9302, gdt_score=0.8927, maxsub=0.8645.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9212, gdt_score=0.8954, maxsub=0.8734.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8893, gdt_score=0.8370, maxsub=0.8226.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.9293, gdt_score=0.9158, maxsub=0.8812.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.672, tm_score=0.8667, gdt_score=0.8030, maxsub=0.7646.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.67, tm_score=0.8777, gdt_score=0.8057, maxsub=0.7846.
>P1;meta_star3.pdb1
structureX:meta_star3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.678, tm_score=0.9134, gdt_score=0.8859, maxsub=0.8675.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.671, tm_score=0.8771, gdt_score=0.8329, maxsub=0.8074.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.661, tm_score=0.8533, gdt_score=0.7826, maxsub=0.7435.
>P1;meta_center3.pdb1
structureX:meta_center3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.68, tm_score=0.9111, gdt_score=0.8750, maxsub=0.8631.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.9090, gdt_score=0.8832, maxsub=0.8600.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.8967, gdt_score=0.8696, maxsub=0.8446.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00681
 : : : : : : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*
