C; model_eva_score=0.697, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.697, tm_score=0.9245, gdt_score=0.8927, maxsub=0.8799.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.693, tm_score=0.8890, gdt_score=0.8641, maxsub=0.8391.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.691, tm_score=0.9444, gdt_score=0.9348, maxsub=0.9130.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.686, tm_score=0.9030, gdt_score=0.8587, maxsub=0.8487.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.688, tm_score=0.9154, gdt_score=0.8818, maxsub=0.8727.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9170, gdt_score=0.8899, maxsub=0.8695.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.9141, gdt_score=0.8764, maxsub=0.8522.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.676, tm_score=0.9114, gdt_score=0.8804, maxsub=0.8524.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.682, tm_score=0.9183, gdt_score=0.8886, maxsub=0.8750.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.8905, gdt_score=0.8478, maxsub=0.8344.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.679, tm_score=0.9209, gdt_score=0.9035, maxsub=0.8842.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.672, tm_score=0.8668, gdt_score=0.8207, maxsub=0.7901.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.67, tm_score=0.8799, gdt_score=0.8193, maxsub=0.8006.
>P1;meta_star3.pdb1
structureX:meta_star3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.678, tm_score=0.9137, gdt_score=0.8818, maxsub=0.8662.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.671, tm_score=0.8817, gdt_score=0.8424, maxsub=0.8211.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.661, tm_score=0.8655, gdt_score=0.8179, maxsub=0.7771.
>P1;meta_center3.pdb1
structureX:meta_center3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.68, tm_score=0.9101, gdt_score=0.8668, maxsub=0.8601.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.9134, gdt_score=0.8832, maxsub=0.8695.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C; model_eva_score=0.674, tm_score=0.9030, gdt_score=0.8736, maxsub=0.8565.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 184: : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*

C;total number of template models = 20
>P1;C00681
 : : : : : : : : : 
GGYAVDYNEPIIIKENGEIKVVKIGELIDKIIENSENIRREGILEIAKCKGIEVIAFNSNYKFKFMPVSEVSRHPVSEMFEIVVEGNKKVRVTRSHSVFTIRDNEVVPIRVDELKVGDILVLAKRITNIYTNRKLEKLINSDFIFLKIKEINKVEPTSGYAYDLTVPNAENFVAGFGGFVLHNA*
