C; model_eva_score=0.662, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.671, tm_score=0.8992, gdt_score=0.8742, maxsub=0.8354.
>P1;meta_center4.pdb1
structureX:meta_center4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.672, tm_score=0.9008, gdt_score=0.8727, maxsub=0.8418.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9915, gdt_score=0.9938, maxsub=0.9838.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.8821, gdt_score=0.8509, maxsub=0.8121.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.663, tm_score=0.9221, gdt_score=0.9068, maxsub=0.8729.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.9198, gdt_score=0.9037, maxsub=0.8723.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.659, tm_score=0.8906, gdt_score=0.8602, maxsub=0.8229.
>P1;meta_star4.pdb1
structureX:meta_star4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.8771, gdt_score=0.8509, maxsub=0.8009.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.657, tm_score=0.9465, gdt_score=0.9394, maxsub=0.9203.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.656, tm_score=0.9538, gdt_score=0.9488, maxsub=0.9292.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9245, gdt_score=0.9053, maxsub=0.8704.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9245, gdt_score=0.9053, maxsub=0.8704.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.8739, gdt_score=0.8401, maxsub=0.7900.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.651, tm_score=0.9305, gdt_score=0.9177, maxsub=0.8840.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.652, tm_score=0.9203, gdt_score=0.8991, maxsub=0.8629.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.646, tm_score=0.9381, gdt_score=0.9177, maxsub=0.8867.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.9359, gdt_score=0.9177, maxsub=0.8923.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.9720, gdt_score=0.9612, maxsub=0.9543.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9357, gdt_score=0.9068, maxsub=0.8785.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C;total number of template models = 20
>P1;C00481
 : : : : : : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*
