C; model_eva_score=0.661, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.671, tm_score=0.9294, gdt_score=0.9006, maxsub=0.8843.
>P1;meta_center4.pdb1
structureX:meta_center4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.662, tm_score=0.8821, gdt_score=0.8509, maxsub=0.8121.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.8816, gdt_score=0.8509, maxsub=0.8094.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.672, tm_score=0.9716, gdt_score=0.9627, maxsub=0.9497.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.663, tm_score=0.9297, gdt_score=0.9037, maxsub=0.8813.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.9360, gdt_score=0.9099, maxsub=0.8877.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.659, tm_score=0.9325, gdt_score=0.8898, maxsub=0.8920.
>P1;meta_star4.pdb1
structureX:meta_star4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9771, gdt_score=0.9736, maxsub=0.9556.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.657, tm_score=0.8768, gdt_score=0.8416, maxsub=0.8150.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.656, tm_score=0.8816, gdt_score=0.8509, maxsub=0.8132.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9049, gdt_score=0.8866, maxsub=0.8566.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9049, gdt_score=0.8866, maxsub=0.8566.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9882, gdt_score=0.9876, maxsub=0.9779.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.651, tm_score=0.8736, gdt_score=0.8401, maxsub=0.7953.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.652, tm_score=0.8881, gdt_score=0.8696, maxsub=0.8329.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.646, tm_score=0.8715, gdt_score=0.8276, maxsub=0.7767.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.8877, gdt_score=0.8401, maxsub=0.8193.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.8688, gdt_score=0.8199, maxsub=0.7939.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.8900, gdt_score=0.8432, maxsub=0.8278.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C;total number of template models = 20
>P1;C00481
 : : : : : : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*
