C; model_eva_score=0.671, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_center4.pdb1
structureX:meta_center4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.672, tm_score=0.9448, gdt_score=0.9224, maxsub=0.9112.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.662, tm_score=0.8992, gdt_score=0.8742, maxsub=0.8354.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.8994, gdt_score=0.8758, maxsub=0.8344.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.9294, gdt_score=0.9006, maxsub=0.8843.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.663, tm_score=0.9400, gdt_score=0.9161, maxsub=0.8972.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.9385, gdt_score=0.9068, maxsub=0.9006.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.659, tm_score=0.9531, gdt_score=0.9348, maxsub=0.9162.
>P1;meta_star4.pdb1
structureX:meta_star4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9167, gdt_score=0.8882, maxsub=0.8639.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.657, tm_score=0.8859, gdt_score=0.8571, maxsub=0.8268.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.656, tm_score=0.8900, gdt_score=0.8618, maxsub=0.8295.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.8978, gdt_score=0.8758, maxsub=0.8432.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.8978, gdt_score=0.8758, maxsub=0.8432.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9251, gdt_score=0.8898, maxsub=0.8762.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.651, tm_score=0.8848, gdt_score=0.8571, maxsub=0.8203.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.652, tm_score=0.8929, gdt_score=0.8789, maxsub=0.8443.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.646, tm_score=0.8802, gdt_score=0.8432, maxsub=0.7973.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.8810, gdt_score=0.8370, maxsub=0.8023.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.8830, gdt_score=0.8447, maxsub=0.8115.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.8996, gdt_score=0.8556, maxsub=0.8455.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C;total number of template models = 20
>P1;C00481
 : : : : : : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*
