C; model_eva_score=0.658, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.671, tm_score=0.8994, gdt_score=0.8758, maxsub=0.8344.
>P1;meta_center4.pdb1
structureX:meta_center4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.662, tm_score=0.9915, gdt_score=0.9938, maxsub=0.9838.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.672, tm_score=0.9007, gdt_score=0.8696, maxsub=0.8405.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.8816, gdt_score=0.8509, maxsub=0.8094.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.663, tm_score=0.9251, gdt_score=0.9084, maxsub=0.8808.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.9250, gdt_score=0.9084, maxsub=0.8806.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.659, tm_score=0.8943, gdt_score=0.8649, maxsub=0.8290.
>P1;meta_star4.pdb1
structureX:meta_star4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.8770, gdt_score=0.8447, maxsub=0.7976.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.657, tm_score=0.9497, gdt_score=0.9425, maxsub=0.9239.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.656, tm_score=0.9550, gdt_score=0.9503, maxsub=0.9304.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9181, gdt_score=0.8960, maxsub=0.8575.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9181, gdt_score=0.8960, maxsub=0.8575.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.8739, gdt_score=0.8385, maxsub=0.7865.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.651, tm_score=0.9313, gdt_score=0.9177, maxsub=0.8870.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.652, tm_score=0.9204, gdt_score=0.8960, maxsub=0.8667.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.646, tm_score=0.9418, gdt_score=0.9239, maxsub=0.8937.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.9376, gdt_score=0.9208, maxsub=0.8944.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.9769, gdt_score=0.9689, maxsub=0.9610.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9428, gdt_score=0.9208, maxsub=0.8957.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C;total number of template models = 20
>P1;C00481
 : : : : : : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*
