C; model_eva_score=0.672, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.671, tm_score=0.9448, gdt_score=0.9224, maxsub=0.9112.
>P1;meta_center4.pdb1
structureX:meta_center4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.662, tm_score=0.9008, gdt_score=0.8727, maxsub=0.8418.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9007, gdt_score=0.8696, maxsub=0.8405.
>P1;meta_hmmer2.pdb1
structureX:meta_hmmer2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.9716, gdt_score=0.9627, maxsub=0.9497.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.663, tm_score=0.9501, gdt_score=0.9255, maxsub=0.9105.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.661, tm_score=0.9506, gdt_score=0.9224, maxsub=0.9166.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.659, tm_score=0.9421, gdt_score=0.9115, maxsub=0.9081.
>P1;meta_star4.pdb1
structureX:meta_star4.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9590, gdt_score=0.9457, maxsub=0.9284.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.657, tm_score=0.8937, gdt_score=0.8618, maxsub=0.8431.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.656, tm_score=0.8971, gdt_score=0.8634, maxsub=0.8371.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9206, gdt_score=0.9068, maxsub=0.8795.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.658, tm_score=0.9206, gdt_score=0.9068, maxsub=0.8795.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9669, gdt_score=0.9550, maxsub=0.9435.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.651, tm_score=0.8903, gdt_score=0.8587, maxsub=0.8210.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.652, tm_score=0.9053, gdt_score=0.8835, maxsub=0.8568.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.646, tm_score=0.8861, gdt_score=0.8447, maxsub=0.7978.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.8910, gdt_score=0.8416, maxsub=0.8201.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.65, tm_score=0.8866, gdt_score=0.8385, maxsub=0.8162.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C; model_eva_score=0.655, tm_score=0.9084, gdt_score=0.8634, maxsub=0.8560.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 161: : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*

C;total number of template models = 20
>P1;C00481
 : : : : : : : : : 
GTGVPETVFEELKRYVGWGDGDERALRSLHGAAAPHFPRLAEEFYDRILGHEGARTALVGGESQVGHLKVTMIAWLDELLGGPWDEAYWDRRYRIGRVHVRIGLPQHYMFGAMNVHRTGLARLAYERFHGDPPELERVRNALGKVLDLELAVMLHTYREDL*
