C; model_eva_score=0.074, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite9.pdb1
structureX:meta_hhsuite9.pdb: 1: : 283: : : : : 
GPSILEEYIRMAKNKEFFDALEEIAESAKNDETLRNELAKVLDDILKTDPSDPEAFRKIVAEHQEFWDEHDPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEKSDTDTLVAILKNNPEECRAYIESKKPGLGNFSEGNVHGWLKEEYTPTIPPKAINKSTGVLSDEAIKRIKEQARDLLLLKLINSSGNTQLLKDLRDAMSKPEAERAANALGFPTEGNGVLFLSREVVDALEERVEKLEQEAAKRGFDSYVQSLSHNALLA*

C; model_eva_score=0.075, tm_score=0.6517, gdt_score=0.5265, maxsub=0.4736.
>P1;meta_super8.pdb1
structureX:meta_super8.pdb: 71: : 128: : : : : 
----------------------------------------------------------------------DPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEKSDTD-----------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00231
 : : : : : : : : : 
GPSILEEYIRMAKNKEFFDALEEIAESAKNDETLRNELAKVLDDILKTDPSDPEAFRKIVAEHQEFWDEHDPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEKSDTDTLVAILKNNPEECRAYIESKKPGLGNFSEGNVHGWLKEEYTPTIPPKAINKSTGVLSDEAIKRIKEQARDLLLLKLINSSGNTQLLKDLRDAMSKPEAERAANALGFPTEGNGVLFLSREVVDALEERVEKLEQEAAKRGFDSYVQSLSHNALLA*
