C; model_eva_score=0.067, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 283: : : : : 
GPSILEEYIRMAKNKEFFDALEEIAESAKNDETLRNELAKVLDDILKTDPSDPEAFRKIVAEHQEFWDEHDPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEKSDTDTLVAILKNNPEECRAYIESKKPGLGNFSEGNVHGWLKEEYTPTIPPKAINKSTGVLSDEAIKRIKEQARDLLLLKLINSSGNTQLLKDLRDAMSKPEAERAANALGFPTEGNGVLFLSREVVDALEERVEKLEQEAAKRGFDSYVQSLSHNALLA*

C; model_eva_score=0.068, tm_score=0.7253, gdt_score=0.5283, maxsub=0.4590.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 71: : 124: : : : : 
----------------------------------------------------------------------DPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEK---------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00231
 : : : : : : : : : 
GPSILEEYIRMAKNKEFFDALEEIAESAKNDETLRNELAKVLDDILKTDPSDPEAFRKIVAEHQEFWDEHDPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEKSDTDTLVAILKNNPEECRAYIESKKPGLGNFSEGNVHGWLKEEYTPTIPPKAINKSTGVLSDEAIKRIKEQARDLLLLKLINSSGNTQLLKDLRDAMSKPEAERAANALGFPTEGNGVLFLSREVVDALEERVEKLEQEAAKRGFDSYVQSLSHNALLA*
