C; model_eva_score=0.072, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 283: : : : : 
GPSILEEYIRMAKNKEFFDALEEIAESAKNDETLRNELAKVLDDILKTDPSDPEAFRKIVAEHQEFWDEHDPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEKSDTDTLVAILKNNPEECRAYIESKKPGLGNFSEGNVHGWLKEEYTPTIPPKAINKSTGVLSDEAIKRIKEQARDLLLLKLINSSGNTQLLKDLRDAMSKPEAERAANALGFPTEGNGVLFLSREVVDALEERVEKLEQEAAKRGFDSYVQSLSHNALLA*

C; model_eva_score=0.069, tm_score=0.6402, gdt_score=0.5080, maxsub=0.4506.
>P1;meta_super2.pdb1
structureX:meta_super2.pdb: 129: : 166: : : : : 
--------------------------------------------------------------------------------------------------------------------------------TLVAILKNNPEECRAYIESKKPGLGNFSEGNVHGWLKE---------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00231
 : : : : : : : : : 
GPSILEEYIRMAKNKEFFDALEEIAESAKNDETLRNELAKVLDDILKTDPSDPEAFRKIVAEHQEFWDEHDPSLMEFNEGRFFGKSRKQYLKSDDFLNSTDPTYNFQKLHQFAAEQRVKLGLEKSDTDTLVAILKNNPEECRAYIESKKPGLGNFSEGNVHGWLKEEYTPTIPPKAINKSTGVLSDEAIKRIKEQARDLLLLKLINSSGNTQLLKDLRDAMSKPEAERAANALGFPTEGNGVLFLSREVVDALEERVEKLEQEAAKRGFDSYVQSLSHNALLA*
