C; model_eva_score=0.773, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9812, gdt_score=0.9776, maxsub=0.9683.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9854, gdt_score=0.9847, maxsub=0.9790.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9812, gdt_score=0.9776, maxsub=0.9683.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9838, gdt_score=0.9837, maxsub=0.9772.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.774, tm_score=0.9699, gdt_score=0.9551, maxsub=0.9384.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9840, gdt_score=0.9827, maxsub=0.9765.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9826, gdt_score=0.9816, maxsub=0.9742.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9712, gdt_score=0.9408, maxsub=0.9352.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9776, gdt_score=0.9755, maxsub=0.9617.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9628, gdt_score=0.9235, maxsub=0.9132.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9606, gdt_score=0.9235, maxsub=0.9150.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9826, gdt_score=0.9827, maxsub=0.9746.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.769, tm_score=0.9593, gdt_score=0.9276, maxsub=0.9150.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.768, tm_score=0.9797, gdt_score=0.9776, maxsub=0.9601.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.765, tm_score=0.9780, gdt_score=0.9745, maxsub=0.9606.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.766, tm_score=0.9568, gdt_score=0.9163, maxsub=0.9044.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9636, gdt_score=0.9388, maxsub=0.9237.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.762, tm_score=0.9580, gdt_score=0.9398, maxsub=0.9149.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9655, gdt_score=0.9418, maxsub=0.9222.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C;total number of template models = 20
>P1;C00421
 : : : : : : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*
