C;cover size:167; local alignment length=167 (original info = 4div_U	253	17.58	1.3e+02	0)
>P1;4DIVA
structureX:4div_U:1:U:144:U: : : : 
HYRNLPFIPTSAMSYDGAWLEE---LIEGYQTL-AVEGRE-MYSLSFETQDM--QVGGVITNVKYPPRELTIKYKLEDRDP---RVLQEKFDTLKAFLIRQ----EDVPIIFNDDLE-----YTFYGRFKTADN-VAGD-----TNSIISSFTVLCSDPFKHGKIQSVK*

C;query_length:167 num_of_temps:1 cover_ratio:1 cover:167 not_cover:0
>P1;domain0
 : : : : : : : : : 
MSL--LERGLSKLTLNAWKDREGKIPAGSMSAMYNPETIQLDYQTRFDTEDTINTASQSNRYVISEPVGLNLTLLFDSQMPGNTTPIETQLAMLKSLCAVDAATGSPYFLRITWGKMRWENKGWFAGRARDLSVTYTLFDRDATPLRATVQLSLVADESFVIQQSLKTQ*
