C; model_eva_score=0.162, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_rapt8.pdb1
structureX:meta_rapt8.pdb: 1: : 105: : : : : 
SLALIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIRHIPRRIRQGLERILL*

C; model_eva_score=0.162, tm_score=0.8763, gdt_score=0.8905, maxsub=0.8326.
>P1;meta_rapt7.pdb1
structureX:meta_rapt7.pdb: 1: : 105: : : : : 
SLALIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIRHIPRRIRQGLERILL*

C; model_eva_score=0.162, tm_score=0.9170, gdt_score=0.9190, maxsub=0.8860.
>P1;meta_rapt5.pdb1
structureX:meta_rapt5.pdb: 1: : 105: : : : : 
SLALIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIRHIPRRIRQGLERILL*

C;total number of template models = 3
>P1;C00801
 : : : : : : : : : 
SLALIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIRHIPRRIRQGLERILL*
