C; model_eva_score=0.165, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_rapt10.pdb1
structureX:meta_rapt10.pdb: 1: : 105: : : : : 
SLALIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIRHIPRRIRQGLERILL*

C; model_eva_score=0.162, tm_score=0.8254, gdt_score=0.8238, maxsub=0.7965.
>P1;meta_rapt8.pdb1
structureX:meta_rapt8.pdb: 5: : 90: : : : : 
----IWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIR---------------*

C; model_eva_score=0.162, tm_score=0.8329, gdt_score=0.8333, maxsub=0.8080.
>P1;meta_rapt5.pdb1
structureX:meta_rapt5.pdb: 4: : 90: : : : : 
---LIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIR---------------*

C;total number of template models = 3
>P1;C00801
 : : : : : : : : : 
SLALIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVNLLNATAIAVAEGTDRVIEVLQAAYRAIRHIPRRIRQGLERILL*
