C; model_eva_score=0.911, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9981, gdt_score=1.0000, maxsub=0.9974.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9907, gdt_score=0.9881, maxsub=0.9877.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9945, gdt_score=0.9980, maxsub=0.9924.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9945, gdt_score=0.9980, maxsub=0.9924.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9980, gdt_score=1.0000, maxsub=0.9972.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9977, gdt_score=1.0000, maxsub=0.9968.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9905, gdt_score=0.9881, maxsub=0.9874.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9905, gdt_score=0.9881, maxsub=0.9874.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9937, gdt_score=0.9921, maxsub=0.9916.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9874, gdt_score=0.9881, maxsub=0.9834.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9939, gdt_score=0.9921, maxsub=0.9917.
>P1;meta_ss10.pdb1
structureX:meta_ss10.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9893, gdt_score=0.9881, maxsub=0.9859.
>P1;meta_ss8.pdb1
structureX:meta_ss8.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9946, gdt_score=0.9960, maxsub=0.9927.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9876, gdt_score=0.9881, maxsub=0.9835.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9896, gdt_score=0.9881, maxsub=0.9841.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9896, gdt_score=0.9881, maxsub=0.9841.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.908, tm_score=0.9853, gdt_score=0.9901, maxsub=0.9779.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.908, tm_score=0.9853, gdt_score=0.9901, maxsub=0.9779.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9917, gdt_score=0.9940, maxsub=0.9886.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00252
 : : : : : : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*
