C; model_eva_score=0.91, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9890, gdt_score=0.9881, maxsub=0.9856.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9907, gdt_score=0.9881, maxsub=0.9877.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9933, gdt_score=0.9960, maxsub=0.9912.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9933, gdt_score=0.9960, maxsub=0.9912.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9913, gdt_score=0.9881, maxsub=0.9885.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9895, gdt_score=0.9881, maxsub=0.9862.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9976, gdt_score=1.0000, maxsub=0.9967.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9976, gdt_score=1.0000, maxsub=0.9967.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9901, gdt_score=0.9921, maxsub=0.9861.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9873, gdt_score=0.9921, maxsub=0.9829.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9908, gdt_score=0.9921, maxsub=0.9878.
>P1;meta_ss10.pdb1
structureX:meta_ss10.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9969, gdt_score=0.9980, maxsub=0.9957.
>P1;meta_ss8.pdb1
structureX:meta_ss8.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9902, gdt_score=0.9881, maxsub=0.9871.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9878, gdt_score=0.9921, maxsub=0.9836.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9908, gdt_score=0.9921, maxsub=0.9850.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9908, gdt_score=0.9921, maxsub=0.9850.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.908, tm_score=0.9846, gdt_score=0.9881, maxsub=0.9793.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.908, tm_score=0.9846, gdt_score=0.9881, maxsub=0.9793.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9836, gdt_score=0.9821, maxsub=0.9785.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00252
 : : : : : : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*
