C; model_eva_score=0.911, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9890, gdt_score=0.9881, maxsub=0.9856.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9981, gdt_score=1.0000, maxsub=0.9974.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9941, gdt_score=0.9940, maxsub=0.9918.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9941, gdt_score=0.9940, maxsub=0.9918.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9965, gdt_score=0.9960, maxsub=0.9952.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9962, gdt_score=0.9960, maxsub=0.9948.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9898, gdt_score=0.9861, maxsub=0.9865.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.911, tm_score=0.9898, gdt_score=0.9861, maxsub=0.9865.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9925, gdt_score=0.9921, maxsub=0.9900.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9859, gdt_score=0.9841, maxsub=0.9816.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9949, gdt_score=0.9980, maxsub=0.9930.
>P1;meta_ss10.pdb1
structureX:meta_ss10.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9886, gdt_score=0.9861, maxsub=0.9849.
>P1;meta_ss8.pdb1
structureX:meta_ss8.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9952, gdt_score=0.9980, maxsub=0.9934.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9856, gdt_score=0.9841, maxsub=0.9809.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9879, gdt_score=0.9881, maxsub=0.9818.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.909, tm_score=0.9879, gdt_score=0.9881, maxsub=0.9818.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.908, tm_score=0.9840, gdt_score=0.9841, maxsub=0.9775.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.908, tm_score=0.9840, gdt_score=0.9841, maxsub=0.9775.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C; model_eva_score=0.91, tm_score=0.9934, gdt_score=0.9980, maxsub=0.9908.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 126: : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*

C;total number of template models = 20
>P1;C00252
 : : : : : : : : : 
SQVQLVESGGGSVQAGGSLRLSCVASGDIKYISYLGWFRQAPGKEREGVAALYTSTGRTYYADSVKGRFTVSLDNAKNTVYLQMNSLKPEDTALYYCAAAEWGSQSPLTQWFYRYWGQGTQVTVSA*
