C; model_eva_score=0.882, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.88, tm_score=0.9909, gdt_score=0.9940, maxsub=0.9870.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9963, gdt_score=1.0000, maxsub=0.9949.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9920, gdt_score=0.9940, maxsub=0.9894.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9920, gdt_score=0.9940, maxsub=0.9894.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9974, gdt_score=1.0000, maxsub=0.9963.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.88, tm_score=0.9971, gdt_score=1.0000, maxsub=0.9960.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9943, gdt_score=0.9980, maxsub=0.9923.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9861, gdt_score=0.9921, maxsub=0.9811.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9906, gdt_score=0.9960, maxsub=0.9846.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9938, gdt_score=0.9980, maxsub=0.9916.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9905, gdt_score=0.9960, maxsub=0.9855.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9967, gdt_score=1.0000, maxsub=0.9953.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.88, tm_score=0.9938, gdt_score=0.9960, maxsub=0.9915.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9945, gdt_score=0.9980, maxsub=0.9927.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9945, gdt_score=0.9980, maxsub=0.9927.
>P1;meta_blits5.pdb1
structureX:meta_blits5.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9945, gdt_score=0.9980, maxsub=0.9927.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9945, gdt_score=0.9980, maxsub=0.9927.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9942, gdt_score=0.9980, maxsub=0.9921.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9921, gdt_score=0.9980, maxsub=0.9893.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C;total number of template models = 20
>P1;C01281
 : : : : : : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*
