C; model_eva_score=0.88, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.882, tm_score=0.9909, gdt_score=0.9940, maxsub=0.9870.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9919, gdt_score=0.9960, maxsub=0.9879.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9931, gdt_score=0.9960, maxsub=0.9909.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9931, gdt_score=0.9960, maxsub=0.9909.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.881, tm_score=0.9925, gdt_score=0.9940, maxsub=0.9892.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.88, tm_score=0.9916, gdt_score=0.9960, maxsub=0.9873.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9920, gdt_score=0.9960, maxsub=0.9877.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9920, gdt_score=0.9980, maxsub=0.9892.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9934, gdt_score=0.9980, maxsub=0.9912.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9924, gdt_score=0.9960, maxsub=0.9877.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9969, gdt_score=1.0000, maxsub=0.9956.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9909, gdt_score=0.9960, maxsub=0.9864.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.88, tm_score=0.9917, gdt_score=0.9960, maxsub=0.9861.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9933, gdt_score=0.9960, maxsub=0.9885.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9933, gdt_score=0.9960, maxsub=0.9885.
>P1;meta_blits5.pdb1
structureX:meta_blits5.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9933, gdt_score=0.9960, maxsub=0.9885.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.879, tm_score=0.9933, gdt_score=0.9960, maxsub=0.9885.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9914, gdt_score=0.9960, maxsub=0.9865.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C; model_eva_score=0.878, tm_score=0.9891, gdt_score=0.9960, maxsub=0.9839.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 126: : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*

C;total number of template models = 20
>P1;C01281
 : : : : : : : : : 
MAILGLGTDIVEIARIEAVIARSGDRLARRVLSDNEWAIWKTHHQPVRFLAKRFAVKEAAAKAFGTGIRNGLAFNQFEVFNDELGKPRLRLWGEALKLAEKLGVANMHVTLADERHYACATVIIES*
