C;cover size:299; local alignment length=299 (original info = e3ad7A2	353	277.05	7.2e-40	287	13	100.00)
>P1;e3ad7A2
structureX:e3ad7A2: 2: : 318: : : : : 
-------------------DVLVVGAGPAGLAAAREASRSGARVMLLDERPEAGGTLRE--ASGEQI-D-GIDAAQWIDAVTEELAAAEET-TH-LQRTTVFGSYDANYILAAQRRTVHLDGPSGQGVSRERIWHIRAKQVVLATAAHERPIVFENNDRPGIMLAGSV-RSYLNRFGVRAGSKI-AVAT-----TNDSVYPLVSELAASGGVVAVIDARQNIS--AAA-----AQAVTDGVTVLTGSVVANTE-ADASGELSAVLVATLDEQRNLGEAQRFEADVLAVSGGFNPVVHLHSQRQG---K-----L-NWDTSIHAFVPADAVANQHLAGALTG-LLDTASALSTGAATGAAAASAAGFE---------------------------------*

C;cover size:304; local alignment length=304 (original info = e1y56A1	303	276.35	1.5e-40	267	19	100.00)
>P1;e1y56A1
structureX:e1y56A1: 2: : 276: : : : : 
-------------------DVAIIGGGPAGIGAALELQQYL-TVALIEERGWLGGDMWLKGIKQE--GF-NKDSRKVVEELVGKLNE-N-T-KIYLET-SALGVFDKGEYFLVP---------V---VRGDKLIEILAKRVVLATGAIDSTMLFENND------------------------MP-GVFR-----RDFALEVMNVWEVAPGRKVAVTGSKADE----VI-----QELERWGIDYVHIPNVKRVE-GN--EKVERVI---------DMNNHEYKVDALIFADGRRPDINPITQAGGKLRFRRGYYS-PVL-----DEYHRIKDGIYVAGSAVS-IKPHYANYLEGKLVGAYILKEFGYDAQPCI----------------------------*

C;cover size:315; local alignment length=315 (original info = e4ntcA1	325	316.49	4.5e-46	307	24	100.00)
>P1;e4ntcA1
structureX:e4ntcA1: 1: : 323: : : : : 
---MSIGKLLSNGALL--VDVLIIGAGPAGLSTATGLARQLHTAVVFDSG---VYRNAKTQHMHNVLGWDHRNPAELRAAGRADLTTRY-STIQ-FQN-STIEAIRQVE---TN---------QLFEARDNEGHSWYGRKVVLATGVRDIPLDIE---GYSECWANGIYHCLFCDGYEERGQETVGVLALGPIANPARALHLARMALRLSESVTIYTNGNEQLAKEIQQAAEESPVGASGLKFEAR-PIRRFEKGD-VAKTVIVH---------LGESESKTEGFLVYNPQTEVNGPFAKQLALN--MTEGGDILTTP-----PFYETSVPGVFAVGDCATPLKAVTPAVSMGSLAAGGLVAQLQAQ---------------------------------*

C;query_length:351 num_of_temps:1 cover_ratio:0.85 cover:299 not_cover:52
>P1;2017-11-11_00000052_1_72
 : : : : : : : : : 
GSHMILKREHFDEKQAQLYDVIIAGGGAGGLSAAVYLARYNLKVLVIEKG---RGRSFWMQDLWNYVPR-VVSGKELIEGGKEMALHYG-A-DW-LNG-FVEAVTDTGEEFQVR---------VKYRFKNSDYPVFRAKYLIAATGLMDVLPQLENMQNVYEYAGYNLHVCLICDGYEMTNRRA-ALIA-----GSEKAINTAFVLNWFTPYITVLTLGAYPVGDEMR-----AKLADHGYPLIEK-PIARFL-GK-DHVMDGIE---------FADGTSIKVDTGLISMGSIRHDGYLKNLDL---LTDGGDI-VTE-----YDCRTSHPRVFALGDLKKGLNQVSIAVADGTLAATAIWKEIRRASAPRKWTAPLQEAAARAEESARPEISLGAPRGG*
