C;cover size:88; local alignment length=88 (original info = d1onfa2	117	118.18	1.1e-19	88	8	99.61)
>P1;d1onfa2
structureX:d1onfa2: 21: : 117: : : : : 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------ESKKI-GIVG-----SGYIAVELINVIKRLGIDSYIFARGNRILRKFDESVINVLE-----NDMKKNNINIVTFA-DVVEIK-KVSDKNLSIHLSDGRIYEHFDHVIYCV---------------------------------------------------------------------------------------------------------*

C;cover size:304; local alignment length=304 (original info = e1y56A1	303	276.35	1.5e-40	267	19	100.00)
>P1;e1y56A1
structureX:e1y56A1: 2: : 276: : : : : 
-------------------DVAIIGGGPAGIGAALELQQYL-TVALIEERGWLGGDMWLKGIKQE--GF-NKDSRKVVEELVGKLNE-NT-KIYLETSALGVFDKGEYFLVPV---VRGDKLIEILAKRVVLATGAIDSTMLFENND------------------------MP-GVFR-----RDFALEVMNVWEVAPGRKVAVTGSKADE-----------VI-----QELERWGIDYV-HIPNVKRVE-GN-EKVERVIDMNNHEY-KVDALIFADGRRPDINPITQAGGKLRFRRGYYS-PVLDEYHRIKDGIYVAGSAVS-IKPHYANYLEGKLVGAYILKEFGYDAQPCI----------------------------*

C;cover size:315; local alignment length=315 (original info = e4ntcA1	325	316.49	4.5e-46	307	24	100.00)
>P1;e4ntcA1
structureX:e4ntcA1: 1: : 323: : : : : 
---MSIGKLLSNGALL--VDVLIIGAGPAGLSTATGLARQLHTAVVFDSG---VYRNAKTQHMHNVLGWDHRNPAELRAAGRADLTTRYSTIQ-FQNSTIEAIRQVE---TNQLFEARDNEGHSWYGRKVVLATGVRDIPLDIE---GYSECWANGIYHCLFCDGYEERGQETVGVLALGPIANPARALHLARMALRLSESVTIYTNGNEQLA-------KEIQQAAEESPVGASGLKFE-AR-PIRRFEKGDVAKTVIVHLGESESK-TEGFLVYNPQTEVNGPFAKQLALN--MTEGGDILTTPPFYETSVPGVFAVGDCATPLKAVTPAVSMGSLAAGGLVAQLQAQ---------------------------------*

C;query_length:351 num_of_temps:1 cover_ratio:0.25 cover:88 not_cover:263
>P1;2017-11-11_00000052_1_72
 : : : : : : : : : 
GSHMILKREHFDEKQAQLYDVIIAGGGAGGLSAAVYLARYNLKVLVIEKG---RGRSFWMQDLWNYVPR-VVSGKELIEGGKEMALHYGA-DW-LNGFVEAVTDTGEEFQVRVKYRFKNSDYPVFRAKYLIAATGLMDVLPQLENMQNVYEYAGYNLHVCLICDGYEMTNRRA-ALIA-----GSEKAINTAFVLNWFTPYITVLTLGAYPVG-------DEMR-----AKLADHGYPLI-EK-PIARFL-GKDHVMDGIEFADGTSI-KVDTGLISMGSIRHDGYLKNLDL---LTDGGDI-VTEYDCRTSHPRVFALGDLKKGLNQVSIAVADGTLAATAIWKEIRRASAPRKWTAPLQEAAARAEESARPEISLGAPRGG*
