C;cover size:304; local alignment length=304 (original info = e4ntdA1	318	481.43	1.5e-70	298	27	100.00)
>P1;e4ntdA1
structureX:e4ntdA1: 5: : 304: : : : : 
--------------HEGGIDVVVIGAGAGGLNAALVLARARRRVVLVDSGAPRNAPSAHMQGFLSRDGMAPSALLETGRAEVSGYGAEFIRGEVDDVEREGEDDAP--RFTVRLVGGVALSTRRVVVATGLRDELPDI---PGVRERWGKDLLHCPYCHGYEVSDQPLGVLGTSPGAVRHALLLRQWSDDVVLFRHGLEL-TDDDRRALSARQVPVIEGTVKRLVVEDDRLRGVELAEDSGVARSTVFVVPRMVPRDGLLTALGCERGADGWIATDRSGLTSVPGVWAVGNVVDPRALVVSSAGMGSAAAFALNHQLVDE---------------------------------*

C;query_length:351 num_of_temps:1 cover_ratio:0.87 cover:304 not_cover:47
>P1;2017-11-11_00000052_1_72
 : : : : : : : : : 
GSHMILKREHFDEKQAQLYDVIIAGGGAGGLSAAVYLARYNLKVLVIEKGRGRSFWMQDLWNYVPR-VVSGKELIEGGKEMALHYGADWLNGFVEAVTDTGEEFQVRVKYRFKNSDYPVFRAKYLIAATGLMDVLPQLENMQNVYEYAGYNLHVCLICDGYEMTNRRAALIAGSEKAINTAFVLNWFTPYITVLTLGAYPVGDEMRAKLADHGYPLIEKPIARFLGKDHVMDGIEFADGTSIKVDTGLISMGSIRHDGYLKNLDL-LTDGGDIVTEYDCRTSHPRVFALGDLKKGLNQVSIAVADGTLAATAIWKEIRRASAPRKWTAPLQEAAARAEESARPEISLGAPRGG*
