C;cover size:304; local alignment length=304 (original info = e4ntdA1	318	481.43	1.5e-70	298	27	100.00)
>P1;e4ntdA1
structureX:e4ntdA1: 5: : 304: : : : : 
--------------HEGGIDVVVIGAGAGGLNAALVLARARRRVVLVDSG---APRNAPSAHMQGFLSRDGMAPSALLETGRAEVSGYGA-EF-IRGEVDDVEREGEDDAP--RFTVRLVGGVALSTRRVVVATGLRDELPDI---PGVRERWGKDLLHCPYCHGYEVSDQPL-GVLG-----TSPGAVRHALLLRQWSDDVVLFRHGLEL-TDDDR-----RALSARQVPVIEG-TVKRLV-VEDDRLRGVELAEDSGVARSTVFVVPRMVPRDGLLTALGCE--RGADGWI-ATDRSGLTSVPGVWAVGNVVDPRALVVSSAGMGSAAAFALNHQLVDE---------------------------------*

C;cover size:304; local alignment length=304 (original info = e1y56A1	303	276.35	1.5e-40	267	19	100.00)
>P1;e1y56A1
structureX:e1y56A1: 2: : 276: : : : : 
-------------------DVAIIGGGPAGIGAALELQQYL-TVALIEERGWLGGDMWLKGIKQE--GF-NKDSRKVVEELVGKLNE-NT-KIYLETSALGVFDKGEYFLVPV---VRGDKLIEILAKRVVLATGAIDSTMLFENND------------------------MP-GVFR-----RDFALEVMNVWEVAPGRKVAVTGSKADE----VI-----QELERWGIDYVHIPNVKRVE-GN-EKVERVIDMNNHEYKVDALIFADGRRPDINPITQAGGKLRFRRGYYS-PVLDEYHRIKDGIYVAGSAVS-IKPHYANYLEGKLVGAYILKEFGYDAQPCI----------------------------*

C;cover size:315; local alignment length=315 (original info = e4ntcA1	325	316.49	4.5e-46	307	24	100.00)
>P1;e4ntcA1
structureX:e4ntcA1: 1: : 323: : : : : 
---MSIGKLLSNGALL--VDVLIIGAGPAGLSTATGLARQLHTAVVFDSG---VYRNAKTQHMHNVLGWDHRNPAELRAAGRADLTTRYSTIQ-FQNSTIEAIRQVE---TNQLFEARDNEGHSWYGRKVVLATGVRDIPLDIE---GYSECWANGIYHCLFCDGYEERGQETVGVLALGPIANPARALHLARMALRLSESVTIYTNGNEQLAKEIQQAAEESPVGASGLKFEAR-PIRRFEKGDVAKTVIVHLGESESKTEGFLVYNPQTEVNGPFAKQLALN--MTEGGDILTTPPFYETSVPGVFAVGDCATPLKAVTPAVSMGSLAAGGLVAQLQAQ---------------------------------*

C;query_length:351 num_of_temps:1 cover_ratio:0.87 cover:304 not_cover:47
>P1;2017-11-11_00000052_1_72
 : : : : : : : : : 
GSHMILKREHFDEKQAQLYDVIIAGGGAGGLSAAVYLARYNLKVLVIEKG---RGRSFWMQDLWNYVPR-VVSGKELIEGGKEMALHYGA-DW-LNGFVEAVTDTGEEFQVRVKYRFKNSDYPVFRAKYLIAATGLMDVLPQLENMQNVYEYAGYNLHVCLICDGYEMTNRRA-ALIA-----GSEKAINTAFVLNWFTPYITVLTLGAYPVGDEMR-----AKLADHGYPLIEK-PIARFL-GKDHVMDGIEFADGTSIKVDTGLISMGSIRHDGYLKNLDL---LTDGGDI-VTEYDCRTSHPRVFALGDLKKGLNQVSIAVADGTLAATAIWKEIRRASAPRKWTAPLQEAAARAEESARPEISLGAPRGG*
