C;cover size:153; local alignment length=153 (original info = d1lssa_	132	32.71	3.8e-06	123	15	88.49)
>P1;d1lssa_
structureX:d1lssa_: 1: : 132: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------MYI-IIAG-----IGRVGYTLAKSLSEKGHDIVLIDIDKDIC----------KKASAEIDALVING-DCTKI-----KTLE-----DAGIEDADMYIAVTGKEEVNLMSSLLAKSYG------IN-KT-IARISEIEY--KDVFERLGVDVVVS-P---------ELIAANYIEKLIER----------------------------------*

C;cover size:304; local alignment length=304 (original info = e1y56A1	303	276.35	1.5e-40	267	19	100.00)
>P1;e1y56A1
structureX:e1y56A1: 2: : 276: : : : : 
-------------------DVAIIGGGPAGIGAALELQQYL-TVALIEERGWLGGDMWLKGIKQE--GF-NKDSRKVVEELVGKLNE-NT-KIYLETSALGVFDKGEYFLVPV---VRGDKLIEILAKRVVLATGAIDSTMLFENND------------------------MP-GVFR-----RDFALEVMNVWEVAPGRKVAVTGSKADE----VI-----QELER-WGIDYVHIPNVKRVE-GN-EKVERVIDMNNHEYKVDALIFADGRRP-DI---NPITQAGGKLRFRRGYYS-P--VLDEYHRIKDGIYVAG-S-AVS-IKPHYANYLEGKLVGAYILKEFGYDAQPCI----------------------------*

C;cover size:315; local alignment length=315 (original info = e4ntcA1	325	316.49	4.5e-46	307	24	100.00)
>P1;e4ntcA1
structureX:e4ntcA1: 1: : 323: : : : : 
---MSIGKLLSNGALL--VDVLIIGAGPAGLSTATGLARQLHTAVVFDSG---VYRNAKTQHMHNVLGWDHRNPAELRAAGRADLTTRYSTIQ-FQNSTIEAIRQVE---TNQLFEARDNEGHSWYGRKVVLATGVRDIPLDIE---GYSECWANGIYHCLFCDGYEERGQETVGVLALGPIANPARALHLARMALRLSESVTIYTNGNEQLAKEIQQAAEESPVGA-SGLKFEAR-PIRRFEKGDVAKTVIVHLGESESKTEGFLVYNPQTEV-NG---PFAKQLALN--MTEGGDILT--TPPFYETSVPGVFAVG-D-CATPLKAVTPAVSMGSLAAGGLVAQLQAQ---------------------------------*

C;query_length:351 num_of_temps:1 cover_ratio:0.44 cover:153 not_cover:198
>P1;2017-11-11_00000052_1_72
 : : : : : : : : : 
GSHMILKREHFDEKQAQLYDVIIAGGGAGGLSAAVYLARYNLKVLVIEKG---RGRSFWMQDLWNYVPR-VVSGKELIEGGKEMALHYGA-DW-LNGFVEAVTDTGEEFQVRVKYRFKNSDYPVFRAKYLIAATGLMDVLPQLENMQNVYEYAGYNLHVCLICDGYEMTNRRA-ALIA-----GSEKAINTAFVLNWFTPYITVLTLGAYPVGDEMR-----AKLAD-HGYPLIEK-PIARFL-GKDHVMDGIEFADGTSIKVDTGLISMGSIR-HD---GYLKNLDL---LTDGGDI-V--TEYDCRTSHPRVFALG-D-LKKGLNQVSIAVADGTLAATAIWKEIRRASAPRKWTAPLQEAAARAEESARPEISLGAPRGG*
