C; model_eva_score=0.53, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.53, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.526, tm_score=0.9544, gdt_score=0.9144, maxsub=0.9026.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.526, tm_score=0.9544, gdt_score=0.9144, maxsub=0.9026.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.526, tm_score=0.9514, gdt_score=0.9120, maxsub=0.9087.
>P1;meta_hhbl2.pdb1
structureX:meta_hhbl2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.524, tm_score=0.9441, gdt_score=0.8970, maxsub=0.8853.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.524, tm_score=0.9499, gdt_score=0.8993, maxsub=0.8833.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.521, tm_score=0.9416, gdt_score=0.8912, maxsub=0.8708.
>P1;meta_muster1.pdb1
structureX:meta_muster1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9414, gdt_score=0.8924, maxsub=0.8696.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9367, gdt_score=0.8831, maxsub=0.8637.
>P1;meta_ff3.pdb1
structureX:meta_ff3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.518, tm_score=0.9448, gdt_score=0.8993, maxsub=0.8926.
>P1;meta_psiblast2.pdb1
structureX:meta_psiblast2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.518, tm_score=0.9448, gdt_score=0.8993, maxsub=0.8926.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9518, gdt_score=0.9132, maxsub=0.9043.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.519, tm_score=0.9535, gdt_score=0.9074, maxsub=0.9048.
>P1;meta_csiblast5.pdb1
structureX:meta_csiblast5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.519, tm_score=0.9535, gdt_score=0.9074, maxsub=0.9048.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9600, gdt_score=0.9190, maxsub=0.9043.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9646, gdt_score=0.9572, maxsub=0.9329.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9663, gdt_score=0.9606, maxsub=0.9374.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9480, gdt_score=0.9005, maxsub=0.8969.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9377, gdt_score=0.8993, maxsub=0.8823.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C;total number of template models = 20
>P1;C00861
 : : : : : : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*
