C; model_eva_score=0.526, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.53, tm_score=0.9544, gdt_score=0.9144, maxsub=0.9026.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.526, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.53, tm_score=0.9544, gdt_score=0.9144, maxsub=0.9026.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.526, tm_score=0.9770, gdt_score=0.9722, maxsub=0.9656.
>P1;meta_hhbl2.pdb1
structureX:meta_hhbl2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.524, tm_score=0.9846, gdt_score=0.9734, maxsub=0.9670.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.524, tm_score=0.9690, gdt_score=0.9537, maxsub=0.9416.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.521, tm_score=0.9730, gdt_score=0.9583, maxsub=0.9444.
>P1;meta_muster1.pdb1
structureX:meta_muster1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9593, gdt_score=0.9456, maxsub=0.9167.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9752, gdt_score=0.9618, maxsub=0.9433.
>P1;meta_ff3.pdb1
structureX:meta_ff3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.518, tm_score=0.9764, gdt_score=0.9664, maxsub=0.9560.
>P1;meta_psiblast2.pdb1
structureX:meta_psiblast2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.518, tm_score=0.9764, gdt_score=0.9664, maxsub=0.9560.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9705, gdt_score=0.9595, maxsub=0.9431.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.519, tm_score=0.9736, gdt_score=0.9595, maxsub=0.9440.
>P1;meta_csiblast5.pdb1
structureX:meta_csiblast5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.519, tm_score=0.9736, gdt_score=0.9595, maxsub=0.9440.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9675, gdt_score=0.9549, maxsub=0.9329.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9306, gdt_score=0.8623, maxsub=0.8540.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9266, gdt_score=0.8449, maxsub=0.8513.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9794, gdt_score=0.9699, maxsub=0.9559.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9676, gdt_score=0.9606, maxsub=0.9436.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C;total number of template models = 20
>P1;C00861
 : : : : : : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*
