C; model_eva_score=0.526, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhbl2.pdb1
structureX:meta_hhbl2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.53, tm_score=0.9514, gdt_score=0.9120, maxsub=0.9087.
>P1;meta_center1.pdb1
structureX:meta_center1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.526, tm_score=0.9770, gdt_score=0.9722, maxsub=0.9656.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.526, tm_score=0.9770, gdt_score=0.9722, maxsub=0.9656.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.53, tm_score=0.9514, gdt_score=0.9120, maxsub=0.9087.
>P1;meta_star1.pdb1
structureX:meta_star1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.524, tm_score=0.9701, gdt_score=0.9630, maxsub=0.9470.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.524, tm_score=0.9670, gdt_score=0.9537, maxsub=0.9447.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.521, tm_score=0.9607, gdt_score=0.9468, maxsub=0.9248.
>P1;meta_muster1.pdb1
structureX:meta_muster1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9545, gdt_score=0.9375, maxsub=0.9115.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9616, gdt_score=0.9502, maxsub=0.9249.
>P1;meta_ff3.pdb1
structureX:meta_ff3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.518, tm_score=0.9664, gdt_score=0.9618, maxsub=0.9479.
>P1;meta_psiblast2.pdb1
structureX:meta_psiblast2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.518, tm_score=0.9664, gdt_score=0.9618, maxsub=0.9479.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9641, gdt_score=0.9537, maxsub=0.9361.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.519, tm_score=0.9647, gdt_score=0.9537, maxsub=0.9381.
>P1;meta_csiblast5.pdb1
structureX:meta_csiblast5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.519, tm_score=0.9647, gdt_score=0.9537, maxsub=0.9381.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9642, gdt_score=0.9549, maxsub=0.9374.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9350, gdt_score=0.8692, maxsub=0.8634.
>P1;meta_compro1.pdb1
structureX:meta_compro1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.52, tm_score=0.9375, gdt_score=0.8727, maxsub=0.8697.
>P1;meta_msaprobs1.pdb1
structureX:meta_msaprobs1.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9644, gdt_score=0.9525, maxsub=0.9340.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C; model_eva_score=0.517, tm_score=0.9558, gdt_score=0.9479, maxsub=0.9315.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 216: : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*

C;total number of template models = 20
>P1;C00861
 : : : : : : : : : 
MNNMNVIIADDHPIVLFGIRKSLEQIEWVNVVGEFEDSTALINNLPKLDAHVLITDLSMPGDKYGDGITLIKYIKRHFPSLSIIVLTMNNNPAILSAVLDLDIEGIVLKQGAPTDLPKALAALQKGKKFTPESVSRLLEKISAGGYGDKRLSPKESEVLRLFAEGFLVTEIAKKLNRSIKTISSQKKSAMMKLGVENDIALLNYLSSVTLSPTDKE*
