C; model_eva_score=0.365, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 81: : : : : 
TQEGQRYQALKAHAEEKLQLANEEIAQVRSKAQAEALALQASLRKEQMRIQSLEKTVEQKTKENEELTRICDDLISKMEKI*

C; model_eva_score=0.366, tm_score=0.7453, gdt_score=0.7562, maxsub=0.7660.
>P1;meta_muster4.pdb1
structureX:meta_muster4.pdb: 1: : 81: : : : : 
TQEGQRYQALKAHAEEKLQLANEEIAQVRSKAQAEALALQASLRKEQMRIQSLEKTVEQKTKENEELTRICDDLISKMEKI*

C; model_eva_score=0.358, tm_score=0.7788, gdt_score=0.8025, maxsub=0.7698.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 81: : : : : 
TQEGQRYQALKAHAEEKLQLANEEIAQVRSKAQAEALALQASLRKEQMRIQSLEKTVEQKTKENEELTRICDDLISKMEKI*

C;total number of template models = 3
>P1;C00311
 : : : : : : : : : 
TQEGQRYQALKAHAEEKLQLANEEIAQVRSKAQAEALALQASLRKEQMRIQSLEKTVEQKTKENEELTRICDDLISKMEKI*
