C; model_eva_score=0.358, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 266: : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*

C; model_eva_score=0.35, tm_score=0.7440, gdt_score=0.6739, maxsub=0.6666.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 16: : 108: : : : : 
---------------ENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTI--------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00161
 : : : : : : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*
