C; model_eva_score=0.35, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_jackhmmer8.pdb1
structureX:meta_jackhmmer8.pdb: 1: : 266: : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*

C; model_eva_score=0.349, tm_score=0.8978, gdt_score=0.8402, maxsub=0.8029.
>P1;meta_jackhmmer4.pdb1
structureX:meta_jackhmmer4.pdb: 1: : 266: : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*

C; model_eva_score=0.352, tm_score=0.9162, gdt_score=0.8675, maxsub=0.8486.
>P1;meta_jackhmmer9.pdb1
structureX:meta_jackhmmer9.pdb: 1: : 266: : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*

C; model_eva_score=0.345, tm_score=0.9060, gdt_score=0.8336, maxsub=0.8078.
>P1;meta_jackhmmer5.pdb1
structureX:meta_jackhmmer5.pdb: 1: : 266: : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*

C; model_eva_score=0.348, tm_score=0.9143, gdt_score=0.8600, maxsub=0.8331.
>P1;meta_jackhmmer7.pdb1
structureX:meta_jackhmmer7.pdb: 1: : 266: : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*

C; model_eva_score=0.342, tm_score=0.9067, gdt_score=0.8506, maxsub=0.8244.
>P1;meta_jackhmmer6.pdb1
structureX:meta_jackhmmer6.pdb: 1: : 266: : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*

C;total number of template models = 6
>P1;C00161
 : : : : : : : : : 
MASMIDNRIVKASFRENPVEERKLFPQSSCLMPISVGQAIHEDEKFAAVIKLINASFKQCTILVDDSVQRHTIGIMNHATTEELYQLAVKEGDEWLKRNQRFYKQLTIPFEIMRWDDWYNSPNYINSHLRVQKEYDTNKAFQNAIHANIDDFLTRYLSRFSPADVDHERAFRLCLDYLIEECSVMCLWTEQKYDFEVYPSGRNKAMAATYEFLIKPHHPNYLRPVALRFKKYPAKITGDNLNLIQEQVHENGSMVGGFSRHHHHHH*
