C; model_eva_score=0.644, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9851, gdt_score=0.9826, maxsub=0.9686.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9851, gdt_score=0.9826, maxsub=0.9686.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.64, tm_score=0.9823, gdt_score=0.9860, maxsub=0.9660.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9956, gdt_score=0.9977, maxsub=0.9898.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.641, tm_score=0.9885, gdt_score=0.9884, maxsub=0.9793.
>P1;meta_hhsuite8.pdb1
structureX:meta_hhsuite8.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9788, gdt_score=0.9721, maxsub=0.9555.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9860, gdt_score=0.9767, maxsub=0.9677.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9860, gdt_score=0.9767, maxsub=0.9677.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9651, gdt_score=0.9302, maxsub=0.9277.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9745, gdt_score=0.9442, maxsub=0.9426.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.636, tm_score=0.9767, gdt_score=0.9628, maxsub=0.9498.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.635, tm_score=0.9826, gdt_score=0.9663, maxsub=0.9595.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9768, gdt_score=0.9616, maxsub=0.9482.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.632, tm_score=0.9656, gdt_score=0.9279, maxsub=0.9267.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9730, gdt_score=0.9384, maxsub=0.9389.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9712, gdt_score=0.9407, maxsub=0.9386.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9645, gdt_score=0.9279, maxsub=0.9240.
>P1;meta_compro4.pdb1
structureX:meta_compro4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9752, gdt_score=0.9558, maxsub=0.9469.
>P1;meta_rapt7.pdb1
structureX:meta_rapt7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.63, tm_score=0.9623, gdt_score=0.9093, maxsub=0.9180.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*
