C; model_eva_score=0.64, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9839, gdt_score=0.9860, maxsub=0.9681.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.644, tm_score=0.9823, gdt_score=0.9860, maxsub=0.9660.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9839, gdt_score=0.9860, maxsub=0.9681.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9796, gdt_score=0.9756, maxsub=0.9594.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.641, tm_score=0.9794, gdt_score=0.9535, maxsub=0.9553.
>P1;meta_hhsuite8.pdb1
structureX:meta_hhsuite8.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9864, gdt_score=0.9837, maxsub=0.9719.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9872, gdt_score=0.9884, maxsub=0.9767.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9872, gdt_score=0.9884, maxsub=0.9767.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9852, gdt_score=0.9779, maxsub=0.9659.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9832, gdt_score=0.9837, maxsub=0.9683.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.636, tm_score=0.9827, gdt_score=0.9779, maxsub=0.9665.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.635, tm_score=0.9836, gdt_score=0.9849, maxsub=0.9702.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9681, gdt_score=0.9372, maxsub=0.9359.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.632, tm_score=0.9850, gdt_score=0.9826, maxsub=0.9667.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9788, gdt_score=0.9733, maxsub=0.9590.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9865, gdt_score=0.9860, maxsub=0.9712.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9823, gdt_score=0.9791, maxsub=0.9628.
>P1;meta_compro4.pdb1
structureX:meta_compro4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9805, gdt_score=0.9733, maxsub=0.9575.
>P1;meta_rapt7.pdb1
structureX:meta_rapt7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.63, tm_score=0.9735, gdt_score=0.9570, maxsub=0.9478.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*
