C; model_eva_score=0.642, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.644, tm_score=0.9851, gdt_score=0.9826, maxsub=0.9686.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.64, tm_score=0.9839, gdt_score=0.9860, maxsub=0.9681.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9837, gdt_score=0.9826, maxsub=0.9654.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.641, tm_score=0.9727, gdt_score=0.9547, maxsub=0.9444.
>P1;meta_hhsuite8.pdb1
structureX:meta_hhsuite8.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9785, gdt_score=0.9744, maxsub=0.9574.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9869, gdt_score=0.9872, maxsub=0.9740.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9869, gdt_score=0.9872, maxsub=0.9740.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9753, gdt_score=0.9744, maxsub=0.9482.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9748, gdt_score=0.9698, maxsub=0.9466.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.636, tm_score=0.9821, gdt_score=0.9779, maxsub=0.9624.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.635, tm_score=0.9773, gdt_score=0.9744, maxsub=0.9521.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9767, gdt_score=0.9686, maxsub=0.9502.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.632, tm_score=0.9728, gdt_score=0.9651, maxsub=0.9438.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9750, gdt_score=0.9628, maxsub=0.9442.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9759, gdt_score=0.9744, maxsub=0.9507.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9720, gdt_score=0.9512, maxsub=0.9424.
>P1;meta_compro4.pdb1
structureX:meta_compro4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9767, gdt_score=0.9663, maxsub=0.9510.
>P1;meta_rapt7.pdb1
structureX:meta_rapt7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.63, tm_score=0.9674, gdt_score=0.9326, maxsub=0.9305.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*
