C; model_eva_score=0.642, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9837, gdt_score=0.9826, maxsub=0.9654.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.644, tm_score=0.9956, gdt_score=0.9977, maxsub=0.9898.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.64, tm_score=0.9796, gdt_score=0.9756, maxsub=0.9594.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.642, tm_score=0.9837, gdt_score=0.9826, maxsub=0.9654.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.641, tm_score=0.9875, gdt_score=0.9895, maxsub=0.9765.
>P1;meta_hhsuite8.pdb1
structureX:meta_hhsuite8.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9784, gdt_score=0.9698, maxsub=0.9545.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9848, gdt_score=0.9744, maxsub=0.9648.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9848, gdt_score=0.9744, maxsub=0.9648.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9631, gdt_score=0.9209, maxsub=0.9228.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9696, gdt_score=0.9256, maxsub=0.9323.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.636, tm_score=0.9795, gdt_score=0.9686, maxsub=0.9552.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.635, tm_score=0.9795, gdt_score=0.9628, maxsub=0.9536.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.638, tm_score=0.9788, gdt_score=0.9651, maxsub=0.9523.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.632, tm_score=0.9630, gdt_score=0.9163, maxsub=0.9206.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9700, gdt_score=0.9302, maxsub=0.9333.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.634, tm_score=0.9677, gdt_score=0.9302, maxsub=0.9308.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9621, gdt_score=0.9209, maxsub=0.9199.
>P1;meta_compro4.pdb1
structureX:meta_compro4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.631, tm_score=0.9692, gdt_score=0.9465, maxsub=0.9318.
>P1;meta_rapt7.pdb1
structureX:meta_rapt7.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C; model_eva_score=0.63, tm_score=0.9590, gdt_score=0.8965, maxsub=0.9110.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 215: : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*

C;total number of template models = 20
>P1;C00361
 : : : : : : : : : 
QSALTQEASVSGTVGQKVTLSCTGNTNNIGSYPVGWYQQISHGPPKTVMFGNSLPSGIPDRFSGSKSGTTASLTISGLQPEDEADYYCSTWDSSLSVQVIGGGTKVTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS*
