C; model_eva_score=0.185, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 209: : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*

C; model_eva_score=0.186, tm_score=0.6998, gdt_score=0.6376, maxsub=0.5946.
>P1;meta_super1.pdb1
structureX:meta_super1.pdb: 26: : 89: : : : : 
-------------------------EQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQ------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00751
 : : : : : : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*
