C; model_eva_score=0.178, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 209: : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*

C; model_eva_score=0.186, tm_score=0.7235, gdt_score=0.6268, maxsub=0.6108.
>P1;meta_super1.pdb1
structureX:meta_super1.pdb: 27: : 106: : : : : 
--------------------------QIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKH-------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00751
 : : : : : : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*
