C; model_eva_score=0.179, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 209: : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*

C; model_eva_score=0.162, tm_score=0.5813, gdt_score=0.5335, maxsub=0.4986.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 36: : 130: : : : : 
-----------------------------------GKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLP-------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00751
 : : : : : : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*
