C; model_eva_score=0.181, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 209: : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*

C; model_eva_score=0.174, tm_score=0.5634, gdt_score=0.4773, maxsub=0.4440.
>P1;meta_hhsuite10.pdb1
structureX:meta_hhsuite10.pdb: 120: : 167: : : : : 
-----------------------------------------------------------------------------------------------------------------------PFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRA------------------------------------------*

C;total number of template models = 2
>P1;C00751
 : : : : : : : : : 
GPDSMRQLPYHADKLSWDEKHRVNEEQIYCYCGKPGKFDHNMLQCCKCRNWFHTQCMQNFKKKLLRGDMFFVFCCTVCNNGIEFVRRMQIEWVDVLHIALYNLRKHQHQKYHHLLNDIWPFILEQRHQLPICEKWRTLPETALMERLKQTLKDYSDRFVCGREFKRAPAFYALRHSGPPHIPKVFLEPHEELSDELLEKRFKLMLMPEE*
