C; model_eva_score=0.81, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9635, gdt_score=0.9549, maxsub=0.9486.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9540, gdt_score=0.9530, maxsub=0.9326.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9515, gdt_score=0.9511, maxsub=0.9254.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.811, tm_score=0.9384, gdt_score=0.9342, maxsub=0.9104.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9780, gdt_score=0.9793, maxsub=0.9657.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9500, gdt_score=0.9436, maxsub=0.9305.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9453, gdt_score=0.9417, maxsub=0.9272.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9610, gdt_score=0.9474, maxsub=0.9396.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9473, gdt_score=0.9436, maxsub=0.9265.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.806, tm_score=0.9476, gdt_score=0.9474, maxsub=0.9291.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9320, gdt_score=0.9286, maxsub=0.9028.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9471, gdt_score=0.9474, maxsub=0.9243.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9289, gdt_score=0.9229, maxsub=0.8958.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.802, tm_score=0.9301, gdt_score=0.9286, maxsub=0.9012.
>P1;meta_msaprobs4.pdb1
structureX:meta_msaprobs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.803, tm_score=0.9269, gdt_score=0.9248, maxsub=0.8951.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9257, gdt_score=0.9117, maxsub=0.8898.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9190, gdt_score=0.9098, maxsub=0.8862.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.801, tm_score=0.9405, gdt_score=0.9305, maxsub=0.9146.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.799, tm_score=0.9601, gdt_score=0.9586, maxsub=0.9448.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C;total number of template models = 20
>P1;C00341
 : : : : : : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*
