C; model_eva_score=0.811, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9349, gdt_score=0.9361, maxsub=0.9042.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9317, gdt_score=0.9286, maxsub=0.9005.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9319, gdt_score=0.9267, maxsub=0.8980.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9384, gdt_score=0.9342, maxsub=0.9104.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9384, gdt_score=0.9398, maxsub=0.9104.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9336, gdt_score=0.9248, maxsub=0.9026.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9492, gdt_score=0.9436, maxsub=0.9266.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9382, gdt_score=0.9342, maxsub=0.9040.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9809, gdt_score=0.9831, maxsub=0.9717.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.806, tm_score=0.9379, gdt_score=0.9305, maxsub=0.9165.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9254, gdt_score=0.9135, maxsub=0.8916.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9273, gdt_score=0.9267, maxsub=0.8942.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9151, gdt_score=0.9135, maxsub=0.8691.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.802, tm_score=0.9285, gdt_score=0.9211, maxsub=0.8938.
>P1;meta_msaprobs4.pdb1
structureX:meta_msaprobs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.803, tm_score=0.9641, gdt_score=0.9605, maxsub=0.9490.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9481, gdt_score=0.9361, maxsub=0.9184.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9470, gdt_score=0.9417, maxsub=0.9257.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.801, tm_score=0.9263, gdt_score=0.9248, maxsub=0.8950.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.799, tm_score=0.9287, gdt_score=0.9192, maxsub=0.9010.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C;total number of template models = 20
>P1;C00341
 : : : : : : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*
