C; model_eva_score=0.808, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9635, gdt_score=0.9549, maxsub=0.9486.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9674, gdt_score=0.9699, maxsub=0.9559.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9505, gdt_score=0.9492, maxsub=0.9263.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.811, tm_score=0.9349, gdt_score=0.9361, maxsub=0.9042.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9684, gdt_score=0.9718, maxsub=0.9553.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9520, gdt_score=0.9305, maxsub=0.9322.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9510, gdt_score=0.9417, maxsub=0.9316.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9565, gdt_score=0.9549, maxsub=0.9405.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9336, gdt_score=0.9267, maxsub=0.9022.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.806, tm_score=0.9450, gdt_score=0.9417, maxsub=0.9231.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9372, gdt_score=0.9342, maxsub=0.9119.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9459, gdt_score=0.9398, maxsub=0.9295.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9371, gdt_score=0.9361, maxsub=0.9029.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.802, tm_score=0.9233, gdt_score=0.9229, maxsub=0.8843.
>P1;meta_msaprobs4.pdb1
structureX:meta_msaprobs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.803, tm_score=0.9158, gdt_score=0.9117, maxsub=0.8764.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9166, gdt_score=0.9098, maxsub=0.8731.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9259, gdt_score=0.9192, maxsub=0.8926.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.801, tm_score=0.9284, gdt_score=0.9192, maxsub=0.9028.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.799, tm_score=0.9672, gdt_score=0.9699, maxsub=0.9497.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C;total number of template models = 20
>P1;C00341
 : : : : : : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*
