C; model_eva_score=0.807, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9505, gdt_score=0.9492, maxsub=0.9263.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9650, gdt_score=0.9662, maxsub=0.9471.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9515, gdt_score=0.9511, maxsub=0.9254.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.811, tm_score=0.9319, gdt_score=0.9267, maxsub=0.8980.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9463, gdt_score=0.9492, maxsub=0.9186.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9631, gdt_score=0.9549, maxsub=0.9465.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9477, gdt_score=0.9398, maxsub=0.9198.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9507, gdt_score=0.9436, maxsub=0.9282.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9371, gdt_score=0.9267, maxsub=0.8995.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.806, tm_score=0.9368, gdt_score=0.9361, maxsub=0.9053.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9277, gdt_score=0.9248, maxsub=0.8845.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9336, gdt_score=0.9286, maxsub=0.9115.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9154, gdt_score=0.9079, maxsub=0.8725.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.802, tm_score=0.9284, gdt_score=0.9267, maxsub=0.9001.
>P1;meta_msaprobs4.pdb1
structureX:meta_msaprobs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.803, tm_score=0.9191, gdt_score=0.9079, maxsub=0.8772.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9472, gdt_score=0.9455, maxsub=0.9177.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9306, gdt_score=0.9211, maxsub=0.8880.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.801, tm_score=0.9306, gdt_score=0.9267, maxsub=0.8975.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.799, tm_score=0.9420, gdt_score=0.9398, maxsub=0.9105.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C;total number of template models = 20
>P1;C00341
 : : : : : : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*
