C; model_eva_score=0.81, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9674, gdt_score=0.9699, maxsub=0.9559.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.81, tm_score=0.9540, gdt_score=0.9530, maxsub=0.9326.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9650, gdt_score=0.9662, maxsub=0.9471.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.811, tm_score=0.9317, gdt_score=0.9286, maxsub=0.9005.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9557, gdt_score=0.9568, maxsub=0.9366.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.807, tm_score=0.9521, gdt_score=0.9342, maxsub=0.9322.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.808, tm_score=0.9417, gdt_score=0.9305, maxsub=0.9157.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9542, gdt_score=0.9568, maxsub=0.9353.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.809, tm_score=0.9310, gdt_score=0.9248, maxsub=0.8966.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.806, tm_score=0.9428, gdt_score=0.9361, maxsub=0.9209.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9268, gdt_score=0.9229, maxsub=0.8927.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.804, tm_score=0.9532, gdt_score=0.9474, maxsub=0.9341.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9267, gdt_score=0.9286, maxsub=0.8940.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.802, tm_score=0.9186, gdt_score=0.9079, maxsub=0.8840.
>P1;meta_msaprobs4.pdb1
structureX:meta_msaprobs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.803, tm_score=0.9133, gdt_score=0.9079, maxsub=0.8747.
>P1;meta_multicom4.pdb1
structureX:meta_multicom4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9224, gdt_score=0.9041, maxsub=0.8852.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.8, tm_score=0.9242, gdt_score=0.9117, maxsub=0.8922.
>P1;meta_center2.pdb1
structureX:meta_center2.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.801, tm_score=0.9421, gdt_score=0.9323, maxsub=0.9177.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C; model_eva_score=0.799, tm_score=0.9390, gdt_score=0.9380, maxsub=0.9104.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 133: : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*

C;total number of template models = 20
>P1;C00341
 : : : : : : : : : 
GSMAETKAKAEDLKMQGNKAMANKDYELAINKYTEAIKVLPTNAIYYANRAAAHSSLKEYDQAVKDAESAISIDPSYFRGYSRLGFAKYAQGKPEEALEAYKKVLDIEGDNATEAMKRDYESAKKKVEQSLNL*
