C; model_eva_score=0.307, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 664: : : : : 
MGSSHHHHHHSSGLVPRGSHMNIIEIKQLNRYFGEGENRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFSKDQLMEAFRMSVSAIVAHKMRSLLTMLGIIIGITSVVSVVALGNGSQQKILENIRGIGTNTMTIFNGNGFGDRRSRHIQNLKISDANTLSKQSYIQSVTPNTSSSGILVVGNKSFTSANLYGIGEQYFDVEGLKLKQGRLLTEDDVDQSNQVVVLDESAKKAIFANENPLGKTVIFNKRPFRVIGVVSDQQLGGFPGNSLNLYSPYSTVLNKITGGSRIGSITVKISDDVNSTVAEKSLTELLKSLHGKKDFFIMNSDTIKQTIENTTGTMKLLISSIAFISLIVGGIGVMNIMLVSVTERTKEIGVRMAIGARQINILQQFLIEAVLICLIGGVAGILLSVLIGVLFNSFITDFSMDFSTASIVTAVLFSTLIGVLFGYMPAKKAAELNPITALAQE*

C; model_eva_score=0.307, tm_score=0.4094, gdt_score=0.4002, maxsub=0.3959.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 3: : 269: : : : : 
--SSHHHHHHSSGLVPRGSHMNIIEIKQLNRYFGEGENRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFSKDQ-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00201
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMNIIEIKQLNRYFGEGENRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFSKDQLMEAFRMSVSAIVAHKMRSLLTMLGIIIGITSVVSVVALGNGSQQKILENIRGIGTNTMTIFNGNGFGDRRSRHIQNLKISDANTLSKQSYIQSVTPNTSSSGILVVGNKSFTSANLYGIGEQYFDVEGLKLKQGRLLTEDDVDQSNQVVVLDESAKKAIFANENPLGKTVIFNKRPFRVIGVVSDQQLGGFPGNSLNLYSPYSTVLNKITGGSRIGSITVKISDDVNSTVAEKSLTELLKSLHGKKDFFIMNSDTIKQTIENTTGTMKLLISSIAFISLIVGGIGVMNIMLVSVTERTKEIGVRMAIGARQINILQQFLIEAVLICLIGGVAGILLSVLIGVLFNSFITDFSMDFSTASIVTAVLFSTLIGVLFGYMPAKKAAELNPITALAQE*
