C; model_eva_score=0.307, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 664: : : : : 
MGSSHHHHHHSSGLVPRGSHMNIIEIKQLNRYFGEGENRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFSKDQLMEAFRMSVSAIVAHKMRSLLTMLGIIIGITSVVSVVALGNGSQQKILENIRGIGTNTMTIFNGNGFGDRRSRHIQNLKISDANTLSKQSYIQSVTPNTSSSGILVVGNKSFTSANLYGIGEQYFDVEGLKLKQGRLLTEDDVDQSNQVVVLDESAKKAIFANENPLGKTVIFNKRPFRVIGVVSDQQLGGFPGNSLNLYSPYSTVLNKITGGSRIGSITVKISDDVNSTVAEKSLTELLKSLHGKKDFFIMNSDTIKQTIENTTGTMKLLISSIAFISLIVGGIGVMNIMLVSVTERTKEIGVRMAIGARQINILQQFLIEAVLICLIGGVAGILLSVLIGVLFNSFITDFSMDFSTASIVTAVLFSTLIGVLFGYMPAKKAAELNPITALAQE*

C; model_eva_score=0.307, tm_score=0.4725, gdt_score=0.4206, maxsub=0.3844.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 320: : 457: : : : : 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------IRGIGTNTMTIFNGNGFGDRRSRHIQNLKISDANTLSKQSYIQSVTPNTSSSGILVVGNKSFTSANLYGIGEQYFDVEGLKLKQGRLLTEDDVDQSNQVVVLDESAKKAIFANENPLGKTVIFNKRPFRVIGVVSDQQ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C; model_eva_score=0.307, tm_score=0.4725, gdt_score=0.4206, maxsub=0.3844.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 465: : 542: : : : : 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SLNLYSPYSTVLNKITGGSRIGSITVKISDDVNSTVAEKSLTELLKSLHGKKDFFIMNSDTIKQTIENTTGTMKLLIS--------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 3
>P1;C00201
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMNIIEIKQLNRYFGEGENRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFSKDQLMEAFRMSVSAIVAHKMRSLLTMLGIIIGITSVVSVVALGNGSQQKILENIRGIGTNTMTIFNGNGFGDRRSRHIQNLKISDANTLSKQSYIQSVTPNTSSSGILVVGNKSFTSANLYGIGEQYFDVEGLKLKQGRLLTEDDVDQSNQVVVLDESAKKAIFANENPLGKTVIFNKRPFRVIGVVSDQQLGGFPGNSLNLYSPYSTVLNKITGGSRIGSITVKISDDVNSTVAEKSLTELLKSLHGKKDFFIMNSDTIKQTIENTTGTMKLLISSIAFISLIVGGIGVMNIMLVSVTERTKEIGVRMAIGARQINILQQFLIEAVLICLIGGVAGILLSVLIGVLFNSFITDFSMDFSTASIVTAVLFSTLIGVLFGYMPAKKAAELNPITALAQE*
