C; model_eva_score=0.307, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 664: : : : : 
MGSSHHHHHHSSGLVPRGSHMNIIEIKQLNRYFGEGENRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFSKDQLMEAFRMSVSAIVAHKMRSLLTMLGIIIGITSVVSVVALGNGSQQKILENIRGIGTNTMTIFNGNGFGDRRSRHIQNLKISDANTLSKQSYIQSVTPNTSSSGILVVGNKSFTSANLYGIGEQYFDVEGLKLKQGRLLTEDDVDQSNQVVVLDESAKKAIFANENPLGKTVIFNKRPFRVIGVVSDQQLGGFPGNSLNLYSPYSTVLNKITGGSRIGSITVKISDDVNSTVAEKSLTELLKSLHGKKDFFIMNSDTIKQTIENTTGTMKLLISSIAFISLIVGGIGVMNIMLVSVTERTKEIGVRMAIGARQINILQQFLIEAVLICLIGGVAGILLSVLIGVLFNSFITDFSMDFSTASIVTAVLFSTLIGVLFGYMPAKKAAELNPITALAQE*

C; model_eva_score=0.295, tm_score=0.4148, gdt_score=0.3806, maxsub=0.3765.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 38: : 266: : : : : 
-------------------------------------NRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFS--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00201
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMNIIEIKQLNRYFGEGENRVHVLKDISLSIERGDFVAIMGQSGSGKSTLMNIIGCLDTATGGSSKIDGKETIELTNDQLSDLRSQKFGFIFQRYNLLSSLTAAENVALPAIYAGMPQSQRLERAKQLLEKLGLGDKWQNKPNQLSGGQQQRVSIARALMNGGEIILADQPTGALDSHSGENVMEILRQLHEEGHTIIMVTHDKHIAASANRIIEIKDGEIISDTQKRQVKSAVKNPSVFKGRFGFSKDQLMEAFRMSVSAIVAHKMRSLLTMLGIIIGITSVVSVVALGNGSQQKILENIRGIGTNTMTIFNGNGFGDRRSRHIQNLKISDANTLSKQSYIQSVTPNTSSSGILVVGNKSFTSANLYGIGEQYFDVEGLKLKQGRLLTEDDVDQSNQVVVLDESAKKAIFANENPLGKTVIFNKRPFRVIGVVSDQQLGGFPGNSLNLYSPYSTVLNKITGGSRIGSITVKISDDVNSTVAEKSLTELLKSLHGKKDFFIMNSDTIKQTIENTTGTMKLLISSIAFISLIVGGIGVMNIMLVSVTERTKEIGVRMAIGARQINILQQFLIEAVLICLIGGVAGILLSVLIGVLFNSFITDFSMDFSTASIVTAVLFSTLIGVLFGYMPAKKAAELNPITALAQE*
