C; model_eva_score=0.772, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9849, gdt_score=0.9827, maxsub=0.9730.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9864, gdt_score=0.9857, maxsub=0.9773.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.773, tm_score=0.9838, gdt_score=0.9837, maxsub=0.9772.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9849, gdt_score=0.9827, maxsub=0.9730.
>P1;meta_star0.pdb1
structureX:meta_star0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.774, tm_score=0.9710, gdt_score=0.9531, maxsub=0.9380.
>P1;meta_csblast2.pdb1
structureX:meta_csblast2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9855, gdt_score=0.9847, maxsub=0.9760.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9945, gdt_score=0.9939, maxsub=0.9872.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.772, tm_score=0.9619, gdt_score=0.9327, maxsub=0.9265.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9848, gdt_score=0.9796, maxsub=0.9651.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9490, gdt_score=0.9092, maxsub=0.8986.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.77, tm_score=0.9578, gdt_score=0.9173, maxsub=0.9120.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.771, tm_score=0.9865, gdt_score=0.9867, maxsub=0.9719.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.769, tm_score=0.9651, gdt_score=0.9306, maxsub=0.9170.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.768, tm_score=0.9772, gdt_score=0.9724, maxsub=0.9597.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.765, tm_score=0.9859, gdt_score=0.9806, maxsub=0.9675.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.766, tm_score=0.9512, gdt_score=0.9071, maxsub=0.8999.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9646, gdt_score=0.9398, maxsub=0.9202.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.762, tm_score=0.9620, gdt_score=0.9398, maxsub=0.9186.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C; model_eva_score=0.767, tm_score=0.9630, gdt_score=0.9367, maxsub=0.9226.
>P1;meta_csblast1.pdb1
structureX:meta_csblast1.pdb: 1: : 245: : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*

C;total number of template models = 20
>P1;C00421
 : : : : : : : : : 
GPAVRTIRIYQPGEYQPGQLLELSPEAGQHVGVVLRMEQGEQLTLFNGDNKEFTASIERVKKKQVFVRIASVLEVNRESPLKIHLAQAISKGERMEMVMQKSAELGVACITPLITERCQVKIDKEKMAKKMHQWLNIIIGACEQCGRNQIPELRQPVYLDQFVREAKEHLKLILHPAFSKTWRDYPVQPPDVALIIGPEGGFSDEEIRLTSGHGFLPLSLGPRVLRTETAAITALSVLQAAGGDL*
