C; model_eva_score=0.859, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.857, tm_score=0.9871, gdt_score=0.9808, maxsub=0.9726.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9964, gdt_score=0.9964, maxsub=0.9921.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9878, gdt_score=0.9856, maxsub=0.9772.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9867, gdt_score=0.9796, maxsub=0.9715.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9863, gdt_score=0.9808, maxsub=0.9704.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9925, gdt_score=0.9892, maxsub=0.9850.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.855, tm_score=0.9867, gdt_score=0.9856, maxsub=0.9748.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9850, gdt_score=0.9832, maxsub=0.9719.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9837, gdt_score=0.9760, maxsub=0.9646.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9758, gdt_score=0.9724, maxsub=0.9568.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9836, gdt_score=0.9724, maxsub=0.9645.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9802, gdt_score=0.9736, maxsub=0.9601.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9837, gdt_score=0.9748, maxsub=0.9648.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9838, gdt_score=0.9796, maxsub=0.9676.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9827, gdt_score=0.9808, maxsub=0.9678.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9680, gdt_score=0.9603, maxsub=0.9473.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.851, tm_score=0.9819, gdt_score=0.9700, maxsub=0.9608.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9877, gdt_score=0.9820, maxsub=0.9768.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9828, gdt_score=0.9832, maxsub=0.9652.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C;total number of template models = 20
>P1;C00021
 : : : : : : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*
