C; model_eva_score=0.856, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.857, tm_score=0.9870, gdt_score=0.9820, maxsub=0.9720.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.859, tm_score=0.9964, gdt_score=0.9964, maxsub=0.9921.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9871, gdt_score=0.9844, maxsub=0.9754.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9863, gdt_score=0.9796, maxsub=0.9706.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9872, gdt_score=0.9820, maxsub=0.9721.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9911, gdt_score=0.9880, maxsub=0.9782.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.855, tm_score=0.9847, gdt_score=0.9820, maxsub=0.9704.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9837, gdt_score=0.9820, maxsub=0.9690.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9849, gdt_score=0.9784, maxsub=0.9670.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9740, gdt_score=0.9651, maxsub=0.9528.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9842, gdt_score=0.9772, maxsub=0.9654.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9787, gdt_score=0.9724, maxsub=0.9569.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9839, gdt_score=0.9772, maxsub=0.9652.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9823, gdt_score=0.9784, maxsub=0.9644.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9815, gdt_score=0.9772, maxsub=0.9645.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9673, gdt_score=0.9567, maxsub=0.9461.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.851, tm_score=0.9833, gdt_score=0.9724, maxsub=0.9637.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9861, gdt_score=0.9820, maxsub=0.9693.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9812, gdt_score=0.9760, maxsub=0.9616.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C;total number of template models = 20
>P1;C00021
 : : : : : : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*
