C; model_eva_score=0.856, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.857, tm_score=0.9986, gdt_score=0.9988, maxsub=0.9969.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9863, gdt_score=0.9796, maxsub=0.9706.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9815, gdt_score=0.9736, maxsub=0.9609.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.859, tm_score=0.9867, gdt_score=0.9796, maxsub=0.9715.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9985, gdt_score=0.9988, maxsub=0.9967.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9828, gdt_score=0.9736, maxsub=0.9639.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.855, tm_score=0.9788, gdt_score=0.9675, maxsub=0.9577.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9782, gdt_score=0.9651, maxsub=0.9541.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9953, gdt_score=0.9952, maxsub=0.9894.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9714, gdt_score=0.9579, maxsub=0.9434.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9970, gdt_score=0.9964, maxsub=0.9931.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9874, gdt_score=0.9880, maxsub=0.9741.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9975, gdt_score=0.9976, maxsub=0.9944.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9750, gdt_score=0.9591, maxsub=0.9465.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9737, gdt_score=0.9555, maxsub=0.9457.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9598, gdt_score=0.9447, maxsub=0.9325.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.851, tm_score=0.9958, gdt_score=0.9964, maxsub=0.9906.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9782, gdt_score=0.9651, maxsub=0.9566.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9742, gdt_score=0.9567, maxsub=0.9450.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C;total number of template models = 20
>P1;C00021
 : : : : : : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*
