C; model_eva_score=0.857, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.859, tm_score=0.9871, gdt_score=0.9808, maxsub=0.9726.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9870, gdt_score=0.9820, maxsub=0.9720.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9830, gdt_score=0.9772, maxsub=0.9638.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9986, gdt_score=0.9988, maxsub=0.9969.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9988, gdt_score=1.0000, maxsub=0.9971.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9841, gdt_score=0.9772, maxsub=0.9667.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.855, tm_score=0.9807, gdt_score=0.9724, maxsub=0.9616.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9796, gdt_score=0.9700, maxsub=0.9569.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9952, gdt_score=0.9988, maxsub=0.9891.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9742, gdt_score=0.9663, maxsub=0.9495.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9972, gdt_score=0.9988, maxsub=0.9935.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9877, gdt_score=0.9880, maxsub=0.9757.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9981, gdt_score=1.0000, maxsub=0.9957.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9765, gdt_score=0.9615, maxsub=0.9496.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9753, gdt_score=0.9603, maxsub=0.9487.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9621, gdt_score=0.9519, maxsub=0.9374.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.851, tm_score=0.9959, gdt_score=0.9988, maxsub=0.9905.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9790, gdt_score=0.9688, maxsub=0.9584.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9756, gdt_score=0.9615, maxsub=0.9477.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C;total number of template models = 20
>P1;C00021
 : : : : : : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*
