C; model_eva_score=0.854, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.857, tm_score=0.9830, gdt_score=0.9772, maxsub=0.9638.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9871, gdt_score=0.9844, maxsub=0.9754.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.859, tm_score=0.9878, gdt_score=0.9856, maxsub=0.9772.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9815, gdt_score=0.9736, maxsub=0.9609.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.856, tm_score=0.9819, gdt_score=0.9724, maxsub=0.9612.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9815, gdt_score=0.9712, maxsub=0.9653.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.855, tm_score=0.9918, gdt_score=0.9928, maxsub=0.9804.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.854, tm_score=0.9957, gdt_score=0.9964, maxsub=0.9903.
>P1;meta_ss2.pdb1
structureX:meta_ss2.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9798, gdt_score=0.9688, maxsub=0.9566.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9793, gdt_score=0.9748, maxsub=0.9602.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.852, tm_score=0.9788, gdt_score=0.9651, maxsub=0.9550.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9777, gdt_score=0.9712, maxsub=0.9582.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.853, tm_score=0.9791, gdt_score=0.9675, maxsub=0.9553.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9905, gdt_score=0.9916, maxsub=0.9797.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.85, tm_score=0.9929, gdt_score=0.9928, maxsub=0.9850.
>P1;meta_ss3.pdb1
structureX:meta_ss3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9680, gdt_score=0.9591, maxsub=0.9460.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.851, tm_score=0.9781, gdt_score=0.9651, maxsub=0.9538.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.848, tm_score=0.9761, gdt_score=0.9639, maxsub=0.9563.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C; model_eva_score=0.849, tm_score=0.9934, gdt_score=0.9952, maxsub=0.9846.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 208: : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*

C;total number of template models = 20
>P1;C00021
 : : : : : : : : : 
MAIPKIASYQVLPLESFPTNKVDWVIDPKKSVVLVHDLQAYFLNFFDKTLSPVPELLRNVNKVTESARSAGIPVVYTAQPANQDPNERALLTDFWGVGLTQDTEIVPEVSPQPEDIQYTKWRYSAFKKTPLLEWMKEEQRDQLVIVGVYGHIGILSTALDAFMLDIKPFVIGDAIADFSKEDHMNTLKYVASRSGSVKSVDEFIDSVT*
