C;cover size:222; local alignment length=222 (original info = e4eirA1	222	546.32	2.1e-84	212	33	100.00)
>P1;e4eirA1
structureX:e4eirA1: 1: : 221: : : : : 
-TIFSSLEVNGVNQGLGE--GVRVPTYNGPIEDVTSASIACNGSPNTVASTSKVITVQAGTNVTAIWRYMLSTTGDSPADVMDSSHKGPTIAYLKKVDNAATASGVGNGWFKIQQDGMDS-SGVWGTERVINGKGRHSIKIPECIAPGQYLLRAEMIALHAASN------YPGAQFYMECAQLNVVGGTGAK-TPSTVSFPGAYSGSDPGVKISIYWPPVTAYTVPGPSVFT-----------------------------*

C;cover size:230; local alignment length=230 (original info = e5acfA1	234	568.63	2.7e-87	225	46	100.00)
>P1;e5acfA1
structureX:e5acfA1: 1: : 226: : : : : 
-TLVWGVWVNGVDQGDGRNIYIRSPPNNNPVKNLTSPDMTCNVD-N--RVVPKSVPVNAGDTLTFEWYHNTRDD-----DIIASSHHGPIAVYIAPAAS----NGQGNVWVKLFEDAYNVTNSTWAVDRLITAHGQHSVVVPH-VAPGDYLFRAEIIALHEADSLYSQNPIRGAQFYISCAQITINSSDDSTPLPAGVPFPGAYTDSTPGIQFNIYTTPATSYVAPPPSVWSGALGGSIA---------------------*

C;query_length:252 num_of_temps:1 cover_ratio:0.88 cover:222 not_cover:30
>P1;2017-10-28_00000052_1_72
 : : : : : : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGG--EPVPQFVSASAGDKLTFEWYRVKRGD-----DIIDPSHSGPITTWIAAFTSP-TMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTD-FDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*
