C;cover size:230; local alignment length=230 (original info = e5acfA1	234	568.63	2.7e-87	225	46	100.00)
>P1;e5acfA1
structureX:e5acfA1: 1: : 226: : : : : 
-TLVWGVWVNGVDQGDGRN-------IYIRSPPNNNPVKNLTSPDMTCNVD-N--RVVPKSVPVNAGDTLTFEWYHNTRD-------D-----DIIASSHHGPIAVYIAPAAS------NGQGNVWVKLFEDAYNVT----------NSTWAVDRLITAHGQHSVVVPH-VAPGDYLFRAEIIALHEADSLYSQNPIRGAQFYISCAQITINSSDDSTPLP-AGVPFPGAYTDSTPGIQFNIYT--TP------ATSYVAPPPSVWSGALGGSIA---------------------*

C;cover size:223; local alignment length=223 (original info = e4d7uA1	227	552.50	4e-85	211	37	100.00)
>P1;e4d7uA1
structureX:e4d7uA1: 1: : 226: : : : : 
HTIFQKVSVNGADQGQLK---------GIRAPANNNPVTDVMSSDIICNAV-T--MKDSNVLTVPAGAKVGHFWGHEIGGAAGPNDAD-----NPIAASHKGPIMVYLAKVDNAAT--TGTSGLKWFKVAEAGLS------------NGKWAVDDLIANNGWSYFDMPTCIAPGQYLMRAELIALHNAGS------QAGAQFYIGCAQINVTGGGSAS-PS-NTVSFPGAYSASDPGILINIYG--GSGKTDNGGKPYQIPGPALFT-----------------------------*

C;cover size:224; local alignment length=224 (original info = e5ufvA1	227	515.97	2e-79	205	30	100.00)
>P1;e5ufvA1
structureX:e5ufvA1: 1: : 227: : : : : 
-GAVTSYNIAGKDYPGYSGFAPTGQDVIQWQWPDYNPVLSASDPKLRCNG--G--TGAALYAEAAPGDTITATWAQWT--------------------HSQGPILVWMYKCPGD-FSSCDGSGAGWFKIDEAGFHGDGTTVFLDTETPSGWDIAKLVGGNKSWSSKIPDGLAPGNYLVRHELIALHQA---------NNPQFYPECAQIKVTGSGTAEPAASYKAAIPGYCQQSDPNISFNINDHSL-------PQEYKIPGPPVFKGT---------------------------*

C;cover size:222; local alignment length=222 (original info = e4eirA1	222	546.32	2.1e-84	212	33	100.00)
>P1;e4eirA1
structureX:e4eirA1: 1: : 221: : : : : 
-TIFSSLEVNGVNQGLGE---------GVRVPTYNGPIEDVTSASIACNGSPNTVASTSKVITVQAGTNVTAIWRYMLST-------TGDSPADVMDSSHKGPTIAYLKKVDNAAT--ASGVGNGWFKIQQDGMDS-----------SGVWGTERVINGKGRHSIKIPECIAPGQYLLRAEMIALHAASN------YPGAQFYMECAQLNVVGGTGAK-TP-STVSFPGAYSGSDPGVKISIYW--PP------VTAYTVPGPSVFT-----------------------------*

C;query_length:252 num_of_temps:1 cover_ratio:0.91 cover:230 not_cover:22
>P1;2017-10-28_00000052_1_72
 : : : : : : : : : 
HTRMFSVWVNGVDQGDGQN-------VYIRTPPNTDPIKDLASPALACNVKGG--EPVPQFVSASAGDKLTFEWYRVKRG-------D-----DIIDPSHSGPITTWIAAFTSP-T--MDGTGPVWSKIHEEGYDAS----------TKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPD-QAFDFNKGYKYSDPGIAFDMYT--D-------FDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*
