C;cover size:223; local alignment length=223 (original info = e4d7uA1	227	552.50	4e-85	211	37	100.00)
>P1;e4d7uA1
structureX:e4d7uA1: 1: : 226: : : : : 
HTIFQKVSVNGADQGQLK--GIRAPANNNPVTDVMSSDIICNAV-TMKDSNVLTVPAGAKVGHFWGHEIGGAAGPNDADNPIAASHKGPIMVYLAKVDNAATTGTSGLKWFKVAEAGLS--NGKWAVDDLIANNGWSYFDMPTCIAPGQYLMRAELIALHNAGS------QAGAQFYIGCAQINVTGGGSAS-PSNTVSFPGAYSASDPGILINIYGGSGKTDNGGKPYQIPGPALFT-----------------------------*

C;cover size:230; local alignment length=230 (original info = e5acfA1	234	568.63	2.7e-87	225	46	100.00)
>P1;e5acfA1
structureX:e5acfA1: 1: : 226: : : : : 
-TLVWGVWVNGVDQGDGRNIYIRSPPNNNPVKNLTSPDMTCNVD-NRVVPKSVPVNAGDTLTFEWYHNTRD-------DDIIASSHHGPIAVYIAPAAS----NGQGNVWVKLFEDAYNVTNSTWAVDRLITAHGQHSVVVPH-VAPGDYLFRAEIIALHEADSLYSQNPIRGAQFYISCAQITINSSDDSTPLPAGVPFPGAYTDSTPGIQFNIYTTP------ATSYVAPPPSVWSGALGGSIA---------------------*

C;query_length:252 num_of_temps:1 cover_ratio:0.88 cover:223 not_cover:29
>P1;2017-10-28_00000052_1_72
 : : : : : : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRG-------DDIIDPSHSGPITTWIAAFTSP-TMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTD-------FDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*
