C;cover size:224; local alignment length=224 (original info = e5fohA1	218	548.59	5.8e-85	212	32	100.00)
>P1;e5fohA1
structureX:e5fohA1: 1: : 217: : : : : 
HTIFVQLEADGTTYPVSY--GIRTPSYDGPITDVTSNDLACNGGPNPTTPSDKIITVNAGSTVKAIWRHTLTSGADDVMDASHKGPTLAYLKKVDDALTDTGIGGGWFKIQEDGYN--NGQWGTSTVITNGGFQYIDIPACIPSGQYLLRAEMIALHAASS------TAGAQLYMECAQINIVG-GTAL-PSTTYSIPGIYKATDPGLLVNIYSM-SPTYTIPGPAKFTC----------------------------*

C;cover size:230; local alignment length=230 (original info = e5acfA1	234	568.63	2.7e-87	225	46	100.00)
>P1;e5acfA1
structureX:e5acfA1: 1: : 226: : : : : 
-TLVWGVWVNGVDQGDGRNIYIRSPPNNNPVKNLTSPDMTCNVD---NRVVPKSVPVNAGDTLTFEWYHNTRD--DDIIASSHHGPIAVYIAPAAS----NGQGNVWVKLFEDAYNVTNSTWAVDRLITAHGQHSVVVPH-VAPGDYLFRAEIIALHEADSLYSQNPIRGAQFYISCAQITINSSDDSTPLPAGVPFPGAYTDSTPGIQFNIYTTPATSYVAPPPSVWSGALGGSIA---------------------*

C;query_length:252 num_of_temps:1 cover_ratio:0.89 cover:224 not_cover:28
>P1;2017-10-28_00000052_1_72
 : : : : : : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKG--GEPVPQFVSASAGDKLTFEWYRVKRG--DDIIDPSHSGPITTWIAAFTSP-TMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTD-FDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*
