C;cover size:49; local alignment length=49 (original info = e3db2C2	183	13.57	0.099	43	9	0.70)
>P1;e3db2C2
structureX:e3db2C2: 2: : 44: : : : : 
--NPVGVAAIGL-GR--WAYVADAYT---KSEKLKLVTCYSRTEDKREKFG----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:213; local alignment length=213 (original info = d2fyia1	220	257.05	3.7e-45	211	18	100.00)
>P1;d2fyia1
structureX:d2fyia1: 4: : 217: : : : : 
TSGVLTIATTHTQARYSLPEVIKAFRE--LFPEVRLELIQGTPQEIATLLQNGEADIGIASERLSNDPQLVAFPWFRWHHSLLVPHDHPLTQISPLTLESIAKWPLITYRQGITGRSRIDDAFARKGLLADIVLSAQDSDVIKTYVALGLGIGLVAEQSSGEQEEENLIRLDTRHLFDANTVWLGLKRGQLQRNYVWRFLELCNAGLSVEDIKRQV-------------*

C;query_length:226 num_of_temps:1 cover_ratio:0.22 cover:49 not_cover:177
>P1;2017-10-14_00000061_1_71
 : : : : : : : : : 
SHGNIDLGFIYTMGAHTVPELVQNFTKVESHKDITFSFFQGATKSIIPDLKNEKFDLAICSYVE-NEPDIEFLPLTKQELVVVVAENHPLAKYDSIDLQDTADYSYIFFSDTSGLRPLIDSLFAEINIQPKIGCYVEEDTAMVGLVSVDYGISIMPKISS--LAHYNVKVLSINEPKHDRFIYLASLKNHYISPASKAFKDFALRYGKKHFLRENLYFQGLEHHHHHHH*
