C;cover size:53; local alignment length=53 (original info = d1ofux_	118	3.88	0.5	53	4	0.09)
>P1;d1ofux_
structureX:d1ofux_: 46: : 118: : : : : 
----------------------------------------------------------------------------------------------------------------------THEWLRRAGLNRERILLLQAKDNAAALALSCEALRLGRSHTVVSWLEPLSR--AARKQLSRAAQLGQAQSLNIRL--------------------------------------------------------*

C;cover size:213; local alignment length=213 (original info = d2fyia1	220	257.05	3.7e-45	211	18	100.00)
>P1;d2fyia1
structureX:d2fyia1: 4: : 217: : : : : 
TSGVLTIATTHTQARYSLPEVIKAFRE--LFPEVRLELIQGTPQEIATLLQNGEADIGIASERLSNDPQLVAFPWFRWHHSLLVPHDHPLTQISPLTLESIAKWPLITYRQGITGRSRIDDAFARKGLLADIV--LSAQDS----DVIKTYVALGLG---IGLVAEQSSGEQ---------EEEN--LIRLDTRHLFDANTVWLGLKRGQLQRNYVWRFLELCNAGLSVEDIKRQV-------------*

C;query_length:226 num_of_temps:1 cover_ratio:0.23 cover:53 not_cover:173
>P1;2017-10-14_00000061_1_71
 : : : : : : : : : 
SHGNIDLGFIYTMGAHTVPELVQNFTKVESHKDITFSFFQGATKSIIPDLKNEKFDLAICSYVE-NEPDIEFLPLTKQELVVVVAENHPLAKYDSIDLQDTADYSYIFFSDTSGLRPLIDSLFAEINIQPKIG--CYVEED----TAMVGLVSVDYG---ISIMPKISS--L---------AHYN--VKVLSINEPKHDRFIYLASLKNHYISPASKAFKDFALRYGKKHFLRENLYFQGLEHHHHHHH*
