C;cover size:170; local alignment length=170 (original info = d1wdna_	223	58.42	1.2e-09	155	14	98.26)
>P1;d1wdna_
structureX:d1wdna_: 24: : 189: : : : : 
----------------FDVDLWAAIAK---ELKLDYELKPMDFSGIIPALQTKNVDLALAGITITDE-RKKAIDFSDGYYKSGLLVMVKANNND----VKSVKDLDGKVVAV-KSGTGSVDYAKANIKTK----DL-RQFPNIDNAYMELGTNRADAVLHDTPNILYFI--KTAGNGQFKAVG--DSLEAQQYGIAFPKG----------------------------------------*

C;cover size:213; local alignment length=213 (original info = d2fyia1	220	257.05	3.7e-45	211	18	100.00)
>P1;d2fyia1
structureX:d2fyia1: 4: : 217: : : : : 
TSGVLTIATTHTQARYSLPEVIKAFRE--LFPEVRLELIQGTPQEIATLLQNGEADIGIASER---LSNDPQLV-AFPWFRWHHSLLVPHDHPLTQISPLTLESIAKWPLITYRQGITGRSRIDDAFARKGLLADIVLSAQDSDVIKTYVALGLG-IGLVAEQS----SGEQ--EEENLIRLDTRHLFDANTVWLGLKRGQLQRNYVWRFLELCNAGLSVEDIKRQV-------------*

C;query_length:226 num_of_temps:1 cover_ratio:0.75 cover:170 not_cover:56
>P1;2017-10-14_00000061_1_71
 : : : : : : : : : 
SHGNIDLGFIYTMGAHTVPELVQNFTKVESHKDITFSFFQGATKSIIPDLKNEKFDLAICSYV---E-NEPDIE-FLPLTKQELVVVVAENHPLAKYDSIDLQDTADYSYIFFSDTSGLRPLIDSLFAEINIQPKIGCYVEEDTAMVGLVSVDYG-ISIMPKIS----S--L--AHYNVKVLSINEPKHDRFIYLASLKNHYISPASKAFKDFALRYGKKHFLRENLYFQGLEHHHHHHH*
