C;cover size:213; local alignment length=213 (original info = d2fyia1	220	257.05	3.7e-45	211	18	100.00)
>P1;d2fyia1
structureX:d2fyia1: 4: : 217: : : : : 
TSGVLTIATTHTQARYSLPEVIKAFRE--LFPEVRLELIQGTPQEIATLLQNGEADIGIASERLSNDPQLVAFPWFRWHHSLLVPHDHPLTQISPLTLESIAKWPLITYRQGITGRSRIDDAFARKGLLADIVLSAQDSDVIKTYVALGLGIGLVAEQSSGEQEEENLIRLDTRHLFDANTVWLGLKRGQLQRNYVWRFLELCNAGLSVEDIKRQV-------------*

C;query_length:226 num_of_temps:1 cover_ratio:0.94 cover:213 not_cover:13
>P1;2017-10-14_00000061_1_71
 : : : : : : : : : 
SHGNIDLGFIYTMGAHTVPELVQNFTKVESHKDITFSFFQGATKSIIPDLKNEKFDLAICSYVE-NEPDIEFLPLTKQELVVVVAENHPLAKYDSIDLQDTADYSYIFFSDTSGLRPLIDSLFAEINIQPKIGCYVEEDTAMVGLVSVDYGISIMPKISS--LAHYNVKVLSINEPKHDRFIYLASLKNHYISPASKAFKDFALRYGKKHFLRENLYFQGLEHHHHHHH*
