C; model_eva_score=0.908, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=0.9952, gdt_score=0.9940, maxsub=0.9885.
>P1;meta_blits5.pdb1
structureX:meta_blits5.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=0.9952, gdt_score=0.9940, maxsub=0.9885.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=0.9943, gdt_score=0.9900, maxsub=0.9860.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.906, tm_score=0.9902, gdt_score=0.9840, maxsub=0.9768.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.906, tm_score=0.9910, gdt_score=0.9830, maxsub=0.9783.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.907, tm_score=0.9973, gdt_score=0.9970, maxsub=0.9930.
>P1;meta_blits7.pdb1
structureX:meta_blits7.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.906, tm_score=0.9903, gdt_score=0.9810, maxsub=0.9764.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.907, tm_score=0.9911, gdt_score=0.9810, maxsub=0.9785.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.907, tm_score=0.9886, gdt_score=0.9750, maxsub=0.9732.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9878, gdt_score=0.9850, maxsub=0.9712.
>P1;meta_blits8.pdb1
structureX:meta_blits8.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9878, gdt_score=0.9850, maxsub=0.9712.
>P1;meta_blits9.pdb1
structureX:meta_blits9.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9878, gdt_score=0.9850, maxsub=0.9712.
>P1;meta_blits10.pdb1
structureX:meta_blits10.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.904, tm_score=0.9832, gdt_score=0.9680, maxsub=0.9591.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9907, gdt_score=0.9820, maxsub=0.9780.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9814, gdt_score=0.9660, maxsub=0.9525.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9915, gdt_score=0.9840, maxsub=0.9781.
>P1;meta_hhsuite8.pdb1
structureX:meta_hhsuite8.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9874, gdt_score=0.9750, maxsub=0.9698.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C;total number of template models = 20
>P1;C00001
 : : : : : : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*
