C; model_eva_score=0.908, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_blits5.pdb1
structureX:meta_blits5.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=0.9952, gdt_score=0.9940, maxsub=0.9885.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=0.9952, gdt_score=0.9940, maxsub=0.9885.
>P1;meta_blits4.pdb1
structureX:meta_blits4.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=0.9952, gdt_score=0.9940, maxsub=0.9885.
>P1;meta_blits3.pdb1
structureX:meta_blits3.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.908, tm_score=0.9934, gdt_score=0.9880, maxsub=0.9833.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.906, tm_score=0.9906, gdt_score=0.9840, maxsub=0.9778.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.906, tm_score=0.9911, gdt_score=0.9810, maxsub=0.9796.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.907, tm_score=0.9952, gdt_score=0.9940, maxsub=0.9887.
>P1;meta_blits7.pdb1
structureX:meta_blits7.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.906, tm_score=0.9904, gdt_score=0.9820, maxsub=0.9774.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.907, tm_score=0.9929, gdt_score=0.9870, maxsub=0.9828.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.907, tm_score=0.9899, gdt_score=0.9760, maxsub=0.9767.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9876, gdt_score=0.9810, maxsub=0.9725.
>P1;meta_blits8.pdb1
structureX:meta_blits8.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9876, gdt_score=0.9810, maxsub=0.9725.
>P1;meta_blits9.pdb1
structureX:meta_blits9.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9876, gdt_score=0.9810, maxsub=0.9725.
>P1;meta_blits10.pdb1
structureX:meta_blits10.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.904, tm_score=0.9830, gdt_score=0.9670, maxsub=0.9584.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9890, gdt_score=0.9780, maxsub=0.9736.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9821, gdt_score=0.9670, maxsub=0.9543.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9936, gdt_score=0.9880, maxsub=0.9842.
>P1;meta_hhsuite8.pdb1
structureX:meta_hhsuite8.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C; model_eva_score=0.905, tm_score=0.9883, gdt_score=0.9760, maxsub=0.9733.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 250: : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*

C;total number of template models = 20
>P1;C00001
 : : : : : : : : : 
IVGGTNASLGEWPWQVSLQVKLVSQTHLCGGSIIGRQWVLTAAHCFDGIPYPDVWRIYGGILSLSEITKETPSSRIKELIIHQEYKVSEGNYDIALIKLQTPLNYTEFQKPISLPSKADTNTIYTNCWVTGWGYTKEQGETQNILQKATIPLVPNEECQKKYRDYVINKQMICAGYKEGGTDACKGDSGGPLVCKHSGRWQLVGITSWGEGCARKDQPGVYTKVSEYMDWILEKTQSSDVRALETSSAVD*
