C; model_eva_score=0.16, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ap4.pdb1
structureX:meta_ap4.pdb: 1: : 110: : : : : 
AARYDDVLYFPASRYPETGAHISDAIKAGHADVCTIERSGADKRRQESLKGIPTKPGFDRDEWPMAMCEEGGKGASVRYVSSSDNRGAGSWVGNRLNGYADGTRILFIVQ*

C; model_eva_score=0.157, tm_score=0.6052, gdt_score=0.6068, maxsub=0.5783.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 5: : 69: : : : : 
----DDVLYFPASRYPETGAHISDAIKAGHADVCTIERSGADKRRQESLKGIPTKPGFDRDEWPMAMCE-----------------------------------------*

C;total number of template models = 2
>P1;C00931
 : : : : : : : : : 
AARYDDVLYFPASRYPETGAHISDAIKAGHADVCTIERSGADKRRQESLKGIPTKPGFDRDEWPMAMCEEGGKGASVRYVSSSDNRGAGSWVGNRLNGYADGTRILFIVQ*
