C; model_eva_score=0.085, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_blits2.pdb1
structureX:meta_blits2.pdb: 1: : 666: : : : : 
MAAAPQINAELVTANLEAFLELMPEMGERLRVHRPQSNLVVNEDGDLDVEFRGEFLYGPGGRKRIEDMATRTALGPDHRISAAPLSSGHVDLIVKRFLYNILKRATDSGLSFLQHPEESGGFHMVCLGLGLGYQLPILLEQDNPAGIHIVEPNFDFLYHSLSTVDWRPLLETRRENPLRLNIIIEEEPGQIARQLRSAIRCCCPIVVDWTRLFVAYNSPLLTAAMSEFMRDAQLIGIGLGFLHDEMEMTRASYKNMRDGRYSILQHSATQLHTPVFIVGSGPSIDDDIEVIKANQDRAVIISCGTASRVLLANGIQPDFQMLLENGAAPYRALAAVHEEFGFGSATLIGSNTVDPRVRDLFEDVVYYFRPALSSYALFSPGIEYSLDDSGPTVTNTGTTAALALGFRELYLFGVDLGSRNPKRHHSKQSLYRHADDTKDGQKGAMDFDAVFDVREPGNFGGVVYSETIMLWTRDALGRIIGRYRPAANAFNCSDGVMIENTRPLSSQSLRLKSTPDMKAKDLAKVRASFRPGGEELFHDRWDREDWPRSIVTLLGECAQAMDDHVGDSNRLMLVLSEMLLRDYKQPPTVAQFFVRGTLMMAAMCYDYYVKRVTPADRKAEFWEIIRDEFHQMIRVMTLQVEWYFDNIEAFESDEELFDKVTGWDYD*

C; model_eva_score=0.076, tm_score=0.4441, gdt_score=0.3656, maxsub=0.3452.
>P1;meta_gbli2.pdb1
structureX:meta_gbli2.pdb: 317: : 334: : : : : 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------PDFQMLLENGAAPYRALA--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00501
 : : : : : : : : : 
MAAAPQINAELVTANLEAFLELMPEMGERLRVHRPQSNLVVNEDGDLDVEFRGEFLYGPGGRKRIEDMATRTALGPDHRISAAPLSSGHVDLIVKRFLYNILKRATDSGLSFLQHPEESGGFHMVCLGLGLGYQLPILLEQDNPAGIHIVEPNFDFLYHSLSTVDWRPLLETRRENPLRLNIIIEEEPGQIARQLRSAIRCCCPIVVDWTRLFVAYNSPLLTAAMSEFMRDAQLIGIGLGFLHDEMEMTRASYKNMRDGRYSILQHSATQLHTPVFIVGSGPSIDDDIEVIKANQDRAVIISCGTASRVLLANGIQPDFQMLLENGAAPYRALAAVHEEFGFGSATLIGSNTVDPRVRDLFEDVVYYFRPALSSYALFSPGIEYSLDDSGPTVTNTGTTAALALGFRELYLFGVDLGSRNPKRHHSKQSLYRHADDTKDGQKGAMDFDAVFDVREPGNFGGVVYSETIMLWTRDALGRIIGRYRPAANAFNCSDGVMIENTRPLSSQSLRLKSTPDMKAKDLAKVRASFRPGGEELFHDRWDREDWPRSIVTLLGECAQAMDDHVGDSNRLMLVLSEMLLRDYKQPPTVAQFFVRGTLMMAAMCYDYYVKRVTPADRKAEFWEIIRDEFHQMIRVMTLQVEWYFDNIEAFESDEELFDKVTGWDYD*
