C;cover size:158; local alignment length=158 (original info = e5kngB1	159	248.59	1.7e-44	158	84	100.00)
>P1;e5kngB1
structureX:e5kngB1: 1: : 158: : : : : 
--GSDLDKKLLEAARAGQDDEVRILMANGADVNARDSYGSTPLHLAAREGHLEIVEVLLKYGADVN-AADFIGDTPLHLAAYRGHLEIVEVLLKY-GADVNASDITGETPLHLAAQIGHLEIVEVLLKH-GADVNAQDKFGKTPADIAADNGHEDIAEVLQKL-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:293; local alignment length=293 (original info = e5et0A1	327	395.90	1e-63	288	35	100.00)
>P1;e5et0A1
structureX:e5et0A1: 5: : 322: : : : : 
-------EQALQAARRGDLDVLRSLHAAGL----LDSLDALPVHHAARSGKLHCLRYLVEEVALPAVSRARNGATPAHDAAATGYLSCLQWLLTQGGCRVQEKDNSGATVLHLAARFGHPDVVKWLLYQGGANSAITTDTGALPIHYAAAKGDLPSLKLLVGHYPEGVNAQTNNGATPLYLACQEGHLEVTKYLVQECSADPHLRAQDGMTPLHAAAQMGHNPVLVWLVSFADVSFSEQDHDGATAMHFAASRGHTKVLSWLLLHGAEIS-QDLWGGTPLHDAAENGELECCQILAVNGAGLDVRDHDGYTAADLAEFNGHTHCSRYLRT--*

C;query_length:302 num_of_temps:1 cover_ratio:0.52 cover:158 not_cover:144
>P1;2017-11-04_00000019_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADVNAADDVGVTPLHLAAQRGHLEIVEVLLKYGADVN-AADLWGQTPLHLAATAGHLEIVEVLLKN-GADVNARDNIGHTPLHLAAWAGHLEIVEVLLKY-GADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAAGGGSGGG-------------------------SGGGDVNAYDEVGWTPLHRAAW-GHLELVEKLLKNG-ADVNAADIDGYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAA*
