C;cover size:160; local alignment length=160 (original info = e4gmrA1	167	244.48	2.3e-43	160	57	100.00)
>P1;e4gmrA1
structureX:e4gmrA1: 1: : 160: : : : : 
---SELGKRLIEAAENGNKDRVKDLLENGADVNASDSDGKTPLHLAAENGHKEVVKLLLSQGADPN-AKDSDGKTPLHLAAENGHKEVVKLLLSQ-GADPNAKDSDGKTPLHLAAENGHKEVVKLLLSQ-GADPNTSDSDGRTPLDLAREHGNEEVVKLLEKQGGW----------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:293; local alignment length=293 (original info = e5et0A1	327	395.90	1e-63	288	35	100.00)
>P1;e5et0A1
structureX:e5et0A1: 5: : 322: : : : : 
-------EQALQAARRGDLDVLRSLHAAGL----LDSLDALPVHHAARSGKLHCLRYLVEEVALPAVSRARNGATPAHDAAATGYLSCLQWLLTQGGCRVQEKDNSGATVLHLAARFGHPDVVKWLLYQGGANSAITTDTGALPIHYAAAKGDLPSLKLLVGHYPEGVNAQTNNGATPLYLACQEGHLEVTKYLVQECSADPHLRAQDGMTPLHAAAQMGHNPVLVWLVSFADVSFSEQDHDGATAMHFAASRGHTKVLSWLLLHGAEIS-QDLWGGTPLHDAAENGELECCQILAVNGAGLDVRDHDGYTAADLAEFNGHTHCSRYLRT--*

C;query_length:302 num_of_temps:1 cover_ratio:0.53 cover:160 not_cover:142
>P1;2017-11-04_00000019_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADVNAADDVGVTPLHLAAQRGHLEIVEVLLKYGADVN-AADLWGQTPLHLAATAGHLEIVEVLLKN-GADVNARDNIGHTPLHLAAWAGHLEIVEVLLKY-GADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAAGGGSGGG-------------------------SGGGDVNAYDEVGWTPLHRAAW-GHLELVEKLLKNG-ADVNAADIDGYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAA*
