C;cover size:156; local alignment length=156 (original info = e4jb8P1	158	247.39	2.6e-44	156	78	100.00)
>P1;e4jb8P1
structureX:e4jb8P1: 1: : 156: : : : : 
----DLGKKLLDAASAGQ--DDEV-RILMANG--ADVNASNQQGWTPLHATAEYG-HLEIVDVLLAY---GADVN-ASDSYGSTPLHSAAWAGHLEIVDVLLAH-GADVNASDNYGWTPLHLAAHTGHLEIVDVLLAN-GADVNANNWWGKTPFDLAIDNGNEDIAEVLQKA-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:63; local alignment length=63 (original info = d1y6ia1	82	-0.57	0.99	59	17	0.02)
>P1;d1y6ia1
structureX:d1y6ia1: 15: : 82: : : : : 
ASEKKQLTAIAALAEMGEGGQGILLDYLAKNVPLEKPVLA--VGN--VYQTLRNLEQETITTQLQRNYPTGI-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:293; local alignment length=293 (original info = e5et0A1	327	395.90	1e-63	288	35	100.00)
>P1;e5et0A1
structureX:e5et0A1: 5: : 322: : : : : 
-------EQALQAARRGD--LDVL-RSLHAAG--L----LDSLDALPVHHAARSG-KLHCLRYLVEE---VALPAVSRARNGATPAHDAAATGYLSCLQWLLTQGGCRVQEKDNSGATVLHLAARFGHPDVVKWLLYQGGANSAITTDTGALPIHYAAAKGDLPSLKLLVGHYPEGVNAQTNNGATPLYLACQEGHLEVTKYLVQECSADPHLRAQDGMTPLHAAAQMGHNPVLVWLVSFADVSFSEQDHDGATAMHFAASRGHTKVLSWLLLHGAEIS-QDLWGGTPLHDAAENGELECCQILAVNGAGLDVRDHDGYTAADLAEFNGHTHCSRYLRT--*

C;query_length:302 num_of_temps:1 cover_ratio:0.52 cover:156 not_cover:146
>P1;2017-11-04_00000019_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQ--DDEV-RILMANG--ADVNAADDVGVTPLHLAAQRG-HLEIVEVLLKY---GADVN-AADLWGQTPLHLAATAGHLEIVEVLLKN-GADVNARDNIGHTPLHLAAWAGHLEIVEVLLKY-GADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAAGGGSGGG-------------------------SGGGDVNAYDEVGWTPLHRAAW-GHLELVEKLLKNG-ADVNAADIDGYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAA*
