C;cover size:153; local alignment length=153 (original info = d1awcb_	153	243.41	6.6e-44	152	64	100.00)
>P1;d1awcb_
structureX:d1awcb_: 1: : 152: : : : : 
----DLGKKLLEAARAGQ--DDEV-RILMANG--APFT-TDWLGTSPLHLAAQYG-HFSTTEVLLRA---GVSRD-ARTKVDRTPLHMAASEGHANIVEVLLKH-GADVNAKDMLKMTALHWATEHNHQEVVELLIKY-GADVHTQSKFCKTAFDISIDNGNEDLAEIL----------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:63; local alignment length=63 (original info = d1y6ia1	82	-0.57	0.99	59	17	0.02)
>P1;d1y6ia1
structureX:d1y6ia1: 15: : 82: : : : : 
ASEKKQLTAIAALAEMGEGGQGILLDYLAKNVPLEKPVLA--VGN--VYQTLRNLEQETITTQLQRNYPTGI-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:293; local alignment length=293 (original info = e5et0A1	327	395.90	1e-63	288	35	100.00)
>P1;e5et0A1
structureX:e5et0A1: 5: : 322: : : : : 
-------EQALQAARRGD--LDVL-RSLHAAG--L----LDSLDALPVHHAARSG-KLHCLRYLVEE---VALPAVSRARNGATPAHDAAATGYLSCLQWLLTQGGCRVQEKDNSGATVLHLAARFGHPDVVKWLLYQGGANSAITTDTGALPIHYAAAKGDLPSLKLLVGHYPEGVNAQTNNGATPLYLACQEGHLEVTKYLVQECSADPHLRAQDGMTPLHAAAQMGHNPVLVWLVSFADVSFSEQDHDGATAMHFAASRGHTKVLSWLLLHGAEIS-QDLWGGTPLHDAAENGELECCQILAVNGAGLDVRDHDGYTAADLAEFNGHTHCSRYLRT--*

C;query_length:302 num_of_temps:1 cover_ratio:0.51 cover:153 not_cover:149
>P1;2017-11-04_00000019_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQ--DDEV-RILMANG--ADVNAADDVGVTPLHLAAQRG-HLEIVEVLLKY---GADVN-AADLWGQTPLHLAATAGHLEIVEVLLKN-GADVNARDNIGHTPLHLAAWAGHLEIVEVLLKY-GADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAAGGGSGGG-------------------------SGGGDVNAYDEVGWTPLHRAAW-GHLELVEKLLKNG-ADVNAADIDGYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAA*
