C;cover size:158; local alignment length=158 (original info = e4f6rD1	159	251.32	5.6e-45	158	86	100.00)
>P1;e4f6rD1
structureX:e4f6rD1: 1: : 158: : : : : 
--GSDLGKKLLEAARAGQDDEVRILMANGADVNAEDDSGKTPLHLAAIKGHLEIVEVLLKHGADVN-AADKMGDTPLHLAALYGHLEIVEVLLKN-GADVNATDTYGFTPLHLAADAGHLEIVEVLLKY-GADVNAQDKFGKTAFDISIDNGNEDLAEILQKL-------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:293; local alignment length=293 (original info = e5et0A1	327	395.90	1e-63	288	35	100.00)
>P1;e5et0A1
structureX:e5et0A1: 5: : 322: : : : : 
-------EQALQAARRGDLDVLRSLHAAGL----LDSLDALPVHHAARSGKLHCLRYLVEEVALPAVSRARNGATPAHDAAATGYLSCLQWLLTQGGCRVQEKDNSGATVLHLAARFGHPDVVKWLLYQGGANSAITTDTGALPIHYAAAKGDLPSLKLLVGHYPEGVNAQTNNGATPLYLACQEGHLEVTKYLVQECSADPHLRAQDGMTPLHAAAQMGHNPVLVWLVSFADVSFSEQDHDGATAMHFAASRGHTKVLSWLLLHGAEIS-QDLWGGTPLHDAAENGELECCQILAVNGAGLDVRDHDGYTAADLAEFNGHTHCSRYLRT--*

C;query_length:302 num_of_temps:1 cover_ratio:0.52 cover:158 not_cover:144
>P1;2017-11-04_00000019_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADVNAADDVGVTPLHLAAQRGHLEIVEVLLKYGADVN-AADLWGQTPLHLAATAGHLEIVEVLLKN-GADVNARDNIGHTPLHLAAWAGHLEIVEVLLKY-GADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAAGGGSGGG-------------------------SGGGDVNAYDEVGWTPLHRAAW-GHLELVEKLLKNG-ADVNAADIDGYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQKAA*
