C;cover size:261; local alignment length=261 (original info = e4qfvA1	229	330.26	4.4e-55	219	62	100.00)
>P1;e4qfvA1
structureX:e4qfvA1: 7: : 225: : : : : 
----------------------------------------KKLLEAARAGHDDSVEVLLKKGADINAKDNSGRTPLHVAALNGHLELVKLLLEKGADINARDMFGLTPLHTAASNGHLELVKLLLEKGADINARDEDGSTPLHLAASNGHLELVKLLL------------------------------------------------------------------------------------------------------------------------------------EKGADINAEDHSGTTPLHFAAKNGHLELVKLLLEKGADINASDFSGPTPLHSAAENGHLELVKLLLEKGADINARDKFGKTPFDLAIDNGNEDIAEVLQKA-*

C;cover size:293; local alignment length=293 (original info = e1n11A1	404	416.41	2.7e-64	293	41	100.00)
>P1;e1n11A1
structureX:e1n11A1: 2: : 384: : : : : 
-------TPLHVASFMGHLPIVKNLLQRGASPNVSNVKVETPLHMAARAGHTEVAKYLLQNKAKVNAKAKDDQTPLHCAARIGHTNMVKLLLENNANPNLATTAGHTPLHIAAREGHVETVLALLEKEASQACMTKKGFTPLHVAAKYGKVRVAELLLERDAHPNAAGKNGLTPLHVAVHHNNLDIVKLLLPRGGSPHSPAWNGYTPLHIAAKQNQVEVARSLLQYGGSANAESVQGVTPLHLAAQEGHAEMVALLLSKQANGNLGNKSGLTPLHLVAQEGHVPVADVLIKHGVMVDATTRMGYTPLHVASHYGNIKLVKFLLQHQADVNAKTKLGYSPLHQAAQQGHTDIVTLLLKNGASPNEVSSDGTTPLAIAKRLGYISVTDVLKV--*

C;cover size:158; local alignment length=158 (original info = e5kbaB1	160	241.82	1.3e-42	158	56	100.00)
>P1;e5kbaB1
structureX:e5kbaB1: 2: : 159: : : : : 
-GSSELGKRLIEAAENGNKDRVKDLIENGADVNASDSDGRTPLHHAAENGHAEVVALLIEKGADVNAKDSDGRTPLHHAAENGHDEVVLILLLKGADVNAKDSDGRTPLHHAAENGHKRVVLVLILAGADVNTSDSDGRTPLDLAREHGNEEVVKALEK-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:302 num_of_temps:1 cover_ratio:0.86 cover:261 not_cover:41
>P1;2017-11-04_00000021_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADVNAADDVGVTPLHLAAQRGHLEIVEVLLKYGADVNAADLWGQTPLHLAATAGHLEIVEVLLKNGADVNARDNIGHTPLHLAAWAGHLEIVEVLLKYGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQK---------------------------------AAGGGSGGG-----------------------SGGGDVNAYDEVGWTPLHK---------------------------------AA-WGHLEKVEDLLKNGADVNAADIDGYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEILQKAA*
