C;cover size:270; local alignment length=270 (original info = e3eu9A1	233	330.43	4.9e-55	228	34	100.00)
>P1;e3eu9A1
structureX:e3eu9A1: 1: : 231: : : : : 
-------------------------------MTHIDDYSTWDIVKATQYGIYERCRELVEAGYDVRQPDKENVTLLHWAAINNRIDLVKYYISKGAIVDQLGGDLNSTPLHWATRQGHLSMVVQLMKYGADPSLIDGEGCSCIHLAAQFGHTSIV------------------------------------------------------------------------------------------------------------------------------------AYLIAKGQDVDMMDQNGMTPLMWAAYRTHSVDPTRLLLTFNVSVNLGDKYHKNTALHWAVLAGNTTVISLLLEAGANVDAQNIKGESALDLAKQRKNVWMINHLQEA-*

C;cover size:293; local alignment length=293 (original info = e1n11A1	404	416.41	2.7e-64	293	41	100.00)
>P1;e1n11A1
structureX:e1n11A1: 2: : 384: : : : : 
-------TPLHVASFMGHLPIVKNLLQRGASPNVSNVKVETPLHMAARAGHTEVAKYLLQNKAKVNAKAKDDQTPLHCAARIGHTNMVKLLLENNANPNLAT-TAGHTPLHIAAREGHVETVLALLEKEASQACMTKKGFTPLHVAAKYGKVRVAELLLERDAHPNAAGKNGLTPLHVAVHHNNLDIVKLLLPRGGSPHSPAWNGYTPLHIAAKQNQVEVARSLLQYGGSANAESVQGVTPLHLAAQEGHAEMVALLLSKQANGNLGNKSGLTPLHLVAQEGHVPVADVLIKHGVMVDATTRMGYTPLHVASHYGN-IKLVKFLLQHQADVNAKTK-LGYSPLHQAAQQGHTDIVTLLLKNGASPNEVSSDGTTPLAIAKRLGYISVTDVLKV--*

C;cover size:158; local alignment length=158 (original info = e5kbaB1	160	241.82	1.3e-42	158	56	100.00)
>P1;e5kbaB1
structureX:e5kbaB1: 2: : 159: : : : : 
-GSSELGKRLIEAAENGNKDRVKDLIENGADVNASDSDGRTPLHHAAENGHAEVVALLIEKGADVNAKDSDGRTPLHHAAENGHDEVVLILLLKGADVNAKD-SDGRTPLHHAAENGHKRVVLVLILAGADVNTSDSDGRTPLDLAREHGNEEVVKALEK-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;query_length:302 num_of_temps:1 cover_ratio:0.89 cover:270 not_cover:32
>P1;2017-11-04_00000021_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADVNAADDVGVTPLHLAAQRGHLEIVEVLLKYGADVNAADLWGQTPLHLAATAGHLEIVEVLLKNGADVNARD-NIGHTPLHLAAWAGHLEIVEVLLKYGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQK---------------------------------AAGGGSGGG-----------------------SGGGDVNAYDEVGWTPLHK---------------------------------AA-WGHLEKVEDLLKNGADVNAADIDGYTPLHLAAFSGH-LEIVEVLLKYGADVNADDQ-AGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEILQKAA*
