C;cover size:158; local alignment length=158 (original info = e5kbaB1	160	241.82	1.3e-42	158	56	100.00)
>P1;e5kbaB1
structureX:e5kbaB1: 2: : 159: : : : : 
-GSSELGKRLIEAAENGNKDRVKDLIENGADVNASDSDGRTPLHHAAENGHAEVVALLIEKGADVNAKDSDGRTPLHHAAENGHDEVVLILLLKGADVNAKDSDGRTPLHHAAENGHKRVVLVLILAGADVNTSDSDGRTPLDLAREHGNEEVVKALEK-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:293; local alignment length=293 (original info = e1n11A1	404	416.41	2.7e-64	293	41	100.00)
>P1;e1n11A1
structureX:e1n11A1: 2: : 384: : : : : 
-------TPLHVASFMGHLPIVKNLLQRGASPNVSNVKVETPLHMAARAGHTEVAKYLLQNKAKVNAKAKDDQTPLHCAARIGHTNMVKLLLENNANPNLATTAGHTPLHIAAREGHVETVLALLEKEASQACMTKKGFTPLHVAAKYGKVRVAELLLERDAHPNAAGKNGLTPLHVAVHHNNLDIVKLLLPRGGSPHSPAWNGYTPLHIAAKQNQVEVARSLLQYGGSANAESVQGVTPLHLAAQEGHAEMVALLLSKQANGNLGNKSGLTPLHLVAQEGHVPVADVLIKHGVMVDATTRMGYTPLHVASHYGNIKLVKFLLQHQADVNAKTKLGYSPLHQAAQQGHTDIVTLLLKNGASPNEVSSDGTTPLAIAKRLGYISVTDVLKV--*

C;query_length:302 num_of_temps:1 cover_ratio:0.52 cover:158 not_cover:144
>P1;2017-11-04_00000021_2_72
 : : : : : : : : : 
GPGSDLGKKLLEAARAGQDDEVRILMANGADVNAADDVGVTPLHLAAQRGHLEIVEVLLKYGADVNAADLWGQTPLHLAATAGHLEIVEVLLKNGADVNARDNIGHTPLHLAAWAGHLEIVEVLLKYGADVNAQDKFGKTPFDLAIDNGNEDIAEVLQK---------------------------------AAGGGSGGG-----------------------SGGGDVNAYDEVGWTPLHK---------------------------------AA-WGHLEKVEDLLKNGADVNAADIDGYTPLHLAAFSGHLEIVEVLLKYGADVNADDQAGFTPLHLAAIFGHLEIVEVLLKNGADVNAQDKFGKTPFDLAIDNGNEDIAEILQKAA*
