C; model_eva_score=0.556, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.559, tm_score=0.9769, gdt_score=0.9648, maxsub=0.9481.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9832, gdt_score=0.9765, maxsub=0.9622.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9864, gdt_score=0.9765, maxsub=0.9700.
>P1;meta_multicom8.pdb1
structureX:meta_multicom8.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.56, tm_score=0.9858, gdt_score=0.9742, maxsub=0.9687.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9753, gdt_score=0.9484, maxsub=0.9475.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.555, tm_score=0.9598, gdt_score=0.9073, maxsub=0.9130.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.553, tm_score=0.9729, gdt_score=0.9448, maxsub=0.9389.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.552, tm_score=0.9561, gdt_score=0.9120, maxsub=0.9130.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.551, tm_score=0.9253, gdt_score=0.8474, maxsub=0.8446.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9661, gdt_score=0.9425, maxsub=0.9304.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9260, gdt_score=0.8756, maxsub=0.8471.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9244, gdt_score=0.8627, maxsub=0.8465.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9372, gdt_score=0.9026, maxsub=0.8708.
>P1;meta_csblast3.pdb1
structureX:meta_csblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9111, gdt_score=0.8380, maxsub=0.8174.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9350, gdt_score=0.8920, maxsub=0.8656.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.547, tm_score=0.9348, gdt_score=0.9061, maxsub=0.8709.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.544, tm_score=0.9175, gdt_score=0.8592, maxsub=0.8279.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.541, tm_score=0.9227, gdt_score=0.8521, maxsub=0.8385.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.539, tm_score=0.9096, gdt_score=0.8322, maxsub=0.8131.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C;total number of template models = 20
>P1;C00541
 : : : : : : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*
