C; model_eva_score=0.558, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_multicom8.pdb1
structureX:meta_multicom8.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.559, tm_score=0.9771, gdt_score=0.9531, maxsub=0.9505.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9875, gdt_score=0.9836, maxsub=0.9712.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.56, tm_score=0.9842, gdt_score=0.9754, maxsub=0.9641.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.556, tm_score=0.9864, gdt_score=0.9765, maxsub=0.9700.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9830, gdt_score=0.9742, maxsub=0.9629.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.555, tm_score=0.9747, gdt_score=0.9542, maxsub=0.9453.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.553, tm_score=0.9794, gdt_score=0.9730, maxsub=0.9556.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.552, tm_score=0.9550, gdt_score=0.9155, maxsub=0.9087.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.551, tm_score=0.9161, gdt_score=0.8345, maxsub=0.8223.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9743, gdt_score=0.9671, maxsub=0.9468.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9155, gdt_score=0.8451, maxsub=0.8252.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9159, gdt_score=0.8357, maxsub=0.8240.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9360, gdt_score=0.8908, maxsub=0.8694.
>P1;meta_csblast3.pdb1
structureX:meta_csblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9030, gdt_score=0.8239, maxsub=0.8076.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9355, gdt_score=0.8920, maxsub=0.8664.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.547, tm_score=0.9396, gdt_score=0.9143, maxsub=0.8823.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.544, tm_score=0.9049, gdt_score=0.8286, maxsub=0.7989.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.541, tm_score=0.9462, gdt_score=0.8908, maxsub=0.8859.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.539, tm_score=0.9062, gdt_score=0.8157, maxsub=0.8122.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C;total number of template models = 20
>P1;C00541
 : : : : : : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*
