C; model_eva_score=0.559, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.56, tm_score=0.9830, gdt_score=0.9742, maxsub=0.9636.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9856, gdt_score=0.9789, maxsub=0.9693.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9771, gdt_score=0.9531, maxsub=0.9505.
>P1;meta_multicom8.pdb1
structureX:meta_multicom8.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.556, tm_score=0.9769, gdt_score=0.9648, maxsub=0.9481.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9659, gdt_score=0.9319, maxsub=0.9237.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.555, tm_score=0.9463, gdt_score=0.9014, maxsub=0.8867.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.553, tm_score=0.9588, gdt_score=0.9272, maxsub=0.9167.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.552, tm_score=0.9406, gdt_score=0.8873, maxsub=0.8732.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.551, tm_score=0.9336, gdt_score=0.8744, maxsub=0.8617.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9629, gdt_score=0.9167, maxsub=0.9227.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9313, gdt_score=0.8991, maxsub=0.8528.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9207, gdt_score=0.8533, maxsub=0.8373.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9582, gdt_score=0.9437, maxsub=0.9132.
>P1;meta_csblast3.pdb1
structureX:meta_csblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9259, gdt_score=0.8815, maxsub=0.8464.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9549, gdt_score=0.9354, maxsub=0.9087.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.547, tm_score=0.9430, gdt_score=0.9167, maxsub=0.8844.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.544, tm_score=0.9422, gdt_score=0.9014, maxsub=0.8809.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.541, tm_score=0.9172, gdt_score=0.8474, maxsub=0.8311.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.539, tm_score=0.8878, gdt_score=0.8063, maxsub=0.7689.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C;total number of template models = 20
>P1;C00541
 : : : : : : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*
