C; model_eva_score=0.558, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.559, tm_score=0.9856, gdt_score=0.9789, maxsub=0.9693.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.56, tm_score=0.9842, gdt_score=0.9777, maxsub=0.9642.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9875, gdt_score=0.9836, maxsub=0.9712.
>P1;meta_multicom8.pdb1
structureX:meta_multicom8.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.556, tm_score=0.9832, gdt_score=0.9765, maxsub=0.9622.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9746, gdt_score=0.9472, maxsub=0.9447.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.555, tm_score=0.9612, gdt_score=0.9225, maxsub=0.9146.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.553, tm_score=0.9755, gdt_score=0.9671, maxsub=0.9457.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.552, tm_score=0.9525, gdt_score=0.9167, maxsub=0.9019.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.551, tm_score=0.9326, gdt_score=0.8650, maxsub=0.8600.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9641, gdt_score=0.9249, maxsub=0.9239.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9279, gdt_score=0.8932, maxsub=0.8547.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9109, gdt_score=0.8439, maxsub=0.8195.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9434, gdt_score=0.9155, maxsub=0.8840.
>P1;meta_csblast3.pdb1
structureX:meta_csblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9127, gdt_score=0.8486, maxsub=0.8232.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9374, gdt_score=0.9026, maxsub=0.8729.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.547, tm_score=0.9424, gdt_score=0.9249, maxsub=0.8850.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.544, tm_score=0.9185, gdt_score=0.8545, maxsub=0.8294.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.541, tm_score=0.9250, gdt_score=0.8650, maxsub=0.8453.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.539, tm_score=0.8989, gdt_score=0.8134, maxsub=0.7928.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C;total number of template models = 20
>P1;C00541
 : : : : : : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*
