C; model_eva_score=0.56, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_multicom6.pdb1
structureX:meta_multicom6.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.559, tm_score=0.9830, gdt_score=0.9742, maxsub=0.9636.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9842, gdt_score=0.9777, maxsub=0.9642.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.558, tm_score=0.9842, gdt_score=0.9754, maxsub=0.9641.
>P1;meta_multicom8.pdb1
structureX:meta_multicom8.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.556, tm_score=0.9858, gdt_score=0.9742, maxsub=0.9687.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9831, gdt_score=0.9695, maxsub=0.9615.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.555, tm_score=0.9582, gdt_score=0.9120, maxsub=0.9059.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.553, tm_score=0.9743, gdt_score=0.9730, maxsub=0.9465.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.552, tm_score=0.9478, gdt_score=0.9049, maxsub=0.8895.
>P1;meta_star2.pdb1
structureX:meta_star2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.551, tm_score=0.9431, gdt_score=0.8862, maxsub=0.8790.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.554, tm_score=0.9673, gdt_score=0.9425, maxsub=0.9312.
>P1;meta_sam3.pdb1
structureX:meta_sam3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9277, gdt_score=0.8885, maxsub=0.8490.
>P1;meta_hp2.pdb1
structureX:meta_hp2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9306, gdt_score=0.8803, maxsub=0.8606.
>P1;meta_hp1.pdb1
structureX:meta_hp1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.55, tm_score=0.9396, gdt_score=0.8920, maxsub=0.8758.
>P1;meta_csblast3.pdb1
structureX:meta_csblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9099, gdt_score=0.8439, maxsub=0.8214.
>P1;meta_ap2.pdb1
structureX:meta_ap2.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.548, tm_score=0.9325, gdt_score=0.8779, maxsub=0.8628.
>P1;meta_csblast4.pdb1
structureX:meta_csblast4.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.547, tm_score=0.9386, gdt_score=0.9155, maxsub=0.8796.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.544, tm_score=0.9257, gdt_score=0.8627, maxsub=0.8445.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.541, tm_score=0.9250, gdt_score=0.8568, maxsub=0.8480.
>P1;meta_sam5.pdb1
structureX:meta_sam5.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C; model_eva_score=0.539, tm_score=0.9168, gdt_score=0.8404, maxsub=0.8298.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 213: : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*

C;total number of template models = 20
>P1;C00541
 : : : : : : : : : 
TIQTVNGVPQYVALDPKMVSIFMEKAREGLGGEEVQLWFTAFSANLTPTDMATLIMAAPGCAADKEILDESLKQLTAEYDRTHPPDAPRPLPYFTAAEIMGIGLTQEQQAEARFAPARMQCRAWYLEALGKLAAIKAKSPRAVQLRQGAKEDYSSFIDRLFAQIDQEQNTAEVKLYLKQSLSIANANADCKKAMSHLKPESTLEEKLRACQEI*
