C; model_eva_score=0.5, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.5, tm_score=0.9460, gdt_score=0.9458, maxsub=0.9290.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.5, tm_score=0.9779, gdt_score=0.9685, maxsub=0.9637.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9194, gdt_score=0.9196, maxsub=0.9060.
>P1;meta_ff1.pdb1
structureX:meta_ff1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9194, gdt_score=0.9196, maxsub=0.9060.
>P1;meta_blast1.pdb1
structureX:meta_blast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9194, gdt_score=0.9196, maxsub=0.9060.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9194, gdt_score=0.9196, maxsub=0.9060.
>P1;meta_psiblast1.pdb1
structureX:meta_psiblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.498, tm_score=0.9074, gdt_score=0.9056, maxsub=0.8839.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.497, tm_score=0.9410, gdt_score=0.9371, maxsub=0.9174.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.497, tm_score=0.9092, gdt_score=0.9056, maxsub=0.8920.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9283, gdt_score=0.9318, maxsub=0.9050.
>P1;meta_muster1.pdb1
structureX:meta_muster1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9512, gdt_score=0.9545, maxsub=0.9279.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9512, gdt_score=0.9545, maxsub=0.9279.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9512, gdt_score=0.9545, maxsub=0.9279.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.8983, gdt_score=0.8986, maxsub=0.8797.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C;total number of template models = 15
>P1;C00701
 : : : : : : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*
