C; model_eva_score=0.501, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss1.pdb1
structureX:meta_ss1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.501, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.5, tm_score=0.9584, gdt_score=0.9528, maxsub=0.9301.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9268, gdt_score=0.9301, maxsub=0.8999.
>P1;meta_hhbl1.pdb1
structureX:meta_hhbl1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9126, gdt_score=0.9213, maxsub=0.8979.
>P1;meta_ff1.pdb1
structureX:meta_ff1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9126, gdt_score=0.9213, maxsub=0.8979.
>P1;meta_blast1.pdb1
structureX:meta_blast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9126, gdt_score=0.9213, maxsub=0.8979.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9126, gdt_score=0.9213, maxsub=0.8979.
>P1;meta_psiblast1.pdb1
structureX:meta_psiblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9154, gdt_score=0.9178, maxsub=0.9033.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C;total number of template models = 9
>P1;C00701
 : : : : : : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*
