C; model_eva_score=0.5, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.5, tm_score=0.9460, gdt_score=0.9458, maxsub=0.9290.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.5, tm_score=0.9409, gdt_score=0.9441, maxsub=0.9204.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9233, gdt_score=0.9248, maxsub=0.9076.
>P1;meta_ff1.pdb1
structureX:meta_ff1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9233, gdt_score=0.9248, maxsub=0.9076.
>P1;meta_blast1.pdb1
structureX:meta_blast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9233, gdt_score=0.9248, maxsub=0.9076.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9233, gdt_score=0.9248, maxsub=0.9076.
>P1;meta_psiblast1.pdb1
structureX:meta_psiblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.497, tm_score=0.9223, gdt_score=0.9213, maxsub=0.9004.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.497, tm_score=0.9142, gdt_score=0.9073, maxsub=0.8951.
>P1;meta_compro0.pdb1
structureX:meta_compro0.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9314, gdt_score=0.9336, maxsub=0.9086.
>P1;meta_muster1.pdb1
structureX:meta_muster1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9221, gdt_score=0.9353, maxsub=0.8973.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9221, gdt_score=0.9353, maxsub=0.8973.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9221, gdt_score=0.9353, maxsub=0.8973.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9067, gdt_score=0.9038, maxsub=0.8890.
>P1;meta_msaprobs0.pdb1
structureX:meta_msaprobs0.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.472, tm_score=0.8460, gdt_score=0.8287, maxsub=0.7845.
>P1;meta_ff3.pdb1
structureX:meta_ff3.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C;total number of template models = 15
>P1;C00701
 : : : : : : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*
