C; model_eva_score=0.5, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.5, tm_score=0.9409, gdt_score=0.9441, maxsub=0.9204.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.5, tm_score=0.9779, gdt_score=0.9685, maxsub=0.9637.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9216, gdt_score=0.9196, maxsub=0.9067.
>P1;meta_ff1.pdb1
structureX:meta_ff1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9216, gdt_score=0.9196, maxsub=0.9067.
>P1;meta_blast1.pdb1
structureX:meta_blast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9216, gdt_score=0.9196, maxsub=0.9067.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.499, tm_score=0.9216, gdt_score=0.9196, maxsub=0.9067.
>P1;meta_psiblast1.pdb1
structureX:meta_psiblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.498, tm_score=0.9080, gdt_score=0.9091, maxsub=0.8846.
>P1;meta_newblast1.pdb1
structureX:meta_newblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.497, tm_score=0.9342, gdt_score=0.9318, maxsub=0.9117.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9265, gdt_score=0.9336, maxsub=0.9094.
>P1;meta_muster1.pdb1
structureX:meta_muster1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9448, gdt_score=0.9423, maxsub=0.9129.
>P1;meta_hmmer1.pdb1
structureX:meta_hmmer1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9448, gdt_score=0.9423, maxsub=0.9129.
>P1;meta_csiblast1.pdb1
structureX:meta_csiblast1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C; model_eva_score=0.496, tm_score=0.9448, gdt_score=0.9423, maxsub=0.9129.
>P1;meta_multicom1.pdb1
structureX:meta_multicom1.pdb: 1: : 143: : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*

C;total number of template models = 13
>P1;C00701
 : : : : : : : : : 
GPGMSASGSGDATLGIVHTLMCHRQGGESENFAKRAVESLVKKLKDKRDELDALITAVTSNGIQQSKCVTIARTLDGRLQVAGKKGFPHVIYSRIWRWPDLHKNELKHIKLCKFAFDLKLDHVCVNPYHYERVISPGYNVTDI*
