C; model_eva_score=0.555, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_novel2.pdb1
structureX:meta_novel2.pdb: 1: : 162: : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*

C; model_eva_score=0.564, tm_score=0.7690, gdt_score=0.7346, maxsub=0.7210.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 3: : 112: : : : : 
--VGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRP--------------------------------------------------*

C; model_eva_score=0.563, tm_score=0.7526, gdt_score=0.7114, maxsub=0.6943.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 4: : 111: : : : : 
---GILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELR---------------------------------------------------*

C;total number of template models = 3
>P1;T041482
 : : : : : : : : : 
MAVGILEVSLISGKGLKRSDFLGKIDPYVEIQYKGQTRKSSVAKEDGGRNPTWNDKLKWRAEFPGSGADYKLIVKVMDHDTFSSDDFIGEATVHVKELLEMGVEKGTAELRPTKYNIVDSDLSFVGELLIGVSYSLLQDRGMDGEQFGGWKHSNVDHHHHHH*
