C;cover size:70; local alignment length=70 (original info = d2pjua1	186	13.19	0.28	51	22	0.36)
>P1;d2pjua1
structureX:d2pjua1: 40: : 92: : : : : 
------------------------------------------------------------------------VTYIRKKL--ANERCD-AIIAAGS-----NGAYLK---SRLSVPVILIK------PSGYD----VLQFLAKAGK-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:318; local alignment length=318 (original info = d1agxa_	331	618.68	1.2e-88	310	24	100.00)
>P1;d1agxa_
structureX:d1agxa_: 3: : 330: : : : : 
-NVVIVATGGTIAGAGAS--STNSATYSAAKVPVDALIKA-VPQVNDLANITGIQALQVASESITDKELLSLARQVNDLVKKP--SVNGVVITHGTDTMEETAFFLNLVV-HTDKPIVLVGSMRPSTALSADGPLNLYSAVALASSNEAKNK-------GVMVLMNDSIFAARDVTKGINIHTHAFVSQ-WGALGTLVEGKPYWFRSSVKKHTNN--SEFNIEKIQGDALPGVQIVYGSDNMMPDAYQAFAK-AGVKAIIHAGTGNGSMANYLVPEV--RKL-HDEQGLQIVRSSRVAQGFVLRNAEQP---DDKYGWIAAHDLNPQKARLLMALALTKTNDAKEIQNMFWN---------*

C;cover size:327; local alignment length=327 (original info = d2d6fa2	352	669.43	2.2e-95	322	36	100.00)
>P1;d2d6fa2
structureX:d2d6fa2: 9: : 344: : : : : 
-DVSIISTGGTVASIIDYRTGA----V-HPAFTADDLLRAN-PELLDIANIRGRAVFNILSENMKPEYWVETARAVYGEIK-D--GADGVVVAHGTDTMHYTSAALSFMLR-TPVPVVFTGAQRSSDRPSSDASLNIQCSVRAATSE---IAEVTVCMHATMDDLSCHLHRGVKVRKMHTSRRDTFRSMNALPLAEVTPDGIKILEENYRKR-GSDELEL-----SDRVEERVAFIKSYPGISPDIIKWH-LDEGYRGIVIEGTGLGHCPDTLI---PVIGEAH-DMGVPVAMTSQCLNGRVNMNVYSTGRRLLQAGVIPCDDMLPEVAYVKMCWVLGQTDDPEMAREMMRENIAGEINER*

C;query_length:328 num_of_temps:1 cover_ratio:0.21 cover:70 not_cover:258
>P1;2017-11-04_00000053_1_72
 : : : : : : : : : 
MKLLVLGTGGTIASAKTE--MG----Y-KAALSADDILQLAGIRREDGAKIETRDILNLDSTLIQPEDWVTIGRAVFEAF--D--EYDGIVITHGTDTLAYTSSALSFMIRNPPIPVVLTGSMLPITEPNSDAPRNLRTALTFARKG---FP-------GIYVAFMDKIMLGTRVSKVHSLGLNAFQSINYPDIAYVKGDEVLVRHKPRIGN-GE--PLF-----DPELDPNVVHIRLTPGLSPEVLRAV-A-RATDGIVLEGYGAGGIPYRGRNLLEVVSE-T-AREKPVVMTTQALYGGVDLTRYEVGRRALEAGVIPAGDMTKEATLTKLMWALGHTRDLEEIRKIMERNIAGEITGS*
