C;cover size:97; local alignment length=97 (original info = e2ks6A1	201	6.65	0.19	84	17	0.20)
>P1;e2ks6A1
structureX:e2ks6A1: 111: : 201: : : : : 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------DLVISHAGTGSI-------LDSL-----RLNKPLIVCVNDS--LMDNHQQQIADKFVELGYVWSCAPTET-GLIAGLRASQTEKLKPFPVSHNPSFERLLVETIYS-----*

C;cover size:318; local alignment length=318 (original info = d1agxa_	331	618.68	1.2e-88	310	24	100.00)
>P1;d1agxa_
structureX:d1agxa_: 3: : 330: : : : : 
-NVVIVATGGTIAGAGAS--STNSATYSAAKVPVDALIKA-VPQVNDLANITGIQALQVASESITDKELLSLARQVNDLVKKPSVNGVVITHGTDTMEETAFFLNLVV-HTDKPIVLVGSMRPSTALSADGPLNLYSAVALASSNEAKNK-------GVMVLMNDSIFAARDVTKGINIHTHAFVSQ-WGALGTLVEGKPYWFRSSVKKHTNN--SEFNIEKIQGDALPGVQIVYGSDNMMPDAYQAFAK-AGVKAIIHAGTGNGSMANYLVPEV--RKL-HDEQGLQIVRSSRVAQGFVLRNAEQP---DDKYGWIAAHDLNPQKARLLMALALT----K---TNDAKEIQNMFWN---------*

C;cover size:327; local alignment length=327 (original info = d2d6fa2	352	669.43	2.2e-95	322	36	100.00)
>P1;d2d6fa2
structureX:d2d6fa2: 9: : 344: : : : : 
-DVSIISTGGTVASIIDYRTGA----V-HPAFTADDLLRAN-PELLDIANIRGRAVFNILSENMKPEYWVETARAVYGEIK-DGADGVVVAHGTDTMHYTSAALSFMLR-TPVPVVFTGAQRSSDRPSSDASLNIQCSVRAATSE---IAEVTVCMHATMDDLSCHLHRGVKVRKMHTSRRDTFRSMNALPLAEVTPDGIKILEENYRKR-GSDELEL-----SDRVEERVAFIKSYPGISPDIIKWH-LDEGYRGIVIEGTGLGHCPDTLI---PVIGEAH-DMGVPVAMTSQCLNGRVNMNVYSTGRRLLQAGVIPCDDMLPEVAYVKMCWVLG----Q---TDDPEMAREMMRENIAGEINER*

C;query_length:328 num_of_temps:1 cover_ratio:0.3 cover:97 not_cover:231
>P1;2017-11-04_00000053_1_72
 : : : : : : : : : 
MKLLVLGTGGTIASAKTE--MG----Y-KAALSADDILQLAGIRREDGAKIETRDILNLDSTLIQPEDWVTIGRAVFEAF--DEYDGIVITHGTDTLAYTSSALSFMIRNPPIPVVLTGSMLPITEPNSDAPRNLRTALTFARKG---FP-------GIYVAFMDKIMLGTRVSKVHSLGLNAFQSINYPDIAYVKGDEVLVRHKPRIGN-GE--PLF-----DPELDPNVVHIRLTPGLSPEVLRAV-A-RATDGIVLEGYGAGGIPYRGRNLLEVVSE-T-AREKPVVMTTQALYGGVDLTRYEVGRRALEAGVIPAGDMTKEATLTKLMWALG----H---TRDLEEIRKIMERNIAGEITGS*
