C;cover size:69; local alignment length=69 (original info = d1u11a_	159	14.90	0.17	59	14	0.78)
>P1;d1u11a_
structureX:d1u11a_: 5: : 67: : : : : 
---------------------------------------------------------------------------------------VGIIMGSQSDWETMRHADALLTE-L-EIPHETLIVSAHRTPD--------RLADYARTAAER---GL-------NVIIAGAGG-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;cover size:318; local alignment length=318 (original info = d1agxa_	331	618.68	1.2e-88	310	24	100.00)
>P1;d1agxa_
structureX:d1agxa_: 3: : 330: : : : : 
-NVVIVATGGTIAGAGAS--STNSATYSAAKVPVDALIKA-VPQVNDLANITGIQALQVASESITDKELLSLARQVNDLVKKPSVNGVVITHGTD----TMEETAFFLNLVV-HTDKPIVLVGSMRPSTALSADGPLNLYSAVALASSNEAKNK-------GVMVLMNDSIFAARDVTKGINIHTHAFVSQ-WGALGTLVEGKPYWFRSSVKKHTNN--SEFNIEKIQGDALPGVQIVYGSDNMMPDAYQAFAK-AGVKAIIHAGTGNGSMANYLVPEV--RKL-HDEQGLQIVRSSRVAQGFVLRNAEQP---DDKYGWIAAHDLNPQKARLLMALALTKTNDAKEIQNMFWN---------*

C;cover size:327; local alignment length=327 (original info = d2d6fa2	352	669.43	2.2e-95	322	36	100.00)
>P1;d2d6fa2
structureX:d2d6fa2: 9: : 344: : : : : 
-DVSIISTGGTVASIIDYRTGA----V-HPAFTADDLLRAN-PELLDIANIRGRAVFNILSENMKPEYWVETARAVYGEIK-DGADGVVVAHGTD----TMHYTSAALSFMLR-TPVPVVFTGAQRSSDRPSSDASLNIQCSVRAATSE---IAEVTVCMHATMDDLSCHLHRGVKVRKMHTSRRDTFRSMNALPLAEVTPDGIKILEENYRKR-GSDELEL-----SDRVEERVAFIKSYPGISPDIIKWH-LDEGYRGIVIEGTGLGHCPDTLI---PVIGEAH-DMGVPVAMTSQCLNGRVNMNVYSTGRRLLQAGVIPCDDMLPEVAYVKMCWVLGQTDDPEMAREMMRENIAGEINER*

C;query_length:328 num_of_temps:1 cover_ratio:0.21 cover:69 not_cover:259
>P1;2017-11-04_00000053_1_72
 : : : : : : : : : 
MKLLVLGTGGTIASAKTE--MG----Y-KAALSADDILQLAGIRREDGAKIETRDILNLDSTLIQPEDWVTIGRAVFEAF--DEYDGIVITHGTD----TLAYTSSALSFMIRNPPIPVVLTGSMLPITEPNSDAPRNLRTALTFARKG---FP-------GIYVAFMDKIMLGTRVSKVHSLGLNAFQSINYPDIAYVKGDEVLVRHKPRIGN-GE--PLF-----DPELDPNVVHIRLTPGLSPEVLRAV-A-RATDGIVLEGYGAGGIPYRGRNLLEVVSE-T-AREKPVVMTTQALYGGVDLTRYEVGRRALEAGVIPAGDMTKEATLTKLMWALGHTRDLEEIRKIMERNIAGEITGS*
