C;cover size:318; local alignment length=318 (original info = d1nnsa_	326	637.42	1.5e-91	310	25	100.00)
>P1;d1nnsa_
structureX:d1nnsa_: 3: : 325: : : : : 
-NITILATGGTIAGGGDS--ATKSNYTVGKVGVENLVNA-VPQLKDIANVKGEQVVNIGSQDMNDNVWLTLAKKINTDC-DKTDGFVITHGTDTMEETAYFLDLTV-KCDKPVVMVGAMRPSTSMSADGPFNLYNAVVTAADKASANR-------GVLVVMNDTVLDGRDVTKTNTTDVATFKSVNYGPLGYIHNGKIDYQRTPARKHTS--DTPFDVSKLNELPKVGIVYNYANASDLPAKALVD-AGYDGIVSAGVGNGNLYKS---VFDTLAT-AAKTGTAVVRSSRVPTGATTQDAE---VDDAKYGFVASGTLNPQKARVLLQLALTQTKDPQQIQQIFNQ---------*

C;cover size:327; local alignment length=327 (original info = d2d6fa2	352	669.43	2.2e-95	322	36	100.00)
>P1;d2d6fa2
structureX:d2d6fa2: 9: : 344: : : : : 
-DVSIISTGGTVASIIDYRTGA---V-HPAFTADDLLRAN-PELLDIANIRGRAVFNILSENMKPEYWVETARAVYGEIKDGADGVVVAHGTDTMHYTSAALSFMLR-TPVPVVFTGAQRSSDRPSSDASLNIQCSVRAATSE---IAEVTVCMHATMDDLSCHLHRGVKVRKMHTSRRDTFRSMNALPLAEVTPDGIKILEENYRKRGSDEL-EL---SDRVEERVAFIKSYPGISPDIIKWH-LDEGYRGIVIEGTGLGHCPDTLI---PVIGEAH-DMGVPVAMTSQCLNGRVNMNVYSTGRRLLQAGVIPCDDMLPEVAYVKMCWVLGQTDDPEMAREMMRENIAGEINER*

C;query_length:328 num_of_temps:1 cover_ratio:0.97 cover:318 not_cover:10
>P1;2017-11-04_00000053_1_72
 : : : : : : : : : 
MKLLVLGTGGTIASAKTE--MG---Y-KAALSADDILQLAGIRREDGAKIETRDILNLDSTLIQPEDWVTIGRAVFEAF-DEYDGIVITHGTDTLAYTSSALSFMIRNPPIPVVLTGSMLPITEPNSDAPRNLRTALTFARKG---FP-------GIYVAFMDKIMLGTRVSKVHSLGLNAFQSINYPDIAYVKGDEVLVRHKPRIGNGE--P-LF---DPELDPNVVHIRLTPGLSPEVLRAV-A-RATDGIVLEGYGAGGIPYRGRNLLEVVSE-T-AREKPVVMTTQALYGGVDLTRYEVGRRALEAGVIPAGDMTKEATLTKLMWALGHTRDLEEIRKIMERNIAGEITGS*
