C; model_eva_score=0.862, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.865, tm_score=0.9775, gdt_score=0.9807, maxsub=0.9667.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.865, tm_score=0.9775, gdt_score=0.9807, maxsub=0.9667.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9673, gdt_score=0.9658, maxsub=0.9528.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.864, tm_score=0.9785, gdt_score=0.9792, maxsub=0.9700.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9764, gdt_score=0.9777, maxsub=0.9610.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9770, gdt_score=0.9777, maxsub=0.9691.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9862, gdt_score=0.9836, maxsub=0.9758.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9665, gdt_score=0.9702, maxsub=0.9493.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9651, gdt_score=0.9658, maxsub=0.9495.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9648, gdt_score=0.9658, maxsub=0.9477.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9683, gdt_score=0.9702, maxsub=0.9510.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9683, gdt_score=0.9702, maxsub=0.9510.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9650, gdt_score=0.9688, maxsub=0.9485.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9775, gdt_score=0.9762, maxsub=0.9674.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.864, tm_score=0.9756, gdt_score=0.9732, maxsub=0.9612.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9854, gdt_score=0.9836, maxsub=0.9751.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9765, gdt_score=0.9762, maxsub=0.9681.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.86, tm_score=0.9698, gdt_score=0.9717, maxsub=0.9542.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9812, gdt_score=0.9792, maxsub=0.9728.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C;total number of template models = 20
>P1;C00291
 : : : : : : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*
