C; model_eva_score=0.865, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.865, tm_score=1.0000, gdt_score=1.0000, maxsub=1.0000.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9775, gdt_score=0.9807, maxsub=0.9667.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9633, gdt_score=0.9628, maxsub=0.9498.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.864, tm_score=0.9754, gdt_score=0.9747, maxsub=0.9691.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9669, gdt_score=0.9658, maxsub=0.9508.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9732, gdt_score=0.9762, maxsub=0.9663.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9728, gdt_score=0.9732, maxsub=0.9579.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9636, gdt_score=0.9628, maxsub=0.9504.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9620, gdt_score=0.9613, maxsub=0.9494.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9624, gdt_score=0.9643, maxsub=0.9490.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9860, gdt_score=0.9866, maxsub=0.9768.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9860, gdt_score=0.9866, maxsub=0.9768.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9621, gdt_score=0.9628, maxsub=0.9487.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9713, gdt_score=0.9717, maxsub=0.9616.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.864, tm_score=0.9811, gdt_score=0.9821, maxsub=0.9714.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9741, gdt_score=0.9762, maxsub=0.9628.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9707, gdt_score=0.9688, maxsub=0.9613.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.86, tm_score=0.9624, gdt_score=0.9613, maxsub=0.9485.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9766, gdt_score=0.9732, maxsub=0.9655.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C;total number of template models = 20
>P1;C00291
 : : : : : : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*
