C; model_eva_score=0.862, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.865, tm_score=0.9633, gdt_score=0.9628, maxsub=0.9498.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9673, gdt_score=0.9658, maxsub=0.9528.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.865, tm_score=0.9633, gdt_score=0.9628, maxsub=0.9498.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.864, tm_score=0.9664, gdt_score=0.9658, maxsub=0.9519.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9848, gdt_score=0.9866, maxsub=0.9768.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9684, gdt_score=0.9688, maxsub=0.9512.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9635, gdt_score=0.9643, maxsub=0.9472.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9873, gdt_score=0.9851, maxsub=0.9782.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9830, gdt_score=0.9836, maxsub=0.9758.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9895, gdt_score=0.9881, maxsub=0.9803.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9759, gdt_score=0.9792, maxsub=0.9689.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9759, gdt_score=0.9792, maxsub=0.9689.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9871, gdt_score=0.9851, maxsub=0.9754.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9756, gdt_score=0.9717, maxsub=0.9597.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.864, tm_score=0.9651, gdt_score=0.9658, maxsub=0.9499.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9638, gdt_score=0.9658, maxsub=0.9461.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9664, gdt_score=0.9643, maxsub=0.9462.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.86, tm_score=0.9819, gdt_score=0.9836, maxsub=0.9745.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9638, gdt_score=0.9628, maxsub=0.9468.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C;total number of template models = 20
>P1;C00291
 : : : : : : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*
