C; model_eva_score=0.864, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.865, tm_score=0.9754, gdt_score=0.9747, maxsub=0.9691.
>P1;meta_hg4.pdb1
structureX:meta_hg4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9785, gdt_score=0.9792, maxsub=0.9700.
>P1;meta_multicom9.pdb1
structureX:meta_multicom9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9664, gdt_score=0.9658, maxsub=0.9519.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.865, tm_score=0.9754, gdt_score=0.9747, maxsub=0.9691.
>P1;meta_ss4.pdb1
structureX:meta_ss4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9677, gdt_score=0.9702, maxsub=0.9521.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9848, gdt_score=0.9866, maxsub=0.9757.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9754, gdt_score=0.9762, maxsub=0.9607.
>P1;meta_csblast5.pdb1
structureX:meta_csblast5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9668, gdt_score=0.9658, maxsub=0.9530.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9702, gdt_score=0.9702, maxsub=0.9556.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.863, tm_score=0.9670, gdt_score=0.9673, maxsub=0.9539.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9644, gdt_score=0.9643, maxsub=0.9518.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9644, gdt_score=0.9643, maxsub=0.9518.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.862, tm_score=0.9673, gdt_score=0.9643, maxsub=0.9539.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9780, gdt_score=0.9777, maxsub=0.9701.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.864, tm_score=0.9732, gdt_score=0.9762, maxsub=0.9652.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9794, gdt_score=0.9821, maxsub=0.9683.
>P1;meta_multicom10.pdb1
structureX:meta_multicom10.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9780, gdt_score=0.9777, maxsub=0.9684.
>P1;meta_multicom2.pdb1
structureX:meta_multicom2.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.86, tm_score=0.9745, gdt_score=0.9732, maxsub=0.9575.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C; model_eva_score=0.861, tm_score=0.9790, gdt_score=0.9762, maxsub=0.9655.
>P1;meta_multicom5.pdb1
structureX:meta_multicom5.pdb: 1: : 168: : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*

C;total number of template models = 20
>P1;C00291
 : : : : : : : : : 
HEEGNDVRRNFDVSKISGYWYSVLLASDVREKTEENSSMRVFVNHIEVLSNSSLLFNMHIKVDGKCTEIALVSDKTEKDGEYSVEYDGYNVFRIVETDYTDYIIFHLVNFKEKDSFQMMELSAREPDTSEEVRKRFVEYCQKHGIVKENIFDLTEVDRCLQARGSEKA*
