C; model_eva_score=0.149, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 131: : : : : 
AAPTTPGAGAPCAACKFLRRKCLPGCVFAPYFPPEEPQKFANVHKVFGASNVTKLLNELPPHQREDAVSSLAYEAEARVKDPVYGCVGAISVLQRQVHRLQKELDAAHTELLRYACGELGGIPTALPVVTA*

C; model_eva_score=0.153, tm_score=0.5742, gdt_score=0.5420, maxsub=0.4706.
>P1;meta_super8.pdb1
structureX:meta_super8.pdb: 50: : 113: : : : : 
-------------------------------------------------SNVTKLLNELPPHQREDAVSSLAYEAEARVKDPVYGCVGAISVLQRQVHRLQKELDAAHTELLR------------------*

C;total number of template models = 2
>P1;C00331
 : : : : : : : : : 
AAPTTPGAGAPCAACKFLRRKCLPGCVFAPYFPPEEPQKFANVHKVFGASNVTKLLNELPPHQREDAVSSLAYEAEARVKDPVYGCVGAISVLQRQVHRLQKELDAAHTELLRYACGELGGIPTALPVVTA*
