C;cover size:509; local alignment length=509 (original info = 2JG7A	509	1235.53	0	0)
>P1;2JG7A
structureN:2JG7A: 1: : 509: : : :6.0: 
-S-------------GL-------L---------------------INQP------K---------------Y-------------SW-------------L-K--EL---------G-----L-S-E-D-----N-PG-----------V-------YNGSW---------G-G---SG-EVI-TSYCPA-N-N-E-PI-ARV---------TQATLAEYEETVQKTREAWK-----M--WADIP-APKRGEIVRQIGDALR-K-K-IKVLGSLVSLEMGKIYVEGV-G-EVQE----YVDVCDYAVG----LS-RM-I----GG-P----V--L---P---------S-----E-------R--------P----G-HALIEQWNPVGLVGIITAFNFPVAV--YGWNNAIALTCGNVCLWKGAPTTPLTSVAVTKIVAEVLEQ-NNLPGAICSMTCG----G---A-D-IGTAMAKDERVDLLSFTGSTHVGKMVAMM--------VQ------E------R------F------GRKLL--ELGGNNAIIVFEDA---D-----LNLV--VPS-AVFASVGTAGQRCTTTR-RLM-LHE---------SVH-DAVVERIAKA-YKQ---------------VRIGD-P-W-DP-STLYGPLHTKQAVDQYLAAIEQAK--QQGGT-LVC-GGKV-M----D--------R----PGNYVEPTII--T---G-LAHDA---PIVHTETFVPILYVLKF--K--T------EE-EA-FAWN-NE-VQ---QGLSSSIFTK--D-LGRVFRWLGPKGSD--CGIVNVNI-P-T-S----------G---A---------EI---G-GAFGGE--KHTGG-G--RE--SG-S-DS-WKQYMRRSTCTINYSK---DL--P---LAQ------GI-KF-*

C;cover size:497; local alignment length=497 (original info = 2J6LA	497	1200.78	0	1)
>P1;2J6LA
structureX:2J6LA: 1: : 497: : : :1.3: 
---------------TL-------L---------------------INQP------Q---------------Y-------------AW-------------L-K--EL---------G-----L-R-E-E-----N-EG-----------V-------YNGSW---------G-G---RG-EVI-TTYCPA-N-N-E-PI-ARV---------RQASVADYEETVKKAREAWK-----I--WADIP-APKRGEIVRQIGDALR-E-K-IQVLGSLVSLEMGKILVEGV-G-EVQE----YVDICDYAVG----LS-RM-I----GG-P----I--L---P---------S-----E-------R--------S----G-HALIEQWNPVGLVGIITAFNFPVAV--YGWNNAIAMICGNVCLWKGAPTTSLISVAVTKIIAKVLED-NKLPGAICSLTCG----G---A-D-IGTAMAKDERVNLLSFTGSTQVGKQVGLM--------VQ------E------R------F------GRSLL--ELGGNNAIIAFEDA---D-----LSLV--VPS-ALFAAVGTAGQRCTTAR-RLF-IHE---------SIH-DEVVNRLKKA-YAQ---------------IRVGN-P-W-DP-NVLYGPLHTKQAVSMFLGAVEEAK--KEGGT-VVY-GGKV-M----D--------R----PGNYVEPTIV--T---G-LGHDA---SIAHTETFAPILYVFKF--Q--N------EE-EV-FAWN-NE-VK---QGLSSSIFTK--D-LGRIFRWLGPKGSD--CGIVNVNI-P-T-S----------G---A---------EI---G-GAFGGE--KHTGG-G--RE--SG-S-DA-WKQYMRRSTCTINYS---------------------------*

C;cover size:486; local alignment length=486 (original info = 1T90A	484	1170.42	0	2)
>P1;1T90A
structureX:1T90A: 1: : 484: : : :2.50: 
---------------------------------------------------------------------------------------------------------------------------E-I-R-K-----L-KN-----------Y-------INGEW---------V-ESK-TD-QYE-DVVNPA-T-K-E-VL-CQV---------PISTKEDIDYAAQTAAEAFK-----T--WSKVA-VPRRARILFNFQQLLS-Q-H-KEELAHLITIENGKNTKEAL-G-EVGR----GIENVEFAAG----AP-SL-M----MG-D----S--L---A---------S-----I-------A--------T----D-VEAANYRYPIGVVGGIAPFNFPMMV--PCWMFPMAIALGNTFILKPSERTPLLTEK----LVELFEK-AGLPKGVFNVVYG----A---H-D-VVNGILEHPEIKAISFVGSKPVGEYVYKK--------GS------E------N------L------KRVQS--LTGAKNHTIVLNDA---N-----LEDT--VTN-IVGAAFGSAGERCMACA-VVT-VEE---------GIA-DEFMAKLQEK-VAD---------------IKIGN-G-L-DD-GVFLGPVIREDNKKRTLSYIEKGL--EEGAR-LVC-DGRE-N----VS-------D----DGYFVGPTIF--D---N-VTTEM---TIWKDEIFAPVLSVIRV--K--N------LK-EA-IEIA-NK-SE---FANGACLFTS--N-SNAIRYF--RENID--AGMLGINL-G-V-P----------A---P---------MA---F-FPFSGW--KSSFF-GTLHA--NG-K-DS-VDFYTRKKVVTARYPA---PD------F--------------*

C;cover size:480; local alignment length=480 (original info = 1EUHA	474	1157.37	0	3)
>P1;1EUHA
structureX:1EUHA: 1: : 474: : : :1.82: 
-----------------------------------------------------------------------------------------------------------------------------T-K-Q-----Y-KN-----------Y-------VNGEW---------K-L---SE-NEI-KIYEPA-S-G-A-EL-GSV---------PAMSTEEVDYVYASAKKAQP-----A--WRALS-YIERAAYLHKVADILM-R-D-KEKIGAILSKEVAKGYKSAV-S-EVVR----TAEIINYAAE----EG-LR-M----EG-E----V--L---E---------GGSFEAA-------S--------K----K-KIAVVRREPVGLVLAISPFNYPVNL--AGSKIAPALIAGNVIAFKPPTQGSISGLL----LAEAFAE-AGLPAGVFNTITGR---G---S-E-IGDYIVEHQAVNFINFTGSTGIGERIGKM--------AG--------------------M------RPIML--ELGGKDSAIVLEDA---D-----LELT--AKN-IIAGAFGYSGQRCTAVK-RVL-VME---------SVA-DELVEKIREK-VLA---------------LTIGN-P-E-D--DADITPLIDTKSADYVEGLINDAN--DKGAT-ALT-EIKR--------------------EGNLICPILF--D---K-VTTDM---RLAWEEPFGPVLPIIRV--T--S------VE-EA-IEIS-NK-SE---YGLQASIFTN--D-FPRAFGI--AEQLE--VGTVHINN-K-T-Q----------R---G---------TD---N-FPFLGA--KKSGA-G--IQ--GV-K-YS-IEAMTTVKSVVFDIK---------------------------*

C;cover size:504; local alignment length=504 (original info = 1A4SA	503	1151.91	0	4)
>P1;1A4SA
structureX:1A4SA: 1: : 503: : : :2.1: 
-A-------------QL-------V---------------------DSMP------S---------------A-------------ST------------------GS---------V-----V-V-T-D-----D-LN-----------Y-------WGGRR---------I-KSK-DG-ATTEPVFEPA-T-G-R-VL-CQM---------VPCGAEEVDQAVQSAQAAYL-----K--WSKMA-GIERSRVMLEAARIIR-E-R-RDNIAKLEVINNGKTITEAE-Y-DIDA----AWQCIEYYAG----LA-PT-L----SG-Q----H--I---Q---------L-----P----------------G----G-AFAYTRREPLGVCAGILAWNYPFMI--AAWKCAPALACGNAVVFKPSPMTPVTGVI----LAEIFHE-AGVPVGLVNVVQG----G---A-E-TGSLLCHHPNVAKVSFTGSVPTGKKVMEM--------SA------K------T------V------KHVTL--ELGGKSPLLIFKDC---E-----LENA--VRG-ALMANFLTQGQVCTNGT-RVF-VQR---------EIM-PQFLEEVVKR-TKA---------------IVVGD-P-L-LT-ETRMGGLISKPQLDKVLGFVAQAK--KEGAR-VLC-GGEP-L----TPSDPKL--K----NGYFMSPCVL--D---N-CRDDM---TCVKEEIFGPVMSVLPF--D--T------EE-EV-LQRA-NN-TT---FGLASGVFTR--D-ISRAHRV--AANLE--AGTCYINT-Y-S-I--------------S---------PV---E-VPFGGY--KMSGF-G--RE--NG-Q-AT-VDYYSQLKTVIVEMGD---VD--S---LF-------------*

C;cover size:499; local alignment length=499 (original info = 1BXSA	494	1144.35	0	5)
>P1;1BXSA
structureX:1BXSA: 1: : 494: : : :2.35: 
------------------------D---------------------VP--------------------------------------AP-------------L-T--NL---------Q-------F-K-Y-----T-KI-----------F-------INNEW---------H-SSV-SG-KKF-PVFNPA-T-E-E-KL-CEV---------EEGDKEDVDKAVKAARQAFQIGS--P--WRTMD-ASERGRLLNKLADLIE-R-D-RLLLATMEAMNGGKLFSNAYLM-DLGG----CIKTLRYCAG----WA-DK-I----QG-R----T--I---P---------M-------------D--------G----N-FFTYTRSEPVGVCGQIIPWNFPLLM--FLWKIGPALSCGNTVVVKPAEQTPLTALHMG----SLIKE-AGFPPGVVNIVPGY---G---P-T-AGAAISSHMDVDKVAFTGSTEVGKLIKEA--------AG------KS-----N------L------KRVSL--ELGGKSPCIVFADA---D-----LDNA--VEF-AHQGVFYHQGQCCIAAS-RLF-VEE---------SIY-DEFVRRSVER-AKK---------------YVLGN-P-L-TP-GVSQGPQIDKEQYEKILDLIESGK--KEGAK-LEC-GGGP-W----G--------N----KGYFIQPTVF--S---D-VTDDM---RIAKEEIFGPVQQIMKF--K--S------LD-DV-IKRA-NN-TF---YGLSAGIFTN--D-IDKAITV--SSALQ--SGTVWVNC-Y-S------------V---V---------SA---Q-CPFGGF--KMSGN-G--RE--LG-E-YG-FHEYTEVKTVTIKISQ---KN--S------------------*

C;cover size:478; local alignment length=478 (original info = 1WNDA	474	1149.33	0	6)
>P1;1WNDA
structureX:1WNDA: 1: : 474: : : :2.10: 
-------------------------------------------------------------------------------------------------------------------------------M-Q-----H-KL-----------L-------INGEL---------V-SG--EG-EKQ-PVYNPA-T-G-D-VL-LEI---------AEASAEQVDAAVRAADAAFA-----E--WGQTT-PKVRAECLLKLADVIE-E-N-GQVFAELESRNCGKPLHSAFND-EIPA----IVDVFRFFAG----AA-RC-L----NG-L----A--A---G---------E-----Y-------L--------E----G-HTSMIRRDPLGVVASIAPWNYPLMM--AAWKLAPALAAGNCVVLKPSEITPLTALKLAELA-----K-DIFPAGVVNILFGR---G---K-T-VGDPLTGHPKVRMVSLTGSIATGEHIISH--------TA------S------S------I------KRTHM--ELGGKAPVIVFDDA---D-----IEAV--VEG-VRTFGYYNAGQDCTAAC-RIY-AQK---------GIY-DTLVEKLGAA-VAT---------------LKSGA-P-D-DE-STELGPLSSLAHLERVGKAVEEAK--ATGHI-KVITGGEK-R----K--------G----NGYYYAPTLL--A---G-ALQDD---AIVQKEVFGPVVSVTPF--D--N------EE-QV-VNWA-ND-SQ---YGLASSVWTK--D-VGRAHRV--SARLQ--YGCTWVNT-H-F-M--------------L---------VS---E-MPHGGQ--KLSGY-G--KD--MS-L-YG-LEDYTVVRHVMVKH----------------------------*

C;cover size:509; local alignment length=509 (original info = 1KY8A	499	1151.67	0	7)
>P1;1KY8A
structureX:1KY8A: 1: : 499: : : :2.40: 
---------------AG-------L---------------------LE--------------------------------------GV-------------I-K--EK---------G-----G-V-P-V-----Y-PS-----------Y-------LAGEW---------G-G---SG-QEI-EVKSPI-D-L-A-TI-AKV---------ISPSREEVERTLDVLFKRGRW----S--ARDMP-GTERLAVLRKAADIIE-R-N-LDVFAEVLVMNAGKPKSAAV-G-EVKA----AVDRLRLAEL----DL-KK-I----GG-D----Y--I---P---------G-----D-------WTYDT----L----E-TEGLVRREPLGVVAAITPFNYPLFD--AVNKITYSFIYGNAVVVKPSISDPLPAAM----AVKALLD-AGFPPDAIALLNL----P---G-K-EAEKIVADDRVAAVSFTGSTEVGERVVKV--------GG--------------------V------KQYVM--ELGGGDPAIVLEDA---D-----LDLA--ADK-IARGIYSYAGQRCDAIK-LVL-AER---------PVY-GKLVEEVAKR-LSS---------------LRVGD-P-R-DP-TVDVGPLISPSAVDEMMAAIEDAV--EKGGR-VLA-GGRR-L------------------GPTYVQPTLV--EAPAD-RVKDM---VLYKREVFAPVASAVEV--K--D------LD-QA-IELA-NG-RP---YGLDAAVFGR--D-VVKIRRA--VRLLE--VGAIYIND-M-P-R----------H---G---------IG---Y-YPFGGR--KKSGV-F--RE--GI-G-YA-VEAVTAYKTIVFNYKG---KG--V---WK-----------YE*

C;cover size:499; local alignment length=499 (original info = 1O9JA	494	1142.24	0	8)
>P1;1O9JA
structureX:1O9JA: 1: : 494: : : :2.4: 
------------------------D---------------------LPAP---------------------------------------------------L-T--NI---------K-------I-Q-H-----T-KL-----------F-------INNEW---------H-ESV-SG-KTF-PVFNPA-T-E-E-KI-CEV---------EEADKEDVDKAVKAAREAFQMGS--P--WRTMD-ASERGQLIYKLADLIE-R-D-RLLLATLESINAGKVFASAYLM-DLDY----CIKALRYCAG----WA-DK-I----QG-R----T--I---P---------V-----D----------------G----E-FFSYTRHEPIGVCGLIFPWNAPMIL--LACKIGPALCCGNTVIVKPAEQTPLTALHVA----SLIKE-AGFPPGVVNIVPGY---G---P-T-AGAAISSHMDVDKVAFTGSTEVGKMIQEA--------AA------KS-----N------L------KRVTL--ELGAKNPCIVFADA---D-----LDSA--VEF-AHQGVFTNQGQSCIAAS-KLF-VEE---------AIY-DEFVQRSVER-AKK---------------YVFGN-P-L-TP-GVNHGPQINKAQHNKIMELIESGK--KEGAK-LEC-GGGP-W----G--------N----KGYFIQPTVF--S---N-VTDDM---RIAKEEIFGPVQQIMKF--K--S------LD-EV-IKRA-NN-TY---YGLVAGVFTK--D-LDKAVTV--SSALQ--AGTVWVNC-Y-L------------A---A---------SA---Q-SPAGGF--KMSGH-G--RE--MG-E-YG-IHEYTEVKTVTMKISE---KN--S------------------*

C;cover size:499; local alignment length=499 (original info = 1O04A	494	1141.09	0	9)
>P1;1O04A
structureX:1O04A: 1: : 494: : : :1.42: 
------------------------A---------------------VPAP------N----------------------------------------------Q--Q----------P-----E-V-F-C-----N-QI-----------F-------INNEW---------H-DAV-SR-KTF-PTVNPS-T-G-E-VI-CQV---------AEGDKEDVDKAVKAARAAFQLGS--P--WRRMD-ASHRGRLLNRLADLIE-R-D-RTYLAALETLDNGKPYVISYLV-DLDM----VLKCLRYYAG----WA-DK-Y----HG-K----T--I---P---------I-------------D--------G----D-FFSYTRHEPVGVCGQIIPWNFPLLM--QAWKLGPALATGNVVVMKVAEQTPLTALYVA----NLIKE-AGFPPGVVNIVPGF---G---P-T-AGAAIASHEDVDKVAFTGSTEIGRVIQVA--------AGS-----S------N------L------KRVTL--ELGGKSPNIIMSDA---D-----MDWA--VEQ-AHFALFFNQGQCSCAGS-RTF-VQE---------DIY-DEFVERSVAR-AKS---------------RVVGN-P-F-DS-KTEQGPQVDETQFKKILGYINTGK--QEGAK-LLC-GGGI-A----A--------D----RGYFIQPTVF--G---D-VQDGM---TIAKEEIFGPVMQILKF--K--T------IE-EV-VGRA-NN-ST---YGLAAAVFTK--D-LDKANYL--SQALQ--AGTVWVNC-Y-D------------V---F---------GA---Q-SPFGGY--KMSGS-G--RE--LG-E-YG-LQAYTEVKTVTVKVPQ---KN--S------------------*

C;cover size:500; local alignment length=500 (original info = 3EK1A	485	1127.67	0	10)
>P1;3EK1A
structureN:3EK1A: 1: : 485: : : :6.0: 
GS-------------ML-------A---------------------LKDP------S------------------------------------------------------------------L---L-K-----S-QC-----------L-------VNGRW---------I-DAA-DG-TTI-KVTNPA-D-G-S-VI-GTV---------PSLSVATIKEAIDASAKALS-----G--WAAKT-AKERAGILRKWFDLII-A-N-ADDIALIMTSEQGKPLAEAR-G-EVLY----AASFIEWFAE----EA-KR-V----YG-D----T--I---P---------A-----P-------Q--------N----G-QRLTVIRQPVGVTAAITPWNFPAAM--ITRKAAPALAAGCTMIVRPADLTPLTALA----LGVLAEK-AGIPAGVLQIVTGK---A---R-E-IGAELTSNDTVRKLSFTGSTEVGRLLMAQ--------CA------P------T------I------KRISL--ELGGNAPFIVFDDA---D-----LDAA--VDG-AMVSKYRNAGQTCVCAN-RIY-VQR---------GVY-DKFAEKLAAK-VKE---------------LKVGN-G-T-EP-GVVIGPMIEEKAITKVKAHIEDAV--SKGAK-LIT-GGKE-L------------------GGLFFEPGIL--T---G-VTSDM---LVAKEETFGPLAPLFAF--D--T------EE-EV-IAQA-ND-TI---FGLAAYFYTE--N-FSRAIRV--SEALE--YGMVGHNT-G-L-I--------------S---------NE---V-APFGGV--KQSGL-G--RE--GS-K-YG-IEEYLETKYICSAYKR--------------------------*

C;cover size:498; local alignment length=498 (original info = 1UZBA	516	1129.25	0	11)
>P1;1UZBA
structureX:1UZBA: 1: : 516: : : :1.4: 
MT-------------VEP------F---------------------RNEP------IETFQTEEARRAMREAL-------------RR-------------V-R--E----------E-----F-G-R-H-----Y-PL-----------Y-------IGGEW---------V-D---TKERMV-SLNPSA-P-S-E-VV-GTT---------AKAGKAEAEAALEAAWKAFK-----T--WKDWP-QEDRSRLLLKAAALMR-R-R-KRELEATLVYEVGKNWVEAS-A-DVAE----AIDFIEYYAR----AA-LR-Y----RY-P----A--V---E---------V-----VP------Y--------P----G-EDNESFYVPLGAGVVIAPWNFPVAI--FTGMIVGPVAVGNTVIAKPAEDAVVVGAK----VFEIFHE-AGFPPGVVNFLPGV---G---E-E-VGAYLVEHPRIRFINFTGSLEVGLKIYEA--------AG------RLAPGQTW------F------KRAYV--ETGGKNAIIVDETA---D-----FDLA--AEG-VVVSAYGFQGQKCSAAS-RLI-LTQ---------GAY-EPVLERVLKR-AER---------------LSVGP---A-EE-NPDLGPVVSAEQERKVLSYIEIGK--NEGQL-VLG-GKR--L----E--------G----EGYFIAPTVF--T---E-VPPKA---RIAQEEIFGPVLSVIRV--K--D------FA-EA-LEVA-ND-TP---YGLTGGVYSR--K-REHLEWA--RREFH--VGNLYFNR-K-I-T----------G---AL--------VG---V-QPFGGF--KLSGT-N--AK--TGAL-DY-LRLFLEMKAVAERF----------------------------*

C;cover size:504; local alignment length=504 (original info = 3ED6A	502	1118.02	0	12)
>P1;3ED6A
structureN:3ED6A: 1: : 501: : : :6.0: 
------------------------------------------------YF------Q---------------S-------------NA-------------M-E--LL---------K-------H-L-S-----Q-RQ-----------Y-------IDGEW---------V-ESA-NK-NTR-DIINPY-N-Q-E-VI-FTV---------SEGTKEDAERAILAARRAFE-----SGEWSQET-AETRGKKVRAIADKIK-E-H-REALARLETLDTGKTLEESY-A-DMDD----IHNVFMYFAG----LA-DK-D----GG-E----M--I---D---------S-----P-------I--------P----D-TESKIVKEPVGVVTQITPWNYPLLQ--ASWKIAPALATGCSLVMKPSEITPLTTIR----VFELMEE-VGFPKGTINLILGA---G---S-E-VGDVMSGHKEVDLVSFTGGIETGKHIMKN--------AA------N------N------V------TNIAL--ELGGKNPNIIFDDA---D-----FELA--VDQ-ALNGGYFHAGQVCSAGS-RIL-VQN---------SIK-DKFEQALIDR-VKK---------------IKLGN-G-F-DA-DTEMGPVISTEHRNKIESYMDVAK--AEGAT-IAV-GGKR-P----DRDDL----K----DGLFFEPTVI--T---N-CDTSM---RIVQEEVFGPVVTVEGF--E--T------EQ-EA-IQLA-ND-SI---YGLAGAVFSK--D-IGKAQRV--ANKLK--LGTVWIND-F-H------------P---Y---------FA---Q-APWGGY--KQSGI-G--RE--LG-K-EG-LEEYLVSKHILTNTNP---QL--V------------NW--FS*

C;cover size:508; local alignment length=508 (original info = 2D4EA	513	1116.85	0	13)
>P1;2D4EA
structureX:2D4EA: 5: : 513: : : :2.10: 
VA-------------GISWE----T---------------------IEEV------R-----------------------------RR-------------L-K---------------------E-R-P-----A-LH-----------F-------IAGEF---------V-PSE-SG-ETF-PSLDPA-T-N-E-VL-GVA---------ARGGEREVDRAAKAAHEAFQ-----R--WSRTK-AKERKRYLLRIAELIE-K-H-ADELAVMECLDAGQVLRIVR-A-QVAR----AAENFAFYAE----YA-EHAM----ED-R----T--F---P---------V-------------D--------R----D-WLYYTVRVPAGPVGIITPWNAPLML--STWRIAPALAFGNTVVLKPAEWSPFTATKL----AEILKE-ADLPPGVFNLVQGF---G---E-E-AGAALVAHPLVPLLTLTGETETGKIVMRN--------AA------D------H------L------KRLSP--ELGGKSPALVFADA---D-----LERA--LDA-VVFQIFSFNGERCTASS-RLL-VEE---------KIF-EDFVGKVVER-ARA---------------IRVGH-P-L-DP-ETEVGPLIHPEHLQRVLGYVEAGK--REGAR-LLV-GGER-A----KTSFRGEDLS----RGNYLLPTVF--V---G-EN-HM---KIAQEEIFGPVLVAIPF--K--D------EE-EA-LRKA-ND-TK---YGLAAYVFTR--D-LERAHRL--ALELE--AGMVYLNS-H-N------------V---R---------HL---P-TPFGGV--KGSGD-R--RE--GG-T-YA-LDFYTDLKTIALPLRP---PH--V---PKF------GK----*

C;cover size:480; local alignment length=480 (original info = 2IMPA	476	1120.73	0	14)
>P1;2IMPA
structureX:2IMPA: 1: : 476: : : :2.10: 
---------------------------------------------------------------------------------------------------------------------------V-P-V-Q-----H-PM-----------Y-------IDGQF---------V-TWR-GD-AWI-DVVNPA-T-E-A-VI-SRI---------PDGQAEDARKAIDAAERAQP-----E--WEALP-AIERASWLRKISAGIR-E-R-ASEISALIVEEGGKIQQLAE-V-EVAF----TADYIDYMAE----WA-RR-Y----EG-E----I--I---Q---------S-----D-------R--------P----G-ENILLFKRALGVTTGILPWNFPFFL--IARKMAPALLTGNTIVIKPSEFTPNNAIAF----AKIVDE-IGLPRGVFNLVLGR---G---E-T-VGQELAGNPKVAMVSMTGSVSAGEKIMAT--------AA------K------N------I------TK-VL--ELGGKAPAIVMDDA---D-----LELA--VKA-IVDSRVINSGQVCNCAE-RVY-VQK---------GIY-DQFVNRLGEA-MQA---------------VQFGN-P-A-ERNDIAMGPLINAAALERVEQKVARAV--EEGAR-VAF-GGKA-V----E--------G----KGYYYPPTLL--L---D-VRQEM---SIMHEETFGPVLPVVAF--D--T------LE-DA-ISMA-ND-SD---YGLTSSIYTQ--N-LNVAMKA--IKGLK--FGETYINR-E-N------------F---E---------AM---Q-GFHAGW--RKSGI-G--GA--DG-K-HG-LHEYLQTQVVYLQS----------------------------*

C;cover size:488; local alignment length=488 (original info = 2VE5A	489	1116.62	0	15)
>P1;2VE5A
structureN:2VE5A: 1: : 489: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------A-----R-F-E-E-----Q-KL-----------Y-------IGGRY---------V-EAS-SG-ATF-ETINPA-N-G-E-VL-AKV---------QRASREDVERAVQSAVEGQK-----V--WAAMT-AMQRSRILRRAVDILR-E-R-NDELAALETLDTGKPLAETR-SVDIVT----GADVLEYYAG----LV-PA-I----EG-E----Q--I---P---------L-----R----------------E----T-SFVYTRREPLGVVAGIGAWNYPVQI--ALWKSAPALAAGNAMIFKPSEVTPLTALKLA----EIYTE-AGVPDGVFNVLTGS---G---R-E-VGQWLTEHPLIEKISFTGGTSTGKKVMAS--------AS------SS-----S------L------KEVTM--ELGGKSPLIIFPDA---D-----LDRA--ADI-AVMANFFSSGQVCTNGT-RVF-IHR---------SQQ-ARFEAKVLER-VQR---------------IRLGD-P-Q-DE-NTNFGPLVSFPHMESVLGYIESGK--AQKAR-LLC-GGER-V----T--------DGAFGKGAYVAPTVF--T---D-CRDDM---TIVREEIFGPVMSILVY--D--D------ED-EA-IRRA-ND-TE---YGLAAGVVTQ--D-LARAHRA--IHRLE--AGICWINT-W-G------------E---S---------PA---E-MPVGGY--KQSGV-G--RE--NG-L-TT-LAHYTRIKSVQVELGD---YA--S---VF-------------*

C;cover size:485; local alignment length=485 (original info = 3B4WA	483	1115.68	0	16)
>P1;3B4WA
structureN:3B4WA: 1: : 483: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------S-----A-T-E-Y-----D-KL-----------F-------IGGKW---------T-KPS-TS-DVI-EVRCPA-T-G-E-YV-GKV---------PMAAAADVDAAVAAARAAFD-----NGPWPSTP-PHERAAVIAAAVKMLA-E-R-KDLFTKLLAAETGQPPTIIE-TMHWMG----SMGAMNYFAG----AA-DK-V----TW-T----E--T---R---------T-------------G--------S----Y-GQSIVSREPVGVVGAIVAWNVPLFL--AVNKIAPALLAGCTIVLKPAAETPLTANA----LAEVFAE-VGLPEGVLSVVPG----G---I-E-TGQALTSNPDIDMFTFTGSSAVGREVGRR--------AA------E------M------L------KPCTL--ELGGKSAAIILEDV---D-----LAAA--IPM-MVFSGVMNAGQGCVNQT-RIL-APR---------SRY-DEIVAAVTNF-VTA---------------LPVGP-P-S-DP-AAQIGPLISEKQRTRVEGYIAKGI--EEGAR-LVC-GGGR-P----EGL------D----NGFFIQPTVF--A---D-VDNKM---TIAQEEIFGPVLAIIPY--D--T------EE-DA-IAIA-ND-SV---YGLAGSVWTT--D-VPKGIKI--SQQIR--TGTYGINW-Y--------------A---F---------DP---G-SPFGGY--KNSGI-G--RE--NG-P-EG-VEHFTQQKSVLLPMGY---TV---------------------*

C;cover size:498; local alignment length=498 (original info = 4PXNA	498	1113.13	0	17)
>P1;4PXNA
structureN:4PXNA: 1: : 498: : : :6.0: 
------------------------------------------------KE------E---------------H-------------QF-------------L-A--EL---------G-----L-A-Q-R-----NPGA-----------F-------ACGAW---------G-G---SG-PTV-TSTSPT-N-N-Q-VI-AEV---------VEASVHDYEEGMRACFDAAK-----T--WMAIP-APKRGEIVRQIGDALR-A-K-LHHLGRLVSLEMGKILPEGI-G-EVQE----IIDMCDYAVG----LS-RQ-L----NG-S----I--I---P---------S-----E-------R--------P----N-HMMMEVWNPLGVVGVITAFNFPCAV--LGWNACIALVCGNCVVWKGAPTTPLITIAMTKIVASVLEK-NNLPGAIFTSFCG----G---T-E-IGQAIALDIRIPLVSFTGSTRAGLMVQQQ--------VS------A------R------F------GKCLL--ELSGNNAIIVMDDA---D-----IQLA--VRS-VLFAAVGTAGQRCTTCR-RLI-LHE---------NIY-QTFLDQLVEV-YKQ---------------VRIGD-P-L-EK-GTLLGPLHTPASKENFLKGIQTIK--SQGGK-ILF-GGSA-I----E--------S----EGNFVQPTIV--E-----ITPSA---PVVKEELFGPVLYVMKF--Q--T------LK-EA-IEIN-NS-VP---QGLSSSIFTK--R-PDIIFKWLGPHGSD--CGIVNVNI-P-T-N----------G---A---------EI---G-GAFGGE--KATGG-G--RE--AG-S-DS-WKQYMRRATCTINYGS---EL--P---LA-------------*

C;cover size:486; local alignment length=486 (original info = 3JZ4A	481	1091.25	0	18)
>P1;3JZ4A
structureN:3JZ4A: 1: : 481: : : :6.0: 
---------------------------------------------------------------------------------------K-------------L-N--DS---------N-----L---F-R-----Q-QA-----------L-------INGEW---------L-DAN-NG-EAI-DVTNPA-N-G-D-KL-GSV---------PKMGADETRAAIDAANRALP-----A--WRALT-AKERATILRNWFNLMM-E-H-QDDLARLMTLEQGKPLAEAK-G-EISY----AASFIEWFAE----EG-KR-I----YG-D----T--I---P---------G-----H-------Q--------A----D-KRLIVIKQPIGVTAAITPWNFPAAM--ITRKAGPALAAGCTMVLKPASQTPFSALALAELA----IR-AGVPAGVFNVVTGS---A---G-A-VGNELTSNPLVRKLSFTGSTEIGRQLMEQ--------CA------K------D------I------KKVSL--ELGGNAPFIVFDDA---D-----LDKA--VEG-ALASKFRNAGQTCVCAN-RLY-VQD---------GVY-DRFAEKLQQA-MSK---------------LHIGD-G-L-DN-GVTIGPLIDEKAVAKVEEHIADAL--EKGAR-VVC-GGKA-H----E--------R----GGNFFQPTIL--V---D-VPANA---KVSKEETFGPLAPLFRF--K--D------EA-DV-IAQA-ND-TE---FGLAAYFYAR--D-LSRVFRV--GEALE--YGIVGINT-G-I------------I---S---------NE---V-APFGGI--KASGL-G--RE--GS-K-YG-IEDYLEIKYMCIGL----------------------------*

C;cover size:488; local alignment length=488 (original info = 4ZZ7A	489	1093.17	0	19)
>P1;4ZZ7A
structureN:4ZZ7A: 1: : 489: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------M-T-T-----I-GH-----------L-------INGQL---------V-TE--NT-RSQ-NVFNPA-T-G-E-IG-KQL---------DLASTKTVEQAISAAQHAFP-----T--WRNTP-PLKRARVMFRFKELLE-Q-H-ADEICRLIGEEHGKIAHDAM-G-ELQR----GIENVEYACG----AP-EL-L----KG-E----H--S---R---------N-----V-------G--------P----G-IDSWSEFQPMGVVAGITPFNFPVMV--PLWMFPMAIVCGNCFVLKPSERDPSSTLYIAQLL----QE-AGLPDGVMNVVNG----D---K-E-AVDALLHDDRVKAVSFVGSTPIAEYIYRT--------AS------A------N------G------KRCQA--LGGAKNHAIVMPDA---D-----MDNA--VNQ-LLGAAFGSSGERCMALSVAVA-VGD---------AAG-DALVSKMTQA-MQK---------------LKVGP-S-T-DS-GNDFGPVITRQHQEKVIGYINSAE--QQGAT-IVV-DGRQ-PKVPNH--------E----NGFFVGGTLI--D---H-VTPEM---TSYQEEIFGPVLQVVRV--A--T------MQ-DA-MDLI-DA-HE---YGNGTCIFTR--D-GEAARYF--SDNIQ--VGMVGINI-P-L-P----------V---P---------VA---Y-HSFGGW--KRSLF-GDLHA--YG-P-DA-VRFYTKRKTVTQRWPS---AG------VRE------G-----*

C;cover size:495; local alignment length=495 (original info = 4A0MA	494	1085.49	0	20)
>P1;4A0MA
structureN:4A0MA: 1: : 493: : : :6.0: 
-----------------------------------------------------------------------------------------------------------F---------P-----I---P-A-----R-QL-----------F-------IDGEW---------R-EPI-KK-NRI-PVINPS-T-E-E-II-GDI---------PAATAEDVEVAVVAARRAFRRN---N--WSATS-GAHRATYLRAIAAKIT-E-K-KDHFVKLETIDSGKPFDEAV-L-DIDD----VASCFEYFAG----QA-EA-L----DG-K----Q--K---A---------PVTL--P-------M--------E----R-FKSHVLRQPLGVVGLISPWNYPLLM--ATWKIAPALAAGCTAVLKPSELASVTCLEFG----EVCNE-VGLPPGVLNILTGL---G---P-D-AGAPLVSHPDVDKIAFTGSSATGSKVMAS--------AA------Q------L------V------KPVTL--ELGGKSPIVVFEDV---D-----IDKV--VEW-TIFGCFWTNGQICSATS-RLL-VHE---------SIA-AEFVDKLVKW-TKN---------------IKISD-P-F-EE-GCRLGPVISKGQYDKIMKFISTAK--SEGAT-ILY-GGSR-P----E--------HLK--KGYYIEPTIV--T---D-ISTSM---QIWKEEVFGPVLCVKTF--S--S------ED-EA-IALA-ND-TE---YGLAAAVFSN--D-LERCERI--TKALE--VGAVWVNC-S-Q-P--------------C---------FV---Q-APWGGI--KRSGF-G--RE--LG-E-WG-IQNYLNIKQVTQDISD---EP--W------------GW--YK*

C;cover size:490; local alignment length=490 (original info = 4I8QA	495	1080.69	0	21)
>P1;4I8QA
structureN:4I8QA: 1: : 495: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------P-I-P-R-----R-QL-----------Y-------IGGEW---------R-EPV-KK-NRI-PIINPA-T-E-E-II-GDI---------PAATAEDVDIAVEAARKAIARD---D--WGSTT-GAQRAKYLRAIAAKVL-E-K-KSVLATLESLDSGKTLYESA-A-DMDD----VAGCFEYYAG----LA-EA-L----DS-R----R--M---T---------P-----VNLN----S--------D----S-YKSYVLREPLGVVGLITPWNYPLLM--AIWKVAPALAAGCAAILKPSELASITCLELGE----ICRE-IGLPSGALNILTGL---G---P-E-AGGPLASHPHVDKISFTGSGPTGSKIMTA--------AA------Q------L------V------KPVSL--ALGGKSPIVVFDDI---DN----LDIA--AEW-TLFGIFANTGQVCSATS-RLI-VQE---------NIA-SAFMDRLLKW-TKN---------------IKISD-P-L-EE-DCKLGPVVSAGQYEKVLKFISNAK--SEGAT-ILC-GGER-P----Q--------HLK--KGYYVQPTII--T---D-VNTSM---EIWKEEVFGPVLCVKTF--K--T------EE-QA-IELA-ND-TK---YGLGAAVMSK--D-VKRCERF--TKAFQ--TGIIWINC-S-Q-P--------------T---------FN---E-LPWGGK--KRSGF-G--RD--LG-K-WG-LENFLNIKQVTEYTSA---EP--LA--FYK------SP----*

C;cover size:498; local alignment length=498 (original info = 2O2PA	498	1083.32	0	22)
>P1;2O2PA
structureX:2O2PA: 1: : 498: : : :1.70: 
VI-------------NY-------V---------------------EKAV-----------------------------------------------------N--KL---------T-----L-Q-M-P-----Y-QL-----------F-------IGGEF---------V-DAE-GS-KTY-NTINPT-D-G-S-VI-CQV---------SLAQVSDVDKAVAAAKEAFENG---L--WGKIN-ARDRGRLLYRLADVME-Q-H-QEELATIEALDAGAVYTLALKT-HVGM----SIQTFRYFAG----WC-DK-I----QG-A----T--I---P---------I-----N-------Q--------ARPN-R-NLTLTKKEPVGVCGIVIPWNYPLMM--LSWKTAACLAAGNTVVIKPAQVTPLTALKFAEL----TLK-AGIPKGVVNILPGS---G---S-L-VGQRLSDHPDVRKIGFTGSTEVGKHIMKS--------CA------LS-----N------V------KKVSL--ELGGKSPLIIFADC---D-----LNKA--VQM-GMSSVFFNKGENCIAAG-RLF-VEE---------SIH-NQFVQKVVEE-VEK---------------MKIGN-P-L-ER-DTNHGPQNHEAHLRKLVEYCQRGV--KEGAT-LVC-GGNQ-V----P--------R----PGFFFQPTVF--T---D-VEDHM---YIAKEESFGPIMIISRF--ADGD------VD-AV-LSRA-NA-TE---FGLASGVFTR--D-INKALYV--SDKLQ--AGTVFINT-Y---N----------K---T---------DV---A-APFGGF--KQSGF-G--KD--LG-E-AA-LNEYLRIKTVTFEY----------------------------*

C;cover size:486; local alignment length=486 (original info = 4H73A	482	1077.75	0	23)
>P1;4H73A
structureN:4H73A: 1: : 482: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------------V-AN-----------Y-------INGEF---------K-EPS-TG-AFQ-VKTSPV-D-G-S-KI-AEV---------PRSGREDAREAIDSAFEALK-----A--WANIP-AIRRAEYLYKMLEVFR-Q-M-KEDFMKILTVEGGGTYRKVW-G-EVVF----TERLIQNAAE----LA-RH-Y----QG-R----V--L---Q---------S-----D-------S--------E----S-TISVVFKRSKGVVGVITPWNYPLSI--SMKKIAHTLAVGNTVVYKPASDTPVTGWLIAQMV----AK-AGLPKGVFNLVIGP---G---P-V-VGEEIVTHKRVAHVTFTGESSTGREIAAK--------AA------G------T------L------KTVTL--ELGGSDPLIILDDV---D-----VDYA--ARL-AVFASLFHQGQICTSAK-RII-VHK---------AVA-DKFIERYVHY-VKM---------------LRIDD-P-RKDE-KVDLGPLINERQVALMKEFVDDAV--SRGGR-LLI-GGRS--------------------WGNFFEPAIF--V---D-VDRNF---RIMREEVFGPVRPIVVV--E--N------DD-QA-VEVA-ND-TD---YGLSGAVLTN--N-VNRAFRI--AEAVE--SGMFHIND-V-T-F----------L---E---------ES---H-VPFGGI--KASGV-G--RE--GG-E-WS-FHETTYDRWVTVTLRT---RRF-P---IPS------AL----*

C;cover size:489; local alignment length=489 (original info = 3IWKA	496	1076.98	0	24)
>P1;3IWKA
structureN:3IWKA: 1: : 496: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------S-----R-QL-----------F-------IDGEW---------R-VPI-LN-KRI-PNINPS-T-E-N-II-GDI---------PAATKEDVDLAVDAAKRAISRKNGRD--WSAAS-GSLRARYLRAIAAKIK-E-K-KDELGKLESIDCGKPLEEAL-A-DLDD----VVACFEYYAG----LA-EE-L----DS-K----Q--K---A---------PISL--P-------M--------D----T-FKSYILKEPIGVVALITPWNYPFLM--ATWKIAPALAAGCAAILKPSELASVTCLEL----GEICKE-VGLPRGVLNIVTGL---G---H-E-AGASLASHPDVDKISFTGSSATGSKIMTT--------AA------Q------L------V------KPVSL--ELGGKSPIVVFEDV---D-----LDKV--AEW-TVFGCFFTNGQICSATS-RLI-VHE---------SIA-VEFVDKLVKW-AEN---------------IKISD-P-L-EE-GCRLGPIVSEAQYKKVLNCISSAK--SEGAT-ILT-GGRR-P----E--------HLK--KGYFVEPTII--T---D-VTTSM---QIWREEVFGPVLAVKTF--S--T------EE-EA-INLA-ND-TH---YGLGSAVMSN--D-LERCERL--SKALQ--AGIVWINC-A-Q-P--------------S---------FI---Q-APWGGI--KRSGF-G--RE--LG-E-WG-LENYLSVKQVTRYTSD---EP--WG--WYQ------PP-SK-*

C;cover size:480; local alignment length=480 (original info = 5X5UA	476	1077.84	0	26)
>P1;5X5UA
structureN:5X5UA: 1: : 476: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------T-Y-T-D-----T-QL-----------L-------IDGEW---------V-DAA-SG-KTI-DVVNPA-T-G-K-PI-GRV---------AHAGIADLDRALAAAQSGFE-----A--WRKVP-AHERAATMRKAAALVR-E-R-ADAIAQLMTQEQGKPLTEAR-V-EVLS----AADIIEWFAD----EG-RR-V----YG-R----I--V---P---------P-----R-------N--------L----G-AQQTVVKEPVGPVAAFTPWNFPVNQ--VVRKLSAALATGCSFLVKAPEETPASPAALLRA----FVD-AGVPAGVIGLVYGD---P---A-E-ISSYLIPHPVIRKVTFTGSTPVGKQLASL--------AG------L------H------M------KRATM--ELGGHAPVIVAEDA---D-----VALA--VKA-AGGAKFRNAGQVCISPT-RFL-VHN---------SIR-DEFTRALVKH-AEG---------------LKVGN-G-L-EE-GTTLGALANPRRLTAMASVIDNAR--KVGAS-IET-GGER-I----G--------S----EGNFFAPTVI--A---N-VPLDA---DVFNNEPFGPVAAIRGF--D--K------LE-EA-IAEA-NR-LP---FGLAGYAFTR--S-FANVHLL--TQRLE--VGMLWINQ-P-A------------T---P---------WP---E-MPFGGV--KDSGY-G--SE--GG-P-EA-LEPYLVTKSVTVMA----------------------------*

C;cover size:492; local alignment length=492 (original info = 3IWJA	500	1073.40	0	27)
>P1;3IWJA
structureN:3IWJA: 1: : 500: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------P-I-P-T-----R-QL-----------F-------INGDW---------K-APV-LN-KRI-PVINPA-T-Q-N-II-GDI---------PAATKEDVDVAVAAAKTALTRNKGAD--WATAS-GAVRARYLRAIAAKVT-E-K-KPELAKLESIDCGKPLDEAA-W-DIDD----VAGCFEYYAD----LA-EK-L----DA-R----Q--K---A---------PVSL--P-------M--------D----T-FKSHVLREPIGVVGLITPWNYPMLM--ATWKVAPALAAGCAAILKPSELASLTCLE----LGEICKE-VGLPPGVLNILTGL---G---P-E-AGAPLATHPDVDKVAFTGSSATGSKIMTA--------AA------Q------L------V------KPVSL--ELGGKSPLVVFEDV---D-----LDKA--AEW-AIFGCFWTNGQICSATS-RLI-LHE---------SIA-TEFLNRIVKW-IKN---------------IKISD-P-L-EE-GCRLGPVVSEGQYEKILKFVSNAK--SEGAT-ILT-GGSR-P----EHL------K----KGFFIEPTII--T---D-VTTNM---QIWREEVFGPVLCVKTF--S--T------EE-EA-IDLA-ND-TV---YGLGAAVISN--D-LERCERV--TKAFK--AGIVWVNC-S-Q-P--------------C---------FT---Q-APWGGV--KRSGF-G--RE--LG-E-WG-LDNYLSVKQVTQYISE---EP--WG--WYQ------PPAKL-*

C;cover size:480; local alignment length=480 (original info = 4U3WA	485	1072.40	0	28)
>P1;4U3WA
structureN:4U3WA: 1: : 485: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------R-Q-L-----L-RH-----------Y-------INGEF---------V-A---SG-TTF-PNLSPV-D-G-R-KL-ADV---------CEADAALVDSAVQAAHAAQKA----G--WRDTT-PAQRAAWLHKIADGIE-A-R-FDEFVAAEVADTGRPVAQAR-TLDIAR----GIANFRTFAD----LV-RT-A----SG-E----Y--F---E---------T-----H-------A--------ADGS-E-LINYVTRKPLGVIGIISPWNLPLLL--FTWKVAPALAMGNCVVAKPSEETPSSATLLAEVM----HD-VGLPPGVFNLIHGH---G---Q-NAAGEFLTRHPDISAITFTGESRTGSTIMKA--------VA------D------G------V------KEVSF--ELGGKNAAVVFADA---D-----FDAA--VAG-VLRSSFTNAGQVCLCSE-RVY-VER---------PIF-ERFVAALKEQ-AQA---------------LRVGA-P-E-DP-ATTMGPLISRGHRDKVLSYFRLAV--EEGAT-VVT-GGGA-P----SFGDAR---D----DGAFVMPTIW--T---G-LPDSA---RCVREEIFGPVCHIAPF--D--D------EA-EV-VKRV-ND-SA---YGLAASIWTT--Q-LARGHRV--AKQIE--TGIVWVNA-W-F------------V---R---------DL---R-TPFGGT--KLSGL-G--RE--GG-R-HS-LDFYSELTNVCVRIA---------------------------*

C;cover size:487; local alignment length=487 (original info = 3IFHQ	482	1080.58	0	29)
>P1;3IFHQ
structureN:3IFHQ: 1: : 482: : : :6.0: 
--------------------------------------------------------------------------------------GS-------------M-K--DP---------S-----L---L-R-----H-QA-----------Y-------IGGEW---------Q-AAD-SD-ATF-EVFDPA-T-G-E-SL-GTV---------PKMGAAETARAIEAAQAAWA-----G--WRMKT-AKERAAILRRWFDLVI-A-N-SDDLALILTTEQGKPLAEAK-G-EIAY----AASFIEWFAE----EG-KR-V----AG-D----T--L---P---------T-----P-------D--------A----N-KRIVVVKEPIGVCAAITPWNFPAAM--IARKVGPALAAGCPIVVKPAESTPFSALAMAFLA----ER-AGVPKGVLSVVIGD---P---K-A-IGTEITSNPIVRKLSFTGSTAVGRLLMAQ--------SA------P------T------V------KKLTL--ELGGNAPFIVFDDA---D-----LDAA--VEG-AIASKYRNNGQTCVCTN-RFF-VHE---------RVY-DAFADKLAAA-VSK---------------LKVGR-G-T-ES-GATLGPLINEAAVKKVESHIADAL--AKGAS-LMT-GGKR-H----A--------L----GHGFFEPTVL--T---G-VKPDM---DVAKEETFGPLAPLFRF--A--S------EE-EL-VRLA-ND-TE---FGLAAYLYSR--D-IGRVWRV--AEALE--YGMVGINT-G-L------------I---S---------NE---V-APFGGV--KQSGL-G--RE--GS-H-YG-IDDYVVIKYLCVAV----------------------------*

C;cover size:503; local alignment length=503 (original info = 1BI9A	478	1076.46	0	30)
>P1;1BI9A
structureX:1BI9A: 1: : 478: : : :2.7: 
MA-------------SL-------Q---------------------LLPS------P---------------T-------------PN-------------L---------------------E-I-K-Y-----T-KI-----------F-------INNEW---------Q-NSE-SG-RVF-PVCNPA-T-G-E-QV-CEV---------QEADKVDIDKAVQAARLAFSLGS--V--WRRMD-ASERGRLLDKLADLVE-R-D-RATLATMESLNGGKPFLQAFYI-DLQG----VIKTLRYYAG----WA-DK-I----HG-M----T--I---P---------V-------------D--------G----D-YFTFTRHEPIGVCGQIIPWNFPLLM--FTWKIAPALCCGNTVVIKPAEQTPLSALYMG----ALIKE-AGFPPGVVNILPGY---G---P-T-AGAAIASHIGIDKIAFTGSTEVGKLIQEA--------AG------RS-----N------L------KRVTL--ELGGKSPNIIFADA---D-----LDYA--VEQ-AHQGVFFNQGQCCTAGS-RIF-VEE---------SIY-EEFVKRSVER-AKR---------------RIVGS-P-F-DP-TTEQGPQIDKKQYNKILELIQSGV--AEGAK-LEC-GGKG-L----G--------R----KGFFIEPTVF--S---N-VTDDM---RIAKEEIFGPVQEILRF--K--T------MD-EV-IERA-NN-SD---FGLVAAVFTN--D-INKALMV--SSAMQ--AGTVWINC-Y---------------------------------------------------------G-E-FG-LREYSEVKTVTVKIPQ---KN--S------------------*

C;cover size:498; local alignment length=498 (original info = 3QANA	516	1074.47	0	31)
>P1;3QANA
structureN:3QANA: 11: : 516: : : :6.0: 
FT-------------DF-------T---------------------VEAN------R---------------K-------------AF-------------E-E--AL---------GLVEKEL-G-K-E-----Y-PL-----------I-------INGER---------V-T---TE-DKI-QSWNPARK-D-Q-LV-GSV---------SKANQDLAEKAIQSADEAFQ-----T--WRNVN-PEERANILVKAAAIIR-R-R-KHEFSAWLVHEAGKPWKEAD-A-DTAE----AIDFLEYYAR----QM-IE-L----NR-G----K--E---I---------L-----S-------R--------P----G-EQNRYFYTPMGVTVTISPWNFALAI--MVGTAVAPIVTGNTVVLKPASTTPVVAAKFVEVL----ED-AGLPKGVINYVPGS---G---A-E-VGDYLVDHPKTSLITFTGSKDVGVRLYER--------AAVVRPGQN------H------L------KRVIV--EMGGKDTVVVDRDA---D-----LDLA--AES-ILVSAFGFSGQKCSAGS-RAV-IHK---------DVY-DEVLEKTVAL-AKN---------------LTVGD-P-T-NR-DNYMGPVIDEKAFEKIMSYIEIGK--KEGRL--MT-GGEG-D----S--------S----TGFFIQPTII--A---D-LDPEA---VIMQEEIFGPVVAFSKA--N--D------FD-HA-LEIA-NN-TE---YGLTGAVITR--N-RAHIEQA--KREFH--VGNLYFNR-NCT-G----------A---I---------VG---Y-HPFGGF--KMSGT-D--SK--AGGP-DY-LALHMQAKTVSEMY----------------------------*

C;cover size:477; local alignment length=477 (original info = 6C43A	473	1072.31	0	32)
>P1;6C43A
structureN:6C43A: 1: : 473: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------Q-----Y-QL-----------L-------INGVL---------V-DG--EG-ERQ-SVYNPA-T-G-E-VI-LEI---------AEASPAQVDAAVQAADNAFA-----E--WGQTT-PKARAECLLKLADSIE-Q-N-ALEFARLESQNCGKPLHCVIND-EIPA----IVDVFRFFAG----AA-RC-L----SG-L----A--A---G---------E-----Y-------L--------E----G-HTSMIRRDPIGVVASIAPWNYPLMM--AAWKLAPALAAGNCVVIKPSEITPLTALKLAVLA-----K-DIFPPGVLNVLFGR---G---Q-T-VGDVLTGHEKVRMVSLTGSIATGEHILRH--------TA------P------A------I------KRTHM--ELGGKAPVIVFDDA---D-----LDAV--AQG-VRTFGFYNAGQDCTAAC-RIY-AQR---------GIY-DALVEKLGNA-VSS---------------LKMGA-P-E-DE-STELGPLSSLAHLKRVTAAVEEAK--ALSHIRVIT-GGSQ-T----E--------G----KGYYFAPTLL--A---D-AKQED---AIVQREVFGPVVSITVF--D--D------ED-QV-LRWA-ND-SR---YGLASSVWTQ--D-VGRAHRL--SARLQ--YGCTWINT-H-F------------M---L---------VS---E-MPHGGQ--KQSGY-G--KD--MS-L-YG-LEDYTLVRHIMVKH----------------------------*

C;cover size:492; local alignment length=492 (original info = 4I8PA	500	1063.36	0	33)
>P1;4I8PA
structureN:4I8PA: 1: : 500: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------M-V-P-L-----R-QL-----------F-------VDGEW---------R-PPA-QG-RRL-PVVNPT-T-E-A-HI-GEI---------PAGTAEDVDAAVAAARAALKRNRGRD--WARAP-GAVRAKYLRAIAAKVI-E-R-KPELAKLEALDCGKPYDEAA-W-DMDD----VAGCFEYFAD----QA-EA-LDKR-QN-S----P--V---S---------L-----P-------M--------E----T-FKCHLRREPIGVVGLITPWNYPLLM--ATWKIAPALAAGCTAVLKPSELASVTCLELA----DICKE-VGLPSGVLNIVTGL---G---P-D-AGAPLSAHPDVDKVAFTGSFETGKKIMAS--------AA------P------M------V------KPVTL--ELGGKSPIVVFDDV---D-----IDKA--VEW-TLFGCFWTNGQICSATS-RLL-IHT---------KIA-KKFNERMVAW-AKN---------------IKVSD-P-L-EE-GCRLGPVVSEGQYEKIKKFISNAK--SQGAT-ILT-GGVR-P----A--------HLE--KGFFIEPTII--T---D-ITTSM---EIWREEVFGPVLCVKEF--S--T------ED-EA-IELA-ND-TQ---YGLAGAVISG--D-RERCQRL--SEEID--AGCIWVNC-S-Q-P--------------C---------FC---Q-APWGGN--KRSGF-G--RE--LG-E-GG-IDNYLSVKQVTEYISD---EP--WG--WYQ------SPSKL-*

C;cover size:489; local alignment length=489 (original info = 4O6RA	489	1063.42	0	34)
>P1;4O6RA
structureN:4O6RA: 1: : 489: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------H-M-Q-----T-QL-----------F-------IDGRF---------V-DAV-DR-GTI-DVLNPH-D-G-S-VI-TKI---------AAATAADVDLAVDAATRAFP-----A--WSAMP-AAERGRLLLRLADAIE-A-N-TEALAQLESLDTGHPIRDSR-ALDVPR----TAACFRYFGG----MA-DK-L----QG-S----V--I---P---------V-----D----------------T----G-FLNYVQRAPIGVVGQIVPWNFPLMF--TSWKMGPALAAGNTVVLKPSEITPLSTLRIVELM----AE-VGFPAGVVNIVPGY---G---H-T-AGQRLAEHPGVGKIAFTGSTATGRRIVEA--------SQ------G------N------L------KRVQL--ELGGKGANIVFDDA---N-----LDAA--ING-AAWAIFHNQGQACIAGS-RLV-LHE---------RIA-DAFLERFVAL-ASS---------------IRIGN-P-L-DP-NTEMGPLTSKQHLDRVLSYVDVAR--EQGGR-VLT-GGSA-P----Q--------DPALANGYYVRPTIV--E---A-KHATD---RVAQEEVFGPFVTVLRF--G--S------DD-EA-LAIA-NA-TE---YGLGSGLWTN--D-LSRAHRM--AARID--AGMCWINC-Y-K------------R---V---------NP---G-SPFGGV--GKSGY-G--RE--MG-F-EA-MHDYTEARSVWVNVDG---NV--P---PHF------KR----*

C;cover size:486; local alignment length=486 (original info = 5J6BA	481	1065.72	0	35)
>P1;5J6BA
structureN:5J6BA: 1: : 481: : : :6.0: 
-----------------------------------------------------------------------------------------------------H-H--HH---------M-----L-K-E-T-----Y-PY-----------Y-------LANEA---------V-Y---AN-AEL-EVTDKY-T-G-K-VA-TRV---------ALADASAIDAAIAAAVGAQK-----P--LRALP-AFRRQAILEHCVARFR-E-R-FDELAQALCIEAGKPINDSK-G-EVTR----LIDTFRVAAE----ES-VR-I----EG-G----L--V---N---------L-----E-------ISPRA----Q----G-YSGYYKRVPIGPCSFISPFNFPLNL--AAHKVAPALAAGCPFVLKPASRTPIGALIIGEVL----AE-TDLPKGAFSILPA----H---R-D-GADLFTTDERFKLLSFTGSPTVGWELKKK--------AG--------------------K------KKVVL--ELGGNAAAIVDADQ---REV---LDYV--VER-LAFGAYYQSGQSCIGVQ-RII-AHA---------DVY-DALREKLIAK-TRS---------------LKMGD-P-K-DP-ATFVGPMISESEARRLAGWMEAAV--AAGAK-IVA-GGKV--------------------DGAMFEATLL--E---G-VGRDQ---DLYRKEAFGPVALLERF--S--D------FD-DA-LARV-ND-SD---FGLQAGVFTD--S-LSHAQRA--WDELE--VGGVVIND-V-P-S----------F---R---------VD---N-MPYGGV--KDSGL-G--RE--GI-R-YA-IEDMTELRLMVVRRR---------------------------*

C;cover size:488; local alignment length=488 (original info = 4GO4A	487	1062.77	0	36)
>P1;4GO4A
structureN:4GO4A: 1: : 487: : : :6.0: 
-------------------------------------------------------------------------------------------------------------------------------M-Q-----N-QL-----------Y-------IDGRF---------V-DAV-AG-GTI-DVVSPH-D-G-S-LI-TRI---------AAAEAADVDLAVAAAKRAFP-----A--WSALG-AAERGRLLLKLADRIE-E-C-SEELAQLESLNTGHPIRDSR-GLDVPR----TAACFRYFGG----MA-DK-I----EG-S----V--I---P---------V-----D----------------A----G-FLNYVQRKPIGVVAQIVPWNFPLMF--TSWKMGPALAAGNTIVIKPSEITPLSTLRIVELM----TE-VGFPKGVVNVVPGY---G---H-T-AGQALAEHLDVGKIAFTGSTATGRRIVEA--------SK------S------N------L------KRIQL--ELGGKGANIVFEDA---N-----IEAA--VNG-AAWAIFHNQGQACIAGS-RLI-LHK---------DIA-DQFLERFIAL-AKS---------------IRLGD-P-M-DP-ETEMGPLTSALRRDRVLSYIDIAI--EQGGK-VLA-GGKA-P----D--------DKALANGFYVEPTVV--E-----AKPQD---RVCQEEVFGPFVTVVRF--S--S------DE-EA-LAIA-NN-TE---YGLGSGLWTQ--N-LARAHKM--AHAIH--AGMCWINC-Y-K------------R---V---------SP---G-SPFGGV--GQSGY-G--RE--MG-F-EA-IHDYTEARSVWVNVDA---KI--A---PHF------KR----*

C;cover size:482; local alignment length=482 (original info = 5JRYA	477	1067.57	0	37)
>P1;5JRYA
structureN:5JRYA: 1: : 477: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------M-----L-K-E-T-----Y-PY-----------Y-------LANAA---------V-Y---AN-TDL-EVTDKY-S-G-K-VA-TRV---------ALADAKAIDAAIGAAVDATK-----P--MRELP-AYKRQAVLDHCVARFR-E-R-FDELAEALCIEAGKPINDAK-G-EVTR----LIDTFRVASE----EA-VR-I----DG-E----V--L---N---------L-----E-------I--------SARAQG-YTGYTRRVPIGPCSFISPFNFPLNL--AAHKVAPALAAGCPFVLKPASRTPVGALIIGEV----LAE-TDLPKGAFSVLPA----H---R-D-GADLFTTDDRFRLLSFTGSPAVGWALKEK--------AG--------------------K------KKVVL--ELGGNAAAIVDADQLD-R-----LDYV--VDR-LAFGAFYQSGQSCIGVQ-RIL-AHA---------DIY-DALRDKLIAK-TRS---------------LKMGD-P-K-DP-STFVGPMISESESRRLSGWMDAAV--AAGAK-IVA-GGKV--------------------DGAMFEATLL--E---N-VGRDQ---DLYRKEAFGPIAILEKF--D--R------FD-DA-LARV-ND-SD---FGLQAGVFTD--S-LAHTQQA--WDELE--VGGVVIND-V-P-S----------F---R---------VD---N-MPYGGV--KDSGL-G--RE--GI-R-YA-IEDMTEPRLLVVRRR---------------------------*

C;cover size:486; local alignment length=486 (original info = 2W8OA	480	1071.30	0	38)
>P1;2W8OA
structureN:2W8OA: 1: : 480: : : :6.0: 
-----------------------------------------------------------------------------------------------------L-A--GL---------S-----A-ALL-R-----T-DS-----------F-------VGGRW---------L-P---AA-ATF-PVQDPA-S-G-A-AL-GMV---------ADCGVREARAAVRAAYEAFC-----R--WREVS-AKERSSLLRKWYNLMI-Q-N-KDDLARIITAESGKPLKEAH-G-EILY----SAFFLEWFSE----EA-RR-V----YG-D----I--I---H---------T-----P-------A--------K----D-RRALVLKQPIGVAAVITPWNFPSAM--ITRKVGAALAAGCTVVVKPAEDTPFSALALAELA----SQ-AGIPSGVYNVIPCSRKNA---K-E-VGEAICTDPLVSKISFTGSTTTGKILLHH--------AA------N------S------V------KRVSM--ELGGLAPFIVFDSA---N-----VDQA--VAG-AMASKFRNTGQTCVCSN-QFL-VQR---------GIH-DAFVKAFAEAMKKN---------------LRVGN-G-F-EE-GTTQGPLINEKAVEKVEKQVNDAV--SKGAT-VVT-GGKR-H----Q--------L----GKNFFEPTLL--C---N-VTQDM--------LTFGPLAPVIKF--D--T------EE-EA-IAIA-NA-AD---VGLAGYFYSQ--D-PAQIWRV--AEQLE--VGMVGVNE-G-L------------I---S---------SV---E-CPFGGV--KQSGL-G--RE--GS-K-YG-IDEYLELKYVCYGGL---------------------------*

C;cover size:478; local alignment length=478 (original info = 4I25A	483	1063.98	0	39)
>P1;4I25A
structureN:4I25A: 1: : 483: : : :6.0: 
-------------------------------------------------------------------------------------------------------------------------------S-Q-----L-LN-----------Y-------IDGNF---------V-T---SA-SSF-ANINPV-N-G-K-LI-SDV---------FEADAKQVNEAVVAAQNALKG----P--WGKLS-VQDRAALIHKIADGIQ-A-R-FEEFVAAEVADTGRPVHQAR-TLDIPR----AIANFRTFAD----LA-KT-S----HT-D----L--F---E---------M-----S-------TSDG-----S----G-ALNYTVRKPLGVIGVISPWNLPLLL--FTWKVAPALACGNTVVAKPSEESPSSATLLAEVM----HD-AGVPPGVFNLIHGF---G---KDS-AGEFLTQHPGISALTFTGESKTGSTIMKA--------VA------D------G------V------KEVSF--ELGGKNAAVVFADA---D-----LDAA--IEG-VLRSSFTNSGQVCLCSE-RVY-VHR---------SIF-DEFVSGLKVE-AER---------------LVVGY-P-D-QD-GVNMGPLISHGHRDKVLSYYRLAV--DEGAT-VVT-GGGV-P----KFNDER---D----QGAYVQPTIW--T---G-LSDKA---RCVTEEIFGPVCHISPF--D--D------ED-EV-INRV-ND-SN---YGLACAIWTT--N-LSRAHRV--SRQIH--VGLVWVNT-W-Y------------L---R---------DL---R-TPFGGV--KLSGL-G--RE--GG-R-FS-MDFYSDIANICIKI----------------------------*

C;cover size:486; local alignment length=486 (original info = 5MZ8A	481	1066.96	0	40)
>P1;5MZ8A
structureN:5MZ8A: 1: : 481: : : :6.0: 
-----------------------------------------------------------------------------------------------------------V---------T-------P-K-K-----Y-NI-----------F-------LASKP---------V-DG--DR-KWL-DVTNKY-T-N-D-VA-AKV---------PQATHKDIDDAIDAAVAAAP-----A--MAAMG-AYERKAVLEKVVAELK-N-R-FEEIAQTLTMESGKPIKDAR-G-EVTR----TIDTFQVAAE----ES-VR-I----YG-E----H--I---P---------L-----D-------I--------SARNKG-LQGIVKKFPIGPVSMVSPWNFPLNL--VAHKVAPAIAVGCPFVLKPASRTPLSALILGEIL----HKIEELPLGAFSILPV----S---R-E-DADMFTVDERFKLLTFTGSGPIGWDMKAR--------AG--------------------K------KKVVM--ELGGNAPCIVDDYVP--D-----LDYT--IQR-LINGGFYQGGQSCIHMQ-RLY-VHE---------RLY-DEVKEGFVAA-VKK---------------LKMGN-P-F-EE-DTYLGPMISESAAKGIEDWVKEAV--AKGGK-LLT-GGNR--------------------KGAFIEPTVI--E---D-VPIEA---NARKEEIFGPVVLLYKY--S--D------FK-EA-VKEC-NN-TH---YGLQSGIFTK--D-LNKAFYA--FEHME--VGGVILND-S-P-A----------L---R---------VD---S-QPYGGL--KDSGI-Q--RE--GV-K-YA-MDDMLETKVLVMRNVG---TL---------------------*

C;cover size:498; local alignment length=498 (original info = 3RJLA	513	1068.81	0	41)
>P1;3RJLA
structureN:3RJLA: 7: : 513: : : :6.0: 
FT-------------NF-------G---------------------IEENRKAFEKA---------------L-------------ET-------------V-N--NE---------W-----L-G-Q-S-----Y-PL-----------V-------IDGER---------Y-E---TE-NKI-VSINPA-N-K-EEVV-GTV---------SKATQDHAEKAIQAAAKAFE-----T--WRYTD-PEERAAVLFRAVAKVR-R-K-KHEFSALLVKEAGKPWNEAD-A-DTAE----AIDFMEYYAR----QM-IE-LA---KG-K----P--V---N---------S-------------R--------E----G-ERNQYVYTPTGVTVVIPPWNFLFAI--MAGTTVAPIVTGNTVVLKPASAAPVIAAKFVEVL----EE-SGLPKGVVNFVPGS---G---A-E-VGDYLVDHPKTSIITFTGSREVGTRIFER--------AA------KVQPGQTH------L------KQVIA--EMGGKDTVVVDEDC---D-----IELA--AQS-IFTSAFGFAGQKCSAGS-RAV-VHE---------KVY-DEVLKRVIEI-TES---------------KKVGE-P-D-SA-DVYMGPVIDQASFNKIMDYIEIGK--EEGRL--VS-GGKG-D----D--------S----KGYFIEPTIF--A---D-LDPKA---RLMQEEIFGPVVAFSKV--S--S------FD-EA-LEVA-NN-TE---YGLTGAVITK--N-RDHINRA--KQEFH--VGNLYFNR-NCT-G----------A---I---------VG---Y-HPFGGF--KMSGT-D--SK--AGGP-DY-LALHMQAKTISEMF----------------------------*

C;cover size:485; local alignment length=485 (original info = 3K2WA	475	1062.01	0	42)
>P1;3K2WA
structureN:3K2WA: 1: : 475: : : :6.0: 
----------------------------------------------------------------------------------------------------------DL---------H-----F---K-N-----K-VN-----------F-------IGGQY---------V-PSN-ES-DTI-DILSPS-T-G-K-VI-GEI---------PAGCKADAENALEVAQAAQK-----A--WAKLT-ARTRQNMLRTFANKIR-E-N-KHILAPMLVAEQGKLLSVAE-M-EVDV----TATFIDYGCD----NA-LT-I----EG-D----I--L---P---------S-----D-------N--------Q----D-EKIYIHKVPRGVVVGITAWNFPLAL--AGRKIGPALITGNTMVLKPTQETPLATTELGRI----AKE-AGLPDGVLNVINGT---G---S-V-VGQTLCESPITKMITMTGSTVAGKQIYKT--------SA------E------Y------M------TPVML--ELGGKAPMVVMDDA---D-----LDKA--AED-ALWGRFANCGQVCTCVE-RLY-VHA---------SVY-DEFMAKFLPL-VKG---------------LKVGD-P-M-DA-DSQMGPKCNQREIDNIDHIVHEAI--KQGAT-VAT-GG----------------------KGCWYEPTVL--V---D-VKQDN---IVVHEETFGPILPIVKV--S--S------ME-QA-IEFC-ND-SI---YGLSAYVHTQ--S-FANINQA--ISDLE--VGEVYINR-G-M------------G---E---------QH---Q-GFHNGW--KQSGF-G--GE--DG-K-FG-LEQYLEKKTVYINEAE--------------------------*

C;cover size:485; local alignment length=485 (original info = 4JZ6A	484	1059.88	0	43)
>P1;4JZ6A
structureN:4JZ6A: 1: : 484: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------H-M-K-----T-KL-----------F-------INNAW---------I-DSS-DQ-QTF-ERKHPV-S-S-E-VM-TES---------ANATVTDAIKAAQAAEEAFK-----T--WKDVG-PSERRRLLLKVADVME-S-K-TPKFIEVMAMEVGASALWAG-F-NVHA----SANVFREAAS----LA-TQ-I----QG-E----T--I---P---------T-----D-------K--------A----E-TLSMTLRQPVGPILSIVPWNGTAVL--AARAIAYPLVCGNTVVFKGSEFSPATHALITQCV----QE-AGLPAGVLNYLNSSPDRS---P-E-IADALISAKEIRRINFTGSTRVGSIIAQK--------AA------Q------H------L------KRCLL--ELGGKSPLIVLDDA---D-----INAA--VKA-AVFGSFLFQGQICMSTE-RLV-VDE---------KIA-DEFVARFVEK-TER---------------LSVGD-PCL-TG-DCIIGPMVSPNSGERINGLFKDAI--DKGAK-VVC-GGMA--------------------QGAVMPATIL--D---H-VKSDM---RIYDEETFGPITVVIRC--K--G------EA-EA-IRIA-ND-SV---YGLSSGVFGR--D-INRALRV--GMSIE--YGCVHING-S-T-V----------Q---N---------EA---Q-APYGGT--KNTGY-G--RF--DG-R-AV-IDEFTELKWLTIEPFE---QQY-P---F--------------*

C;cover size:499; local alignment length=499 (original info = 4O5HA	511	1058.80	0	44)
>P1;4O5HA
structureN:4O5HA: 11: : 511: : : :6.0: 
ME-------------TN-------E-----------------------TF------A---------------LL------------DA-------------T-R--AF---------------L-A-K-P-----K-QM-----------L-------IGAEW---------S-DAA-SG-RQL-DVVNPA-D-G-T-VI-ARV---------PEADERDVQQAVAAARRAFDAG---P--WRTAK-TTDRERLMLVLADLIE-A-N-ARELAEIESLDNGKPVMVAQ-GLDVAM----AAQCFRYMAG----WA-TK-I----EG-S----V--I---D---------A-----GMPYLP--D--------S----E-IFAYTRKEPVGVVGAIIPWNFPLLM--AAWKIAPALATGCTVVLKPAEDTPLSALRLGELI----QA-AGFPDGVVNIVTGY---G---H-T-AGAALSRDPRIDKIAFTGSTQTGKTIGHA--------AL------D------N------M------TRMSL--ELGGKSPVIVLPDV---D-----LDKA--AQG-VANAIFFNQGQVCTAGS-RAY-IHS---------KVF-DGVIERVAKI-AAS---------------LKIGP-G-M-DP-ATQIGPLVSAKQRERVCGYIDSGF--GEGAR-AAA-GGRA-I----D--------G----PGFFVEPTVL--V---D-TTQAM---RVVREEIFGPVLVAMPF--D--D------VD-TA-VQLA-ND-TP---YGLGASIWSN--D-LSAIHKL--VPRIA--AGTVWVNC-H-S------------L---L---------DN---A-LPFGGM--KQSGF-G--RE--LG-R-AV-IDQYTESKSVMMNYA---------------------------*

C;cover size:484; local alignment length=484 (original info = 3R31A	482	1061.40	0	45)
>P1;3R31A
structureN:3R31A: 1: : 482: : : :6.0: 
----------------------------------------------------------------------------------------------------------PL---------K-----A-Q-P-K-----A-SH-----------F-------IDGDY---------V-EDN-TG-TPF-ESIFPA-T-G-E-MI-AKL---------HAATPAIVERAIASAKRAQK-----E--WAAMS-PMARGRILKRAADIMR-E-R-NDALSTLETLDTGKPIQETIVA-DPTS----GADAFEFFGG----IAPSA-L----NG-D----Y--I---P---------L----------------------G----G-DFAYTKRVPLGVCVGIGAWNYPQQI--ACWKAAPALVAGNAMVFKPSENTPLGALKIAEIL----IE-AGLPKGLFNVIQG----D---R-D-TGPLLVNHPDVAKVSLTGSVPTGRKVAAA--------AA------G------H------L------KHVTM--ELGGKSPMIVFDDA---D-----IESA--VGG-AMLGNFYSSGQVCSNGT-RVF-VQK---------KAK-ARFLENLKRR-TEA---------------MILGD-P-L-DY-ATHLGPLVSKAQQEKVLSYIEKGK--AEGAT-LIT-GGGI-PNNV-A--------G----EGAYVQPTVF--A---D-VTDDM---TIAREEIFGPVMCVLDF--D--D------ED-EV-LARA-NA-TE---FGLAGGVFTA--D-LARAHRV--VDGLE--AGTLWINT-Y---N----------L---C---------PV---E-IPFGGS--KQSGF-G--RE--NS-A-AA-LEHYSELKTVYVSTG---------------------------*

C;cover size:491; local alignment length=491 (original info = 5IZDA	493	1059.52	0	46)
>P1;5IZDA
structureN:5IZDA: 1: : 492: : : :6.0: 
-------------------------------------------------------------------------------------------------------------------------------M-D-----T-KL-----------Y-------IDGQW---------V-NSS-SG-KTV-DKYSPV-T-G-Q-VI-GRF---------EAATRDDVDRAIDAAEDAFW-----A--WNDLG-SVERSKIIYRAKELIE-K-N-RAELENIIMEENGKPVKEAK-E-EVDG----VIDQIQYYAE----WA-RK-L----NG-E----V--V---E---------G-----T-------S--------S----H-RKIFQYKVPYGIVVALTPWNFPAGM--VARKLAPALLTGNTVVLKPSSDTPGSAEWIVRK----FVE-AGVPKGVLNFITGR---G---S-E-IGDYIVEHKKVNLITMTGSTATGQRIMQK--------AS------A------N------M------AKLIL--ELGGKAPFMVWKDA---D-----MDNA--LKT-LLWAKYWNAGQS-IAAE-RLY-VHE---------DIY-DTFMSRFVEL-SRK---------------LALGD-P-K----NADMGPLINKGALQATSEIVEEAK--ESGAK-ILF-GGSQ-P----SLSGPY---R----NGYFFLPTII--G---N-ADQKS---KIFQEEIFAPVIGARKI--S--S------VE-EM-YDLA-ND-SK---YGLASYLFTK--D-PNIIFEA--SERIR--FGELYVNM-P-G------------P---E---------AS---Q-GYHTGF--RMTGQ-A--GE--GS-K-YG-ISEYLKLKNIYVDYSG---KP------LHINTVR--DD-LFQ*

C;cover size:479; local alignment length=479 (original info = 3PRLA	475	1052.79	0	47)
>P1;3PRLA
structureN:3PRLA: 1: : 475: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------Q-F-N-----A-NI-----------L-------RNGEW---------V-ESR-TG-ERI-SISAPA-S-G-V-AL-GSI---------PALSQEEVNDAIQGAKDAQK-----I--WKIRP-IHERVDLLYAWADLLE-E-R-KEIIGELIMHEVAKPKKSAI-G-EVSR----TADIIRHTAD----EA-LR-L----NG-E----T--L---K---------G-----D-------QFKGGS---S----K-KIALVEREPLGVVLAISPFNYPVNL--AAAKIAPALVTGNTVVFKPATQGSLSGIKMVEAL----AD-AGAPEGIIQVVTGR---G---S-V-IGDHLVEHPGIDMITFTGGTTTGERISEK--------A--------------K------M------IPVVL--ELGGKDPAIVLDDA---D-----LKLT--ASQ-IVSGAFSYSGQRCTAIK-RVF-VQD---------SVA-DQLVANIKEL-VEQ---------------LTVGS-P-E-D--DADITPVIDEKSAAFIQGLIDDAL--ENGAT-LLS-GNKR--------------------QGNLLSPTLL--D---D-VTPAM---RVAWEEPFGPVLPIIRV--K--D------AN-EA-ISLS-NQ-SD---YGLQASIFTK--D-TDRAINI--GKHLE--VGTVHINA-K-T-E----------R---G---------PD---H-FPFLGV--KKSGL-G--VQ--GI-K-PS-LLSMTRERVTVLNL----------------------------*

C;cover size:496; local alignment length=496 (original info = 5IUVA	495	1047.88	0	48)
>P1;5IUVA
structureN:5IUVA: 1: : 495: : : :6.0: 
---------------TL------------------------------TRA------D---------------W-------------EQ-------------R-A--Q----------N-----L-K-I-E-----G-RA-----------F-------IQGEY---------T-AAA-SG-ETF-DCISPV-D-G-R-LL-AKV---------ASCDAADAQRAVESARSAFDSG---A--WSRLA-PAKRKATMIRFAGLLE-Q-N-AEELALLETLDMGKPISDSL-GVDIPG----GARALSWSGE----AI-DK-L----YD-E----V--A---A---------T-----P----------------H----D-QLGLVTREPVGVVAAIVPWNFPLMM--ACWKLGPALSTGNSVVLKPSEKSPLTAIRIAQLA----IE-AGIPAGVLNVLPGY---G---H-T-VGKALALHMDVDTVVFTGSTKIAKQLMIY--------AG------ES-----N------M------KRVWL--EAGGKSPNIVFADAP--D-----LQAA--ADS-AASAIAFNQGEVCTAGS-RLL-VER---------SIK-DRFLPMVIEA-LGT---------------WKPGN-P-L-DP-ATNVGALVDTQQMNTVLSYIAAGH--TDGAR-LVA-GGKQ-I----L--------QET--GGTYVEPTIF--D---G-VNNAM---RIAQEEIFGPVLSVLTF--D--T------AE-EA-IQIA-ND-TP---YGLAAAVWTA--N-LSKAHLT--ARALR--AGSVWVNQ---Y-D----------G---G---------DM---T-APFGGF--KQSGN-G--RD--KS-L-HA-FDKYTELKSTWIKL----------------------------*

C;cover size:477; local alignment length=477 (original info = 4YWEA	476	1053.76	0	49)
>P1;4YWEA
structureN:4YWEA: 1: : 476: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------------A-KH-----------F-------IAGEW---------T-LPA-QL-ETI-PVVDPS-D-G-Q-PF-ATI---------ARGTAPDIERAVAAARDAFAG----P--WGAAS-AAERGRVLMRLSARVT-D-S-IEELAAIEARDTGKPLKQAR-A-DAAA----LARYFEFYAG----AA-DK-L----HG-E----T--L---P---------Y-----Q----------------A----G-YTVLTVREPHGVTGHIVPWNYPMQI--FGRSVGAALAAGNACVVKPAEDACLSVLRVAELA----AE-AGLPAGALNIVTGY---G---H-E-AGAALARHPGIDHISFTGSPATGKLVTQM--------AA------E------N------H------VPVTL--ELGGKSPQIVFADA---D-----LDAA--LPV-LVSAIVQNGGQTCSAGS-RVL-IER---------AVY-EPLVERLATA-FNG---------------LRVG--P-S-RA-DLDCGPLINAKQQQRVWDFLSDAQ--HDGIP-MAA-HGQV-V----A--------DAPE-SGFYQAPALL--R---D-VPPSH---RLAQEEVFGPVLAAMRF--V--D------ED-EA-VALA-NG-TP---YGLVAGIWTR--D-GARQMRL--ARRLR--AGQVFINN-Y-G-A----------G---G---------GV---E-LPFGGV--GHSGH-G--RE--KG-F-EA-LYGFTALKTIAIRHG---------------------------*

C;cover size:487; local alignment length=487 (original info = 2VROA	521	1064.67	0	50)
>P1;2VROA
structureN:2VROA: 1: : 521: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------H-----M-T-E-L-----L-KN-----------H-------VAGQW---------I-AG--TG-AGI-TLTDPV-T-G-V-AL-VRV---------SSEGLDLARAFSFAREDGGA-----A--LRALT-YAQRAARLADIVKLLQ-A-K-RGDYYAIATANSGTTRNDSA-V-DIDG----GIFTLSYYAK----LG-AS-L----GE-V----H--A---LRDGSAESLSK-----D-------R--------S----F-SAQHVLSPTRGVALFINAFNFPSWG--LWEKAAPALLSGVPVIVKPATATAWLTQRMVA---DVVDA-GILPPGALSIICGS---S---A-G----LLDQIRSFDVVSFTGSADTAATLRAH--------PAFV----Q------R------G------ARLNV--EADSLNSAILCADA---TPDTPAFDLF--IKE-VVREMTVKSGQKCTAIR-RAF-VPE---------AAL-EPVLEALKAK-LAK---------------ITVGN-P-R-ND-AVRMGSLVSREQYENVLAGIAALR--EEAVL-AYD-SSAV-P----LIDADA---N----IAACVAPHLFVVN---D-PDNAT---LLHDVEVFGPVASVAPY--R--VTTDTLPEA-HA-VALA-RR-GQ---GSLVASIYSN--D-DAHLGRL--ALELA--DSHGRVHA-I-S-PSVQHSQTGHGN---V---------MP---M-SLHGGP--GRAGG-G--EE--LG-GLRA-LAFYHRRSAIQAASAA---IG--T---L--------------*

C;cover size:506; local alignment length=506 (original info = 3U4JA	497	1042.46	0	51)
>P1;3U4JA
structureN:3U4JA: 2: : 497: : : :6.0: 
LS-------------NF-------I---------------------APDS------N---------------D-------------PR-------------------L---------R-----I---K-S-----R-YQ-----------L-------VDGKS---------V-DAA-SG-STI-DRVSPGHA-G-E-VV-GTW---------PEASADDVRKAVAAARKAFD-----A--GPWPR-SGAERSRLFKVADLIL-A-R-QEELALIESLEVGKPIAQAR-G-EIGF----CADLWSYAAG----QA-RA-L----EG-Q----T--H---N---------N-----I-------G--------D----D-RLGLVLREPVGVVGIITPWNFPFII--ASERVPWAIGSGCTVVLKPSEFTSGTSIRLAELA----RE-AGIPDGVFNVVTGY---G---D-P-AGQVLAEDP-NVDVAFTGSVRVGTKLGEI--------AA------R------T------V------KRVGL--ELGGKGPQIVFADA---D-----LDAA--ADG-IAYGVYHNAGQCCISGS-RLL-VQE---------GIR-DALE-RLLDI-SRK---------------VAFGD-P-L-NE-RTKIGA-ISEAHAEKVHSYVTAGI--TSGAE-LLL-GGER-I----G--------RE---AGLYYAPTVF--A---G-VTP-D---SIAREEIFGPVLSTLTF--K--T------AD-EA-VALA-NA-TE---FGLSASVWST--N-LETALQT--IRRIR--AGRCWINS-V-I------------D---G---------TP---E-LPIGGY--KKSGL-G--RE--LG-R-YG-FDEYSQFKGVHVTLGR---PA--P---WFT------------*

C;cover size:479; local alignment length=479 (original info = 3I44A	476	1044.02	0	52)
>P1;3I44A
structureN:3I44A: 1: : 476: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------M-L-N-K-----R-KF-----------Y-------INGLW---------D-DPS-TP-HDL-YVIDPS-T-E-E-AC-AVI---------SLGSTRDADKAINAAKKAFQ-----T--WKTTS-PHERLGFVEKILEIYE-K-R-SSDMAKTISMEMGAPIDMALNA-QTAT----GSSHIRNFIK----AY-KE-F----SF-Q----E--A---L---------I-----E----------------G----N-EQAILHYDAIGVVGLITPWNWPMNQ--VTLKVIPALLAGCTMVLKPSEIAPLSAMLFAEI----LDE-AALPSGVFNLINGD---G---A-N-VGSYLSAHPDLEMISFTGSTRAGKDISKN--------AS------N------T------L------KRVCL--ELGGKGANIIFADA---D-----ID-A--LQR-GVRHCFYNSGQSCNAPT-RML-VEQ---------AIY-DKAIKTAKDI-AEK---------------TQVGP-G-H-QT-GNHIGPVVSKEQYDKIQDLIQSGI--DEGAT-LVT-GGTG-LPMG-M--------E----RGYYVRPTVF--A---D-VKPHM---RIFREEIFGPVLSLLPF--N--T------ED-EA-VTLA-ND-TE---YGLTNYIQSQ--D-RSKCRRI--AAQVR--SGMVEVNG-H-E----------------L---------PG---G-SYFGGV--KFSGR-A--RE--GG-L-WG-IKEFLDTKAISYW-----------------------------*

C;cover size:486; local alignment length=486 (original info = 3JU8A	480	1044.39	0	53)
>P1;3JU8A
structureN:3JU8A: 1: : 480: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------------S-TH-----------Y-------IAGQW---------L-AG--QG-ETL-ESLDPV-G-Q-G-VV-WSG---------RGADATQVDAAVCAAREAFP-----A--WARRP-LEQRIELLERFAATLK-S-R-ADELARVIGEETGKPLWESA-T-EVTS----VNKVAISVQA----FR-ER-T----GE-K----S--G---P---------L----------------------A----D-ATAVLRHKPHGVVAVFGPYNFPGHL--PNGHIVPALLAGNCVVFKPSELTPKVAELTL----KAWIQ-AGLPAGVLNLVQG----G---R-E-TGVALAAHRGLDGLFFTGSSRTGNLLHSQ--------FG------G------Q------P------QKILA--LEGGNNPLVVEEVA---D-----LDAA--VYT-IIQSAFISAGQRCTCAR-RLL-VPQ---------GAWGDALLARLVAV-SAT---------------LRVGR-F-D-EQ-PAPFGAVISLSAAEHLLKAQEHLI--GKGAQ-PLL-ATQP-I----D-------------GAALLTPGIL--D-----VSAVA---ERPDEEFFGPLLQVIRY--S--D------FA-AA-IREA-NA-TQ---YGLAAGLLSD--S-RERFEQF--LVESR--AGIVNWNK-Q-L-T----------G---A---------AS---S-APFGGI--GASGN-H--RP--SA-Y-YA-ADYCAYPVASLESPSV---SL--PAT-LTP------GI----*

C;cover size:461; local alignment length=461 (original info = 3VZ3A	453	1044.68	0	54)
>P1;3VZ3A
structureN:3VZ3A: 1: : 453: : : :6.0: 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------AI-ATINPT-T-G-E-IC-QRF---------KALTPAEIDAKLAKAQEAFQ-----A--YRRTS-FSQRRQWLENAAAILE-R-D-TSKFAEIMTTEMGKTHQSAI-A-EAEK----SALVCRYYAE----HG-EQ-F----LA-N----E--Y---T---------E-----T----------------Q----A-TESYVCYQPLGILLAVMPWNFPFWQ--VFRFAAPALMAGNVAVLKHASNVPQCALAVEAIL----EA-AGFPEGVFQTLLI----G---A-S-QVEQVIKDPRVKAATLTGSEPAGASLASL--------AG------Q------E------I------KPTLL--ELGGSDPFVVFPSA---D-----LDEA--VEV-GTVARTMNNGQSAIAAK-RFI-LHE---------AIA-AEFLEKLHLK-FAS---------------LKIGD-P-M-AP-ETDIGPLATEGILQDISRQVDQAV--AAGAK-ILL-GGRP-L----D--------R----AGYFYPPTIL--T---E-IPPGA---KILQEELFAPVAMVFTV--K--D------LD-QA-IALA-ND-IP---FGLGASAWTN--D-PAEQQRF--IQELD--AGAVFING-M---V----------K---S---------DP---R-LPFGGT--KRSGY-G--RE--LG-L-AG-IRTFVNAKTVWLK-----------------------------*

C;cover size:491; local alignment length=491 (original info = 5U0LA	488	1041.76	0	55)
>P1;5U0LA
structureN:5U0LA: 1: : 488: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------N-L-T-----G-NV-----------Y-------IDGLW---------L-PG--HG-APF-ESVQPV-T-G-E-TV-WDG---------NAASLEDVDAAVREARKAFL-----A--WRRKS-LAERQAVIEAFGELLE-A-N-KEELAHQIGLETGKPLWESR-T-EVAA----MMGKIPISVK----AY-NE-R----TG-H----T--E---S---------D-----V----------------A----G-GHAVLRHRPHGVVAVFGPYNFPGHL--PNGHIVPALLAGNTVVFKPSELTPGVAELTVRLW----EK-AGLPDGVINLVQG----G---S-D-TGKCLARHSLIDGLFFTGSSTVGHLLHEQ--------FG------GQ-----P------E------KILAL--EMGGNNPLIVQNVS---D-----LDGA--VHH-ALQSAFLSAGQRCTCAR-RLL-VPK---------GKKGDEFLARLVEV-AAR---------------ITVAEFD-A-DP-QPFMGSVISAEAANQLLKAQAAML--EKGAT-SLL-EMKQ-L----K--------P----DTGLLSPGIV--D---A-T--GI---ELEDQEFFGPLLTVYRY--K--G------FD-EA-LELA-NN-TR---YGLSAGILSD--D-RKLYNRL--VEEVR--AGIVNWNR-P-L-T----------G---A---------SS---A-APFGGV--GASGN-H--RP--SA-Y-YA-AD-YCAWPMASLEAGKS--EL--PDS-LAP------GL-NF-*

C;cover size:475; local alignment length=475 (original info = 4QYJA	481	1053.61	0	56)
>P1;4QYJA
structureN:4QYJA: 1: : 481: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------------------QM-----------L-------IGGQW---------V-SAQ-SG-KTL-NVYNPA-T-G-D-IL-TEV---------PDGDVEDVNAAVESAAATLRSD---T--WRRMP-PSARERILLRLADLLE-V-H-GDELARLETLNNGKLLIYSKLM-EVGA----SAQWLRYMAG----WA-TK-L----TG-S----T--L---D---------L-----S-------LPLPPE---V----R-SRASTQRVPVGVVAAIIPWNFPLLM--AVWKIAPALACGNTVVLKPAEETPLTALRLAELA----ME-AGLPAGALNVVTGR---G---E-T-AGDALVRHPKVAKVAFTGSTEVGRIIGSA--------CG------R------S------L------KAVSL--ELGGKSPVIVLADC---D-----PQEA--AEG-AAAAIFFNHGQVCTAGS-RLY-VHE---------SIY-EDVIQRLAVI-GES---------------IVVGS-G-L-EQ-GVHMGPMVSKKHHENVLRHIRNGI--EDGAD-LIC-GGTEAP----C--------A----QGFFVKPTIF--A---NREKKDI---RLLSQEVFGPVLVATPF--S--D------IA-EV-VNEA-NR-SV---YGLGASIWTN--D-LSAALRI--NDELE--AGTVWVNT-H---N----------M---V---------DP---N-LPFGGF--KDSGV-G--RE--HG-A-AA-IEHYTTTRSLVIAY----------------------------*

C;cover size:489; local alignment length=489 (original info = 4KNAA	487	1040.03	0	57)
>P1;4KNAA
structureN:4KNAA: 1: : 487: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------M-----T-EL-----------F-------IDGAW---------V-DG--AG-PVF-ASRNPG-T-N-E-RV-WEG---------ASASADDVERAVASARRAFA-----A--WSALD-LDARCTIVKRFAALLV-E-R-KEALATMIGRETGKPLWEAR-T-EVAS----MAAKVDISIT----AY-HE-R----TG-E----K--R---A---------P-----M----------------A----D-GVAVLRHRPHGVVAVFGPYNFPGHL--PNGHIVPALIAGNTVVFKPSELAPGVARATVEI----WRD-AGLPAGVLNLVQG----E---K-D-TGVALANHRQIDGLFFTGSSDTGTLLHKQ--------FG------G------RP-----E------IVLAL--EMGGNNPLVVAEVE---D-----IDAA--VHH-AIQSAFLSAGQRCTCAR-RIL-VPR---------GAFGDRFVARLADV-ASK---------------ITASVFD-A-DP-QPFMGAVISARAASRLVAAQARLV--GLGAS-PII-EMKQ-R----D--------P----ALGFVNAAIL--D-----VTNVR---ELPDEEHFGPLAQIVRY--T--D------LD-DA-IARA-ND-TA---FGLSAGLLAD--D-EQAWHTF--RRAIR--AGIVNWNR-P-T-N----------G---A---------SS---A-APFGGA--GRSGN-H--RP--SA-Y-YA-ADYCAYPMASVESAQL---QM--PAS-LSP------GL-HF-*

C;cover size:477; local alignment length=477 (original info = 4I3WA	473	1036.51	0	58)
>P1;4I3WA
structureN:4I3WA: 1: : 473: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------H-----E-PM-----------R-------IAGRL---------V-D---TD-DRV-EVRYPW-N-D-T-VV-GTV---------PAGRAEHAREAFAIAAA--------Y--QPKLT-RYERQKILLATAEALA-A-R-KEEISDVITLELGISKADSL-Y-EVGR----AFDVFTLAGQ----MC-IR-D----DG-E----I--F---S---------C-----D-------L--------TPHGKA-RKIFTMREPLTAISAITPFNHPLNM--VAHKVAPAIATNNCVVVKPTELTPMTALLLADIL----YE-AGLPPEMLSVVTGW---P---A-D-IGMEMITNPHVDLVTFTGSVPVGKLIAAN----------------A------H------Y------KRQVL--ELGGNDPLIILNDLSDDD-----LARA--ADL-AVAGATKNSGQRCTAVK-RIL-CQE---------SVA-DRFVPLVLER-AKR---------------LRFGD-P-M-DR-STDLGTVIHEKAAALFEERVMRAA--EEGAD-ILY-HPGR--------------------SGALLPPIVV--D---R-VPHQS---DLVLEETFGPIIPIVRV--P--D------DD-DATITLS-NS-TA---FGLSSGVCTN--D-YRRMQKY--IAGLK--VGTVNIWE-V-P-G----------Y---R---------IE---M-SPFGGI--KDSGN-G--YK--EG-VIEA-MKSFTNVKTFSLPW----------------------------*

C;cover size:466; local alignment length=466 (original info = 3PQAA	456	1027.68	0	59)
>P1;3PQAA
structureN:3PQAA: 1: : 456: : : :6.0: 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------I---NR-EDM-DVINPY-S-L-E-VI-KKI---------PALSREEAKEAIDTAEKYKE-----V--MKNLP-ITKRYNILMNIAKQIK-E-K-KEELAKILAIDAGKPIKQAR-V-EVER----SIGTFKLAAF----YV-KE-H----RD-E----V--I---P---------S----------------------D----D-RLIFTRREPVGIVGAITPFNFPLNL--SAHKIAPAIATGNVIVHHPSSKAPLVCIELAKIIENALKK-YNVPLGVYNLLTGA---G---E-V-VGDEIVVNEKVNMISFTGSSKVGELITKK--------AG--------------------F------KKIAL--ELGGVNPNIVLKDA---D-----LNKA--VNA-LIKGSFIYAGQVCISVG-MIL-VDE---------SIA-DKFIEMFVNK-AKV---------------LNVGN-P-L-DE-KTDVGPLISVEHAEWVEKVVEKAI--DEGGK-LLL-GGKR--------------------DKALFYPTIL--E-----VDRDN---ILCKTETFAPVIPIIRT--N--E-------E-EM-IDIA-NS-TE---YGLHSAIFTN--D-INKSLKF--AENLE--FGGVVIND-S-S-L----------F---R---------QD---N-MPFGGV--KKSGL-G--RE--GV-K-YA-MEEMSNIKTIIISK----------------------------*

C;cover size:499; local alignment length=499 (original info = 4LIHA	494	1023.52	0	60)
>P1;4LIHA
structureN:4LIHA: 2: : 494: : : :6.0: 
LT----------------------------------------------LA------D---------------W-------------QH---------------K--AA---------S-----L-E-I-E-----G-RA-----------F-------IDGAS---------R-DAH-GG-RTF-DCVSPI-D-G-R-VL-AKV---------ADCGEADVNAAVAAARRAFDAG---V--WAGLN-PRARKAVLLRWAALMR-E-H-LDELSLLETLDAGKPIGDTTTV-DVPG----AAYCVEWFAE----AI-DK-V----GG-E----V--A---P---------A-----D----------------H----H-LVGLVTREPVGVVAAVVPWNFPILM--AAWKFGPALAAGNSVVLKPSEKSPLTAIRVAQLA----FE-AGIPAGVFNVVPG----A---G-E-PGKLLALHRDVDCIAFTGSTAVGKLIMQY--------AA------QS-----N------L------KRAWL--ELGGKSPNIVLPDCP--D-----LDRA--AQT-AAGAIFYNMGEMCTAGS-RLL-VHR---------DIK-DAFIEKLVAA-ARA---------------YVPGN-P-L-DP-SVSMGAIVDGIQLERVLGYIEAGR--GEGRL-VTG-GARV-N----A--------ET---GGFYVEPTVF--E-----VKPDA---KIAREEIFGPVLSVIVF--D--D------VD-EA-VRIA-ND-TE---YGLAAAVWTS--N-LTTAHDV--SRRLR--AGTVWVNC-Y-D-E----------G---G---------DM---N-FPFGGY--KQSGN-G--RD--KS-L-HA-LEKYTELKSTLIRLR---------------------------*

C;cover size:491; local alignment length=491 (original info = 4PZ2A	491	1019.57	0	61)
>P1;4PZ2A
structureN:4PZ2A: 1: : 491: : : :6.0: 
-----------------------------------------------------------------------------------------------------L-F--DV---------P-----E-I-R-F-----T-KL-----------F-------INGSF---------V-DAV-SG-RTF-DTRDPR-T-G-G-VI-ASV---------AEADKEDVDLAVRAARAAFDHG---E--WPRMS-GSERGRIMARLADLVE-E-H-AGELAALESLDAGKHPAVTRAV-DVGN----AAGSLRYFAG----AA-DK-I----HG-E----T--L---K---------M-----P-------G-------------Q-FQGHTLREPLGVAGVIIPWNFPSTM--FAVKVAPALAAGCALVVKPAEQTPLSALYLAQL----AKQ-AGVPDGVINVVPGF---G---P-T-AGAALASHMDVDMVSFTGSTEVGRLIMKA--------SA------ES-----N------L------KPVYL--ELGGKSPLIVFDDA---D-----LDMA--VEL-AVGASFFNKGEACVAAS-RVY-VQE---------RVY-DRFEERLAER-MRS---------------WVVGD-P-FSDP-RADQGPQVDKAQYERVLSYIDHGK--REGAT-LLT-GGRP-C----A--------P----KGYYIEPTVF--T---N-VKEDM---IIAKEEIFGPVMCLMKF--K--T------VE-EA-IARA-ND-TR---YGLGAGVVTR--D-LDVANRV--VRSVR--AGVVWVNC---Y-F----------A---M---------GS---D-CPFGGR--KMSGF-G--KD--EG-M-HA-LDKYLAVKSVVTPLRA---SP--W---I--------------*

C;cover size:498; local alignment length=498 (original info = 4PS9A	491	1012.34	0	62)
>P1;4PS9A
structureN:4PS9A: 1: : 491: : : :6.0: 
-T-------------NI-----------------------------ELKP------K---------------VE------------AF-------------L-----------------------N-E-E-----I-KM-----------F-------INGEF---------V-SAI-GG-KTF-ETYNPA-T-E-D-VL-AVV---------CEAQEEDIDAAVKAARSAFESG---P--WAEMT-TAERAHLIYKLADLIE-E-H-REELAQLEALDNGKPYQVALDD-DISA----TVENYRYYAG----WT-TK-I----IG-Q----T--I---P---------I-------------S--------K----D-YLNYTRHEPVGVVGQIIPWNFPLVM--SSWKMGAALATGCTIVLKPAEQTPLSLLYAAK----LFKE-AGFPNGVVNFVPGF---G---P-E-AGAAIVNHHDIDKVAFTGSTVTGKYIMRQ--------SA------E------M------I------KHVTL--ELGGKSPNIILEDA---D-----LEEA--ING-AFQGIMYNHGQNCSAGS-RVF-VHR---------KHY-ETVVDALVKM-ANN---------------VKLGA-G-M-EK-ETEMGPLVSKKQQERVLNYIEQGK--KEGAT-VAA-GGER-A----L--------E----KGYFVKPTVF--T---D-VTDDM---TIVKEEIFGPVVVVLPF--D--S------TE-EV-IERA-NN-SS---YGLAAGVWTQ--N-IKTGHQV--ANKLK--AGTVWIND-Y---N----------L---E---------NA---A-APFGGY--KQSGI-G--RE--LG-S-YA-LDNYTEVKSVWVNIK---------------------------*

C;cover size:465; local alignment length=465 (original info = 3ETFA	445	1020.52	0	63)
>P1;3ETFA
structureN:3ETFA: 1: : 445: : : :6.0: 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------A-TQA-LSVNPA-T-G-Q-TL-A-A---------PWANAQEIEHALSLAASGFK-----K--WKT-S-VAQRAQTLRDIGQALR-A-H-AEEAQCIT--REGKPIKQAR-A-EVTK----SAALCDWYAE----HG-PA-L----NP-E----P--T---L---------V----------------------E----N-QQAVIEYRPLGVILAI-PWNFPLWQ--VLRGAVPILLAGNSYLLKHAPNVTGCAQ-----IARILAE-AGTPAGVYGWVNA----N---N---EGVSQINDPRIAAVTVTGSVRAGAAIGAQ--------AG------A------A------L------KKCVL--ELGGSDPFIVLNDA---D-----LELA--VKA-AVAGRYQNTGQVCAAAK-RFI-VEE---------GIA-QAFTDRFVAA-AAA---------------L-KGD-P-L-VE-ENDLGPARFD-LRDELHQQVQASV--AEGAR-LLL-GGEK-I----A--------G----EGNYYAATVL--A---D-VTPDT---AF-RQELFGPVAAITVA--K--D------AA-HA-LALA-ND-SE---FGLSATIFTA--D-DTLAAEA---ARLE--CGGVFING-Y-S------------A---S---------DA---R-VAFGGV--KKSGF-G--RE--LS-H-FG-LHEFCNVQTVWKNRV---------------------------*

C;cover size:511; local alignment length=511 (original info = 3V9JA	544	1015.38	0	64)
>P1;3V9JA
structureN:3V9JA: 8: : 544: : : :6.0: 
TS-------------SL-------KV--------------------ANEP------I---------------LAFSQGSPERDALQKA-------------L-K--DL---------K-----G-Q-TEA-----I-PC-----------V-------VGDEE---------V-W---TS-DIQ-YQLSPF-NHA-H-KV-AKF---------CYADKALLNRAIDAALAARK-----E--WDLKP-MADRAQVFLKAADMLS-G-PRRAEVLAKTMVGQGKTVIQAEID-AAAE----LIDFFRFNAK----FA-VE-L----EG-E----Q--P---I---------S-----V-------P--------P----S-TNHTVYRGLEGFVAAISPFNFTAIG--GNLAGAPALM-GNVVLWKPSDTAMLASYAVYRIL----RE-AGLPPNIIQFVPAD---G---P-T-FGDTVTSSEHLCGINFTGSVPTFKHLWRQ--------VA------QNLDRFRT------F------PRLAG--ECGGKNFHFVHSSA---D-----VDSV--VSG-TLRSAFEYGGQKCSACS-RLY-VPK---------SLW-PQIKGRLLEE-HSR---------------IKVGD-P-AEDF-GTFFSAVIDAKAFARIKKWLEHAR--SSPSL-SILAGGQC-N----E--------S----VGYYVEPCII--E---S-KDPQE---PIMKEEIFGPVLTVYVY--PDDK------YR-ET-LKLV-DSTTS---YGLTGAVFAQ--D-KAIVQEA--TRMLRNAAGNFYIND-K-S-T----------GS--V---------VG---Q-QPFGGA--RASGT-N--DK--PGGP-HY-ILRWTSPQVIKETHKP---LG--D---WRY------SY--MQ*

C;cover size:475; local alignment length=475 (original info = 3R64A	468	1029.02	0	65)
>P1;3R64A
structureN:3R64A: 1: : 468: : : :6.0: 
--------------------------------------------------------------------------------------TF-------------------A---------G-----I---D-A-----T-KH-----------L-------IGGQW---------V-EGN-SD-RIS-TNINPY-D-D-S-VI-AES---------KQASIADVDAAYEAAKKAQA-----E--WAATP-AAERSAIIYRAAELLE-E-H-REEIVEWLIKESGSTRSKAN-L-EITL----AGNITKESAS----FP-GR-V----HG-R----I--S---P---------S-----N-------T--------P----G-KENRVYRVAKGVVGVISPWNFPLNL--SIRSVAPALAVGNAVVIKPASDTPVTGGVI---PARIFEE-AGVPAGVISTVAGA---G---S-E-IGDHFVTHAVPKLISFTGSTPVGRRVGEL--------AI------N------GGP----M------KTVAL--ELGGNAPFVVLADA---D-----IDAA--AQA-AAVGAFLHQGQICMSIN-RVI-VDA---------AVH-DEFLEKFVEA-VKN---------------IPTGD-P-S-AE-GTLVGPVINDSQLSGLKEKIELAK--KEGAT-VQV-EGPI--------------------EGRLVHPHVF--S---D-VTSDM---EIAREEIFGPLISVLKA--D--D------EA-HA-AELA-NA-SD---FGLSAAVWSK--D-IDRAAQF--ALQID--SGMVHIND-R-F-N--------------G---------DWA--I-EEFTTD--RWIGI-K--RS--AE-N-LY-FQ----------------------------------------*

C;cover size:462; local alignment length=462 (original info = 4OGDA	455	1018.65	0	66)
>P1;4OGDA
structureN:4OGDA: 1: : 455: : : :6.0: 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------AY-QTIYPY-T-N-E-VL-HTF---------DNMTDQGLADVLERAHLLYK-----K--WRKEDHLEERKAQLHQVANILR-R-D-RDKYAEIMTKDMGKLFTEAQ-G-EVDL----CADIADYYAD----KA-DE-F----LM-S----T--P---L---------E-----T----------------D----S-GQAYYLKQSTGVILAVEPWNFPYYQ--IMRVFAPNFIVGNPMVLKHASICPRSAQSFEELV----LE-AGAEAGSITNLFI----S---Y-D-QVSQVIADKRVVGVCLTGSERGGASIAEE--------AG------K------N------L------KKTTL--ELGGDDAFIILDDA---D-----WDQL--EKV-LYFSRLYNAGQVCTSSK-RFI-VLD---------KDY-DRFKELLTKV-FKT---------------AKWGD-P-M-DP-ETTLAPLSSAQAKADVLDQIKLAL--DHGAE-LVY-GGEA-I----D--------H----PGHFVMPTII--A---G-LTKDN---PIYYQEIFGPVGEIYKV--S--S------EE-EA-IEVA-ND-SN---YGLGGTIFSS--N-QEHAKAV--AAKIE--TGMSFINS-G-W------------T---S---------LP---E-LPFGGI--KHSGY-G--RE--LS-E-LG-FTSFVNEHLIYIPN----------------------------*

C;cover size:453; local alignment length=453 (original info = 1AD3A	446	1018.16	0	67)
>P1;1AD3A
structureX:1AD3A: 1: : 442: : : :2.6: 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SISDTVKRAREAFN-----S--GKTRS-LQFRIQQLEALQRMIN-E-N-LKSISGALASDLGKNEWTSYYE-EVAH----VLEELDTTIK----EL-PD-W----AE-D----E--PVAKT---------R-----Q-------T--------Q----Q-DDLYIHSEPLGVVLVIGAWNYPFNL--TIQPMVGAVAAGNAVILKPSEVSGHMADLLATLI-----P-QYMDQNLYLVVKGG---V---P-E-TTELL--KERFDHIMYTGSTAVGKIVMAA--------AA------K------H------L------TPVTL--ELGGKSPCYVDKDC---D-----LDVA--CRR-IAWGKFMNSGQTCVAPD-YIL-CDP---------SIQ-NQIVEKLKKS-LKD---------------F-YGE-D-A-KQ-SRDYGRIINDRHFQRVKGLID-------NQK-VAH-GGTW-D----Q-------------SSRYIAPTIL--V---D-VDPQS---PVMQEEIFGPVMPIVCV--R--S------LE-EA-IQFI-NQ-RE---KPLALYVFSN--N-EKVIKKM--IAETS--SGGVTAND-V-IVH----------I---T---------VP---T-LPFGGV--GNSGM-G--AY--HG-K-KS-FETFSHRRSCLVKSLL---NEE-A---H--------KA-RYP*

C;cover size:488; local alignment length=488 (original info = 4PXLA	485	992.50	0	68)
>P1;4PXLA
structureN:4PXLA: 1: : 485: : : :6.0: 
-----------------------------------------------------------------------------------------------------------V---------E-----V---R-F-----T-KL-----------F-------IDGKF---------V-DAV-SG-KTF-ETRDPR-T-G-E-VI-ASI---------AEGDKADVDLAVKAAREAFDNG---P--WPRMT-GYERGRILHRFADLID-E-H-VEELAALDTVDAGKLFAVGK-ARDIPG----AAHLLRYYAG----AA-DK-V----HG-A----T--L---K---------M-----A-------Q-------------R-MHGYTLKEPVGVVGHIVPWNYPTTM--FFFKVGPALAAGCAVVVKPAEQTPLSALFYAHLA----RE-AGVPAGVLNVVPGF---G---P-T-AGAAVAAHMDVDKVSFTGSTEVGRLVMRA--------AA------ES-----N------L------KPVSL--ELGGKSPVIVFDDA---D-----LDMA--VNL-VNFATYTNKGEIV-AGT-RIY-VQE---------GIY-DEFVKKAAEL-ASK---------------SVVGD-P-F-NP-SVSQGPQVDKDQYEKVLRYIDIGK--REGAT-LVT-GGKP-C----G--------D----KGYYIEPTIF--T---D-VKDDM---TIAQDEIFGPVMALMKF--K--T------VE-EV-IQKA-NN-TR---YGLAAGIVTK--N-IDVANTV--SRSIR--AGAIWINC-Y---F----------A---F---------DP---D-APFGGY--KMSGF-G--KD--MG-M-DA-LDKYLQTKTVVTPLYN---TP--W---L--------------*

C;cover size:506; local alignment length=506 (original info = 4IHIA	535	991.97	0	69)
>P1;4IHIA
structureN:4IHIA: 15: : 535: : : :6.0: 
VH-------------DY-------A---------------------PKSP------E---------------RTRLRTEL------AS-------------L-A--D----------------H-P-I-D-----L-PH-----------V-------IGGRH---------R-MG--DG-ERI-DVVQPH-RHA-A-RL-GTL---------TNATHADAAAAVEAAMSAKS-----D--WAALP-FDERAAVFLRAADLLA-G-PWREKIAAATMLGQSKSVYQAEID-AVCE----LIDFWRFNVA----FA-RQ-I----LE-Q----Q--P---I---------S-----G-------P--------G----E-WNRIDYRPLDGFVYAITPFNFTSIA--GNLPTAPALM-GNTVIWKPSITQTLAAYLTMQLL----EA-AGLPPGVINLVTGD---G---F-A-VSDVALADPRLAGIHFTGSTATFGHLWQW--------VG------T------N------IGRYHSYPRLVG--ETGGKDFVVAHASA---R-----PDVL--RTA-LIRGAFDYQGQKCSAVS-RAF-IAH---------SVW-QRMGDELLAK-AAE---------------LRYGD-I-T-DL-SNYGGALIDQRAFVKNVDAIERAK--GAAAV-TVAVGGEY-D----D--------S----EGYFVRPTVL--L---S-D----------DPEYFGPLLSVHVY--P--DER----YE-QI-LDVIDTG-SR---YALTGAVIAD--D-RQAVLTA--LDRLRFAAGNFYVND-K-P-TG---------A---V---------VG---R-QPFGGA--RGSDT-N--DK--AGSP-LN-LLRWTSARSIKETFVA---ATDHIYPHMAV------------*

C;cover size:477; local alignment length=477 (original info = 4DALA	464	991.90	0	70)
>P1;4DALA
structureN:4DALA: 1: : 464: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------D-----T-QL-----------L-------IGSRF---------E-AG--TE-AEE-HILNPR-T-G-A-GI-IDL---------AEASHAQIDAAVDAAERAFV-----G--WSQTT-PAERSNALLKIADAIE-K-E-ADEFAALEALNCGKPINAVKND-ELPA----IIDCWRFFAG----AV-RN-L----HA-P----A--A---G---------E-----Y-------L--------P------GHTSIRRDPIGIVGSIAPWNYPL-----AWKLAPAIGGGNTVVFKPSEQTPLTALKLARLIADI------LPEGVVNVITGR---G---E-T-VGNALINHPKV-GVSITGDIATGKKVLAA--------AA------K------T------V------KRTHL--ELGGKAPVIVYGDA---D-----LEAV--VNG-IRTFGYYNAGQDCTAAC-RIY-AEA---------GIY-EKLVADLTSA-VST---------------IRYNL-D-D-DT-ENEIGPLISRRQRDRVASFVERAA--DQKHI-EIT-TGGR-TG---S--------D----EGFFFQPTVV--A---G-ATQED---EIVRREVFGPVVSVTRF--T--G------KD-DA-VAWA-ND-SD---YGLASSVWTK--D-ISKARA---ASRLQ--YGCTWINT----------------H---F---------LT---N-EPHGGI--KQSGY-G--KD--S--V-YA-LEDYTAVRHIINHG----------------------------*

C;cover size:465; local alignment length=465 (original info = 3ROSA	449	996.02	0	71)
>P1;3ROSA
structureN:3ROSA: 1: : 449: : : :6.0: 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SKY-QSVNPY-T-N-E-AF-ASY---------DNPTSKQIDEAINLAHALYK-----K--WRHEE-PASRAEILHDIANALK-E-H-EDELAK---TLEGKLLSESK-E-EVEL----CVSICNYYAD----HG-PE-L----KP-T----K--L---N---------S-----D---------------------L-GNAYYLKQSTGVIA-CEPWNFPLYQ--VIRVFAPNFIVGNPILLKHAHNVPGSAALTAKII----KR-AGAPEGSLINLYP----S---Y-D-QLADIIADPRIQGVALTGSERGGSAVAEA--------AG------K------N------L------KK-ST--ELGGNDAFIVLDDA---D-----PQVL--RNV-LNDARTYNDGQVCTSSK-RII-VEK---------SRY-DEVLHELKNV-FSN---------------LKAGD-P-L-EA-DTTLPP-NSEKAKEKLEAQVKEAI--DAGAK-VFY-QYPE-I----D--------S----KGAFFRPTIL--T---D-IAKDN---PVFDKEVFGPIAEVFVV--E--D------DN-AA-IQLA-ND-SS---YGLGSSVIGS--D-IDRAKKV--SAQIE--TGTVINGR-W--------------I---T---------SG---E-LPFGGI--KKSGY-G--RE--LS-G-LG-LAFVNEHLVIDVTKNN--------------------------*

C;cover size:460; local alignment length=460 (original info = 4DNGA	452	990.26	0	72)
>P1;4DNGA
structureN:4DNGA: 1: : 452: : : :6.0: 
-----------------------------------------------------------------------------------------------------------M---------S-----F-E-T-L-----N-KS-----------F-------INGKW---------T-GGE-SG-RTE-DILNPY-D-Q-S-VI-TTA---------SLATGKQLEDAFDIAQKAQK-----E--WAKST-TEDRKAVLQKARGYLH-E-N-RDDIIMMIARETGGTIIKST-I-ELEQ----TIAILDEAMT----YT-GE-L----GGVK----E--V---P---------S-----D-------I--------E----G-KTNKIYRLPLGVISSISPFNFPMNL--SMRSIAPAIALGNSVVHKPDIQTAISGGT---IIAKAFEH-AGLPAGVLNVMLTD---V---K-E-IGDGMLTNPIPRLISFTGSTAVGRHIGEI--------AG------R------A------F------KRMAL--ELGGNNPFAVLSDA---D-----VDRA--VDA-AIFGKFIH----QMIIN-RII-VHQ---------DVY-DEFVEKFTAR-VKQ---------------LPYGD-Q-T-DP-KTVVGPLINERQIEKALEIIEQAK--TDGIE-LAV-EGKR--------------------VGNVLTPYVF--V---G-ADNNS---KIAQTELFAPIATIIKA--G--S------DQ-EA-IDMA-ND-TE---YGLSSAVFTS--D-LEKGEKF--ALQID--SGMTHVND-Q-N-P--------------W---------VV---EEFTVTKW--ISIQK----------------------------------------------------------*

C;cover size:478; local alignment length=478 (original info = 1EZ0A	504	1006.68	0	73)
>P1;1EZ0A
structureX:1EZ0A: 1: : 490: : : :2.10: 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------TD-NVF-YATNAF-T-G-E-ALPLAF---------PVHTEVEVNQAATAAAKVAR-----D--FRRLN-NSKRASLLRTIASELE-A-R-SDDIIARAHLETALPEVRLT-G-EIAR----TANQLRLFAD----VV-NS-G----SY-H----Q--A---I---------L-----D-------TPNPTRAPLP----K-PDIRRQQIALGPVAVFGASNFPLAFSAAGGDTASALAAGCPVIVKGHTAHPGTSQIVAECIEQALKQ-EQLPQAIFTLLQGN---Q---R-A-LGQALVSHPEIKAVGFTGSVGGGRALFNL--------AH------E------R------P------EPIPFYGELGAINPTFIFPSA---M-----RAKADLADQ-FVASMTMGCGQFCTKPG-VVFALNT---------PET-QAFIETAQSL-IR----------------------Q-Q-SP-STLLTPGIRDSYQSQV---VSRGS--DDGID-VTF-SQAE-S----P--------CVA--SALFVTSS--------E-NWRKH---PAWEEEIFGPQSLIVVC--E--N------VA-DM-LSLS-EM-LA---GSLTATIHATEED-YPQVSQL--IPRLEEIAGRLVFNG-W-P-T----------GVEVG---------YA---M-VHGGPY--PASTH-S--ASTSVG-A-EA-IHRWLRPVAYQA--LP---ES--L---LPD------SL-KAE*

C;cover size:492; local alignment length=492 (original info = 3RH9A	467	985.14	0	75)
>P1;3RH9A
structureN:3RH9A: 1: : 467: : : :6.0: 
----------------------------------------------IE----------------------------------------------------------S----------P-----L-L-E-N-----L-TG-----------Y-------IGGRW---------K-DSA-GG-ATF-DVYNPA-T-G-S-VI-AKV---------PSP-EEDVVAAVEAGQSALR-----L--TNPWP-IETRRKWLEDIRDGLK-E-N-REEIGRIL-CEHGKPWKEAQ-G-EVDY----AAGFFDYCAK----HI-SA-L----DS-H----T--I---P---------E-----K-------P--------K----D-CTWTVHYRPVGVTGLIVPWNFPIGI---AKKLSAALAAGCPSVIKPASETPLTIAFFS------VDK-LDLPDGV--NLVGK---A---S-V-IGKVLCEHK-DVPLSFTGSTEVGRKLIVD--------TA------E------Q------V------KKLAL--ELGGNAPFIVFDDA---D-----LEAA--ADN-LIANKFRGGGQTCVCAN-RIF-VHE---------KVA-DAFGQKLAER-VNK----------------TVGD-G-N-D--GIDIGPLINKQGFDKVKRHLQDAL--DKGAS-LVA-GKQP-A----EL-------G----DGLFFPPTVV--Q---G-VDREC----CYQEETFGPLVPAL-F--R--T------EE-EV-IDAG-ND-TE---FGLASYVFTA--D-AERAQRV--AAGLR--FGHVGWNT-G-T------------G---P---------TP---E-APFGG---KASGI-G--RE--GG-L-EG-LFEFVEAQTVPRG-----------------------------*

C;cover size:479; local alignment length=479 (original info = 4H7NA	462	977.89	0	76)
>P1;4H7NA
structureN:4H7NA: 1: : 462: : : :6.0: 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------N---AT-KTI-EVRNPR-T-G-K-FD-YVI---------IPPPPRLLAQQCNRARRAQS-----R--WQELG-VEGRITTLQQWKQAIL-S-R-REQLTEALVNDTGRLSITV--L-EIDS----FLASIDRWCG----LA-PE-L----LQ-T----S--A---K---------NT----S-------I--------P----F-IALQQSLVPYPLVGVISPWNFPLTL---SIDTIPALLAGCAVVVKPSEIAPRFVAPLLALNTV------PELRDVLIFVEG----G---G-E-TGANLINY--VDFVCFTGSVATGREVAET--------AA------R------R------F------IPAYL--ELGGKDPAIVLESA---N-----LELA--TSA-ILWGAVVNTGQSCLSIE-RIY-VAE---------SKF-EEFYHQLIAK-AHR---------------LQLAY-P-L-VE-DGAIGPIIAEKQAGIINDHILDAV--EKGAV-IHC-GGKV-E----EL-------G----GGWWCRPTVT--N-------VNH---SKVTEETFGPI--PVPF--P--D------VE-EA-VYLA-ND-TI---YGLSAAVFAG--S-EDEALKV--ARQLN--AGAISIND-A-A------------L---T---------AH---E-GEKNAF--NFSGLGG--SR--VG-A-AG-LKRFLRKQAFLIKTNS---TS--D---PW----------WFD*

C;cover size:484; local alignment length=484 (original info = 4E4GA	470	968.99	0	77)
>P1;4E4GA
structureN:4E4GA: 1: : 470: : : :6.0: 
-------------------------------------------------------------------------------------------------------------------------------Y-E-----L-GH-----------F-------IDGKR---------V-AGT-SG-RVS-NIFNPA-T-G-E-VQ-GTV---------ALASDADLAAAVESAKAAQP-----K--WAATN-PQRRARVF-KFVQLLN-D-N-NELAE--LSREHGKTIDDAK-G-DIVR----GLEVCEFVIG----IP-HL-Q----KS-E----F--T---E---------G-----A-------G--------P------GIDYSIRQPVGIGAGITPFNFPG-----IPWFAPAIACGNAFILKPSERDPSVPIRLAELI-----E-AGLPAGILNVVNG----D---K-G-AVDAILTHPDIAAVSFVGSTPIARYVYGT--------AA---------------------------NGKRA--QCFGGAKNHIIPDA---D-----LDQA--ANA-LIGAGYGSAGERCAISV-AVP-VGE---------ETA-NRLIDKLVPV-ES----------------LRIGP-Y-T--D-EKADGPVVTKEAEQRIRSLIDSGI--EQGAK-LVV-DGRD-F----K--------LQGYENGHFIGGCLF--D---D-VTP-D---DIYKTEIFGPVLSVVRA--R--N------YE-EA-LSLP-K--HE---YGNGVAIYTR--D-GDAARDF--ASRIN--IGVGVNVP-I-P------------V---P---------LA---Y-HSFGGW--KSSSF-GDLNQ--HG-T-DS-IKFWTRTKTITSRWPS---GI--K---D--------------*

C;cover size:462; local alignment length=462 (original info = 3VZ0A	445	965.01	0	78)
>P1;3VZ0A
structureN:3VZ0A: 1: : 445: : : :6.0: 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------IVY-QTLNPT-T-E-T-VE-RSF---------DLHTPAQKDITDRAEHVWKT-----D--WKLRS-IAQRKEIVSRAADLLR-R-D-RQHHASLIATE-GKALPDAL-E-EIDV----TADILSFYAN----GA-EE-F----LA-P----T--P---L---------K-----V----------------K----T-GQAKIINQPLGIIYCIEPWNFPYYQ--LARVAGPNLA-GNVVIAKHAPNVPQCALAFEKL----FHD-AGAPVGAYANIFL----D---N-D-QSAELIKDERIRGVALTGSERAGQAVAAQ--------AG------A------A------L------KK-DT--ELGGSDAFIVLDDA---D-----LDLA--VKW-AVWGRFANNGQVCTAAK-RI--VHE---------KVY-DAFLDGLKTA-ITR---------------FRIGN-P-L-DR-DTTHGPSSL--RAELALDQTAEAV--KGGAT-LVA-GGKR-D------------------RKGFFEPTIL--T---D-VSKDN---PVFYQEIFGPVAVVHKV--A--S------EQ-AA-IDLA-ND-SP---YGLGGAVFSR--D-IARAEKV--AEQVE--TG-VFINT-A-T------------A---A---------AP---E-LPFGGI--KNSGF-G--RE--LS-F-LG-IEEFINRKLVRIG-----------------------------*

C;cover size:476; local alignment length=476 (original info = 3V9IA	506	963.10	0	79)
>P1;3V9IA
structureN:3V9IA: 5: : 506: : : :6.0: 
TS-------------SLK------V---------------------ANEP------V---------------L-------------AFTQGSPERDALQKAL-K--DL---------K-----G-R-MEA-----I-PC-----------V-------VGDEE---------V-WT--SD-VQY-QVSPFN-H-G-H-KV-AKF---------CYADKSLLNKAIEAALAARK-----E--WDLKP-IADRAQIFLKAADMLSGP-R-RAEILAKTMVGQGKTVIQAEID-AAAE----LIDFFRFNAK----YA-VE-L----EG-P----S--T---N---------S--------------------------------TVYRGLEGFVAAISPFNFTAIG--GNLAGAPALM-GNVVLWKPSDTAMLASYAVYRIL----RE-AGLPPNIIQFVPAD---G---P-L-FGDTVTSSEHLCGINFTGSVPTFKHLWKQ--------VA------QNLDRF-H------T------FPRLA--GECGKNFHFVHRSA---D-----VESV--VSG-TLRSAFEYGGQKCSACL-RLY-VPH---------SLW-PQIKGRLLEE-HSR---------------IKVGD-P-AEDF-GTFFSAVIDAKSFARIKKWLEHAR--SSPSL-TIL-AGGKCD----D--------S----VGYFVEPCIV--E---S-KDPQE---PIMKEEIFGPVLSVYVY--P--DDK----YK-ET-LQLV-DSTTS---YGLTGAVFSQ--D-KDVVQEA--TKVLRNAAGNFYIND-K-S-T----------I---LRWTSPQVIKET---H-KPLGDW--SYAYM----------------------------------------------------------*

C;cover size:494; local alignment length=494 (original info = 5FHZA	489	941.80	0	80)
>P1;5FHZA
structureN:5FHZA: 1: : 489: : : :6.0: 
------------------------A---------------------LP--------------------------------------RP-------------I-R--NL---------E-----V-K-F-------T-KI-----------F-------INNEW---------H-ESK-SG-KKF-ATCNPS-T-R-E-QI-CEV---------EEGDKPDVDKAVEAAQVAFQRGS--P--WRRLD-ALSRGRLLHQLADLVE-R-D-RATLAALETMDTGKPFLHAF-FIDLEG----CIRTLRYFAG----WA-DK-I----QG-K----T--I---P---------T-----D----------------D----N-VVCFTRHEPIGVCGAITPWNFPLLM--LVWKLAPALCCGNTMVLKPAEQTPLTALYLGSLI----KE-AGFPPGVVNIVPGF---G---P-T-VGAAISSHPQINKIAFTGSTEVGKLVKEA--------AS------RS-----N------L------KRVTL--ELGGKNPCIVCADA---D-----LDLA--VEC-AHQGVFFNQGQCCTAAS-RVF-VEE---------QVY-SEFVRRSVEY-AKK---------------RPVGD-P-F-DV-KTEQGPQIDQKQFDKILELIESGK--KEGAK-LEC-GGSA-M----E--------D----KGLFIKPTVF--S---E-VTDNM---RIAKEEIFGPVQPILKF--K--S------IE-EV-IKRA-NS-TD---YGLTAAVFTK--N-LDKALKL--ASALE--SGTVWINC-Y-N------------A---L---------YA---Q-APFGGF--KMSGN-G--RE--LG-E-YA-LAEYTEVKTVTIKL----------------------------*

C;cover size:492; local alignment length=492 (original info = 3V4CA	493	959.57	0	81)
>P1;3V4CA
structureN:3V4CA: 1: : 493: : : :6.0: 
-----------------------------------------------------------------------------------------------------------I---------F-------T-P-K-----G-KH-----------L-------VAGEW---------L-DGAGTF-ASA-PAHGPA-H-D-F-AV---------------GTVELVNRACEAAEEAFW-----T--YGYSS-RKERAAFLRAIADEIE-A-R-AEAITEIGSQETGLPEARLN-G-ERGR----TTGQLRLFAD----HI-EK-G----DY-L----D--R---R---------V-----DAAPERQPA--------P----R-QEIRLVQRPVGPVAVFGASNFPLAFSTAGGDTAAALAAGCPVVVKGHSAHPGTGEIVAEAVDAAIRK-TGVHPGVFSLIQGG---S---R-D-VGHALVQHPHIKAVGFTGSLAGGRALFDL--------CA------A------R------P------EPIPFFGELGSVNPFLLPEAL---K-----ARAE--TLGQGWAGSLTGAGQFCTNPG-IAV-VIEG--------ADA-DRFTTAAVEA-LAK---------------V--------------APQTLTDGIAKAYRDGQARFAT--RNAVK-PLL-ATES--------------------SGRDASPNLF--E---T-TGAQFLADHALGEEVFGPLGLVVRV--G--S------PA-E--EELA-RG-FQ---GQLTATIHDA--GDLETARRLRPVLERK--AGRVLVNG-F-PTG----------V---E---------VV---D-SVHGGPYPASTNF-G--AT--SV-G-TS-IRRFLRPVAYQN--PE---DL------LPE------DF----*

C;cover size:454; local alignment length=454 (original info = 3SZBA	447	940.01	0	82)
>P1;3SZBA
structureN:3SZBA: 1: : 441: : : :6.0: 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------SKISEAVKRARAAFS-----S--GRTRP-LQFRIQQLEALQRLIQ-E-Q-EQELVGALAADLHKNEWNAYYE-EVVY----VLEEIEYMIQKLPEWA-AD-E----PV-E----K--T---P---------Q-----T----------------Q----Q-DELYIHSEPLGVVLVIGTWNYPFNL--TIQPMVGAIAAGNAVVLKPSELSENMASLLATII-----P-QYLDKDLYPVINGG---V---P-E-TTELL--KERFDHILYTGSTGVGKIIMTA--------AA------K------H------L------TPVTL--ELGGKSPCYVDKNC---D-----LDVA--CRR-IAWGKFMNSGQTCVAPD-YIL-CDP---------SIQ-NQIVEKLKKS-LKE----------------FYGE-D-A-KK-SRDYGRIISARHFQRVMGLI-------EGQK-VAY-GGTG-D-------------A----ATRYIAPTIL--T---D-VDPQS---PVMQEEIFGPVLPIVCV--R--S------LE-EA-IQFI-NQ-RE---KPLALYMFSS--N-DKVIKKM--IAETS--SGGVAANDVI-V-H----------I---T---------LH---S-LPFGGV--GNSGM-G--SY--HG-K-KS-FETFSHRRSCLVRPLMN--DE---------------GL-KVR*

C;cover size:446; local alignment length=446 (original info = 3LV1A	435	936.65	0	83)
>P1;3LV1A
structureN:3LV1A: 1: : 435: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------NYLSPAKIDSLFSAQKAYFA-----T--RATAD-VGFRKQSLERLKEAVI-N-N-KEALYSALAEDLGKPKDVVDLA-EIGA----VLHEIDFALA----HL-DE-W----VA-PVSVPS--P---D---------I-------------I--------A----P-SECYVVQEPYGVTYIIGPFNYPVNL--TLTPLIGAIIGGNTCIIKPSETTPETSAVIEKII----AE-AFAPEYVAVIQGG--------R-D-ENSHLLSL-PFDFIFFTGSPNVGKVVMQA--------AA------K------H------L------TPVVL--ELGGKCPLIVLPDA---D-----LDQT--VNQ-LMFGKFINSGQTCIAPD-YLY-VHY---------SVK-DALLERLVER---------------------VKT-E-L-PE-INSTGKLVTERQVQRLVSLLEA-----TQGQ-VLV-GSQA------D--------V----SKRALSATVV--D---G-VEWND---PLMSEELFGPILPVLEF--D--S------VR-TA-IDQV-NK-HHP--KPLAVYVFGK--D-MDVAKGI--INQIQ--SGDAQVNGVM-L-H----------A---F---------SP---Y-LPFGGI--GASGM-G--EY--HG-H-FS-YLTFTHKKSVRIVP----------------------------*

C;cover size:455; local alignment length=455 (original info = 3TY7A	445	935.20	0	84)
>P1;3TY7A
structureN:3TY7A: 1: : 445: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------A-R-D-Y-----T-KQ-----------Y-------INGEW---------V-ESN-SN-ETI-EVINPA-T-E-E-VI-GKV---------AKGNKADVDKAVEAADDVYL-----E--FRHTS-VKERQALLDKIVKEYE-N-R-KDDIVQAITDELGAPLSLSE-R-V-------HYQGLNHFVA----AR-DA-L----DN-Y----E--F---E---------E-----R---------------------R-GDDLVVKEAIGVSGLITPWNFPTNQ--TSLKLAAAFAAGSPVVLKPSEETPFAAVILAEI----FDK-VGVPKGVFNLVNGD---G---A-G-VGNPLSEHPKV--RSFTGSGPTGSEK-----------AA------K------D------F------KKVSL--ELGGKSPYIVLDDV---D-----IKEA--AKA-TTGKVVNNTGQVCTAGT-RVL-VPN---------KIK-DAFLAELKEQ-FSQ---------------VRVGN-P-R-ED-GTQVGPIISKKQFDQVQNYINKGI--EEGAE-LFY-GGPG-K----P--------EGLE-KGYFARPTIF--I---N-VD-NQ---TIAQEEIFGPV-SVITY--N--D------LD-EA-IQIA-ND-TK---YGLAGYVIGK--D-KETLHKV--ARSIE--AGTVEINE-A-G------------G---I---------EEFLEV-KSIAGY--FK-------------------------------------------------------------*

C;cover size:480; local alignment length=480 (original info = 4OE4A	479	926.64	0	85)
>P1;4OE4A
structureN:4OE4A: 1: : 479: : : :6.0: 
DW-------------DL-------L-----------------------------------------------R-------------AS-------------L-M--KF---------K-----SSS-L-E-----V-PL-----------V-------INGER---------IYDNN-ER-ALF-PQTNPA-NHQ-Q-VL-ANV---------TQATEKDVMNAVKAAKDAKK-----D--WYNLP-FYDRSAIFLKAADLIS-TKY-RYDMLAATMLGQGKNVYQAEID-CITE----LSDFFRYYVK----YA-SD-L----YA-Q----Q--P---V---------E-----S-------A--------D----GTWNKAEYRPLEGFVYAVSPFNFTAIA--ANLIGAPALM-GNTVVWKPSQTAALSNYLLMT----VLEE-AGLPKGVINFIPGD---P---V-Q-VTDQVLADKDFGALHFTGSTNVFKSLYGKIQSGVVEGKY------R------D------Y------PRIIG--ETGGKNFHLVHPSA---N-----ISHA--VLS-TIRGTFEFQGQKCSAAS-RLY-LPE---------SKS-EEFLSDMFGI-LQ-----------------------------SQFMGPVIHEQSFDKLVKVIEDAK--KDPELEILY-GGQY-D----K--------S----QGWFVGPTVI--K---A-KRPDH---PYMSTEFFGPILTVYEY--P--D------TEFNE-ICDI-ID-NT---YALTGAIFAK--D-RKAIEYA--DEKLKFSAGNFYIND-K-C-T--------------G---------NI---L-SRFVSI--RNTKE-NF-YE--L-------------------------------------------------*

C;cover size:463; local alignment length=463 (original info = 5NNOA	484	930.10	0	86)
>P1;5NNOA
structureN:5NNOA: 1: : 470: : : :6.0: 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------A-GVP---------ENTSLENIPVIVSKCREAFN-----D--DANRD-LKKRKQVLRSLLNLVE-E-N-TDEFCKAIHRDRRRHRDETVVM-EILP----LRNEVWHLIE----HM-DE-Y----VK-P----V--K---P---------T-----M-------E--------GAAA-L-DDCELQYEPLGVVLVIGTWNYPLLL--ILQPLLGALAAGNTAVIKPSELAPATAELLTKLLP------KYVSSDVVGIVNGG---V---S-E-TTAVL--KERFDHILYTGSARVAEIVMAA--------AA------K------H------L------TPVTL--ELGGKSPVVVDDTCAD-N-----MKVV--AER-IMWGKIINAGQTSIAPD-YVV-VEK---------SME-SVLVDALAEA-RKAMLGDKFLKVLKGELLVKQKQ-Q-F-LE-ESDYPRIVNASHFQRLMEFMK-------GGK-VAV-GGEA-D-------------E----ATLTIAPTIL--T---N-IDPTH---PVMQEEIFGPILPVLTY--E--N------EK-DI-LKII-NS-RE---KPLALYVFSN--N-KRFIRGV--ESRTS--SGAVVVND-VVV-H----------A---G---------AD---G-LPFGGV--GRSGM-G--AY--HG-R-YS-FETFSHRRPVMRRGFL---FS--S---I-D------TV-RFP*

C;cover size:453; local alignment length=453 (original info = 4QGKA	461	923.22	0	87)
>P1;4QGKA
structureN:4QGKA: 1: : 442: : : :6.0: 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------AMELEVRRVRQAFL-----S--GRSRP-LRFRLQQLEALRRMVQ-E-R-EKDILTAIAADLCKSEFNVYSQ-EVIT----VLGEIDFMLE----NL-PE-WVTAKPV-K----K--N---V---------L-----T----------------M----L-DEAYIQPQPLGVVLIIGAWNYPFVL--TIQPLIGAIAAGNAVIIKPSELSENTAKILAKLLP------QYLDQDLYIVINGG---V---E-E-TTELL--KQRFDHIFYTGNTAVGKIVMEA--------AA------K------H------L------TPVTL--ELGGKSPCYIDKDC---D-----LDIV--CRR-ITWGKYMNCGQTCIAPD-YIL-CEA---------SLQ-NQIVWKIKET-VKE----------------FYGE-N-I-KE-SPDYERIINLRHFKRILSLL-------EGQK-IAF-GGET------D--------E----ATRYIAPTVL--T---D-VDPKT---KVMQEEIFGPILPIVPV--K--N------VD-EA-INFI-NE-RE---KPLALYVFSH--N-HKLIKRM--IDETS--SGGVTGNDVI-M-H----------F---T---------LN---S-FPFGGV--GSSGM-G--AY--HG-K-HS-FDTFSHQRPCLLKSLK---RE--G---AN-------KL-RYP*

C;cover size:509; local alignment length=509 (original info = 5UJUA	558	950.20	0	88)
>P1;5UJUA
structureN:5UJUA: 1: : 558: : : :6.0: 
MT-------------HA-------LFTKHEDTLKRALAAIESRGYWSPFA------E---------------M-------------PS-------------P-K-------------------V-Y-G-E-----S-GN-----------A-------DGEAA---------F-KSH-LG-KTF-ELDQPA-S-G-E-TV-GAERSPYGVALDIRYPKSTPDALIAAAAAAQR-----T--WREAG-PSAWIGVSLEILARLN-R-A-SFEIAYSVMHTTGQAFMMAFQA-GGPHAQDRALEAVAYAWD----QL-RR-I----PA-D----A--H---W---------E-----KPQGKNP-P--------L----A-MQKRYTIVPRGTGLVLGCCTFPTWN--GYPGLFADLATGNTVIVKPHPGAILPLAITVRIARDVLRE-AGFDPNVVTLLAT----EPNDG-A-LVQDLALRPEIKLIDFTGSTQNGTWLERH--------AH--------------------Q------AQVYT--EKAGVNQIVIDSTD---D-----LKAA--AKN-IAFSLALYSGQMCTAPQ-NIY-VPRDGIRTADGHASF-DEVAQAIAGA-VQK---------------L-TGD-P-A-RS-VELIGAIQNDGVTARIDAARAVGRVLLDSQT-LQH-PAFP--------------------DARVRTPLVL--Q---L-DVADR---EKFTQEWFGPISFVIAT--D--S------TA-QS-LDLA-GE-IAAEHGALTLSVYST--A-DDVIDAA--HEAAV--RGGVALSINL-T-G----------G---V---------FV---N-QSAAFS--DFHGT-G--AN--PA-A-NAALADAAFVANRFRVVQS---RV--H---VAP---------K--*

C;cover size:511; local alignment length=511 (original info = 5UR2A	956	846.69	0	90)
>P1;5UR2A
structureN:5UR2A: 427: : 955: : : :6.0: 
TS-------------PVIPKKPGKF---------------------YNEP------L---------------L-------------DFAVKADREKMLKA-L-AEAKA---------S-----L-P-V-N-----V-NI-----------V-------INNKE---------L-Q---SG-KIF-DRVNPS-QSD-Q-IV-GKI---------QMATTEQAEQAMQAAQTAYK-----T--WKNVP-CEQRAALVDKLADIMT-R-D-RFKLIATQVLEVGKPWAEAD-G-DIGE----AIDFCRYYAR----HM-RE-L----QK-P----L--R---V---------G-----G-------L--------P----G-ELSHYIYKSRGVTAVIAPWNFPLAI--LAGMVTAAAVAGNTVVMKPAEQSTVVAWG----LMKMIQE-AGFPQGVINFLPGY---G---E-E-VGEYIVNHKYTTTIAFTGSKAVGLHIMNR--------AA------VVQPGQQH------V------KRCII--EMGGKNAVIIDNDA---D-----LDEA--VDG-VIYSAFGFSGQKCSAAS-RVI-VLD---------EVY-DRFVDRLVET-AKS---------------IEIHP-A-E-NP-KAYMGPVVDKEAYDRILGTIAEAE--KNH-K-LLF-KGSV-P-------------G----GGFFAPPTIF--G---D-VPGDA---KLAQAEIFGPVVAVIRA--K--N------LD-QA-LDIA-NS-TE---YALTGGVFSR--S-PANINRV--KEELE--VGNLYVNR-G-I-T----------G---A---------MVD--R-HPFGGF--KMSGI-GS-KT--GG-P-DY-LKQYMEPACVTENTL-------------RR------GF-APA*

C;cover size:511; local alignment length=511 (original info = 4F9IA	976	839.99	0	91)
>P1;4F9IA
structureN:4F9IA: 456: : 976: : : :6.0: 
MV-------------DF-------T---------------------RADH------R---------------A-------------AFPKHI---------AQV--RT---------Q-----L-G-K-T-----Y-PL-----------F-------INGKE---------V-R---TN-DLI-PTVNPN-KPS-E-VL-GQI---------CQAGTTEVGDAIAAAKAAFP-----A--WRDTD-PRTRAEYLLKAAQAAR-K-R-LFELSAWQVLEIGKQWDQAY-A-DVTE----AIDFLEYYAR----EM-IR-L----GQ-P----Q--R---V---------G-----H-------A--------P----G-ELNHYFYEPKGVAAVIAPWNFPLAI--SMGMASAAIVTGNCVVFKPSGITSIIGWH----LVELFRE-AGLPEGVFNFTPGR---G---S-V-MGDYLVDHPDISLIAFTGSMETGLRIIER--------AA------KVHPGQAN------V------KKIIS--EMGGKNAIIIDDDA---D-----LDEA--VPH-VLYSAFGFQGQKCSACS-RVI-VLD---------AVY-DKFIERLVSM-AKA---------------TKVGP-S-E-DP-ANYMGAVADDKAMKSIKEYAEIGK--REG-H-VLY-ESPV-P----A--------G----EGYFVPMTII--G---G-IKPEH---RIAQEEIFGPVLAVMRA--K--D------FD-QA-IEWA-NS-TQ---FALTGGIFSR--S-PEHLAKA--RREFR--VGNLYINR-N-N-T----------G---A---------LV---ERQPFGGA--RMSGV-GT-KA--GG-P-DY-LLHFMDPRVVTENTMRRG-FA--P---IEE------DD-DWV*

C;cover size:507; local alignment length=507 (original info = 3HAZA	983	676.78	0	94)
>P1;3HAZA
structureN:3HAZA: 458: : 983: : : :6.0: 
NSSFVAQAADYRVPVPA-------L---------------------LQRP------A---------------D-------------AI-------------V-R--PQ---------A-----A-A-H-PRIPLPC-DL-----------FAPERRNSRGVEFGAR------T-A---LD-QLL-TDVKAE-T-G---DL-KPI---------ADATPDQAHAAVAAARAGFA-----G--WSRTP-AGIRAAALEQAAHLLE-S-R-SAHFIALLQREGGKTLDDAL-S-ELRE----AADFCRYYAA----QG-RK-L----FG-S----ETAM---P---------G-----P-------T--------G------ESNALTMRGRGVFVAISPWNFPLAI--FLGQVTAALMAGNSVVAKPAEQTPRIAREAV----ALLHE-AGIPKSALYLVTG----D---G-R-IGAALTAHPDIAGVVFTGSTEVARSINRA--------LA------A------KDGP---I------VPLIA--ETGGINAMIADATA---L-----PEQV--ADD-VVTSAFRSAGQRCSALR-LLF-VQE---------DVA-DRMIEMVAGA-ARE---------------LKIGD-P-S-DV-ATHVGPVIDVEAKQRLDAHIARMK--TEARL-HFA-GPAP--------------------EGCFVAPHIF--E---L--T-EA---GQLTEEVFGPILHVVRYRPE--N------LE-RV-LRAI-ER-TG---YGLTLGVHSR--I-DDSIEAI--IDRVQ--VGNIYVNR-N-M-I----------G---A---------VV---GVQPFGGN--GLSGT-GP-KA--GG-P-HY-LARFATEQTVTINTA-------------AA------G-----*

C;cover size:511; local alignment length=511 (original info = 5KF6A	1207	564.06	0	97)
>P1;5KF6A
structureN:5KF6A: 500: : 1039: : : :6.0: 
MP-------------VV-------G---------------------AKHD------R---------------I-------------AL-------------P-A--ELFGDARTNSAG-----L-D-L-S-----N-EETLASLTEALRES-------AAMKWTALPQLATGP-A---AG-ETR-TVLNPG-D-HRD-VV-GSV---------TETSEEDARRAVRLAADAAP-----D--WAAVP-PSERAACLDRAAELMQ-A-R-MPTLLGLIIREAGKSALNAI-A-EVRE----AIDFLRYYAE----QT-RR-T----LG-P----G----------------------------------------------------HGPLGPIVCISPWNFPLAI--FTGQIAAALVAGNPVLAKPAEETPLIAAEGV----RILRE-AGIPASALQLLPG----D---G-R-VGAALVAAAETAGVMFTGSTEVARLIQAQ--------LA------D------RLSPAGRP------IPLIA--ETGGQNAMIVDSSA---L-----AEQV--VGD-VITSAFDSAGQRCSALR-VLC-LQE---------DVA-DRILTMLKGA-LHE---------------LHIGR-T-D-RL-SVDVGPVITSEAKDNIEKHIERMR--GLGRK-VEQ-IGLA-S----ET-------G----VGTFVPPTII--E---L---EKL---SDLQREVFGPVLHVIRYRRD--D------LD-RL-VDDV-NA-TG---YGLTFGLHTR--L-DETIAHV--TSRIK--AGNLYINR-N-I-I----------G---A---------VV---GVQPFGGR--GLSGT-GP-KA--GG-P-LY-LGRLVTTAPVPPQHSSVHTDP--V---LLDFAKWLDGK-GAR*

C;query_length:511 num_of_temps:1 cover_ratio:1 cover:509 not_cover:2
>P1;ALDH7A1_A171V
 : : : : : : : : : 
MS-------------TL-------L---------------------INQP------Q---------------Y-------------AW-------------L-K--EL---------G-----L-R-E-E-----N-EG-----------V-------YNGSW---------G-G---RG-EVI-TTYCPA-N-N-E-PI-ARV---------RQASVADYEETVKKAREAWK-----I--WADIP-APKRGEIVRQIGDALR-E-K-IQVLGSLVSLEMGKILVEGV-G-EVQE----YVDICDYAVG----LS-RM-I----GG-P----I--L---P---------S-----E-------R--------S----G-HALIEQWNPVGLVGIITAFNFPVVV--YGWNNAIAMICGNVCLWKGAPTTSLISVAVTKIIAKVLED-NKLPGAICSLTCG----G---A-D-IGTAMAKDERVNLLSFTGSTQVGKQVGLM--------VQ------E------R------F------GRSLL--ELGGNNAIIAFEDA---D-----LSLV--VPS-ALFAAVGTAGQRCTTAR-RLF-IHE---------SIH-DEVVNRLKKA-YAQ---------------IRVGN-P-W-DP-NVLYGPLHTKQAVSMFLGAVEEAK--KEGGT-VVY-GGKV-M----D--------R----PGNYVEPTIV--T---G-LGHDA---SIAHTETFAPILYVFKF--K--N------EE-EV-FAWN-NE-VK---QGLSSSIFTK--D-LGRIFRWLGPKGSD--CGIVNVNI-P-T-S----------G---A---------EI---G-GAFGGE--KHTGG-G--RE--SG-S-DA-WKQYMRRSTCTINYSK---DL--P---LAQ------GI-KFQ*
