C;cover size:502; local alignment length=502 (original info = 1A4SA	503	656.54	1.7e-80	1)
>P1;1A4SA
structureX:1A4SA: 2: : 503: : : :2.1: 
------QLVDSMPSASTG---SV-------V--V-----TDDLNYWGGRRIK--SKD-GATTEPVFEPA-T-G-RVLCQMV---------PCGAEEVDQAVQSAQAAY-----L-----K--WSKMA-GIERSRVMLEAARIIR--ER-RDNIAKLEVINNGKTITEA-E-Y-----DIDAAWQCIEYYAGLAPTLSGQHI------QL---------------PGGAFAYTRREPL-GVCAGILAWNYPFMIAAWKCAPALACGNAVVFKPSPMTPVTGVILAEI----FHE-AGVPVGLVNVVQG---G----A--ETGSLLCHHPNVAKVSFTGSVPTGKKVMEMS-A------K------T------V------K------HVTLELGGKSPLLIFKD---C--E-----LENAVRGALMANFLTQGQVCTNGTR-VFVQRE---------IM-PQFLEEVVKRTKAIVVGD-PL-L-TETRMGGLISKPQLDKVLGFVAQAKKEGA-RVLCGGEPLTPSDPK--L----KNGYFMSPCVLDN--CR---DDMTCVKEEIFGPVMSVLPF--D------T--E--EEV-LQRA-NN--TTFG-LASGVFTRDISRAHRVA--ANL--E--AGTCYIN--TYS-I------------------SPVEVPFGGYKMSGFG--R-E--NG-QATVDYYSQLKTVIV-EM-G---D--V-DS--L---F------*

C;cover size:498; local alignment length=498 (original info = 3QANA	516	643.49	1.5e-78	2)
>P1;3QANA
structureN:3QANA: 16: : 516: : : :6.0: 
VE---ANRKAFEEALGLV---EKE------L--G-----KEYPLIINGERVT--T---E-DKIQSWNPA-RKD-QLVGSVS---------KANQDLAEKAIQSADEAF-----Q-----T--WRNVN-PEERANILVKAAAIIR--RR-KHEFSAWLVHEAGKPWKEA-D-A-----DTAEAIDFLEYYARQMIELNRGKE------IL---------S-----RPGEQNRYFYTPM-GVTVTISPWNFALAIMVGTAVAPIVTGNTVVLKPASTTPVVAAKFVEV----LED-AGLPKGVINYVPGS--G----A--EVGDYLVDHPKTSLITFTGSKDVGVRLYERA-AVVRPGQN------H------L------K------RVIVEMGGKDTVVVDRD---A--D-----LDLAAESILVSAFGFSGQKCSAGSR-AVIHKD---------VY-DEVLEKTVALAKNLTVGD-PT-N-RDNYMGPVIDEKAFEKIMSYIEIGKKEG--RLMTGGEGD--------S----STGFFIQPTIIAD--LD---PEAVIMQEEIFGPVVAFSKA--N------D--F--DHA-LEIA-NN--TEYG-LTGAVITRNRAHIEQAK--REF--H--VGNLYFN--RNC-T--------GA--------IVGYHPFGGFKMSGTD--SKA--GG-PDYLALHMQAKTVSE-MY-------------------------*

C;cover size:490; local alignment length=490 (original info = 4PS9A	491	634.19	7.7e-78	3)
>P1;4PS9A
structureN:4PS9A: 1: : 491: : : :6.0: 
------------TNIELKPKVEAF------L--N-----EEIKMFINGEFVSAIG---G-KTFETYNPA-T-E-DVLAVVC---------EAQEEDIDAAVKAARSAF-----E-----SGPWAEMT-TAERAHLIYKLADLIE--EH-REELAQLEALDNGKPYQVA-LDD-----DISATVENYRYYAGWTTKIIGQTI------PI---------------SKDYLNYTRHEPV-GVVGQIIPWNFPLVMSSWKMGAALATGCTIVLKPAEQTPLSLLYAAKLF----KE-AGFPNGVVNFVPGF--G----P--EAGAAIVNHHDIDKVAFTGSTVTGKYIMRQS-A------E------M------I------K------HVTLELGGKSPNIILED---A--D-----LEEAINGAFQGIMYNHGQNCSAGSR-VFVHRK---------HY-ETVVDALVKMANNVKLGA-GM-E-KETEMGPLVSKKQQERVLNYIEQGKKEGA-TVAAGGERA--------L----EKGYFVKPTVFTD--VT---DDMTIVKEEIFGPVVVVLPF--D------S--T--EEV-IERA-NN--SSYG-LAAGVWTQNIKTGHQVA--NKL--K--AGTVWIN--DYN-L------------------ENAAAPFGGYKQSGIG--R-E--LG-SYALDNYTEVKSVWV-NI-K-----------------------*

C;cover size:499; local alignment length=499 (original info = 4O5HA	511	639.65	3.7e-78	4)
>P1;4O5HA
structureN:4O5HA: 11: : 511: : : :6.0: 
ME---TNETFALLDATRA---F--------L--A-----KPKQMLIGAEWSDAAS---G-RQLDVVNPA-D-G-TVIARVP---------EADERDVQQAVAAARRAF-----DAG---P--WRTAK-TTDRERLMLVLADLIE--AN-ARELAEIESLDNGKPVMVA-Q-GL----DVAMAAQCFRYMAGWATKIEGSVI------DA---------GMPYLPDSEIFAYTRKEPV-GVVGAIIPWNFPLLMAAWKIAPALATGCTVVLKPAEDTPLSALRLGEL----IQA-AGFPDGVVNIVTGY--G----H--TAGAALSRDPRIDKIAFTGSTQTGKTIGHAA-L------D------N------M------T------RMSLELGGKSPVIVLPD---V--D-----LDKAAQGVANAIFFNQGQVCTAGSR-AYIHSK---------VF-DGVIERVAKIAASLKIGP-GM-D-PATQIGPLVSAKQRERVCGYIDSGFGEGA-RAAAGGRAI--------D----GPGFFVEPTVLVD--TT---QAMRVVREEIFGPVLVAMPF--D------D--V--DTA-VQLA-ND--TPYG-LGASIWSNDLSAIHKLV--PRI--A--AGTVWVN--CHS-L------------------LDNALPFGGMKQSGFG--R-E--LG-RAVIDQYTESKSVMM-NY-A-----------------------*

C;cover size:492; local alignment length=492 (original info = 3RJLA	513	643.67	1.3e-78	5)
>P1;3RJLA
structureN:3RJLA: 13: : 513: : : :6.0: 
---------EENRKAFEK---ALETVNNEWL--G-----QSYPLVIDGERYE--T---E-NKIVSINPA-NKE-EVVGTVS---------KATQDHAEKAIQAAAKAF-----E-----T--WRYTD-PEERAAVLFRAVAKVR--RK-KHEFSALLVKEAGKPWNEA-D-A-----DTAEAIDFMEYYARQMIELAKGKP------VN---------S-----REGERNQYVYTPT-GVTVVIPPWNFLFAIMAGTTVAPIVTGNTVVLKPASAAPVIAAKFVEV----LEE-SGLPKGVVNFVPGS--G----A--EVGDYLVDHPKTSIITFTGSREVGTRIFERA-A------KVQPGQTH------L------K------QVIAEMGGKDTVVVDED---C--D-----IELAAQSIFTSAFGFAGQKCSAGSR-AVVHEK---------VY-DEVLKRVIEITESKKVGE-PD-S-ADVYMGPVIDQASFNKIMDYIEIGKEEG--RLVSGGKGD--------D----SKGYFIEPTIFAD--LD---PKARLMQEEIFGPVVAFSKV--S------S--F--DEA-LEVA-NN--TEYG-LTGAVITKNRDHINRAK--QEF--H--VGNLYFN--RNC-T--------GA--------IVGYHPFGGFKMSGTD--SKA--GG-PDYLALHMQAKTISE-MF-------------------------*

C;cover size:496; local alignment length=496 (original info = 1UZBA	516	638.97	5.9e-78	6)
>P1;1UZBA
structureX:1UZBA: 16: : 516: : : :1.4: 
-----TEEARRAMREALR---RVR------EEFG-----RHYPLYIGGEWVD--T---K-ERMVSLNPSAP-S-EVVGTTA---------KAGKAEAEAALEAAWKAF-----K-----T--WKDWP-QEDRSRLLLKAAALMR--RR-KRELEATLVYEVGKNWVEA-S-A-----DVAEAIDFIEYYARAALRYRYPAV------EVV--------P-----YPGEDNESFYVPL-GAGVVIAPWNFPVAIFTGMIVGPVAVGNTVIAKPAEDAVVVGAKVFEI----FHE-AGFPPGVVNFLPGV--G----E--EVGAYLVEHPRIRFINFTGSLEVGLKIYEAA-G------RLAPGQTW------F------K------RAYVETGGKNAIIVDET---A--D-----FDLAAEGVVVSAYGFQGQKCSAASR-LILTQG---------AY-EPVLERVLKRAERLSVGP-A--E-ENPDLGPVVSAEQERKVLSYIEIGKNEG--QLVLGGKRL--------E----GEGYFIAPTVFTE--VP---PKARIAQEEIFGPVLSVIRV--K------D--F--AEA-LEVA-ND--TPYG-LTGGVYSRKREHLEWAR--REF--H--VGNLYFN--RKI-T--------GA--------LVGVQPFGGFKLSGTN--A-KT-GA-LDYLRLFLEMKAVAE-RF-------------------------*

C;cover size:497; local alignment length=497 (original info = 2J6LA	497	632.89	1.5e-77	7)
>P1;2J6LA
structureX:2J6LA: 1: : 497: : : :1.3: 
-----TLLINQPQYAWLK---ELG------L--R-----EENEGVYNGSWGG--R---G-EVITTYCPA-N-N-EPIARVR---------QASVADYEETVKKAREAW-----K-----I--WADIP-APKRGEIVRQIGDALR--EK-IQVLGSLVSLEMGKILVEG-V-G-----EVQEYVDICDYAVGLSRMIGGPIL------PS---------E-----RSGHALIEQWNPV-GLVGIITAFNFPVAVYGWNNAIAMICGNVCLWKGAPTTSLISVAVTKIIAKVLED-NKLPGAICSLTCG---G----A--DIGTAMAKDERVNLLSFTGSTQVGKQVGLMV-Q------E------R------F------G------RSLLELGGNNAIIAFED---A--D-----LSLVVPSALFAAVGTAGQRCTTARR-LFIHES---------IH-DEVVNRLKKAYAQIRVGN-PW-D-PNVLYGPLHTKQAVSMFLGAVEEAKKEGG-TVVYGGKVM--------D----RPGNYVEPTIVTG--LG---HDASIAHTETFAPILYVFKF--Q------N--E--EEV-FAWN-NE--VKQG-LSSSIFTKDLGRIFRWLGPKGS--D--CGIVNVN--IPT-S--------G---------AEIGGAFGGEKHTGGG--R-E--SG-SDAWKQYMRRSTCTI-NY-S-----------------------*

C;cover size:498; local alignment length=498 (original info = 4PXNA	498	632.97	1.5e-77	8)
>P1;4PXNA
structureN:4PXNA: 1: : 498: : : :6.0: 
----------KEEHQFLA---ELG------LA-Q-----RNPGAFACGAWGG--S---G-PTVTSTSPT-N-N-QVIAEVV---------EASVHDYEEGMRACFDAA-----K-----T--WMAIP-APKRGEIVRQIGDALR--AK-LHHLGRLVSLEMGKILPEG-I-G-----EVQEIIDMCDYAVGLSRQLNGSII------PS---------E-----RPNHMMMEVWNPL-GVVGVITAFNFPCAVLGWNACIALVCGNCVVWKGAPTTPLITIAMTKIVASVLEK-NNLPGAIFTSFCG---G----T--EIGQAIALDIRIPLVSFTGSTRAGLMVQQQV-S------A------R------F------G------KCLLELSGNNAIIVMDD---A--D-----IQLAVRSVLFAAVGTAGQRCTTCRR-LILHEN---------IY-QTFLDQLVEVYKQVRIGD-PL-E-KGTLLGPLHTPASKENFLKGIQTIKSQGG-KILFGGSAI--------E----SEGNFVQPTIV-E--IT---PSAPVVKEELFGPVLYVMKF--Q------T--L--KEA-IEIN-NS--VPQG-LSSSIFTKRPDIIFKWLGPHGS--D--CGIVNVN--IPT-N--------G---------AEIGGAFGGEKATGGG--R-E--AG-SDSWKQYMRRATCTI-NY-G---S--E-LP--L---A------*

C;cover size:511; local alignment length=511 (original info = 4F9IA	976	680.13	8e-78	9)
>P1;4F9IA
structureN:4F9IA: 461: : 973: : : :6.0: 
RA---DHRAAFPKHIAQV---RTQ------L--G-----KTYPLFINGKEVR--T---N-DLIPTVNPN-KPS-EVLGQIC---------QAGTTEVGDAIAAAKAAF-----P-----A--WRDTD-PRTRAEYLLKAAQAAR--KR-LFELSAWQVLEIGKQWDQA-Y-A-----DVTEAIDFLEYYAREMIRLGQPQR------VG---------H-----APGELNHYFYEPK-GVAAVIAPWNFPLAISMGMASAAIVTGNCVVFKPSGITSIIGWHLVEL----FRE-AGLPEGVFNFTPGR--G----S--VMGDYLVDHPDISLIAFTGSMETGLRIIERA-A------KVHPGQAN------V------K------KIISEMGGKNAIIIDDD---A--D-----LDEAVPHVLYSAFGFQGQKCSACSR-VIVLDA---------VY-DKFIERLVSMAKATKVGP-SE-D-PANYMGAVADDKAMKSIKEYAEIGKREGH-V-LYESPVP--------A----GEGYFVPMTIIGG--IK---PEHRIAQEEIFGPVLAVMRA--K------D--F--DQA-IEWA-NS--TQFA-LTGGIFSRSPEHLAKAR--REF--R--VGNLYIN--RNN-T--------GA--------LVERQPFGGARMSGVG--T-KA-GG-PDYLLHFMDPRVVTE-NT-M---R----RG--F---APIEEDD*

C;cover size:510; local alignment length=510 (original info = 3V9JA	544	638.74	2.1e-77	10)
>P1;3V9JA
structureN:3V9JA: 23: : 543: : : :6.0: 
QG---SPERDALQKA-LK---DLK------G--QT----EAIPCVVGDEEVW--T---S-DIQYQLSPF-NHA-HKVAKFC---------YADKALLNRAIDAALAAR-----K-----E--WDLKP-MADRAQVFLKAADMLSGPRR-AEVLAKTM-VGQGKTVIQA-EID-----AAAELIDFFRFNAKFAVELEGEQP------IS---------V-----PPSTNHTVYRGLE-GFVAAISPFNFTAIGGNLAGAPAL-MGNVVLWKPSDTAMLASYAVYRI----LRE-AGLPPNIIQFVPAD--G----P--TFGDTVTSSEHLCGINFTGSVPTFKHLWRQV-A------Q------N------L------DRFRTFPRLAGECGGKNFHFVHSS---A--D-----VDSVVSGTLRSAFEYGGQKCSACSR-LYVPKS---------LW-PQIKGRLLEEHSRIKVGD-PAED-FGTFFSAVIDAKAFARIKKWLEHARSSPSLSILAGGQCN--------E----SVGYYVEPCIIES--KD---PQEPIMKEEIFGPVLTVYVY--P------DDKY--RET-LKLV-DST-TSYG-LTGAVFAQDKAIVQEAT--RML--RNAAGNFYIN--DKS-T--------GS--------VVGQQPFGGARASGTN--DKP--GG-PHYILRWTSPQVIKE-TH-K---P----LG--D---WRYSYM-*

C;cover size:503; local alignment length=503 (original info = 3U4JA	497	625.66	1.3e-76	11)
>P1;3U4JA
structureN:3U4JA: 1: : 497: : : :6.0: 
------VLSNFIAPDSND---PR-------L--RI----KSRYQLVDGKSVD--AAS-G-STIDRVSPGHA-G-EVVGTWP---------EASADDVRKAVAAARKAF-----D-----A--GPWPR-SGAERSRLFKVADLIL--AR-QEELALIESLEVGKPIAQA-R-G-----EIGFCADLWSYAAGQARALEGQTH------NN---------I-----GDDRLGLVLREPV-GVVGIITPWNFPFIIASERVPWAIGSGCTVVLKPSEFTSGTSIRLAEL----ARE-AGIPDGVFNVVTGY--G----D--PAGQVLAEDPNVD-VAFTGSVRVGTKLGEIA-A------R------T------V------K------RVGLELGGKGPQIVFAD---A--D-----LDAAADGIAYGVYHNAGQCCISGSR-LLVQEG---------IR-DAL-ERLLDISRKVAFGD-PL-N-ERTKIGA-ISEAHAEKVHSYVTAGITSGA-ELLLGGERIG-------R----EAGLYYAPTVFAG--VT---PDS-IAREEIFGPVLSTLTF--K------T--A--DEA-VALA-NA--TEFG-LSASVWSTNLETALQTI--RRI--R--AGRCWIN--SVI-D------------------GTPELPIGGYKKSGLG--R-E--LG-RYGFDEYSQFKGVHV-TL-G---R--P-AP--W---FT-----*

C;cover size:487; local alignment length=487 (original info = 4ZZ7A	489	623.04	2e-76	12)
>P1;4ZZ7A
structureN:4ZZ7A: 1: : 489: : : :6.0: 
---------------------------------M-----TTIGHLINGQLVT--EN--T-RSQNVFNPA-T-G-EIGKQLD---------LASTKTVEQAISAAQHAF-----P-----T--WRNTP-PLKRARVMFRFKELLE--QH-ADEICRLIGEEHGKIAHDA-M-G-----ELQRGIENVEYACGAPELLKGEHS------RN---------V-----GPGIDSWSEFQPM-GVVAGITPFNFPVMVPLWMFPMAIVCGNCFVLKPSERDPSSTLYIAQL----LQE-AGLPDGVMNVVNG---D----K--EAVDALLHDDRVKAVSFVGSTPIAEYIYRTA-S------A------N------G------K------RCQALGGAKNHAIVMPD---A--D-----MDNAVNQLLGAAFGSSGERCMALSVAVAVGDA---------AG-DALVSKMTQAMQKLKVGP-ST-D-SGNDFGPVITRQHQEKVIGYINSAEQQGA-TIVVDGRQPKVPN----H----ENGFFVGGTLIDH--VT---PEMTSYQEEIFGPVLQVVRV--A------T--M--QDA-MDLI-DA--HEYG-NGTCIFTRDGEAARYFS--DNI--Q--VGMVGIN--IPL-P--------V---------PVAYHSFGGWKRSLFGDLH-A--YG-PDAVRFYTKRKTVTQ-RW-P---S--A-GV--R---EG-----*

C;cover size:508; local alignment length=508 (original info = 2D4EA	513	619.23	1.8e-75	13)
>P1;2D4EA
structureX:2D4EA: 8: : 513: : : :2.10: 
IS---WETIEEVRRR-LK---------------E-----RPALHFIAGEFVP--SES-G-ETFPSLDPA-T-N-EVLGVAA---------RGGEREVDRAAKAAHEAF-----Q-----R--WSRTK-AKERKRYLLRIAELIE--KH-ADELAVMECLDAGQVLRIV-R-A-----QVARAAENFAFYAEYAEHAMEDRT------FP---------V-----DRDWLYYTVRVPA-GPVGIITPWNAPLMLSTWRIAPALAFGNTVVLKPAEWSPFTATKLAEI----LKE-ADLPPGVFNLVQGF--G----E--EAGAALVAHPLVPLLTLTGETETGKIVMRNA-A------D------H------L------K------RLSPELGGKSPALVFAD---A--D-----LERALDAVVFQIFSFNGERCTASSR-LLVEEK---------IF-EDFVGKVVERARAIRVGH-PL-D-PETEVGPLIHPEHLQRVLGYVEAGKREGA-RLLVGGERAKTSFRGEDL----SRGNYLLPTVFVG---E---NHMKIAQEEIFGPVLVAIPF--K------D--E--EEA-LRKA-ND--TKYG-LAAYVFTRDLERAHRLA--LEL--E--AGMVYLN--SHN-V------------------RHLPTPFGGVKGSGDR--R-E--GG-TYALDFYTDLKTIAL-PL-R---P--P-HV--P---KFGK---*

C;cover size:493; local alignment length=493 (original info = 2O2PA	498	616.38	2.2e-75	14)
>P1;2O2PA
structureX:2O2PA: 2: : 498: : : :1.70: 
--------INYVEKAVNK---L-T------L--Q-----MPYQLFIGGEFVD--AEG-S-KTYNTINPT-D-G-SVICQVS---------LAQVSDVDKAVAAAKEAF-----E-----NGLWGKIN-ARDRGRLLYRLADVME--QH-QEELATIEALDAGAVYTLA-LKT-----HVGMSIQTFRYFAGWCDKIQGATI------PI---------NQAR--PNRNLTLTKKEPV-GVCGIVIPWNYPLMMLSWKTAACLAAGNTVVIKPAQVTPLTALKFAEL----TLK-AGIPKGVVNILPGS--G----S--LVGQRLSDHPDVRKIGFTGSTEVGKHIMKSC-AL-----S------N------V------K------KVSLELGGKSPLIIFAD---C--D-----LNKAVQMGMSSVFFNKGENCIAAGR-LFVEES---------IH-NQFVQKVVEEVEKMKIGN-PL-E-RDTNHGPQNHEAHLRKLVEYCQRGVKEGA-TLVCGGNQV--------P----RPGFFFQPTVFTD--VE---DHMYIAKEESFGPIMIISRF--A------DGDV--DAV-LSRA-NA--TEFG-LASGVFTRDINKALYVS--DKL--Q--AGTVFIN--TYN-K------------------TDVAAPFGGFKQSGFG--K-D--LG-EAALNEYLRIKTVTF-EY-------------------------*

C;cover size:506; local alignment length=506 (original info = 5UR2A	956	667.30	2.6e-76	15)
>P1;5UR2A
structureN:5UR2A: 449: : 956: : : :6.0: 
KA---DREKMLKALAEAK---ASL---------P-----VNVNIVINNKELQ--S---G-KIFDRVNPS-QSD-QIVGKIQ---------MATTEQAEQAMQAAQTAY-----K-----T--WKNVP-CEQRAALVDKLADIMT--RD-RFKLIATQVLEVGKPWAEA-D-G-----DIGEAIDFCRYYARHMRELQKPLR------VG---------G-----LPGELSHYIYKSR-GVTAVIAPWNFPLAILAGMVTAAAVAGNTVVMKPAEQSTVVAWGLMKM----IQE-AGFPQGVINFLPGY--G----E--EVGEYIVNHKYTTTIAFTGSKAVGLHIMNRA-AVVQPGQQ------H------V------K------RCIIEMGGKNAVIIDND---A--D-----LDEAVDGVIYSAFGFSGQKCSAASR-VIVLDE---------VY-DRFVDRLVETAKSIEIHP-AE-N-PKAYMGPVVDKEAYDRILGTIAEAEKNHK--LLFKGSV---------P----GGGFFAPPTIFGD--VP---GDAKLAQAEIFGPVVAVIRA--K------N--L--DQA-LDIA-NS--TEYA-LTGGVFSRSPANINRVK--EEL--E--VGNLYVN--RGI-T--------GA--------MVDRHPFGGFKMSGIGS-K-T--GG-PDYLKQYMEPACVTE-NT-LR--R--G-FA--P---AE-----*

C;cover size:489; local alignment length=489 (original info = 5IZDA	493	614.29	3.3e-75	16)
>P1;5IZDA
structureN:5IZDA: 3: : 488: : : :6.0: 
-----------------------------------------TKLYIDGQWVNSSS---G-KTVDKYSPV-T-G-QVIGRFE---------AATRDDVDRAIDAAEDAF-----W-----A--WNDLG-SVERSKIIYRAKELIE--KN-RAELENIIMEENGKPVKEA-K-E-----EVDGVIDQIQYYAEWARKLNGEVV------EG---------T-----SSHRKIFQYKVPY-GIVVALTPWNFPAGMVARKLAPALLTGNTVVLKPSSDTPGSAEWIVRKF----VE-AGVPKGVLNFITGR--G----S--EIGDYIVEHKKVNLITMTGSTATGQRIMQKA-S------A------N------M------A------KLILELGGKAPFMVWKD---A--D-----MDNALKTLLWAKYWNAGQ-SIAAER-LYVHED---------IY-DTFMSRFVELSRKLALGD-PK-N---ADMGPLINKGALQATSEIVEEAKESGA-KILFGGSQPSLSGP---Y----RNGYFFLPTIIGN--AD---QKSKIFQEEIFAPVIGARKI--S------S--V--EEM-YDLA-ND--SKYG-LASYLFTKDPNIIFEAS--ERI--R--FGELYVN--MPG-P------------------EASQGYHTGFRMTGQA--G-E--GS-KYGISEYLKLKNIYV-DY-S---G----KP--L---HINTVRD*

C;cover size:486; local alignment length=486 (original info = 4O6RA	489	608.18	1.7e-74	17)
>P1;4O6RA
structureN:4O6RA: 4: : 489: : : :6.0: 
-----------------------------------------TQLFIDGRFVD--AVD-R-GTIDVLNPH-D-G-SVITKIA---------AATAADVDLAVDAATRAF-----P-----A--WSAMP-AAERGRLLLRLADAIE--AN-TEALAQLESLDTGHPIRDS-R-AL----DVPRTAACFRYFGGMADKLQGSVI------PV---------------DTGFLNYVQRAPI-GVVGQIVPWNFPLMFTSWKMGPALAAGNTVVLKPSEITPLSTLRIVELM----AE-VGFPAGVVNIVPGY--G----H--TAGQRLAEHPGVGKIAFTGSTATGRRIVEAS-Q------G------N------L------K------RVQLELGGKGANIVFDD---A--N-----LDAAINGAAWAIFHNQGQACIAGSR-LVLHER---------IA-DAFLERFVALASSIRIGN-PL-D-PNTEMGPLTSKQHLDRVLSYVDVAREQGG-RVLTGGSAPQDPA----L----ANGYYVRPTIVEA--KH---ATDRVAQEEVFGPFVTVLRF--G------S--D--DEA-LAIA-NA--TEYG-LGSGLWTNDLSRAHRMA--ARI--D--AGMCWIN--CYK-R------------------VNPGSPFGGVGKSGYG--R-E--MG-FEAMHDYTEARSVWV-NV-D---G--N-VP--P---HFKR---*

C;cover size:492; local alignment length=492 (original info = 4I8PA	500	610.89	1.3e-74	18)
>P1;4I8PA
structureN:4I8PA: 1: : 499: : : :6.0: 
------------------------------M--V-----PLRQLFVDGEWRPPAQ---G-RRLPVVNPT-T-E-AHIGEIP---------AGTAEDVDAAVAAARAAL-----KRNRGRD--WARAP-GAVRAKYLRAIAAKVI--ER-KPELAKLEALDCGKPYDEA-A-W-----DMDDVAGCFEYFADQAEALDKRQN------SP---------VSLP--METFKCHLRREPI-GVVGLITPWNYPLLMATWKIAPALAAGCTAVLKPSELASVTCLELADI----CKE-VGLPSGVLNIVTGL--G----P--DAGAPLSAHPDVDKVAFTGSFETGKKIMASA-A------P------M------V------K------PVTLELGGKSPIVVFDD---V--D-----IDKAVEWTLFGCFWTNGQICSATSR-LLIHTK---------IA-KKFNERMVAWAKNIKVSD-PL-E-EGCRLGPVVSEGQYEKIKKFISNAKSQGA-TILTGGVRPAH------L----EKGFFIEPTIITD--IT---TSMEIWREEVFGPVLCVKEF--S------T--E--DEA-IELA-ND--TQYG-LAGAVISGDRERCQRLS--EEI--D--AGCIWVN--CSQ-P------------------CFCQAPWGGNKRSGFG--R-E--LG-EGGIDNYLSVKQVTE-YI-S---D--EPWG--W---YQSPSK-*

C;cover size:500; local alignment length=500 (original info = 3ED6A	502	609.14	2.3e-74	19)
>P1;3ED6A
structureN:3ED6A: 1: : 502: : : :6.0: 
-----------YFQSNAM---ELL------K--H-----LSQRQYIDGEWVESAN---K-NTRDIINPY-N-Q-EVIFTVS---------EGTKEDAERAILAARRAF-----ESG---E--WSQET-AETRGKKVRAIADKIK--EH-REALARLETLDTGKTLEES-Y-A-----DMDDIHNVFMYFAGLADKDGGEMI------DS---------P-----IPDTESKIVKEPV-GVVTQITPWNYPLLQASWKIAPALATGCSLVMKPSEITPLTTIRVFEL----MEE-VGFPKGTINLILGA--G----S--EVGDVMSGHKEVDLVSFTGGIETGKHIMKNA-A------N------N------V------T------NIALELGGKNPNIIFDD---A--D-----FELAVDQALNGGYFHAGQVCSAGSR-ILVQNS---------IK-DKFEQALIDRVKKIKLGN-GF-D-ADTEMGPVISTEHRNKIESYMDVAKAEGA-TIAVGGKRPDRDD----L----KDGLFFEPTVITN--CD---TSMRIVQEEVFGPVVTVEGF--E------T--E--QEA-IQLA-ND--SIYG-LAGAVFSKDIGKAQRVA--NKL--K--LGTVWIN--DFH-P------------------YFAQAPWGGYKQSGIG--R-E--LG-KEGLEEYLVSKHILT-NT-N---P--Q-LV--N---WFSK---*

C;cover size:487; local alignment length=487 (original info = 5U0LA	488	607.20	2.2e-74	20)
>P1;5U0LA
structureN:5U0LA: 3: : 486: : : :6.0: 
----------------------------------------TGNVYIDGLWLP--GH--G-APFESVQPV-T-G-ETVWDGN---------AASLEDVDAAVREARKAF-----L-----A--WRRKS-LAERQAVIEAFGELLE--AN-KEELAHQIGLETGKPLWES-R-T-----EVAAMMGKIPISVKAYNERTGHTE------SD---------------VAGGHAVLRHRPH-GVVAVFGPYNFPGHLPNGHIVPALLAGNTVVFKPSELTPGVAELTVRLW----EK-AGLPDGVINLVQG---G----S--DTGKCLARHSLIDGLFFTGSSTVGHLLHEQF-G------G------QP-----E------K------ILALEMGGNNPLIVQNV---S--D-----LDGAVHHALQSAFLSAGQRCTCARR-LLVPKG---------KKGDEFLARLVEVAARITVAEFDA-D-PQPFMGSVISAEAANQLLKAQAAMLEKGA-TSLLEMKQL--------K----PDTGLLSPGIVDA-------TGIELEDQEFFGPLLTVYRY--K------G--F--DEA-LELA-NN--TRYG-LSAGILSDDRKLYNRLV--EEV--R--AGIVNWN--RPL-T--------G---------ASSAAPFGGVGASGNH--R-P--SA-YYAAD-YCAWPMASL-EA-G---KS-E-LPDSL---APGL---*

C;cover size:483; local alignment length=483 (original info = 4H73A	482	604.34	3.9e-74	21)
>P1;4H73A
structureN:4H73A: 2: : 482: : : :6.0: 
------------------------------------------ANYINGEFKEPST---G-AFQVKTSPV-D-G-SKIAEVP---------RSGREDAREAIDSAFEAL-----K-----A--WANIP-AIRRAEYLYKMLEVFR--QM-KEDFMKILTVEGGGTYRKV-W-G-----EVVFTERLIQNAAELARHYQGRVL------QS---------D-----SESTISVVFKRSK-GVVGVITPWNYPLSISMKKIAHTLAVGNTVVYKPASDTPVTGWLIAQM----VAK-AGLPKGVFNLVIGP--G----P--VVGEEIVTHKRVAHVTFTGESSTGREIAAKA-A------G------T------L------K------TVTLELGGSDPLIILDD---V--D-----VDYAARLAVFASLFHQGQICTSAKR-IIVHKA---------VA-DKFIERYVHYVKMLRIDD-PRKD-EKVDLGPLINERQVALMKEFVDDAVSRGG-RLLIGGR---------------SWGNFFEPAIFVD--VD---RNFRIMREEVFGPVRPIVVV--E------N--D--DQA-VEVA-ND--TDYG-LSGAVLTNNVNRAFRIA--EAV--E--SGMFHIN--DVT-F--------L---------EESHVPFGGIKASGVG--R-E--GG-EWSFHETTYDRWVTV-TL-R---T--R-RF--PIPSAL-----*

C;cover size:493; local alignment length=493 (original info = 5IUVA	495	603.59	9e-74	22)
>P1;5IUVA
structureN:5IUVA: 5: : 495: : : :6.0: 
--------ADWEQRAQ-------N------L--K-----IEGRAFIQGEYTAAAS---G-ETFDCISPV-D-G-RLLAKVA---------SCDAADAQRAVESARSAF-----DSG---A--WSRLA-PAKRKATMIRFAGLLE--QN-AEELALLETLDMGKPISDS-L-GV----DIPGGARALSWSGEAIDKLYDEVA------AT---------------PHDQLGLVTREPV-GVVAAIVPWNFPLMMACWKLGPALSTGNSVVLKPSEKSPLTAIRIAQL----AIE-AGIPAGVLNVLPGY--G----H--TVGKALALHMDVDTVVFTGSTKIAKQLMIYA-GE-----S------N------M------K------RVWLEAGGKSPNIVFAD---AP-D-----LQAAADSAASAIAFNQGEVCTAGSR-LLVERS---------IK-DRFLPMVIEALGTWKPGN-PL-D-PATNVGALVDTQQMNTVLSYIAAGHTDGA-RLVAGGKQILQ------E----TGGTYVEPTIFDG--VN---NAMRIAQEEIFGPVLSVLTF--D------T--A--EEA-IQIA-ND--TPYG-LAAAVWTANLSKAHLTA--RAL--R--AGSVWVN--QYD-G------------------GDMTAPFGGFKQSGNG--R-D--KS-LHAFDKYTELKSTWI-KL-------------------------*

C;cover size:491; local alignment length=491 (original info = 4A0MA	494	605.60	4.7e-74	23)
>P1;4A0MA
structureN:4A0MA: 1: : 493: : : :6.0: 
-----------------------F------P--I-----PARQLFIDGEWREPIK---K-NRIPVINPS-T-E-EIIGDIP---------AATAEDVEVAVVAARRAF-----R-----RNNWSATS-GAHRATYLRAIAAKIT--EK-KDHFVKLETIDSGKPFDEA-V-L-----DIDDVASCFEYFAGQAEALDGKQK------AP---------VTLP--MERFKSHVLRQPL-GVVGLISPWNYPLLMATWKIAPALAAGCTAVLKPSELASVTCLEFGEV----CNE-VGLPPGVLNILTGL--G----P--DAGAPLVSHPDVDKIAFTGSSATGSKVMASA-A------Q------L------V------K------PVTLELGGKSPIVVFED---V--D-----IDKVVEWTIFGCFWTNGQICSATSR-LLVHES---------IA-AEFVDKLVKWTKNIKISD-PF-E-EGCRLGPVISKGQYDKIMKFISTAKSEGA-TILYGGSRPEH------L----KKGYYIEPTIVTD--IS---TSMQIWKEEVFGPVLCVKTF--S------S--E--DEA-IALA-ND--TEYG-LAAAVFSNDLERCERIT--KAL--E--VGAVWVN--CSQ-P------------------CFVQAPWGGIKRSGFG--R-E--LG-EWGIQNYLNIKQVTQ-DI-S---D----EP--W---GWYK---*

C;cover size:484; local alignment length=484 (original info = 1T90A	484	604.49	4e-74	24)
>P1;1T90A
structureX:1T90A: 1: : 484: : : :2.50: 
------------------------------E--I-----RKLKNYINGEWVE--SKT-D-QYEDVVNPA-T-K-EVLCQVP---------ISTKEDIDYAAQTAAEAF-----K-----T--WSKVA-VPRRARILFNFQQLLS--QH-KEELAHLITIENGKNTKEA-L-G-----EVGRGIENVEFAAGAPSLMMGDSL------AS---------I-----ATDVEAANYRYPI-GVVGGIAPFNFPMMVPCWMFPMAIALGNTFILKPSERTPLLTEKLVE----LFEK-AGLPKGVFNVVYG---A----H--DVVNGILEHPEIKAISFVGSKPVGEYVYKKG-S------E------N------L------K------RVQSLTGAKNHTIVLND---A--N-----LEDTVTNIVGAAFGSAGERCMACAV-VTVEEG---------IA-DEFMAKLQEKVADIKIGN-GL-D-DGVFLGPVIREDNKKRTLSYIEKGLEEGA-RLVCDGRENV-------S----DDGYFVGPTIFDN--VT---TEMTIWKDEIFAPVLSVIRV--K------N--L--KEA-IEIA-NK--SEFA-NGACLFTSNSNAIRYFR--ENI--D--AGMLGIN--LGV-P--------A---------PMAFFPFSGWKSSFFG--T-LHANG-KDSVDFYTRKKVVTA-RY-PA--P--D-F--------------*

C;cover size:491; local alignment length=491 (original info = 3EK1A	485	603.35	6e-74	25)
>P1;3EK1A
structureN:3EK1A: 2: : 485: : : :6.0: 
------------SMLALK---DPS---------L-----LKSQCLVNGRWID--AAD-G-TTIKVTNPA-D-G-SVIGTVP---------SLSVATIKEAIDASAKAL-----S-----G--WAAKT-AKERAGILRKWFDLII--AN-ADDIALIMTSEQGKPLAEA-R-G-----EVLYAASFIEWFAEEAKRVYGDTI------PA---------P-----QNGQRLTVIRQPV-GVTAAITPWNFPAAMITRKAAPALAAGCTMIVRPADLTPLTALALGV----LAEK-AGIPAGVLQIVTGK--A----R--EIGAELTSNDTVRKLSFTGSTEVGRLLMAQC-A------P------T------I------K------RISLELGGNAPFIVFDD---A--D-----LDAAVDGAMVSKYRNAGQTCVCANR-IYVQRG---------VY-DKFAEKLAAKVKELKVGN-GT-E-PGVVIGPMIEEKAITKVKAHIEDAVSKGA-KLITGGKE--------------LGGLFFEPGILTG--VT---SDMLVAKEETFGPLAPLFAF--D------T--E--EEV-IAQA-ND--TIFG-LAAYFYTENFSRAIRVS--EAL--E--YGMVGHN--TGL-I------------------SNEVAPFGGVKQSGLG--R-E--GS-KYGIEEYLETKYICS-AY-K---R-------------------*

C;cover size:489; local alignment length=489 (original info = 5FHZA	489	604.55	5.1e-74	26)
>P1;5FHZA
structureN:5FHZA: 2: : 489: : : :6.0: 
------------LPRPIR---NLE---------V-----KFTKIFINNEWHE--SKS-G-KKFATCNPS-T-R-EQICEVE---------EGDKPDVDKAVEAAQVAF-----QRGS--P--WRRLD-ALSRGRLLHQLADLVE--RD-RATLAALETMDTGKPFLHA-FFI-----DLEGCIRTLRYFAGWADKIQGKTI------PT---------------DDNVVCFTRHEPI-GVCGAITPWNFPLLMLVWKLAPALCCGNTMVLKPAEQTPLTALYLGSL----IKE-AGFPPGVVNIVPGF--G----P--TVGAAISSHPQINKIAFTGSTEVGKLVKEAA-S------RS-----N------L------K------RVTLELGGKNPCIVCAD---A--D-----LDLAVECAHQGVFFNQGQCCTAASR-VFVEEQ---------VY-SEFVRRSVEYAKKRPVGD-PF-D-VKTEQGPQIDQKQFDKILELIESGKKEGA-KLECGGSAM--------E----DKGLFIKPTVFSE--VT---DNMRIAKEEIFGPVQPILKF--K------S--I--EEV-IKRA-NS--TDYG-LTAAVFTKNLDKALKLA--SAL--E--SGTVWIN--CYN-A------------------LYAQAPFGGFKMSGNG--R-E--LG-EYALAEYTEVKTVTI-KL-------------------------*

C;cover size:483; local alignment length=483 (original info = 4JZ6A	484	596.32	4.7e-73	27)
>P1;4JZ6A
structureN:4JZ6A: 3: : 484: : : :6.0: 
----------------------------------------KTKLFINNAWIDSSD---Q-QTFERKHPV-S-S-EVMTESA---------NATVTDAIKAAQAAEEAF-----K-----T--WKDVG-PSERRRLLLKVADVME--SK-TPKFIEVMAMEVGASALWA-G-F-----NVHASANVFREAASLATQIQGETI------PT---------D-----KAETLSMTLRQPV-GPILSIVPWNGTAVLAARAIAYPLVCGNTVVFKGSEFSPATHALITQC----VQE-AGLPAGVLNYLNS---SPDRSP--EIADALISAKEIRRINFTGSTRVGSIIAQKA-A------Q------H------L------K------RCLLELGGKSPLIVLDD---A--D-----INAAVKAAVFGSFLFQGQICMSTER-LVVDEK---------IA-DEFVARFVEKTERLSVGD-PC-LTGDCIIGPMVSPNSGERINGLFKDAIDKGA-KVVCGGM---------------AQGAVMPATILDH--VK---SDMRIYDEETFGPITVVIRC--K------G--E--AEA-IRIA-ND--SVYG-LSSGVFGRDINRALRVG--MSI--E--YGCVHIN--GST-V--------Q---------NEAQAPYGGTKNTGYG--R-F--DG-RAVIDEFTELKWLTI-EPFE---Q--Q-YP--F----------*

C;cover size:492; local alignment length=492 (original info = 3IWJA	500	598.04	5.9e-73	28)
>P1;3IWJA
structureN:3IWJA: 1: : 499: : : :6.0: 
------------------------------P--I-----PTRQLFINGDWKA--PVL-N-KRIPVINPA-T-Q-NIIGDIP---------AATKEDVDVAVAAAKTALTRNKGA-----D--WATAS-GAVRARYLRAIAAKVT--EK-KPELAKLESIDCGKPLDEA-A-W-----DIDDVAGCFEYYADLAEKLDARQK------AP---------VSLP--MDTFKSHVLREPI-GVVGLITPWNYPMLMATWKVAPALAAGCAAILKPSELASLTCLELGEI----CKE-VGLPPGVLNILTGL--G----P--EAGAPLATHPDVDKVAFTGSSATGSKIMTAA-A------Q------L------V------K------PVSLELGGKSPLVVFED---V--D-----LDKAAEWAIFGCFWTNGQICSATSR-LILHES---------IA-TEFLNRIVKWIKNIKISD-PL-E-EGCRLGPVVSEGQYEKILKFVSNAKSEGA-TILTGGSRPEH------L----KKGFFIEPTIITD--VT---TNMQIWREEVFGPVLCVKTF--S------T--E--EEA-IDLA-ND--TVYG-LGAAVISNDLERCERVT--KAF--K--AGIVWVN--CSQ-P------------------CFTQAPWGGVKRSGFG--R-E--LG-EWGLDNYLSVKQVTQ-YI-S---EE-P-WG--W---YQPPAK-*

C;cover size:486; local alignment length=486 (original info = 3IFHQ	482	600.98	1e-73	29)
>P1;3IFHQ
structureN:3IFHQ: 2: : 482: : : :6.0: 
---------------SMK---DP-------S--L-----LRHQAYIGGEWQAADS---D-ATFEVFDPA-T-G-ESLGTVP---------KMGAAETARAIEAAQAAW-----A-----G--WRMKT-AKERAAILRRWFDLVI--AN-SDDLALILTTEQGKPLAEA-K-G-----EIAYAASFIEWFAEEGKRVAGDTL------PT---------P-----DANKRIVVVKEPI-GVCAAITPWNFPAAMIARKVGPALAAGCPIVVKPAESTPFSALAMAFL----AER-AGVPKGVLSVVIG---DP---K--AIGTEITSNPIVRKLSFTGSTAVGRLLMAQS-A------P------T------V------K------KLTLELGGNAPFIVFDD---A--D-----LDAAVEGAIASKYRNNGQTCVCTNR-FFVHER---------VY-DAFADKLAAAVSKLKVGR-GT-E-SGATLGPLINEAAVKKVESHIADALAKGA-SLMTGGKRH--------A----LGHGFFEPTVLTG--VK---PDMDVAKEETFGPLAPLFRF--A------S--E--EEL-VRLA-ND--TEFG-LAAYLYSRDIGRVWRVA--EAL--E--YGMVGIN--TGL-I------------------SNEVAPFGGVKQSGLG--R-E--GS-HYGIDDYVVIKYLCV-AV-------------------------*

C;cover size:501; local alignment length=501 (original info = 1KY8A	499	602.71	1.4e-73	30)
>P1;1KY8A
structureX:1KY8A: 1: : 499: : : :2.40: 
---------AGLLEGVIK---EKG------G--V-----PVYPSYLAGEWGG--S---G-QEIEVKSPI-D-L-ATIAKVI---------SPSREEVERTLDVLFKRG-----RW----S--ARDMP-GTERLAVLRKAADIIE--RN-LDVFAEVLVMNAGKPKSAA-V-G-----EVKAAVDRLRLAELDLKKIGGDYI------PG---------DWTYD-TLETEGLVRREPL-GVVAAITPFNYPLFDAVNKITYSFIYGNAVVVKPSISDPLPAAMAVKA----LLD-AGFPPDAIALLNL---P----G--KEAEKIVADDRVAAVSFTGSTEVGERVVKVG---------------G------V------K------QYVMELGGGDPAIVLED---A--D-----LDLAADKIARGIYSYAGQRCDAIKL-VLAERP---------VY-GKLVEEVAKRLSSLRVGD-PR-D-PTVDVGPLISPSAVDEMMAAIEDAVEKGG-RVLAGGRR--------------LGPTYVQPTLVEA--PADRVKDMVLYKREVFAPVASAVEV--K------D--L--DQA-IELA-NG--RPYG-LDAAVFGRDVVKIRRAV--RLL--E--VGAIYIN--DMP-R--------H---------GIGYYPFGGRKKSGVF--R-E--GI-GYAVEAVTAYKTIVF-NY-K---G--K-GV--W---KYE----*

C;cover size:476; local alignment length=476 (original info = 4I25A	483	593.73	9.9e-73	31)
>P1;4I25A
structureN:4I25A: 3: : 483: : : :6.0: 
-----------------------------------------LLNYIDGNFVT--S---A-SSFANINPV-N-G-KLISDVF---------EADAKQVNEAVVAAQNAL-----KG----P--WGKLS-VQDRAALIHKIADGIQ--AR-FEEFVAAEVADTGRPVHQA-R-TL----DIPRAIANFRTFADLAKTSHTDLF------EM---------STSD--GSGALNYTVRKPL-GVIGVISPWNLPLLLFTWKVAPALACGNTVVAKPSEESPSSATLLAEVM----HD-AGVPPGVFNLIHG---FGK--D--SAGEFLTQHPGISALTFTGESKTGSTIMKAV-A------D------G------V------K------EVSFELGGKNAAVVFAD---A--D-----LDAAIEGVLRSSFTNSGQVCLCSER-VYVHRS---------IF-DEFVSGLKVEAERLVVGY-PD-Q-DGVNMGPLISHGHRDKVLSYYRLAVDEGA-TVVTGGGVPKFNDE---R----DQGAYVQPTIWTG--LS---DKARCVTEEIFGPVCHISPF--D------D--E--DEV-INRV-ND--SNYG-LACAIWTTNLSRAHRVS--RQI--H--VGLVWVN--TWY-L------------------RDLRTPFGGVKLSGLG--R-E--GG-RFSMDFYSDIANICI-KI-------------------------*

C;cover size:486; local alignment length=486 (original info = 3JU8A	480	592.17	1.3e-72	32)
>P1;3JU8A
structureN:3JU8A: 1: : 480: : : :6.0: 
-----------------------------------------STHYIAGQWLAG-Q---G-ETLESLDPV-G-Q-GVVWSGR---------GADATQVDAAVCAAREAF-----P-----A--WARRP-LEQRIELLERFAATLK--SR-ADELARVIGEETGKPLWES-A-T-----EVTSVNKVAISVQA-FRERTGEKS------GP---------------LADATAVLRHKPH-GVVAVFGPYNFPGHLPNGHIVPALLAGNCVVFKPSELTPKVAELTLKA----WIQ-AGLPAGVLNLVQG---G----R--ETGVALAAHRGLDGLFFTGSSRTGNLLHSQF-G------G------Q------P------Q------KILALEGGNNPLVVEEV---A--D-----LDAAVYTIIQSAFISAGQRCTCARR-LLVPQG---------AWGDALLARLVAVSATLRVGR-FD-E-QPAPFGAVISLSAAEHLLKAQEHLIGKGA-QPLLATQPI-------------DGAALLTPGIL-D--VS---AVAERPDEEFFGPLLQVIRY--S------D--F--AAA-IREA-NA--TQYG-LAAGLLSDSRERFEQFL--VES--R--AGIVNWN--KQL-T--------G---------AASSAPFGGIGASGNH--R-P--SA-YYAADYCAYPVASLE-SP-S---V--S-LPATL---TPGI---*

C;cover size:497; local alignment length=497 (original info = 3HAZA	983	649.17	3.5e-74	33)
>P1;3HAZA
structureN:3HAZA: 483: : 983: : : :6.0: 
--------IVRPQAAAHP---RIP------L--PCDLFAPERRNSRGVEFGA--RTALD-QLLTDVKAE-T-G-D-LKPIA---------DATPDQAHAAVAAARAGF-----A-----G--WSRTP-AGIRAAALEQAAHLLE--SR-SAHFIALLQREGGKTLDDA-L-S-----ELREAADFCRYYAAQGRKLFGSET------AMP--------G-----PTGESNALTMRGR-GVFVAISPWNFPLAIFLGQVTAALMAGNSVVAKPAEQTPRIAREAVAL----LHE-AGIPKSALYLVTG---D----G--RIGAALTAHPDIAGVVFTGSTEVARSINRAL-A------A------KDGP---I------V------PLIAETGGINAMIADAT---A--L-----PEQVADDVVTSAFRSAGQRCSALRL-LFVQED---------VA-DRMIEMVAGAARELKIGD-PS-D-VATHVGPVIDVEAKQRLDAHIARMKTE-A-RLHFAGPA--------------PEGCFVAPHIFEL--T-----EAGQLTEEVFGPILHVVRY--RPE----N--L--ERV-LRAI-ER--TGYG-LTLGVHSRIDDSIEAII--DRV--Q--VGNIYVN--RNM-I--------GA--------VVGVQPFGGNGLSGTG--P-KA-GG-PHYLARFATEQTVTI-NT-A---A--A-G--------------*

C;cover size:477; local alignment length=477 (original info = 4YWEA	476	591.38	1.3e-72	34)
>P1;4YWEA
structureN:4YWEA: 1: : 476: : : :6.0: 
-----------------------------------------AKHFIAGEWTL--PAQ-L-ETIPVVDPS-D-G-QPFATIA---------RGTAPDIERAVAAARDAF-----AG----P--WGAAS-AAERGRVLMRLSARVT--DS-IEELAAIEARDTGKPLKQA-R-A-----DAAALARYFEFYAGAADKLHGETL------PY---------------QAGYTVLTVREPH-GVTGHIVPWNYPMQIFGRSVGAALAAGNACVVKPAEDACLSVLRVAEL----AAE-AGLPAGALNIVTGY--G----H--EAGAALARHPGIDHISFTGSPATGKLVTQMA-A------E------N------H------V------PVTLELGGKSPQIVFAD---A--D-----LDAALPVLVSAIVQNGGQTCSAGSR-VLIERA---------VY-EPLVERLATAFNGLRVGP-S--R-ADLDCGPLINAKQQQRVWDFLSDAQHDGI-PMAAHGQVVADA-----P----ESGFYQAPALLRD--VP---PSHRLAQEEVFGPVLAAMRF--V------D--E--DEA-VALA-NG--TPYG-LVAGIWTRDGARQMRLA--RRL--R--AGQVFIN--NYG-A--------G---------GGVELPFGGVGHSGHG--R-E--KG-FEALYGFTALKTIAI-RH-G-----------------------*

C;cover size:494; local alignment length=494 (original info = 4LIHA	494	590.86	3.8e-72	35)
>P1;4LIHA
structureN:4LIHA: 1: : 494: : : :6.0: 
--------KLTLADWQHK---AAS------L--E-----IEGRAFIDGASRDAHG---G-RTFDCVSPI-D-G-RVLAKVA---------DCGEADVNAAVAAARRAF-----D-----AGVWAGLN-PRARKAVLLRWAALMR--EH-LDELSLLETLDAGKPIGDT-TTV-----DVPGAAYCVEWFAEAIDKVGGEVA------PA---------------DHHLVGLVTREPV-GVVAAVVPWNFPILMAAWKFGPALAAGNSVVLKPSEKSPLTAIRVAQLA----FE-AGIPAGVFNVVPG---A----G--EPGKLLALHRDVDCIAFTGSTAVGKLIMQYA-A------QS-----N------L------K------RAWLELGGKSPNIVLPD---CP-D-----LDRAAQTAAGAIFYNMGEMCTAGSR-LLVHRD---------IK-DAFIEKLVAAARAYVPGN-PL-D-PSVSMGAIVDGIQLERVLGYIEAGRGEG--RLVTGGARVNA------E----TGGFYVEPTVFE---VK---PDAKIAREEIFGPVLSVIVF--D------D--V--DEA-VRIA-ND--TEYG-LAAAVWTSNLTTAHDVS--RRL--R--AGTVWVN--CYD-E--------G---------GDMNFPFGGYKQSGNG--R-D--KS-LHALEKYTELKSTLI-RL-R-----------------------*

C;cover size:487; local alignment length=487 (original info = 4PXLA	485	586.52	9.6e-72	36)
>P1;4PXLA
structureN:4PXLA: 1: : 485: : : :6.0: 
-----------------------V------E--V-----RFTKLFIDGKFVDAVS---G-KTFETRDPR-T-G-EVIASIA---------EGDKADVDLAVKAAREAF-----D-----NGPWPRMT-GYERGRILHRFADLID--EH-VEELAALDTVDAGKLFAVG-K-AR----DIPGAAHLLRYYAGAADKVHGATL------KM---------------AQRMHGYTLKEPV-GVVGHIVPWNYPTTMFFFKVGPALAAGCAVVVKPAEQTPLSALFYAHL----ARE-AGVPAGVLNVVPGF--G----P--TAGAAVAAHMDVDKVSFTGSTEVGRLVMRAA-A------ES-----N------L------K------PVSLELGGKSPVIVFDD---A--D-----LDMAVNLVNFATYTNKGEIV-AGTR-IYVQEG---------IY-DEFVKKAAELASKSVVGD-PF-N-PSVSQGPQVDKDQYEKVLRYIDIGKREGA-TLVTGGKPC--------G----DKGYYIEPTIFTD--VK---DDMTIAQDEIFGPVMALMKF--K------T--V--EEV-IQKA-NN--TRYG-LAAGIVTKNIDVANTVS--RSI--R--AGAIWIN--CYF-A------------------FDPDAPFGGYKMSGFG--K-D--MG-MDALDKYLQTKTVVT-PL-Y---N--T-PW--L----------*

C;cover size:485; local alignment length=485 (original info = 3JZ4A	481	588.19	4.5e-72	37)
>P1;3JZ4A
structureN:3JZ4A: 2: : 481: : : :6.0: 
----------------LN---DS-------N--L-----FRQQALINGEWLD--ANN-G-EAIDVTNPA-N-G-DKLGSVP---------KMGADETRAAIDAANRAL-----P-----A--WRALT-AKERATILRNWFNLMM--EH-QDDLARLMTLEQGKPLAEA-K-G-----EISYAASFIEWFAEEGKRIYGDTI------PG---------H-----QADKRLIVIKQPI-GVTAAITPWNFPAAMITRKAGPALAAGCTMVLKPASQTPFSALALAEL----AIR-AGVPAGVFNVVTGS--A----G--AVGNELTSNPLVRKLSFTGSTEIGRQLMEQC-A------K------D------I------K------KVSLELGGNAPFIVFDD---A--D-----LDKAVEGALASKFRNAGQTCVCANR-LYVQDG---------VY-DRFAEKLQQAMSKLHIGD-GL-D-NGVTIGPLIDEKAVAKVEEHIADALEKGA-RVVCGGKAH--------E----RGGNFFQPTILVD--VP---ANAKVSKEETFGPLAPLFRF--K------D--E--ADV-IAQA-ND--TEFG-LAAYFYARDLSRVFRVG--EAL--E--YGIVGIN--TGI-I------------------SNEVAPFGGIKASGLG--R-E--GS-KYGIEDYLEIKYMCI-GL-------------------------*

C;cover size:488; local alignment length=488 (original info = 3IWKA	496	591.09	3.9e-72	38)
>P1;3IWKA
structureN:3IWKA: 2: : 496: : : :6.0: 
-----------------------------------------RQLFIDGEWRVPIL---N-KRIPNINPS-T-E-NIIGDIP---------AATKEDVDLAVDAAKRAISRKNGR-----D--WSAAS-GSLRARYLRAIAAKIK--EK-KDELGKLESIDCGKPLEEA-L-A-----DLDDVVACFEYYAGLAEELDSKQK------APISL------P-----MDTFKSYILKEPI-GVVALITPWNYPFLMATWKIAPALAAGCAAILKPSELASVTCLELGEI----CKE-VGLPRGVLNIVTGL--G----H--EAGASLASHPDVDKISFTGSSATGSKIMTTA-A------Q------L------V------K------PVSLELGGKSPIVVFED---V--D-----LDKVAEWTVFGCFFTNGQICSATSR-LIVHES---------IA-VEFVDKLVKWAENIKISD-PL-E-EGCRLGPIVSEAQYKKVLNCISSAKSEGA-TILTGGRRP--------EHL--KKGYFVEPTIITD--VT---TSMQIWREEVFGPVLAVKTF--S------T--E--EEA-INLA-ND--THYG-LGSAVMSNDLERCERLS--KAL--Q--AGIVWIN--CAQ-P------------------SFIQAPWGGIKRSGFG--R-E--LG-EWGLENYLSVKQVTR-YT-S---DE-P-WG--W---YQPPSK-*

C;cover size:493; local alignment length=493 (original info = 1O04A	494	591.64	3.1e-72	39)
>P1;1O04A
structureX:1O04A: 2: : 494: : : :1.42: 
------------VPAPNQ---Q-P------E--V-----FCNQIFINNEWHDAVS---R-KTFPTVNPS-T-G-EVICQVA---------EGDKEDVDKAVKAARAAF-----QLGS--P--WRRMD-ASHRGRLLNRLADLIE--RD-RTYLAALETLDNGKPYVISYL-V-----DLDMVLKCLRYYAGWADKYHGKTI------PI---------------DGDFFSYTRHEPV-GVCGQIIPWNFPLLMQAWKLGPALATGNVVVMKVAEQTPLTALYVANL----IKE-AGFPPGVVNIVPGF--G----P--TAGAAIASHEDVDKVAFTGSTEIGRVIQVAAGS------S------N------L------K------RVTLELGGKSPNIIMSD---A--D-----MDWAVEQAHFALFFNQGQCSCAGSR-TFVQED---------IY-DEFVERSVARAKSRVVGN-PF-D-SKTEQGPQVDETQFKKILGYINTGKQEGA-KLLCGGGIA--------A----DRGYFIQPTVFGD--VQ---DGMTIAKEEIFGPVMQILKF--K------T--I--EEV-VGRA-NN--STYG-LAAAVFTKDLDKANYLS--QAL--Q--AGTVWVN--CYD-V------------------FGAQSPFGGYKMSGSG--R-E--LG-EYGLQAYTEVKTVTV-KV-PQ--K--N-S--------------*

C;cover size:509; local alignment length=509 (original info = 4IHIA	535	596.99	3.5e-72	40)
>P1;4IHIA
structureN:4IHIA: 21: : 535: : : :6.0: 
KSPERTRLRTE-----LA---SLA------DH-P-----IDLPHVIGGRHRM--GD--G-ERIDVVQPH-RHA-ARLGTLT---------NATHADAAAAVEAAMSAK-----S-----D--WAALP-FDERAAVFLRAADLLA--GPWREKIAAATMLGQSKSVYQA-EID-----AVCELIDFWRFNVAFARQILEQQP------IS---------------GPGEWNRIDYRPLDGFVYAITPFNFTSIAGNLPTAPALM-GNTVIWKPSITQTLAAYLTMQL----LEA-AGLPPGVINLVTGD--G----F--AVSDVALADPRLAGIHFTGSTATFGHLWQWV-G------T------N------IGRYHSYP------RLVGETGGKDFVVAHAS---A--R-----PDVLRTALIRGAFDYQGQKCSAVSR-AFIAHS---------VW-QRMGDELLAKAAELRYGD-IT-D-LSNYGGALIDQRAFVKNVDAIERAKGAAAVTVAVGGEYD--------D----SEGYFVRPTVLLS--DD----------PEYFGPLLSVHVY--P------D--ERYEQI-LDVIDTG--SRYA-LTGAVIADDRQAVLTAL--DRL--RFAAGNFYVN--DKP-T--------GA--------VVGRQPFGGARGSDTN--DKA--GS-PLNLLRWTSARSIKE-TF-V---AATD-HI--Y---PHMAV--*

C;cover size:485; local alignment length=485 (original info = 5MZ8A	481	591.07	2e-72	41)
>P1;5MZ8A
structureN:5MZ8A: 1: : 481: : : :6.0: 
-----------------------V------T--P-----KKYNIFLASKPVD--GD--R-KWLDVTNKY-T-N-DVAAKVP---------QATHKDIDDAIDAAVAAA-----P-----A--MAAMG-AYERKAVLEKVVAELK--NR-FEEIAQTLTMESGKPIKDA-R-G-----EVTRTIDTFQVAAEESVRIYGEHI------PL---------DISAR-NKGLQGIVKKFPI-GPVSMVSPWNFPLNLVAHKVAPAIAVGCPFVLKPASRTPLSALILGEIL----HKIEELPLGAFSILPV---S----R--EDADMFTVDERFKLLTFTGSGPIGWDMKARA-G--------------------K------K------KVVMELGGNAPCIVDDYV--P--D-----LDYTIQRLINGGFYQGGQSCIHMQR-LYVHER---------LY-DEVKEGFVAAVKKLKMGN-PF-E-EDTYLGPMISESAAKGIEDWVKEAVAKGG-KLLTGGN---------------RKGAFIEPTVIED--VP---IEANARKEEIFGPVVLLYKY--S------D--F--KEA-VKEC-NN--THYG-LQSGIFTKDLNKAFYAF--EHM--E--VGGVILN--DSP-A--------L---------RVDSQPYGGLKDSGIQ--R-E--GV-KYAMDDMLETKVLVM-RN-V---G--T-L--------------*

C;cover size:486; local alignment length=486 (original info = 5J6BA	481	587.42	5.5e-72	42)
>P1;5J6BA
structureN:5J6BA: 1: : 481: : : :6.0: 
----------------HH---HHM------L--K-----ETYPYYLANEAVY--A---N-AELEVTDKY-T-G-KVATRVA---------LADASAIDAAIAAAVGAQ-----K-----P--LRALP-AFRRQAILEHCVARFR--ER-FDELAQALCIEAGKPINDS-K-G-----EVTRLIDTFRVAAEESVRIEGGLV------NLEISP-----R-----AQGYSGYYKRVPI-GPCSFISPFNFPLNLAAHKVAPALAAGCPFVLKPASRTPIGALIIGEV----LAE-TDLPKGAFSILPA---H----R--DGADLFTTDERFKLLSFTGSPTVGWELKKKA-G--------------------K------K------KVVLELGGNAAAIVDAD---Q--REV---LDYVVERLAFGAYYQSGQSCIGVQR-IIAHAD---------VY-DALREKLIAKTRSLKMGD-PK-D-PATFVGPMISESEARRLAGWMEAAVAAGA-KIVAGGKV---------------DGAMFEATLLEG--VG---RDQDLYRKEAFGPVALLERF--S------D--F--DDA-LARV-ND--SDFG-LQAGVFTDSLSHAQRAW--DEL--E--VGGVVIN--DVP-S--------F---------RVDNMPYGGVKDSGLG--R-E--GI-RYAIEDMTELRLMVV-RR-R-----------------------*

C;cover size:474; local alignment length=474 (original info = 5KF6A	1207	650.40	2.7e-73	43)
>P1;5KF6A
structureN:5KF6A: 563: : 1030: : : :6.0: 
----------------------------------------------------------G-ETRTVLNPG-D-HRDVVGSVT---------ETSEEDARRAVRLAADAA-----P-----D--WAAVP-PSERAACLDRAAELMQ--AR-MPTLLGLIIREAGKSALNA-I-A-----EVREAIDFLRYYAEQTRRTLG---------------------------------PGHGPL-GPIVCISPWNFPLAIFTGQIAAALVAGNPVLAKPAEETPLIAAEGVRI----LRE-AGIPASALQLLPG---D----G--RVGAALVAAAETAGVMFTGSTEVARLIQAQL-A------D------RLSPAGRP------I------PLIAETGGQNAMIVDSS---A--L-----AEQVVGDVITSAFDSAGQRCSALRV-LCLQED---------VA-DRILTMLKGALHELHIGR-TD-R-LSVDVGPVITSEAKDNIEKHIERMRGLGR-KVEQIGLASE-------T----GVGTFVPPTIIEL-------EKLSDLQREVFGPVLHVIRYRRD------D--L--DRL-VDDV-NA--TGYG-LTFGLHTRLDETIAHVT--SRI--K--AGNLYIN--RNI-I--------GA--------VVGVQPFGGRGLSGTG--P-KA-GG-PLYLGRLVTTAPVPP-QH-SSVHT--D-PV--L---LDFA---*

C;cover size:485; local alignment length=485 (original info = 4GO4A	487	584.55	1.9e-71	44)
>P1;4GO4A
structureN:4GO4A: 3: : 487: : : :6.0: 
-----------------------------------------NQLYIDGRFVDAVA---G-GTIDVVSPH-D-G-SLITRIA---------AAEAADVDLAVAAAKRAF-----P-----A--WSALG-AAERGRLLLKLADRIE--EC-SEELAQLESLNTGHPIRDS-R-GL----DVPRTAACFRYFGGMADKIEGSVI------PV---------------DAGFLNYVQRKPI-GVVAQIVPWNFPLMFTSWKMGPALAAGNTIVIKPSEITPLSTLRIVELM----TE-VGFPKGVVNVVPGY--G----H--TAGQALAEHLDVGKIAFTGSTATGRRIVEAS-K------S------N------L------K------RIQLELGGKGANIVFED---A--N-----IEAAVNGAAWAIFHNQGQACIAGSR-LILHKD---------IA-DQFLERFIALAKSIRLGD-PM-D-PETEMGPLTSALRRDRVLSYIDIAIEQGG-KVLAGGKAP--------DDKALANGFYVEPTVVE---AK---PQDRVCQEEVFGPFVTVVRF--S------S--D--EEA-LAIA-NN--TEYG-LGSGLWTQNLARAHKMA--HAI--H--AGMCWIN--CYK-R------------------VSPGSPFGGVGQSGYG--R-E--MG-FEAIHDYTEARSVWV-NV-D---AK-I-AP--H---FKR----*

C;cover size:481; local alignment length=481 (original info = 5VBFA	478	584.54	1.2e-71	45)
>P1;5VBFA
structureN:5VBFA: 1: : 478: : : :6.0: 
----------------------RH------D--Y-----APLRLYIDGRFHDADG---R-RTQPVVDPG-T-T-RVLGELP---------HATAHDIDAAVQAAHRAF-----V-----T--WRHES-PLVRSDLLRRAAALAR--ER-AETIGRHITMDQGKPLREA-I-A-----EVVSAAEQLEWHAEEGRRTYGRVV------PA---------R-----SPDVMQTVLREPI-GVCAAFSPWNFPFSQAMHKIAAALASGCTLVLKGPEESPSAIVALAQLF----HD-AGLPPGCLNIVWGV--P----G--DVSKQLIEAPQVRKISFTGSVPVGKQLAALA-A------S------L------M------K------RMTMELGGHAPVLVCAD---A--D-----VERAAAMLAAYKFRNAGQVCVSPTR-FFVQRA---------AF-DRFVCAYLDAVGTIRVGY-GL-D-AGVTMGPLAHARRVDEIDAFVADATAKGA-QIATGGMRL--------P----GPGHYFAPTVVLG--PT---RDTRLMNDEPFGPIVGIVPF--D------D--L--DDA-LAEA-NR--LPFG-LASYAFTTSARNAHRIS--RAL--E--AGMVNIN--HFG-M------------------GPAEIPFGGVKDSGFG--S-E--GG-MEAFDGYLVTKFVTQMN--------------------------*

C;cover size:494; local alignment length=494 (original info = 1O9JA	494	584.80	2.4e-71	46)
>P1;1O9JA
structureX:1O9JA: 2: : 494: : : :2.4: 
------------LPAPLT---NIK---------I-----QHTKLFINNEWHESVS---G-KTFPVFNPA-T-E-EKICEVE---------EADKEDVDKAVKAAREAF-----QMGS--P--WRTMD-ASERGQLIYKLADLIE--RD-RLLLATLESINAGKVFASA-YLM-----DLDYCIKALRYCAGWADKIQGRTI------PV---------------DGEFFSYTRHEPI-GVCGLIFPWNAPMILLACKIGPALCCGNTVIVKPAEQTPLTALHVASLI----KE-AGFPPGVVNIVPGY--G----P--TAGAAISSHMDVDKVAFTGSTEVGKMIQEAA-A------KS-----N------L------K------RVTLELGAKNPCIVFAD---A--D-----LDSAVEFAHQGVFTNQGQSCIAASK-LFVEEA---------IY-DEFVQRSVERAKKYVFGN-PL-T-PGVNHGPQINKAQHNKIMELIESGKKEGA-KLECGGGPW--------G----NKGYFIQPTVFSN--VT---DDMRIAKEEIFGPVQQIMKF--K------S--L--DEV-IKRA-NN--TYYG-LVAGVFTKDLDKAVTVS--SAL--Q--AGTVWVN--CYL-A------------------ASAQSPAGGFKMSGHG--R-E--MG-EYGIHEYTEVKTVTM-KI-S---E--K-NS-------------*

C;cover size:482; local alignment length=482 (original info = 5JRYA	477	585.03	1e-71	47)
>P1;5JRYA
structureN:5JRYA: 1: : 477: : : :6.0: 
-----------------------M------L--K-----ETYPYYLANAAVY--A---N-TDLEVTDKY-S-G-KVATRVA---------LADAKAIDAAIGAAVDAT-----K-----P--MRELP-AYKRQAVLDHCVARFR--ER-FDELAEALCIEAGKPINDA-K-G-----EVTRLIDTFRVASEEAVRIDGEVL------NL---------EISAR-AQGYTGYTRRVPI-GPCSFISPFNFPLNLAAHKVAPALAAGCPFVLKPASRTPVGALIIGEV----LAE-TDLPKGAFSVLPA---H----R--DGADLFTTDDRFRLLSFTGSPAVGWALKEKA-G--------------------K------K------KVVLELGGNAAAIVDAD---QLDR-----LDYVVDRLAFGAFYQSGQSCIGVQR-ILAHAD---------IY-DALRDKLIAKTRSLKMGD-PK-D-PSTFVGPMISESESRRLSGWMDAAVAAGA-KIVAGGK---------------VDGAMFEATLLEN--VG---RDQDLYRKEAFGPIAILEKF--D------R--F--DDA-LARV-ND--SDFG-LQAGVFTDSLAHTQQAW--DEL--E--VGGVVIN--DVP-S--------F---------RVDNMPYGGVKDSGLG--R-E--GI-RYAIEDMTEPRLLVV-RR-R-----------------------*

C;cover size:480; local alignment length=480 (original info = 2IMPA	476	582.02	2.3e-71	48)
>P1;2IMPA
structureX:2IMPA: 1: : 476: : : :2.10: 
------------------------------V--P-----VQHPMYIDGQFVT--WRG-D-AWIDVVNPA-T-E-AVISRIP---------DGQAEDARKAIDAAERAQ-----P-----E--WEALP-AIERASWLRKISAGIR--ER-ASEISALIVEEGGKIQQLA-E-V-----EVAFTADYIDYMAEWARRYEGEII------QS---------D-----RPGENILLFKRAL-GVTTGILPWNFPFFLIARKMAPALLTGNTIVIKPSEFTPNNAIAFAKIV----DE-IGLPRGVFNLVLGR--G----E--TVGQELAGNPKVAMVSMTGSVSAGEKIMATA-A------K------N------I------T------KV-LELGGKAPAIVMDD---A--D-----LELAVKAIVDSRVINSGQVCNCAER-VYVQKG---------IY-DQFVNRLGEAMQAVQFGN-PA-ERNDIAMGPLINAAALERVEQKVARAVEEGA-RVAFGGKAV--------E----GKGYYYPPTLLLD--VR---QEMSIMHEETFGPVLPVVAF--D------T--L--EDA-ISMA-ND--SDYG-LTSSIYTQNLNVAMKAI--KGL--K--FGETYIN--REN-F------------------EAMQGFHAGWRKSGIG--G-A--DG-KHGLHEYLQTQVVYL-QS-------------------------*

C;cover size:491; local alignment length=491 (original info = 4I8QA	495	581.45	6.7e-71	49)
>P1;4I8QA
structureN:4I8QA: 1: : 494: : : :6.0: 
------------------------------P--I-----PRRQLYIGGEWRE--PVK-K-NRIPIINPA-T-E-EIIGDIP---------AATAEDVDIAVEAARKAI-----ARD---D--WGSTT-GAQRAKYLRAIAAKVL--EK-KSVLATLESLDSGKTLYES-A-A-----DMDDVAGCFEYYAGLAEALDSRRM------TPVNL------N-----SDSYKSYVLREPL-GVVGLITPWNYPLLMAIWKVAPALAAGCAAILKPSELASITCLELGEIC----RE-IGLPSGALNILTGL--G----P--EAGGPLASHPHVDKISFTGSGPTGSKIMTAA-A------Q------L------V------K------PVSLALGGKSPIVVFDD---ID-N-----LDIAAEWTLFGIFANTGQVCSATSR-LIVQEN---------IA-SAFMDRLLKWTKNIKISD-PL-E-EDCKLGPVVSAGQYEKVLKFISNAKSEGA-TILCGGERPQH------L----KKGYYVQPTIITD--VN---TSMEIWKEEVFGPVLCVKTF--K------T--E--EQA-IELA-ND--TKYG-LGAAVMSKDVKRCERFT--KAF--Q--TGIIWIN--CSQ-P------------------TFNELPWGGKKRSGFG--R-D--LG-KWGLENFLNIKQVTE-YT-S------A-EP--L---AFYKS--*

C;cover size:487; local alignment length=487 (original info = 2VE5A	489	582.44	3.9e-71	50)
>P1;2VE5A
structureN:2VE5A: 1: : 489: : : :6.0: 
------------------------------A--RF----EEQKLYIGGRYVEASS---G-ATFETINPA-N-G-EVLAKVQ---------RASREDVERAVQSAVEGQ-----K-----V--WAAMT-AMQRSRILRRAVDILR--ER-NDELAALETLDTGKPLAET-R-SV----DIVTGADVLEYYAGLVPAIEGEQI------PL---------------RETSFVYTRREPL-GVVAGIGAWNYPVQIALWKSAPALAAGNAMIFKPSEVTPLTALKLAEI----YTE-AGVPDGVFNVLTGS--G----R--EVGQWLTEHPLIEKISFTGGTSTGKKVMASA-SS-----S------S------L------K------EVTMELGGKSPLIIFPD---A--D-----LDRAADIAVMANFFSSGQVCTNGTR-VFIHRS---------QQ-ARFEAKVLERVQRIRLGD-PQ-D-ENTNFGPLVSFPHMESVLGYIESGKAQKA-RLLCGGERVTDGA----F----GKGAYVAPTVFTD--CR---DDMTIVREEIFGPVMSILVY--D------D--E--DEA-IRRA-ND--TEYG-LAAGVVTQDLARAHRAI--HRL--E--AGICWIN--TWG-E------------------SPAEMPVGGYKQSGVG--R-E--NG-LTTLAHYTRIKSVQV-EL-G---D--Y-AS--V---F------*

C;cover size:480; local alignment length=480 (original info = 4U3WA	485	580.38	5.7e-71	51)
>P1;4U3WA
structureN:4U3WA: 1: : 485: : : :6.0: 
---------------------------------R-----QLLRHYINGEFVA--S---G-TTFPNLSPV-D-G-RKLADVC---------EADAALVDSAVQAAHAAQ-----K-----AG-WRDTT-PAQRAAWLHKIADGIE--AR-FDEFVAAEVADTGRPVAQA-R-TL----DIARGIANFRTFADLVRTASGEYF------ET---------HAAD--GSELINYVTRKPL-GVIGIISPWNLPLLLFTWKVAPALAMGNCVVAKPSEETPSSATLLAEV----MHD-VGLPPGVFNLIHG---H----GQNAAGEFLTRHPDISAITFTGESRTGSTIMKAV-A------D------G------V------K------EVSFELGGKNAAVVFAD---A--D-----FDAAVAGVLRSSFTNAGQVCLCSER-VYVERP---------IF-ERFVAALKEQAQALRVGA-PE-D-PATTMGPLISRGHRDKVLSYFRLAVEEGA-TVVTGGGAPSFGDA---R----DDGAFVMPTIWTG--LP---DSARCVREEIFGPVCHIAPF--D------D--E--AEV-VKRV-ND--SAYG-LAASIWTTQLARGHRVA--KQI--E--TGIVWVN--AWF-V------------------RDLRTPFGGTKLSGLG--R-E--GG-RHSLDFYSELTNVCV-RI-A-----------------------*

C;cover size:485; local alignment length=485 (original info = 3B4WA	483	582.81	2.5e-71	52)
>P1;3B4WA
structureN:3B4WA: 1: : 483: : : :6.0: 
-----------------------S------A--T-----EYDKLFIGGKWTK--PST-S-DVIEVRCPA-T-G-EYVGKVP---------MAAAADVDAAVAAARAAF-----D-----NGPWPSTP-PHERAAVIAAAVKMLA--ER-KDLFTKLLAAETGQPPTII-E-TM----HWMGSMGAMNYFAGAADKVTWTET------RT---------------GSYGQSIVSREPV-GVVGAIVAWNVPLFLAVNKIAPALLAGCTIVLKPAAETPLTANALAE----VFAE-VGLPEGVLSVVPG---G----I--ETGQALTSNPDIDMFTFTGSSAVGREVGRRA-A------E------M------L------K------PCTLELGGKSAAIILED---V--D-----LAAAIPMMVFSGVMNAGQGCVNQTR-ILAPRS---------RY-DEIVAAVTNFVTALPVGP-PS-D-PAAQIGPLISEKQRTRVEGYIAKGIEEGA-RLVCGGGRPEG------L----DNGFFIQPTVFAD--VD---NKMTIAQEEIFGPVLAIIPY--D------T--E--EDA-IAIA-ND--SVYG-LAGSVWTTDVPKGIKIS--QQI--R--TGTYGIN--WYA--------------------FDPGSPFGGYKNSGIG--R-E--NG-PEGVEHFTQQKSVLL-PM-G---Y--T-V--------------*

C;cover size:461; local alignment length=461 (original info = 4OGDA	455	580.17	1.5e-71	53)
>P1;4OGDA
structureN:4OGDA: 2: : 455: : : :6.0: 
--------------------------------------------------------------YQTIYPY-T-N-EVLHTFD---------NMTDQGLADVLERAHLLY-----K-----K--WRKEDHLEERKAQLHQVANILR--RD-RDKYAEIMTKDMGKLFTEA-Q-G-----EVDLCADIADYYADKADEFLMSTP------LE---------------TDSGQAYYLKQST-GVILAVEPWNFPYYQIMRVFAPNFIVGNPMVLKHASICPRSAQSFEEL----VLE-AGAEAGSITNLFI---S----Y--DQVSQVIADKRVVGVCLTGSERGGASIAEEA-G------K------N------L------K------KTTLELGGDDAFIILDD---A--D-----WDQLEKVLYFSRLYNAGQVCTSSKR-FIVLDK---------DY-DRFKELLTKVFKTAKWGD-PM-D-PETTLAPLSSAQAKADVLDQIKLALDHGA-ELVYGGEAI--------D----HPGHFVMPTIIAG--LT---KDNPIYYQEIFGPVGEIYKV--S------S--E--EEA-IEVA-ND--SNYG-LGGTIFSSNQEHAKAVA--AKI--E--TGMSFIN--SGW-T--------S----------LPELPFGGIKHSGYG--R-E--LS-ELGFTSFVNEHLIYI-PN-------------------------*

C;cover size:484; local alignment length=484 (original info = 3K2WA	475	579.94	4.2e-71	54)
>P1;3K2WA
structureN:3K2WA: 2: : 475: : : :6.0: 
----------------------LH------F--------KNKVNFIGGQYVP--SNE-S-DTIDILSPS-T-G-KVIGEIP---------AGCKADAENALEVAQAAQ-----K-----A--WAKLT-ARTRQNMLRTFANKIR--EN-KHILAPMLVAEQGKLLSVA-E-M-----EVDVTATFIDYGCDNALTIEGDIL------PS---------D-----NQDEKIYIHKVPR-GVVVGITAWNFPLALAGRKIGPALITGNTMVLKPTQETPLATTELGRI----AKE-AGLPDGVLNVINGT--G----S--VVGQTLCESPITKMITMTGSTVAGKQIYKTS-A------E------Y------M------T------PVMLELGGKAPMVVMDD---A--D-----LDKAAEDALWGRFANCGQVCTCVER-LYVHAS---------VY-DEFMAKFLPLVKGLKVGD-PM-D-ADSQMGPKCNQREIDNIDHIVHEAIKQGA-TVATGG-----------------KGCWYEPTVLVD--VK---QDNIVVHEETFGPILPIVKV--S------S--M--EQA-IEFC-ND--SIYG-LSAYVHTQSFANINQAI--SDL--E--VGEVYIN--RGM-G------------------EQHQGFHNGWKQSGFG--G-E--DG-KFGLEQYLEKKTVYI-NE-A---E-------------------*

C;cover size:480; local alignment length=480 (original info = 1EUHA	474	577.16	8.4e-71	56)
>P1;1EUHA
structureX:1EUHA: 1: : 474: : : :1.82: 
---------------------------------T-----KQYKNYVNGEWKL--S---E-NEIKIYEPA-S-G-AELGSVP---------AMSTEEVDYVYASAKKAQ-----P-----A--WRALS-YIERAAYLHKVADILM--RD-KEKIGAILSKEVAKGYKSA-V-S-----EVVRTAEIINYAAEEGLRMEGEVL------EG---------GSFEAASKKKIAVVRREPV-GLVLAISPFNYPVNLAGSKIAPALIAGNVIAFKPPTQGSISGLLLAE----AFAE-AGLPAGVFNTITGR--G----S--EIGDYIVEHQAVNFINFTGSTGIGERIGKMA---------------G------M------R------PIMLELGGKDSAIVLED---A--D-----LELTAKNIIAGAFGYSGQRCTAVKR-VLVMES---------VA-DELVEKIREKVLALTIGN-PE-D--DADITPLIDTKSADYVEGLINDANDKGA-TALTEIK---------------REGNLICPILFDK--VT---TDMRLAWEEPFGPVLPIIRV--T------S--V--EEA-IEIS-NK--SEYG-LQASIFTNDFPRAFGIA--EQL--E--VGTVHIN--NKT-Q--------R---------GTDNFPFLGAKKSGAG--I-Q--GV-KYSIEAMTTVKSVVF-DI-K-----------------------*

C;cover size:476; local alignment length=476 (original info = 4I3WA	473	578.32	6.3e-71	60)
>P1;4I3WA
structureN:4I3WA: 2: : 473: : : :6.0: 
-----------------------------------------EPMRIAGRLVD--T---D-DRVEVRYPW-N-D-TVVGTVP---------AGRAEHAREAFAIAAAY---------------QPKLT-RYERQKILLATAEALA--AR-KEEISDVITLELGISKADS-L-Y-----EVGRAFDVFTLAGQMCIRDDGEIF------SCDLTP-----H-----GKARKIFTMREPL-TAISAITPFNHPLNMVAHKVAPAIATNNCVVVKPTELTPMTALLLADI----LYE-AGLPPEMLSVVTGW--P----A--DIGMEMITNPHVDLVTFTGSVPVGKLIAANA---------------H------Y------K------RQVLELGGNDPLIILNDLSDD--D-----LARAADLAVAGATKNSGQRCTAVKR-ILCQES---------VA-DRFVPLVLERAKRLRFGD-PM-D-RSTDLGTVIHEKAAALFEERVMRAAEEGA-DILYHPG---------------RSGALLPPIVVDR--VP---HQSDLVLEETFGPIIPIVRV--P------D--D--DDATITLS-NS--TAFG-LSSGVCTNDYRRMQKYI--AGL--K--VGTVNIW--EVP-G--------Y---------RIEMSPFGGIKDSGNG--Y-K--EGVIEAMKSFTNVKTFSL-PW-------------------------*

C;cover size:474; local alignment length=474 (original info = 3V9IA	506	582.72	7.4e-71	61)
>P1;3V9IA
structureN:3V9IA: 20: : 504: : : :6.0: 
QG---SPERDALQKA-LK---DLK------GR-M-----EAIPCVVGDEEVW--TS--D-VQYQVSPFN-H-G-HKVAKFC---------YADKSLLNKAIEAALAAR-----K-----E--WDLKP-IADRAQIFLKAADMLSG-PR-RAEILAKTMVGQGKTVIQA-EID-----AAAELIDFFRFNAKYAVELEGP---------------------------STNSTVYRGLE-GFVAAISPFNFTAIGGNLAGAPAL-MGNVVLWKPSDTAMLASYAVYRI----LRE-AGLPPNIIQFVPAD--G----P--LFGDTVTSSEHLCGINFTGSVPTFKHLWKQV-A------Q------N------L------DRFHTF-PRLAGECGKNFHFVHRS---A--D-----VESVVSGTLRSAFEYGGQKCSACLR-LYVPHS---------LW-PQIKGRLLEEHSRIKVGD-PA-EDFGTFFSAVIDAKSFARIKKWLEHARSSPSLTILAGGKCD--------D----SVGYFVEPCIVES--KD---PQEPIMKEEIFGPVLSVYVY--P------DDKY--KET-LQLV-DST-TSYG-LTGAVFSQDKDVVQEAT--KVL--RNAAGNFYIN--DKS-T--------ILRWTSPQVIKETHKPLGDWSYA--------------------------------------------------------*

C;cover size:487; local alignment length=487 (original info = 2VROA	521	584.87	7.1e-71	64)
>P1;2VROA
structureN:2VROA: 1: : 521: : : :6.0: 
-----------------------H------M--T-----ELLKNHVAGQWIA--GT--G-AGITLTDPV-T-G-VALVRVS---------SEG-LDLARAFSFAREDGG----A-----A--LRALT-YAQRAARLADIVKLLQ--AK-RGDYYAIATANSGTTRNDS-A-V-----DIDGGIFTLSYYAKLGASLGEVHA------LRDGSAESLSKD-----RSFSAQHVLSPTR-GVALFINAFNFPSWGLWEKAAPALLSGVPVIVKPATATAWLTQRM---VADVVDA-GILPPGALSIICG---S----S----AGLLDQIRSFDVVSFTGSADTAATLRAHP-AFV----Q------R------G------A------RLNVEADSLNSAILCAD---A--TPDTPAFDLFIKEVVREMTVKSGQKCTAIRR-AFVPEA---------AL-EPVLEALKAKLAKITVGN-PR-N-DAVRMGSLVSREQYENVLAGIAALRE-EA-VLAYDSSAVPLIDAD--A----NIAACVAPHLFVVNDPD---NATLLHDVEVFGPVASVAPY--RVTTDTLP--E--AHA-VALA-RR--GQGS-LVASIYSNDDAHLGRLA--LELADS--HGRVHAI--SPS-VQHSQTGHGN---------VMPMSLHGGPGRAGGG--E-E--LG-GLRALAFYHRRSAIQ-AA-SA--A--I-GT--L----------*

C;cover size:504; local alignment length=504 (original info = 5UJUA	558	601.43	1.9e-72	71)
>P1;5UJUA
structureN:5UJUA: 19: : 558: : : :6.0: 
AI---ESRGYWSPFAEMP---SPK------V--Y-----GESGNADGEAAFKSHL---G-KTFELDQPA-S-G-ETVGAERSPYGVALDIRYPKSTPDALIAAAAAAQ-----R-----T--WREAG-PSAWIGVSLEILARLN--RA-SFEIAYSVMHTTGQAFMMA-F-QAGGPHAQDRALEAVAYAWDQLRRIPADAHWEKPQGKN---------P-----PLAMQKRYTIVPR-GTGLVLGCCTFPTWNGYPGLFADLATGNTVIVKPHPGAILPLAITVRIARDVLRE-AGFDPNVVTLLATEPND----G--ALVQDLALRPEIKLIDFTGSTQNGTWLERHA---------------H------Q------A------QVYTEKAGVNQIVIDST---D--D-----LKAAAKNIAFSLALYSGQMCTAPQN-IYVPRDGIRTADGHASF-DEVAQAIAGAVQKL-TGD-PA-R-SVELIGAIQN----DGVTARIDAARAVGR-VLLDSQTLQHPA-----F----PDARVRTPLVLQL--DV---ADREKFTQEWFGPISFVIAT--D------S--T--AQS-LDLA-GEIAAEHGALTLSVYSTADDVIDAAH--EAA--V--RGGVALSINLTGGV--------F---------VNQSAAFSDFHGTGAN--P-A--ANAALADAAFVANRFRVV-QSRV---H--V-AP--K----------*

C;query_length:511 num_of_temps:1 cover_ratio:0.98 cover:502 not_cover:9
>P1;ALDH7A1_A171V
 : : : : : : : : : 
MS---TLLINQPQYAWLK---ELG------L--R-----EENEGVYNGSWGG--R---G-EVITTYCPA-N-N-EPIARVR---------QASVADYEETVKKAREAW-----K-----I--WADIP-APKRGEIVRQIGDALR--EK-IQVLGSLVSLEMGKILVEG-V-G-----EVQEYVDICDYAVGLSRMIGGPIL------PS---------E-----RSGHALIEQWNPV-GLVGIITAFNFPVVVYGWNNAIAMICGNVCLWKGAPTTSLISVAVTKIIAKVLED-NKLPGAICSLTCG---G----A--DIGTAMAKDERVNLLSFTGSTQVGKQVGLMV-Q------E------R------F------G------RSLLELGGNNAIIAFED---A--D-----LSLVVPSALFAAVGTAGQRCTTARR-LFIHES---------IH-DEVVNRLKKAYAQIRVGN-PW-D-PNVLYGPLHTKQAVSMFLGAVEEAKKEGG-TVVYGGKVM--------D----RPGNYVEPTIVTG--LG---HDASIAHTETFAPILYVFKF--K------N--E--EEV-FAWN-NE--VKQG-LSSSIFTKDLGRIFRWLGPKGS--D--CGIVNVN--IPT-S--------G---------AEIGGAFGGEKHTGGG--R-E--SG-SDAWKQYMRRSTCTI-NY-S---K--D-LP--L---AQGIKFQ*
