C;cover size:498; local alignment length=498 (original info = 3QANA	516	643.49	1.5e-78	2)
>P1;3QANA
structureN:3QANA: 16: : 516: : : :6.0: 
VE---ANRKAFEEALGLV---EKE------L--G-----KEYPLIINGERVT--T---EDKIQSWNPA-RKD-QLVG-SVS---------KANQDLAEKAIQSADEAF-----Q-----T--WRNVN-PEERANILVKAAAIIR--RR-KHEFSAWLVHEAGKPWKEA-D-A-----DTAEAIDFLEYYARQMIELNRGKE------IL---------S--------RPGEQNRYFYTPM-GVTVTISPWNFALAIMV--GTAVAPIVTGNTVVLKPASTTPVVAAKFVEV----LED-AGLPKGVINYVPGS--G----A--EVGDYLVDHPKTSLITFTGSKDVGVRLYERA-AVVRPGQN------H------L------K------RVIVEMGGKDTVVVDRD---A--D-----LDLA--AESILVSAFGFSGQKCSAGSR-AVIHK-D---------VY-DEVLEKTVALAKN-LTVGD-PT-N-RDNYMGPVIDEKAFEKIMSYIEIGKKE-G--RLMTGGE-GD--------S----STGFFIQPTIIAD--LD---PEAVIMQEEIFGPVVAFSKA--N------D--F--DHA-LEIA-NN--TEYG-LTGAVITR--NRAHIEQAK--REF--H--VGNLYFN--RNC-T--------GA--------IVGYHPFGG-FKMSGTD--SKA--GG-PDYLALHMQAKTVSE-MY----------------------------*

C;cover size:490; local alignment length=490 (original info = 4PS9A	491	634.19	7.7e-78	3)
>P1;4PS9A
structureN:4PS9A: 1: : 491: : : :6.0: 
------------TNIELKPKVEAF------L--N-----EEIKMFINGEFVSAIG---GKTFETYNPA-T-E-DVLA-VVC---------EAQEEDIDAAVKAARSAF-----E-----SGPWAEMT-TAERAHLIYKLADLIE--EH-REELAQLEALDNGKPYQVA-LDD-----DISATVENYRYYAGWTTKIIGQTI------PI------------------SKDYLNYTRHEPV-GVVGQIIPWNFPLVMSS--WKMGAALATGCTIVLKPAEQTPLSLLYAAKLF----KE-AGFPNGVVNFVPGF--G----P--EAGAAIVNHHDIDKVAFTGSTVTGKYIMRQS-A------E------M------I------K------HVTLELGGKSPNIILED---A--D-----LEEA--INGAFQGIMYNHGQNCSAGSR-VFVHR-K---------HY-ETVVDALVKMANN-VKLGA-GM-E-KETEMGPLVSKKQQERVLNYIEQGKKE-GA-TVAAGGE-RA--------L----EKGYFVKPTVFTD--VT---DDMTIVKEEIFGPVVVVLPF--D------S--T--EEV-IERA-NN--SSYG-LAAGVWTQ--NIKTGHQVA--NKL--K--AGTVWIN--DYN-L------------------ENAAAPFGG-YKQSGIG--R-E--LG-SYALDNYTEVKSVWV-NI-K--------------------------*

C;cover size:499; local alignment length=499 (original info = 4O5HA	511	639.65	3.7e-78	4)
>P1;4O5HA
structureN:4O5HA: 11: : 511: : : :6.0: 
ME---TNETFALLDATRA---F--------L--A-----KPKQMLIGAEWSDAAS---GRQLDVVNPA-D-G-TVIA-RVP---------EADERDVQQAVAAARRAF-----DAG---P--WRTAK-TTDRERLMLVLADLIE--AN-ARELAEIESLDNGKPVMVA-Q-GL----DVAMAAQCFRYMAGWATKIEGSVI------DA---------GMPYLP---DSEIFAYTRKEPV-GVVGAIIPWNFPLLMAA--WKIAPALATGCTVVLKPAEDTPLSALRLGEL----IQA-AGFPDGVVNIVTGY--G----H--TAGAALSRDPRIDKIAFTGSTQTGKTIGHAA-L------D------N------M------T------RMSLELGGKSPVIVLPD---V--D-----LDKA--AQGVANAIFFNQGQVCTAGSR-AYIHS-K---------VF-DGVIERVAKIAAS-LKIGP-GM-D-PATQIGPLVSAKQRERVCGYIDSGFGE-GA-RAAAGGR-AI--------D----GPGFFVEPTVLVD--TT---QAMRVVREEIFGPVLVAMPF--D------D--V--DTA-VQLA-ND--TPYG-LGASIWSN--DLSAIHKLV--PRI--A--AGTVWVN--CHS-L------------------LDNALPFGG-MKQSGFG--R-E--LG-RAVIDQYTESKSVMM-NY-A--------------------------*

C;cover size:492; local alignment length=492 (original info = 3RJLA	513	643.67	1.3e-78	5)
>P1;3RJLA
structureN:3RJLA: 13: : 513: : : :6.0: 
---------EENRKAFEK---ALETVNNEWL--G-----QSYPLVIDGERYE--T---ENKIVSINPA-NKE-EVVG-TVS---------KATQDHAEKAIQAAAKAF-----E-----T--WRYTD-PEERAAVLFRAVAKVR--RK-KHEFSALLVKEAGKPWNEA-D-A-----DTAEAIDFMEYYARQMIELAKGKP------VN---------S--------REGERNQYVYTPT-GVTVVIPPWNFLFAIMA--GTTVAPIVTGNTVVLKPASAAPVIAAKFVEV----LEE-SGLPKGVVNFVPGS--G----A--EVGDYLVDHPKTSIITFTGSREVGTRIFERA-A------KVQPGQTH------L------K------QVIAEMGGKDTVVVDED---C--D-----IELA--AQSIFTSAFGFAGQKCSAGSR-AVVHE-K---------VY-DEVLKRVIEITES-KKVGE-PD-S-ADVYMGPVIDQASFNKIMDYIEIGKEE-G--RLVSGGK-GD--------D----SKGYFIEPTIFAD--LD---PKARLMQEEIFGPVVAFSKV--S------S--F--DEA-LEVA-NN--TEYG-LTGAVITK--NRDHINRAK--QEF--H--VGNLYFN--RNC-T--------GA--------IVGYHPFGG-FKMSGTD--SKA--GG-PDYLALHMQAKTISE-MF----------------------------*

C;cover size:496; local alignment length=496 (original info = 1UZBA	516	638.97	5.9e-78	6)
>P1;1UZBA
structureX:1UZBA: 16: : 516: : : :1.4: 
-----TEEARRAMREALR---RVR------EEFG-----RHYPLYIGGEWVD--T---KERMVSLNPSAP-S-EVVG-TTA---------KAGKAEAEAALEAAWKAF-----K-----T--WKDWP-QEDRSRLLLKAAALMR--RR-KRELEATLVYEVGKNWVEA-S-A-----DVAEAIDFIEYYARAALRYRYPAV------EVV--------P--------YPGEDNESFYVPL-GAGVVIAPWNFPVAIFT--GMIVGPVAVGNTVIAKPAEDAVVVGAKVFEI----FHE-AGFPPGVVNFLPGV--G----E--EVGAYLVEHPRIRFINFTGSLEVGLKIYEAA-G------RLAPGQTW------F------K------RAYVETGGKNAIIVDET---A--D-----FDLA--AEGVVVSAYGFQGQKCSAASR-LILTQ-G---------AY-EPVLERVLKRAER-LSVGP-A--E-ENPDLGPVVSAEQERKVLSYIEIGKNE-G--QLVLGGK-RL--------E----GEGYFIAPTVFTE--VP---PKARIAQEEIFGPVLSVIRV--K------D--F--AEA-LEVA-ND--TPYG-LTGGVYSR--KREHLEWAR--REF--H--VGNLYFN--RKI-T--------GA--------LVGVQPFGG-FKLSGTN--A-KT-GA-LDYLRLFLEMKAVAE-RF----------------------------*

C;cover size:497; local alignment length=497 (original info = 2J6LA	497	632.89	1.5e-77	7)
>P1;2J6LA
structureX:2J6LA: 1: : 497: : : :1.3: 
-----TLLINQPQYAWLK---ELG------L--R-----EENEGVYNGSWGG--R---GEVITTYCPA-N-N-EPIA-RVR---------QASVADYEETVKKAREAW-----K-----I--WADIP-APKRGEIVRQIGDALR--EK-IQVLGSLVSLEMGKILVEG-V-G-----EVQEYVDICDYAVGLSRMIGGPIL------PS---------E--------RSGHALIEQWNPV-GLVGIITAFNFPVAVYG--WNNAIAMICGNVCLWKGAPTTSLISVAVTKIIAKVLED-NKLPGAICSLTCG---G----A--DIGTAMAKDERVNLLSFTGSTQVGKQVGLMV-Q------E------R------F------G------RSLLELGGNNAIIAFED---A--D-----LSLV--VPSALFAAVGTAGQRCTTARR-LFIHE-S---------IH-DEVVNRLKKAYAQ-IRVGN-PW-D-PNVLYGPLHTKQAVSMFLGAVEEAKKE-GG-TVVYGGK-VM--------D----RPGNYVEPTIVTG--LG---HDASIAHTETFAPILYVFKF--Q------N--E--EEV-FAWN-NE--VKQG-LSSSIFTK--DLGRIFRWLGPKGS--D--CGIVNVN--IPT-S--------G---------AEIGGAFGG-EKHTGGG--R-E--SG-SDAWKQYMRRSTCTI-NY-S--------------------------*

C;cover size:498; local alignment length=498 (original info = 4PXNA	498	632.97	1.5e-77	8)
>P1;4PXNA
structureN:4PXNA: 1: : 498: : : :6.0: 
----------KEEHQFLA---ELG------LA-Q-----RNPGAFACGAWGG--S---GPTVTSTSPT-N-N-QVIA-EVV---------EASVHDYEEGMRACFDAA-----K-----T--WMAIP-APKRGEIVRQIGDALR--AK-LHHLGRLVSLEMGKILPEG-I-G-----EVQEIIDMCDYAVGLSRQLNGSII------PS---------E--------RPNHMMMEVWNPL-GVVGVITAFNFPCAVLG--WNACIALVCGNCVVWKGAPTTPLITIAMTKIVASVLEK-NNLPGAIFTSFCG---G----T--EIGQAIALDIRIPLVSFTGSTRAGLMVQQQV-S------A------R------F------G------KCLLELSGNNAIIVMDD---A--D-----IQLA--VRSVLFAAVGTAGQRCTTCRR-LILHE-N---------IY-QTFLDQLVEVYKQ-VRIGD-PL-E-KGTLLGPLHTPASKENFLKGIQTIKSQ-GG-KILFGGS-AI--------E----SEGNFVQPTIV-E--IT---PSAPVVKEELFGPVLYVMKF--Q------T--L--KEA-IEIN-NS--VPQG-LSSSIFTK--RPDIIFKWLGPHGS--D--CGIVNVN--IPT-N--------G---------AEIGGAFGG-EKATGGG--R-E--AG-SDSWKQYMRRATCTI-NY-G---S---E-L--P--L---A------*

C;cover size:511; local alignment length=511 (original info = 4F9IA	976	680.13	8e-78	9)
>P1;4F9IA
structureN:4F9IA: 461: : 973: : : :6.0: 
RA---DHRAAFPKHIAQV---RTQ------L--G-----KTYPLFINGKEVR--T---NDLIPTVNPN-KPS-EVLG-QIC---------QAGTTEVGDAIAAAKAAF-----P-----A--WRDTD-PRTRAEYLLKAAQAAR--KR-LFELSAWQVLEIGKQWDQA-Y-A-----DVTEAIDFLEYYAREMIRLGQPQR------VG---------H--------APGELNHYFYEPK-GVAAVIAPWNFPLAISM--GMASAAIVTGNCVVFKPSGITSIIGWHLVEL----FRE-AGLPEGVFNFTPGR--G----S--VMGDYLVDHPDISLIAFTGSMETGLRIIERA-A------KVHPGQAN------V------K------KIISEMGGKNAIIIDDD---A--D-----LDEA--VPHVLYSAFGFQGQKCSACSR-VIVLD-A---------VY-DKFIERLVSMAKA-TKVGP-SE-D-PANYMGAVADDKAMKSIKEYAEIGKRE-GH-V-LYESP-VP--------A----GEGYFVPMTIIGG--IK---PEHRIAQEEIFGPVLAVMRA--K------D--F--DQA-IEWA-NS--TQFA-LTGGIFSR--SPEHLAKAR--REF--R--VGNLYIN--RNN-T--------GA--------LVERQPFGG-ARMSGVG--T-KA-GG-PDYLLHFMDPRVVTE-NT-M---R-----R--G--F---APIEEDD*

C;cover size:510; local alignment length=510 (original info = 3V9JA	544	638.74	2.1e-77	10)
>P1;3V9JA
structureN:3V9JA: 23: : 543: : : :6.0: 
QG---SPERDALQKA-LK---DLK------G--QT----EAIPCVVGDEEVW--T---SDIQYQLSPF-NHA-HKVA-KFC---------YADKALLNRAIDAALAAR-----K-----E--WDLKP-MADRAQVFLKAADMLSGPRR-AEVLAKTM-VGQGKTVIQA-EID-----AAAELIDFFRFNAKFAVELEGEQP------IS---------V--------PPSTNHTVYRGLE-GFVAAISPFNFTAIGGN--LAGAPAL-MGNVVLWKPSDTAMLASYAVYRI----LRE-AGLPPNIIQFVPAD--G----P--TFGDTVTSSEHLCGINFTGSVPTFKHLWRQV-A------Q------N------L------DRFRTFPRLAGECGGKNFHFVHSS---A--D-----VDSV--VSGTLRSAFEYGGQKCSACSR-LYVPK-S---------LW-PQIKGRLLEEHSR-IKVGD-PAED-FGTFFSAVIDAKAFARIKKWLEHARSS-PSLSILAGGQ-CN--------E----SVGYYVEPCIIES--KD---PQEPIMKEEIFGPVLTVYVY--P------DDKY--RET-LKLV-DST-TSYG-LTGAVFAQ--DKAIVQEAT--RML--RNAAGNFYIN--DKS-T--------GS--------VVGQQPFGG-ARASGTN--DKP--GG-PHYILRWTSPQVIKE-TH-K---P-----L--G--D---WRYSYM-*

C;cover size:503; local alignment length=503 (original info = 3U4JA	497	625.66	1.3e-76	11)
>P1;3U4JA
structureN:3U4JA: 1: : 497: : : :6.0: 
------VLSNFIAPDSND---PR-------L--RI----KSRYQLVDGKSVD--AAS-GSTIDRVSPGHA-G-EVVG-TWP---------EASADDVRKAVAAARKAF-----D-----A--GPWPR-SGAERSRLFKVADLIL--AR-QEELALIESLEVGKPIAQA-R-G-----EIGFCADLWSYAAGQARALEGQTH------NN---------I--------GDDRLGLVLREPV-GVVGIITPWNFPFIIAS--ERVPWAIGSGCTVVLKPSEFTSGTSIRLAEL----ARE-AGIPDGVFNVVTGY--G----D--PAGQVLAEDPNVD-VAFTGSVRVGTKLGEIA-A------R------T------V------K------RVGLELGGKGPQIVFAD---A--D-----LDAA--ADGIAYGVYHNAGQCCISGSR-LLVQE-G---------IR-DAL-ERLLDISRK-VAFGD-PL-N-ERTKIGA-ISEAHAEKVHSYVTAGITS-GA-ELLLGGE-RIG-------R----EAGLYYAPTVFAG--VT---PDS-IAREEIFGPVLSTLTF--K------T--A--DEA-VALA-NA--TEFG-LSASVWST--NLETALQTI--RRI--R--AGRCWIN--SVI-D------------------GTPELPIGG-YKKSGLG--R-E--LG-RYGFDEYSQFKGVHV-TL-G---R---P-A--P--W---FT-----*

C;cover size:487; local alignment length=487 (original info = 4ZZ7A	489	623.04	2e-76	12)
>P1;4ZZ7A
structureN:4ZZ7A: 1: : 489: : : :6.0: 
---------------------------------M-----TTIGHLINGQLVT--EN--TRSQNVFNPA-T-G-EIGK-QLD---------LASTKTVEQAISAAQHAF-----P-----T--WRNTP-PLKRARVMFRFKELLE--QH-ADEICRLIGEEHGKIAHDA-M-G-----ELQRGIENVEYACGAPELLKGEHS------RN---------V--------GPGIDSWSEFQPM-GVVAGITPFNFPVMVPL--WMFPMAIVCGNCFVLKPSERDPSSTLYIAQL----LQE-AGLPDGVMNVVNG---D----K--EAVDALLHDDRVKAVSFVGSTPIAEYIYRTA-S------A------N------G------K------RCQALGGAKNHAIVMPD---A--D-----MDNA--VNQLLGAAFGSSGERCMALSVAVAVGD-A---------AG-DALVSKMTQAMQK-LKVGP-ST-D-SGNDFGPVITRQHQEKVIGYINSAEQQ-GA-TIVVDGR-QPKVPN----H----ENGFFVGGTLIDH--VT---PEMTSYQEEIFGPVLQVVRV--A------T--M--QDA-MDLI-DA--HEYG-NGTCIFTR--DGEAARYFS--DNI--Q--VGMVGIN--IPL-P--------V---------PVAYHSFGG-WKRSLFGDLH-A--YG-PDAVRFYTKRKTVTQ-RW-P---S---A-G--V--R---EG-----*

C;cover size:508; local alignment length=508 (original info = 2D4EA	513	619.23	1.8e-75	13)
>P1;2D4EA
structureX:2D4EA: 8: : 513: : : :2.10: 
IS---WETIEEVRRR-LK---------------E-----RPALHFIAGEFVP--SES-GETFPSLDPA-T-N-EVLG-VAA---------RGGEREVDRAAKAAHEAF-----Q-----R--WSRTK-AKERKRYLLRIAELIE--KH-ADELAVMECLDAGQVLRIV-R-A-----QVARAAENFAFYAEYAEHAMEDRT------FP---------V--------DRDWLYYTVRVPA-GPVGIITPWNAPLMLST--WRIAPALAFGNTVVLKPAEWSPFTATKLAEI----LKE-ADLPPGVFNLVQGF--G----E--EAGAALVAHPLVPLLTLTGETETGKIVMRNA-A------D------H------L------K------RLSPELGGKSPALVFAD---A--D-----LERA--LDAVVFQIFSFNGERCTASSR-LLVEE-K---------IF-EDFVGKVVERARA-IRVGH-PL-D-PETEVGPLIHPEHLQRVLGYVEAGKRE-GA-RLLVGGE-RAKTSFRGEDL----SRGNYLLPTVFVG---E---NHMKIAQEEIFGPVLVAIPF--K------D--E--EEA-LRKA-ND--TKYG-LAAYVFTR--DLERAHRLA--LEL--E--AGMVYLN--SHN-V------------------RHLPTPFGG-VKGSGDR--R-E--GG-TYALDFYTDLKTIAL-PL-R---P---P-H--V--P---KFGK---*

C;cover size:493; local alignment length=493 (original info = 2O2PA	498	616.38	2.2e-75	14)
>P1;2O2PA
structureX:2O2PA: 2: : 498: : : :1.70: 
--------INYVEKAVNK---L-T------L--Q-----MPYQLFIGGEFVD--AEG-SKTYNTINPT-D-G-SVIC-QVS---------LAQVSDVDKAVAAAKEAF-----E-----NGLWGKIN-ARDRGRLLYRLADVME--QH-QEELATIEALDAGAVYTLA-LKT-----HVGMSIQTFRYFAGWCDKIQGATI------PI---------NQAR-----PNRNLTLTKKEPV-GVCGIVIPWNYPLMMLS--WKTAACLAAGNTVVIKPAQVTPLTALKFAEL----TLK-AGIPKGVVNILPGS--G----S--LVGQRLSDHPDVRKIGFTGSTEVGKHIMKSC-AL-----S------N------V------K------KVSLELGGKSPLIIFAD---C--D-----LNKA--VQMGMSSVFFNKGENCIAAGR-LFVEE-S---------IH-NQFVQKVVEEVEK-MKIGN-PL-E-RDTNHGPQNHEAHLRKLVEYCQRGVKE-GA-TLVCGGN-QV--------P----RPGFFFQPTVFTD--VE---DHMYIAKEESFGPIMIISRF--A------DGDV--DAV-LSRA-NA--TEFG-LASGVFTR--DINKALYVS--DKL--Q--AGTVFIN--TYN-K------------------TDVAAPFGG-FKQSGFG--K-D--LG-EAALNEYLRIKTVTF-EY----------------------------*

C;cover size:506; local alignment length=506 (original info = 5UR2A	956	667.30	2.6e-76	15)
>P1;5UR2A
structureN:5UR2A: 449: : 956: : : :6.0: 
KA---DREKMLKALAEAK---ASL---------P-----VNVNIVINNKELQ--S---GKIFDRVNPS-QSD-QIVG-KIQ---------MATTEQAEQAMQAAQTAY-----K-----T--WKNVP-CEQRAALVDKLADIMT--RD-RFKLIATQVLEVGKPWAEA-D-G-----DIGEAIDFCRYYARHMRELQKPLR------VG---------G--------LPGELSHYIYKSR-GVTAVIAPWNFPLAILA--GMVTAAAVAGNTVVMKPAEQSTVVAWGLMKM----IQE-AGFPQGVINFLPGY--G----E--EVGEYIVNHKYTTTIAFTGSKAVGLHIMNRA-AVVQPGQQ------H------V------K------RCIIEMGGKNAVIIDND---A--D-----LDEA--VDGVIYSAFGFSGQKCSAASR-VIVLD-E---------VY-DRFVDRLVETAKS-IEIHP-AE-N-PKAYMGPVVDKEAYDRILGTIAEAEKN-HK--LLFKGS-V---------P----GGGFFAPPTIFGD--VP---GDAKLAQAEIFGPVVAVIRA--K------N--L--DQA-LDIA-NS--TEYA-LTGGVFSR--SPANINRVK--EEL--E--VGNLYVN--RGI-T--------GA--------MVDRHPFGG-FKMSGIGS-K-T--GG-PDYLKQYMEPACVTE-NT-LR--R---G-F--A--P---AE-----*

C;cover size:489; local alignment length=489 (original info = 5IZDA	493	614.29	3.3e-75	16)
>P1;5IZDA
structureN:5IZDA: 3: : 488: : : :6.0: 
-----------------------------------------TKLYIDGQWVNSSS---GKTVDKYSPV-T-G-QVIG-RFE---------AATRDDVDRAIDAAEDAF-----W-----A--WNDLG-SVERSKIIYRAKELIE--KN-RAELENIIMEENGKPVKEA-K-E-----EVDGVIDQIQYYAEWARKLNGEVV------EG---------T--------SSHRKIFQYKVPY-GIVVALTPWNFPAGMVA--RKLAPALLTGNTVVLKPSSDTPGSAEWIVRKF----VE-AGVPKGVLNFITGR--G----S--EIGDYIVEHKKVNLITMTGSTATGQRIMQKA-S------A------N------M------A------KLILELGGKAPFMVWKD---A--D-----MDNA--LKTLLWAKYWNAGQ-SIAAER-LYVHE-D---------IY-DTFMSRFVELSRK-LALGD-PK-N---ADMGPLINKGALQATSEIVEEAKES-GA-KILFGGS-QPSLSGP---Y----RNGYFFLPTIIGN--AD---QKSKIFQEEIFAPVIGARKI--S------S--V--EEM-YDLA-ND--SKYG-LASYLFTK--DPNIIFEAS--ERI--R--FGELYVN--MPG-P------------------EASQGYHTG-FRMTGQA--G-E--GS-KYGISEYLKLKNIYV-DY-S---G-----K--P--L---HINTVRD*

C;cover size:486; local alignment length=486 (original info = 4O6RA	489	608.18	1.7e-74	17)
>P1;4O6RA
structureN:4O6RA: 4: : 489: : : :6.0: 
-----------------------------------------TQLFIDGRFVD--AVD-RGTIDVLNPH-D-G-SVIT-KIA---------AATAADVDLAVDAATRAF-----P-----A--WSAMP-AAERGRLLLRLADAIE--AN-TEALAQLESLDTGHPIRDS-R-AL----DVPRTAACFRYFGGMADKLQGSVI------PV------------------DTGFLNYVQRAPI-GVVGQIVPWNFPLMFTS--WKMGPALAAGNTVVLKPSEITPLSTLRIVELM----AE-VGFPAGVVNIVPGY--G----H--TAGQRLAEHPGVGKIAFTGSTATGRRIVEAS-Q------G------N------L------K------RVQLELGGKGANIVFDD---A--N-----LDAA--INGAAWAIFHNQGQACIAGSR-LVLHE-R---------IA-DAFLERFVALASS-IRIGN-PL-D-PNTEMGPLTSKQHLDRVLSYVDVAREQ-GG-RVLTGGS-APQDPA----L----ANGYYVRPTIVEA--KH---ATDRVAQEEVFGPFVTVLRF--G------S--D--DEA-LAIA-NA--TEYG-LGSGLWTN--DLSRAHRMA--ARI--D--AGMCWIN--CYK-R------------------VNPGSPFGG-VGKSGYG--R-E--MG-FEAMHDYTEARSVWV-NV-D---G---N-V--P--P---HFKR---*

C;cover size:492; local alignment length=492 (original info = 4I8PA	500	610.89	1.3e-74	18)
>P1;4I8PA
structureN:4I8PA: 1: : 499: : : :6.0: 
------------------------------M--V-----PLRQLFVDGEWRPPAQ---GRRLPVVNPT-T-E-AHIG-EIP---------AGTAEDVDAAVAAARAAL-----KRNRGRD--WARAP-GAVRAKYLRAIAAKVI--ER-KPELAKLEALDCGKPYDEA-A-W-----DMDDVAGCFEYFADQAEALDKRQN------SP---------VSLP-----METFKCHLRREPI-GVVGLITPWNYPLLMAT--WKIAPALAAGCTAVLKPSELASVTCLELADI----CKE-VGLPSGVLNIVTGL--G----P--DAGAPLSAHPDVDKVAFTGSFETGKKIMASA-A------P------M------V------K------PVTLELGGKSPIVVFDD---V--D-----IDKA--VEWTLFGCFWTNGQICSATSR-LLIHT-K---------IA-KKFNERMVAWAKN-IKVSD-PL-E-EGCRLGPVVSEGQYEKIKKFISNAKSQ-GA-TILTGGV-RPAH------L----EKGFFIEPTIITD--IT---TSMEIWREEVFGPVLCVKEF--S------T--E--DEA-IELA-ND--TQYG-LAGAVISG--DRERCQRLS--EEI--D--AGCIWVN--CSQ-P------------------CFCQAPWGG-NKRSGFG--R-E--LG-EGGIDNYLSVKQVTE-YI-S---D---EPW--G--W---YQSPSK-*

C;cover size:500; local alignment length=500 (original info = 3ED6A	502	609.14	2.3e-74	19)
>P1;3ED6A
structureN:3ED6A: 1: : 502: : : :6.0: 
-----------YFQSNAM---ELL------K--H-----LSQRQYIDGEWVESAN---KNTRDIINPY-N-Q-EVIF-TVS---------EGTKEDAERAILAARRAF-----ESG---E--WSQET-AETRGKKVRAIADKIK--EH-REALARLETLDTGKTLEES-Y-A-----DMDDIHNVFMYFAGLADKDGGEMI------DS---------P--------IPDTESKIVKEPV-GVVTQITPWNYPLLQAS--WKIAPALATGCSLVMKPSEITPLTTIRVFEL----MEE-VGFPKGTINLILGA--G----S--EVGDVMSGHKEVDLVSFTGGIETGKHIMKNA-A------N------N------V------T------NIALELGGKNPNIIFDD---A--D-----FELA--VDQALNGGYFHAGQVCSAGSR-ILVQN-S---------IK-DKFEQALIDRVKK-IKLGN-GF-D-ADTEMGPVISTEHRNKIESYMDVAKAE-GA-TIAVGGK-RPDRDD----L----KDGLFFEPTVITN--CD---TSMRIVQEEVFGPVVTVEGF--E------T--E--QEA-IQLA-ND--SIYG-LAGAVFSK--DIGKAQRVA--NKL--K--LGTVWIN--DFH-P------------------YFAQAPWGG-YKQSGIG--R-E--LG-KEGLEEYLVSKHILT-NT-N---P---Q-L--V--N---WFSK---*

C;cover size:487; local alignment length=487 (original info = 5U0LA	488	607.20	2.2e-74	20)
>P1;5U0LA
structureN:5U0LA: 3: : 486: : : :6.0: 
----------------------------------------TGNVYIDGLWLP--GH--GAPFESVQPV-T-G-ETVW-DGN---------AASLEDVDAAVREARKAF-----L-----A--WRRKS-LAERQAVIEAFGELLE--AN-KEELAHQIGLETGKPLWES-R-T-----EVAAMMGKIPISVKAYNERTGHTE------SD------------------VAGGHAVLRHRPH-GVVAVFGPYNFPGHLPN--GHIVPALLAGNTVVFKPSELTPGVAELTVRLW----EK-AGLPDGVINLVQG---G----S--DTGKCLARHSLIDGLFFTGSSTVGHLLHEQF-G------G------QP-----E------K------ILALEMGGNNPLIVQNV---S--D-----LDGA--VHHALQSAFLSAGQRCTCARR-LLVPK-G---------KKGDEFLARLVEVAAR-ITVAEFDA-D-PQPFMGSVISAEAANQLLKAQAAMLEK-GA-TSLLEMK-QL--------K----PDTGLLSPGIVDA-------TGIELEDQEFFGPLLTVYRY--K------G--F--DEA-LELA-NN--TRYG-LSAGILSD--DRKLYNRLV--EEV--R--AGIVNWN--RPL-T--------G---------ASSAAPFGG-VGASGNH--R-P--SA-YYAAD-YCAWPMASL-EA-G---KS--E-L--PDSL---APGL---*

C;cover size:483; local alignment length=483 (original info = 4H73A	482	604.34	3.9e-74	21)
>P1;4H73A
structureN:4H73A: 2: : 482: : : :6.0: 
------------------------------------------ANYINGEFKEPST---GAFQVKTSPV-D-G-SKIA-EVP---------RSGREDAREAIDSAFEAL-----K-----A--WANIP-AIRRAEYLYKMLEVFR--QM-KEDFMKILTVEGGGTYRKV-W-G-----EVVFTERLIQNAAELARHYQGRVL------QS---------D--------SESTISVVFKRSK-GVVGVITPWNYPLSISM--KKIAHTLAVGNTVVYKPASDTPVTGWLIAQM----VAK-AGLPKGVFNLVIGP--G----P--VVGEEIVTHKRVAHVTFTGESSTGREIAAKA-A------G------T------L------K------TVTLELGGSDPLIILDD---V--D-----VDYA--ARLAVFASLFHQGQICTSAKR-IIVHK-A---------VA-DKFIERYVHYVKM-LRIDD-PRKD-EKVDLGPLINERQVALMKEFVDDAVSR-GG-RLLIGGR----------------SWGNFFEPAIFVD--VD---RNFRIMREEVFGPVRPIVVV--E------N--D--DQA-VEVA-ND--TDYG-LSGAVLTN--NVNRAFRIA--EAV--E--SGMFHIN--DVT-F--------L---------EESHVPFGG-IKASGVG--R-E--GG-EWSFHETTYDRWVTV-TL-R---T---R-R--F--PIPSAL-----*

C;cover size:493; local alignment length=493 (original info = 5IUVA	495	603.59	9e-74	22)
>P1;5IUVA
structureN:5IUVA: 5: : 495: : : :6.0: 
--------ADWEQRAQ-------N------L--K-----IEGRAFIQGEYTAAAS---GETFDCISPV-D-G-RLLA-KVA---------SCDAADAQRAVESARSAF-----DSG---A--WSRLA-PAKRKATMIRFAGLLE--QN-AEELALLETLDMGKPISDS-L-GV----DIPGGARALSWSGEAIDKLYDEVA------AT------------------PHDQLGLVTREPV-GVVAAIVPWNFPLMMAC--WKLGPALSTGNSVVLKPSEKSPLTAIRIAQL----AIE-AGIPAGVLNVLPGY--G----H--TVGKALALHMDVDTVVFTGSTKIAKQLMIYA-GE-----S------N------M------K------RVWLEAGGKSPNIVFAD---AP-D-----LQAA--ADSAASAIAFNQGEVCTAGSR-LLVER-S---------IK-DRFLPMVIEALGT-WKPGN-PL-D-PATNVGALVDTQQMNTVLSYIAAGHTD-GA-RLVAGGK-QILQ------E----TGGTYVEPTIFDG--VN---NAMRIAQEEIFGPVLSVLTF--D------T--A--EEA-IQIA-ND--TPYG-LAAAVWTA--NLSKAHLTA--RAL--R--AGSVWVN--QYD-G------------------GDMTAPFGG-FKQSGNG--R-D--KS-LHAFDKYTELKSTWI-KL----------------------------*

C;cover size:491; local alignment length=491 (original info = 4A0MA	494	605.60	4.7e-74	23)
>P1;4A0MA
structureN:4A0MA: 1: : 493: : : :6.0: 
-----------------------F------P--I-----PARQLFIDGEWREPIK---KNRIPVINPS-T-E-EIIG-DIP---------AATAEDVEVAVVAARRAF-----R-----RNNWSATS-GAHRATYLRAIAAKIT--EK-KDHFVKLETIDSGKPFDEA-V-L-----DIDDVASCFEYFAGQAEALDGKQK------AP---------VTLP-----MERFKSHVLRQPL-GVVGLISPWNYPLLMAT--WKIAPALAAGCTAVLKPSELASVTCLEFGEV----CNE-VGLPPGVLNILTGL--G----P--DAGAPLVSHPDVDKIAFTGSSATGSKVMASA-A------Q------L------V------K------PVTLELGGKSPIVVFED---V--D-----IDKV--VEWTIFGCFWTNGQICSATSR-LLVHE-S---------IA-AEFVDKLVKWTKN-IKISD-PF-E-EGCRLGPVISKGQYDKIMKFISTAKSE-GA-TILYGGS-RPEH------L----KKGYYIEPTIVTD--IS---TSMQIWKEEVFGPVLCVKTF--S------S--E--DEA-IALA-ND--TEYG-LAAAVFSN--DLERCERIT--KAL--E--VGAVWVN--CSQ-P------------------CFVQAPWGG-IKRSGFG--R-E--LG-EWGIQNYLNIKQVTQ-DI-S---D-----E--P--W---GWYK---*

C;cover size:484; local alignment length=484 (original info = 1T90A	484	604.49	4e-74	24)
>P1;1T90A
structureX:1T90A: 1: : 484: : : :2.50: 
------------------------------E--I-----RKLKNYINGEWVE--SKT-DQYEDVVNPA-T-K-EVLC-QVP---------ISTKEDIDYAAQTAAEAF-----K-----T--WSKVA-VPRRARILFNFQQLLS--QH-KEELAHLITIENGKNTKEA-L-G-----EVGRGIENVEFAAGAPSLMMGDSL------AS---------I--------ATDVEAANYRYPI-GVVGGIAPFNFPMMVPC--WMFPMAIALGNTFILKPSERTPLLTEKLVE----LFEK-AGLPKGVFNVVYG---A----H--DVVNGILEHPEIKAISFVGSKPVGEYVYKKG-S------E------N------L------K------RVQSLTGAKNHTIVLND---A--N-----LEDT--VTNIVGAAFGSAGERCMACAV-VTVEE-G---------IA-DEFMAKLQEKVAD-IKIGN-GL-D-DGVFLGPVIREDNKKRTLSYIEKGLEE-GA-RLVCDGR-ENV-------S----DDGYFVGPTIFDN--VT---TEMTIWKDEIFAPVLSVIRV--K------N--L--KEA-IEIA-NK--SEFA-NGACLFTS--NSNAIRYFR--ENI--D--AGMLGIN--LGV-P--------A---------PMAFFPFSG-WKSSFFG--T-LHANG-KDSVDFYTRKKVVTA-RY-PA--P---D-F----------------*

C;cover size:491; local alignment length=491 (original info = 3EK1A	485	603.35	6e-74	25)
>P1;3EK1A
structureN:3EK1A: 2: : 485: : : :6.0: 
------------SMLALK---DPS---------L-----LKSQCLVNGRWID--AAD-GTTIKVTNPA-D-G-SVIG-TVP---------SLSVATIKEAIDASAKAL-----S-----G--WAAKT-AKERAGILRKWFDLII--AN-ADDIALIMTSEQGKPLAEA-R-G-----EVLYAASFIEWFAEEAKRVYGDTI------PA---------P--------QNGQRLTVIRQPV-GVTAAITPWNFPAAMIT--RKAAPALAAGCTMIVRPADLTPLTALALGV----LAEK-AGIPAGVLQIVTGK--A----R--EIGAELTSNDTVRKLSFTGSTEVGRLLMAQC-A------P------T------I------K------RISLELGGNAPFIVFDD---A--D-----LDAA--VDGAMVSKYRNAGQTCVCANR-IYVQR-G---------VY-DKFAEKLAAKVKE-LKVGN-GT-E-PGVVIGPMIEEKAITKVKAHIEDAVSK-GA-KLITGGK-E--------------LGGLFFEPGILTG--VT---SDMLVAKEETFGPLAPLFAF--D------T--E--EEV-IAQA-ND--TIFG-LAAYFYTE--NFSRAIRVS--EAL--E--YGMVGHN--TGL-I------------------SNEVAPFGG-VKQSGLG--R-E--GS-KYGIEEYLETKYICS-AY-K---R----------------------*

C;cover size:489; local alignment length=489 (original info = 5FHZA	489	604.55	5.1e-74	26)
>P1;5FHZA
structureN:5FHZA: 2: : 489: : : :6.0: 
------------LPRPIR---NLE---------V-----KFTKIFINNEWHE--SKS-GKKFATCNPS-T-R-EQIC-EVE---------EGDKPDVDKAVEAAQVAF-----QRGS--P--WRRLD-ALSRGRLLHQLADLVE--RD-RATLAALETMDTGKPFLHA-FFI-----DLEGCIRTLRYFAGWADKIQGKTI------PT------------------DDNVVCFTRHEPI-GVCGAITPWNFPLLMLV--WKLAPALCCGNTMVLKPAEQTPLTALYLGSL----IKE-AGFPPGVVNIVPGF--G----P--TVGAAISSHPQINKIAFTGSTEVGKLVKEAA-S------RS-----N------L------K------RVTLELGGKNPCIVCAD---A--D-----LDLA--VECAHQGVFFNQGQCCTAASR-VFVEE-Q---------VY-SEFVRRSVEYAKK-RPVGD-PF-D-VKTEQGPQIDQKQFDKILELIESGKKE-GA-KLECGGS-AM--------E----DKGLFIKPTVFSE--VT---DNMRIAKEEIFGPVQPILKF--K------S--I--EEV-IKRA-NS--TDYG-LTAAVFTK--NLDKALKLA--SAL--E--SGTVWIN--CYN-A------------------LYAQAPFGG-FKMSGNG--R-E--LG-EYALAEYTEVKTVTI-KL----------------------------*

C;cover size:483; local alignment length=483 (original info = 4JZ6A	484	596.32	4.7e-73	27)
>P1;4JZ6A
structureN:4JZ6A: 3: : 484: : : :6.0: 
----------------------------------------KTKLFINNAWIDSSD---QQTFERKHPV-S-S-EVMT-ESA---------NATVTDAIKAAQAAEEAF-----K-----T--WKDVG-PSERRRLLLKVADVME--SK-TPKFIEVMAMEVGASALWA-G-F-----NVHASANVFREAASLATQIQGETI------PT---------D--------KAETLSMTLRQPV-GPILSIVPWNGTAVLAA--RAIAYPLVCGNTVVFKGSEFSPATHALITQC----VQE-AGLPAGVLNYLNS---SPDRSP--EIADALISAKEIRRINFTGSTRVGSIIAQKA-A------Q------H------L------K------RCLLELGGKSPLIVLDD---A--D-----INAA--VKAAVFGSFLFQGQICMSTER-LVVDE-K---------IA-DEFVARFVEKTER-LSVGD-PC-LTGDCIIGPMVSPNSGERINGLFKDAIDK-GA-KVVCGGM----------------AQGAVMPATILDH--VK---SDMRIYDEETFGPITVVIRC--K------G--E--AEA-IRIA-ND--SVYG-LSSGVFGR--DINRALRVG--MSI--E--YGCVHIN--GST-V--------Q---------NEAQAPYGG-TKNTGYG--R-F--DG-RAVIDEFTELKWLTI-EPFE---Q---Q-Y--P--F----------*

C;cover size:492; local alignment length=492 (original info = 3IWJA	500	598.04	5.9e-73	28)
>P1;3IWJA
structureN:3IWJA: 1: : 499: : : :6.0: 
------------------------------P--I-----PTRQLFINGDWKA--PVL-NKRIPVINPA-T-Q-NIIG-DIP---------AATKEDVDVAVAAAKTALTRNKGA-----D--WATAS-GAVRARYLRAIAAKVT--EK-KPELAKLESIDCGKPLDEA-A-W-----DIDDVAGCFEYYADLAEKLDARQK------AP---------VSLP-----MDTFKSHVLREPI-GVVGLITPWNYPMLMAT--WKVAPALAAGCAAILKPSELASLTCLELGEI----CKE-VGLPPGVLNILTGL--G----P--EAGAPLATHPDVDKVAFTGSSATGSKIMTAA-A------Q------L------V------K------PVSLELGGKSPLVVFED---V--D-----LDKA--AEWAIFGCFWTNGQICSATSR-LILHE-S---------IA-TEFLNRIVKWIKN-IKISD-PL-E-EGCRLGPVVSEGQYEKILKFVSNAKSE-GA-TILTGGS-RPEH------L----KKGFFIEPTIITD--VT---TNMQIWREEVFGPVLCVKTF--S------T--E--EEA-IDLA-ND--TVYG-LGAAVISN--DLERCERVT--KAF--K--AGIVWVN--CSQ-P------------------CFTQAPWGG-VKRSGFG--R-E--LG-EWGLDNYLSVKQVTQ-YI-S---EE--P-W--G--W---YQPPAK-*

C;cover size:486; local alignment length=486 (original info = 3IFHQ	482	600.98	1e-73	29)
>P1;3IFHQ
structureN:3IFHQ: 2: : 482: : : :6.0: 
---------------SMK---DP-------S--L-----LRHQAYIGGEWQAADS---DATFEVFDPA-T-G-ESLG-TVP---------KMGAAETARAIEAAQAAW-----A-----G--WRMKT-AKERAAILRRWFDLVI--AN-SDDLALILTTEQGKPLAEA-K-G-----EIAYAASFIEWFAEEGKRVAGDTL------PT---------P--------DANKRIVVVKEPI-GVCAAITPWNFPAAMIA--RKVGPALAAGCPIVVKPAESTPFSALAMAFL----AER-AGVPKGVLSVVIG---DP---K--AIGTEITSNPIVRKLSFTGSTAVGRLLMAQS-A------P------T------V------K------KLTLELGGNAPFIVFDD---A--D-----LDAA--VEGAIASKYRNNGQTCVCTNR-FFVHE-R---------VY-DAFADKLAAAVSK-LKVGR-GT-E-SGATLGPLINEAAVKKVESHIADALAK-GA-SLMTGGK-RH--------A----LGHGFFEPTVLTG--VK---PDMDVAKEETFGPLAPLFRF--A------S--E--EEL-VRLA-ND--TEFG-LAAYLYSR--DIGRVWRVA--EAL--E--YGMVGIN--TGL-I------------------SNEVAPFGG-VKQSGLG--R-E--GS-HYGIDDYVVIKYLCV-AV----------------------------*

C;cover size:501; local alignment length=501 (original info = 1KY8A	499	602.71	1.4e-73	30)
>P1;1KY8A
structureX:1KY8A: 1: : 499: : : :2.40: 
---------AGLLEGVIK---EKG------G--V-----PVYPSYLAGEWGG--S---GQEIEVKSPI-D-L-ATIA-KVI---------SPSREEVERTLDVLFKRG-----RW----S--ARDMP-GTERLAVLRKAADIIE--RN-LDVFAEVLVMNAGKPKSAA-V-G-----EVKAAVDRLRLAELDLKKIGGDYI------PG---------DWTYD----TLETEGLVRREPL-GVVAAITPFNYPLFDAV--NKITYSFIYGNAVVVKPSISDPLPAAMAVKA----LLD-AGFPPDAIALLNL---P----G--KEAEKIVADDRVAAVSFTGSTEVGERVVKVG---------------G------V------K------QYVMELGGGDPAIVLED---A--D-----LDLA--ADKIARGIYSYAGQRCDAIKL-VLAER-P---------VY-GKLVEEVAKRLSS-LRVGD-PR-D-PTVDVGPLISPSAVDEMMAAIEDAVEK-GG-RVLAGGR-R--------------LGPTYVQPTLVEA--PADRVKDMVLYKREVFAPVASAVEV--K------D--L--DQA-IELA-NG--RPYG-LDAAVFGR--DVVKIRRAV--RLL--E--VGAIYIN--DMP-R--------H---------GIGYYPFGG-RKKSGVF--R-E--GI-GYAVEAVTAYKTIVF-NY-K---G---K-G--V--W---KYE----*

C;cover size:476; local alignment length=476 (original info = 4I25A	483	593.73	9.9e-73	31)
>P1;4I25A
structureN:4I25A: 3: : 483: : : :6.0: 
-----------------------------------------LLNYIDGNFVT--S---ASSFANINPV-N-G-KLIS-DVF---------EADAKQVNEAVVAAQNAL-----KG----P--WGKLS-VQDRAALIHKIADGIQ--AR-FEEFVAAEVADTGRPVHQA-R-TL----DIPRAIANFRTFADLAKTSHTDLF------EM---------STSD-----GSGALNYTVRKPL-GVIGVISPWNLPLLLFT--WKVAPALACGNTVVAKPSEESPSSATLLAEVM----HD-AGVPPGVFNLIHG---FGK--D--SAGEFLTQHPGISALTFTGESKTGSTIMKAV-A------D------G------V------K------EVSFELGGKNAAVVFAD---A--D-----LDAA--IEGVLRSSFTNSGQVCLCSER-VYVHR-S---------IF-DEFVSGLKVEAER-LVVGY-PD-Q-DGVNMGPLISHGHRDKVLSYYRLAVDE-GA-TVVTGGG-VPKFNDE---R----DQGAYVQPTIWTG--LS---DKARCVTEEIFGPVCHISPF--D------D--E--DEV-INRV-ND--SNYG-LACAIWTT--NLSRAHRVS--RQI--H--VGLVWVN--TWY-L------------------RDLRTPFGG-VKLSGLG--R-E--GG-RFSMDFYSDIANICI-KI----------------------------*

C;cover size:486; local alignment length=486 (original info = 3JU8A	480	592.17	1.3e-72	32)
>P1;3JU8A
structureN:3JU8A: 1: : 480: : : :6.0: 
-----------------------------------------STHYIAGQWLAG-Q---GETLESLDPV-G-Q-GVVW-SGR---------GADATQVDAAVCAAREAF-----P-----A--WARRP-LEQRIELLERFAATLK--SR-ADELARVIGEETGKPLWES-A-T-----EVTSVNKVAISVQA-FRERTGEKS------GP------------------LADATAVLRHKPH-GVVAVFGPYNFPGHLPN--GHIVPALLAGNCVVFKPSELTPKVAELTLKA----WIQ-AGLPAGVLNLVQG---G----R--ETGVALAAHRGLDGLFFTGSSRTGNLLHSQF-G------G------Q------P------Q------KILALEGGNNPLVVEEV---A--D-----LDAA--VYTIIQSAFISAGQRCTCARR-LLVPQ-G---------AWGDALLARLVAVSAT-LRVGR-FD-E-QPAPFGAVISLSAAEHLLKAQEHLIGK-GA-QPLLATQ-PI-------------DGAALLTPGIL-D--VS---AVAERPDEEFFGPLLQVIRY--S------D--F--AAA-IREA-NA--TQYG-LAAGLLSD--SRERFEQFL--VES--R--AGIVNWN--KQL-T--------G---------AASSAPFGG-IGASGNH--R-P--SA-YYAADYCAYPVASLE-SP-S---V---S-L--PATL---TPGI---*

C;cover size:497; local alignment length=497 (original info = 3HAZA	983	649.17	3.5e-74	33)
>P1;3HAZA
structureN:3HAZA: 483: : 983: : : :6.0: 
--------IVRPQAAAHP---RIP------L--PCDLFAPERRNSRGVEFGA--RTALDQLLTDVKAE-T-G-D-LK-PIA---------DATPDQAHAAVAAARAGF-----A-----G--WSRTP-AGIRAAALEQAAHLLE--SR-SAHFIALLQREGGKTLDDA-L-S-----ELREAADFCRYYAAQGRKLFGSET------AMP--------G--------PTGESNALTMRGR-GVFVAISPWNFPLAIFL--GQVTAALMAGNSVVAKPAEQTPRIAREAVAL----LHE-AGIPKSALYLVTG---D----G--RIGAALTAHPDIAGVVFTGSTEVARSINRAL-A------A------KDGP---I------V------PLIAETGGINAMIADAT---A--L-----PEQV--ADDVVTSAFRSAGQRCSALRL-LFVQE-D---------VA-DRMIEMVAGAARE-LKIGD-PS-D-VATHVGPVIDVEAKQRLDAHIARMKTE--A-RLHFAGP-A--------------PEGCFVAPHIFEL--T-----EAGQLTEEVFGPILHVVRY--RPE----N--L--ERV-LRAI-ER--TGYG-LTLGVHSR--IDDSIEAII--DRV--Q--VGNIYVN--RNM-I--------GA--------VVGVQPFGG-NGLSGTG--P-KA-GG-PHYLARFATEQTVTI-NT-A---A---A-G----------------*

C;cover size:477; local alignment length=477 (original info = 4YWEA	476	591.38	1.3e-72	34)
>P1;4YWEA
structureN:4YWEA: 1: : 476: : : :6.0: 
-----------------------------------------AKHFIAGEWTL--PAQ-LETIPVVDPS-D-G-QPFA-TIA---------RGTAPDIERAVAAARDAF-----AG----P--WGAAS-AAERGRVLMRLSARVT--DS-IEELAAIEARDTGKPLKQA-R-A-----DAAALARYFEFYAGAADKLHGETL------PY------------------QAGYTVLTVREPH-GVTGHIVPWNYPMQIFG--RSVGAALAAGNACVVKPAEDACLSVLRVAEL----AAE-AGLPAGALNIVTGY--G----H--EAGAALARHPGIDHISFTGSPATGKLVTQMA-A------E------N------H------V------PVTLELGGKSPQIVFAD---A--D-----LDAA--LPVLVSAIVQNGGQTCSAGSR-VLIER-A---------VY-EPLVERLATAFNG-LRVGP-S--R-ADLDCGPLINAKQQQRVWDFLSDAQHD-GI-PMAAHGQ-VVADA-----P----ESGFYQAPALLRD--VP---PSHRLAQEEVFGPVLAAMRF--V------D--E--DEA-VALA-NG--TPYG-LVAGIWTR--DGARQMRLA--RRL--R--AGQVFIN--NYG-A--------G---------GGVELPFGG-VGHSGHG--R-E--KG-FEALYGFTALKTIAI-RH-G--------------------------*

C;cover size:494; local alignment length=494 (original info = 4LIHA	494	590.86	3.8e-72	35)
>P1;4LIHA
structureN:4LIHA: 1: : 494: : : :6.0: 
--------KLTLADWQHK---AAS------L--E-----IEGRAFIDGASRDAHG---GRTFDCVSPI-D-G-RVLA-KVA---------DCGEADVNAAVAAARRAF-----D-----AGVWAGLN-PRARKAVLLRWAALMR--EH-LDELSLLETLDAGKPIGDT-TTV-----DVPGAAYCVEWFAEAIDKVGGEVA------PA------------------DHHLVGLVTREPV-GVVAAVVPWNFPILMAA--WKFGPALAAGNSVVLKPSEKSPLTAIRVAQLA----FE-AGIPAGVFNVVPG---A----G--EPGKLLALHRDVDCIAFTGSTAVGKLIMQYA-A------QS-----N------L------K------RAWLELGGKSPNIVLPD---CP-D-----LDRA--AQTAAGAIFYNMGEMCTAGSR-LLVHR-D---------IK-DAFIEKLVAAARA-YVPGN-PL-D-PSVSMGAIVDGIQLERVLGYIEAGRGE-G--RLVTGGA-RVNA------E----TGGFYVEPTVFE---VK---PDAKIAREEIFGPVLSVIVF--D------D--V--DEA-VRIA-ND--TEYG-LAAAVWTS--NLTTAHDVS--RRL--R--AGTVWVN--CYD-E--------G---------GDMNFPFGG-YKQSGNG--R-D--KS-LHALEKYTELKSTLI-RL-R--------------------------*

C;cover size:487; local alignment length=487 (original info = 4PXLA	485	586.52	9.6e-72	36)
>P1;4PXLA
structureN:4PXLA: 1: : 485: : : :6.0: 
-----------------------V------E--V-----RFTKLFIDGKFVDAVS---GKTFETRDPR-T-G-EVIA-SIA---------EGDKADVDLAVKAAREAF-----D-----NGPWPRMT-GYERGRILHRFADLID--EH-VEELAALDTVDAGKLFAVG-K-AR----DIPGAAHLLRYYAGAADKVHGATL------KM------------------AQRMHGYTLKEPV-GVVGHIVPWNYPTTMFF--FKVGPALAAGCAVVVKPAEQTPLSALFYAHL----ARE-AGVPAGVLNVVPGF--G----P--TAGAAVAAHMDVDKVSFTGSTEVGRLVMRAA-A------ES-----N------L------K------PVSLELGGKSPVIVFDD---A--D-----LDMA--VNLVNFATYTNKGEIV-AGTR-IYVQE-G---------IY-DEFVKKAAELASK-SVVGD-PF-N-PSVSQGPQVDKDQYEKVLRYIDIGKRE-GA-TLVTGGK-PC--------G----DKGYYIEPTIFTD--VK---DDMTIAQDEIFGPVMALMKF--K------T--V--EEV-IQKA-NN--TRYG-LAAGIVTK--NIDVANTVS--RSI--R--AGAIWIN--CYF-A------------------FDPDAPFGG-YKMSGFG--K-D--MG-MDALDKYLQTKTVVT-PL-Y---N---T-P--W--L----------*

C;cover size:485; local alignment length=485 (original info = 3JZ4A	481	588.19	4.5e-72	37)
>P1;3JZ4A
structureN:3JZ4A: 2: : 481: : : :6.0: 
----------------LN---DS-------N--L-----FRQQALINGEWLD--ANN-GEAIDVTNPA-N-G-DKLG-SVP---------KMGADETRAAIDAANRAL-----P-----A--WRALT-AKERATILRNWFNLMM--EH-QDDLARLMTLEQGKPLAEA-K-G-----EISYAASFIEWFAEEGKRIYGDTI------PG---------H--------QADKRLIVIKQPI-GVTAAITPWNFPAAMIT--RKAGPALAAGCTMVLKPASQTPFSALALAEL----AIR-AGVPAGVFNVVTGS--A----G--AVGNELTSNPLVRKLSFTGSTEIGRQLMEQC-A------K------D------I------K------KVSLELGGNAPFIVFDD---A--D-----LDKA--VEGALASKFRNAGQTCVCANR-LYVQD-G---------VY-DRFAEKLQQAMSK-LHIGD-GL-D-NGVTIGPLIDEKAVAKVEEHIADALEK-GA-RVVCGGK-AH--------E----RGGNFFQPTILVD--VP---ANAKVSKEETFGPLAPLFRF--K------D--E--ADV-IAQA-ND--TEFG-LAAYFYAR--DLSRVFRVG--EAL--E--YGIVGIN--TGI-I------------------SNEVAPFGG-IKASGLG--R-E--GS-KYGIEDYLEIKYMCI-GL----------------------------*

C;cover size:488; local alignment length=488 (original info = 3IWKA	496	591.09	3.9e-72	38)
>P1;3IWKA
structureN:3IWKA: 2: : 496: : : :6.0: 
-----------------------------------------RQLFIDGEWRVPIL---NKRIPNINPS-T-E-NIIG-DIP---------AATKEDVDLAVDAAKRAISRKNGR-----D--WSAAS-GSLRARYLRAIAAKIK--EK-KDELGKLESIDCGKPLEEA-L-A-----DLDDVVACFEYYAGLAEELDSKQK------APISL------P--------MDTFKSYILKEPI-GVVALITPWNYPFLMAT--WKIAPALAAGCAAILKPSELASVTCLELGEI----CKE-VGLPRGVLNIVTGL--G----H--EAGASLASHPDVDKISFTGSSATGSKIMTTA-A------Q------L------V------K------PVSLELGGKSPIVVFED---V--D-----LDKV--AEWTVFGCFFTNGQICSATSR-LIVHE-S---------IA-VEFVDKLVKWAEN-IKISD-PL-E-EGCRLGPIVSEAQYKKVLNCISSAKSE-GA-TILTGGR-RP--------EHL--KKGYFVEPTIITD--VT---TSMQIWREEVFGPVLAVKTF--S------T--E--EEA-INLA-ND--THYG-LGSAVMSN--DLERCERLS--KAL--Q--AGIVWIN--CAQ-P------------------SFIQAPWGG-IKRSGFG--R-E--LG-EWGLENYLSVKQVTR-YT-S---DE--P-W--G--W---YQPPSK-*

C;cover size:493; local alignment length=493 (original info = 1O04A	494	591.64	3.1e-72	39)
>P1;1O04A
structureX:1O04A: 2: : 494: : : :1.42: 
------------VPAPNQ---Q-P------E--V-----FCNQIFINNEWHDAVS---RKTFPTVNPS-T-G-EVIC-QVA---------EGDKEDVDKAVKAARAAF-----QLGS--P--WRRMD-ASHRGRLLNRLADLIE--RD-RTYLAALETLDNGKPYVISYL-V-----DLDMVLKCLRYYAGWADKYHGKTI------PI------------------DGDFFSYTRHEPV-GVCGQIIPWNFPLLMQA--WKLGPALATGNVVVMKVAEQTPLTALYVANL----IKE-AGFPPGVVNIVPGF--G----P--TAGAAIASHEDVDKVAFTGSTEIGRVIQVAAGS------S------N------L------K------RVTLELGGKSPNIIMSD---A--D-----MDWA--VEQAHFALFFNQGQCSCAGSR-TFVQE-D---------IY-DEFVERSVARAKS-RVVGN-PF-D-SKTEQGPQVDETQFKKILGYINTGKQE-GA-KLLCGGG-IA--------A----DRGYFIQPTVFGD--VQ---DGMTIAKEEIFGPVMQILKF--K------T--I--EEV-VGRA-NN--STYG-LAAAVFTK--DLDKANYLS--QAL--Q--AGTVWVN--CYD-V------------------FGAQSPFGG-YKMSGSG--R-E--LG-EYGLQAYTEVKTVTV-KV-PQ--K---N-S----------------*

C;cover size:509; local alignment length=509 (original info = 4IHIA	535	596.99	3.5e-72	40)
>P1;4IHIA
structureN:4IHIA: 21: : 535: : : :6.0: 
KSPERTRLRTE-----LA---SLA------DH-P-----IDLPHVIGGRHRM--GD--GERIDVVQPH-RHA-ARLG-TLT---------NATHADAAAAVEAAMSAK-----S-----D--WAALP-FDERAAVFLRAADLLA--GPWREKIAAATMLGQSKSVYQA-EID-----AVCELIDFWRFNVAFARQILEQQP------IS------------------GPGEWNRIDYRPLDGFVYAITPFNFTSIAGN--LPTAPALM-GNTVIWKPSITQTLAAYLTMQL----LEA-AGLPPGVINLVTGD--G----F--AVSDVALADPRLAGIHFTGSTATFGHLWQWV-G------T------N------IGRYHSYP------RLVGETGGKDFVVAHAS---A--R-----PDVL--RTALIRGAFDYQGQKCSAVSR-AFIAH-S---------VW-QRMGDELLAKAAE-LRYGD-IT-D-LSNYGGALIDQRAFVKNVDAIERAKGA-AAVTVAVGGE-YD--------D----SEGYFVRPTVLLS--DD----------PEYFGPLLSVHVY--P------D--ERYEQI-LDVIDTG--SRYA-LTGAVIAD--DRQAVLTAL--DRL--RFAAGNFYVN--DKP-T--------GA--------VVGRQPFGG-ARGSDTN--DKA--GS-PLNLLRWTSARSIKE-TF-V---AAT-D-H--I--Y---PHMAV--*

C;cover size:485; local alignment length=485 (original info = 5MZ8A	481	591.07	2e-72	41)
>P1;5MZ8A
structureN:5MZ8A: 1: : 481: : : :6.0: 
-----------------------V------T--P-----KKYNIFLASKPVD--GD--RKWLDVTNKY-T-N-DVAA-KVP---------QATHKDIDDAIDAAVAAA-----P-----A--MAAMG-AYERKAVLEKVVAELK--NR-FEEIAQTLTMESGKPIKDA-R-G-----EVTRTIDTFQVAAEESVRIYGEHI------PL---------DISAR----NKGLQGIVKKFPI-GPVSMVSPWNFPLNLVA--HKVAPAIAVGCPFVLKPASRTPLSALILGEIL----HKIEELPLGAFSILPV---S----R--EDADMFTVDERFKLLTFTGSGPIGWDMKARA-G--------------------K------K------KVVMELGGNAPCIVDDYV--P--D-----LDYT--IQRLINGGFYQGGQSCIHMQR-LYVHE-R---------LY-DEVKEGFVAAVKK-LKMGN-PF-E-EDTYLGPMISESAAKGIEDWVKEAVAK-GG-KLLTGGN----------------RKGAFIEPTVIED--VP---IEANARKEEIFGPVVLLYKY--S------D--F--KEA-VKEC-NN--THYG-LQSGIFTK--DLNKAFYAF--EHM--E--VGGVILN--DSP-A--------L---------RVDSQPYGG-LKDSGIQ--R-E--GV-KYAMDDMLETKVLVM-RN-V---G---T-L----------------*

C;cover size:486; local alignment length=486 (original info = 5J6BA	481	587.42	5.5e-72	42)
>P1;5J6BA
structureN:5J6BA: 1: : 481: : : :6.0: 
----------------HH---HHM------L--K-----ETYPYYLANEAVY--A---NAELEVTDKY-T-G-KVAT-RVA---------LADASAIDAAIAAAVGAQ-----K-----P--LRALP-AFRRQAILEHCVARFR--ER-FDELAQALCIEAGKPINDS-K-G-----EVTRLIDTFRVAAEESVRIEGGLV------NLEISP-----R--------AQGYSGYYKRVPI-GPCSFISPFNFPLNLAA--HKVAPALAAGCPFVLKPASRTPIGALIIGEV----LAE-TDLPKGAFSILPA---H----R--DGADLFTTDERFKLLSFTGSPTVGWELKKKA-G--------------------K------K------KVVLELGGNAAAIVDAD---Q--REV---LDYV--VERLAFGAYYQSGQSCIGVQR-IIAHA-D---------VY-DALREKLIAKTRS-LKMGD-PK-D-PATFVGPMISESEARRLAGWMEAAVAA-GA-KIVAGGK-V---------------DGAMFEATLLEG--VG---RDQDLYRKEAFGPVALLERF--S------D--F--DDA-LARV-ND--SDFG-LQAGVFTD--SLSHAQRAW--DEL--E--VGGVVIN--DVP-S--------F---------RVDNMPYGG-VKDSGLG--R-E--GI-RYAIEDMTELRLMVV-RR-R--------------------------*

C;cover size:474; local alignment length=474 (original info = 5KF6A	1207	650.40	2.7e-73	43)
>P1;5KF6A
structureN:5KF6A: 563: : 1030: : : :6.0: 
----------------------------------------------------------GETRTVLNPG-D-HRDVVG-SVT---------ETSEEDARRAVRLAADAA-----P-----D--WAAVP-PSERAACLDRAAELMQ--AR-MPTLLGLIIREAGKSALNA-I-A-----EVREAIDFLRYYAEQTRRTLG------------------------------------PGHGPL-GPIVCISPWNFPLAIFT--GQIAAALVAGNPVLAKPAEETPLIAAEGVRI----LRE-AGIPASALQLLPG---D----G--RVGAALVAAAETAGVMFTGSTEVARLIQAQL-A------D------RLSPAGRP------I------PLIAETGGQNAMIVDSS---A--L-----AEQV--VGDVITSAFDSAGQRCSALRV-LCLQE-D---------VA-DRILTMLKGALHE-LHIGR-TD-R-LSVDVGPVITSEAKDNIEKHIERMRGL-GR-KVEQIGL-ASE-------T----GVGTFVPPTIIEL-------EKLSDLQREVFGPVLHVIRYRRD------D--L--DRL-VDDV-NA--TGYG-LTFGLHTR--LDETIAHVT--SRI--K--AGNLYIN--RNI-I--------GA--------VVGVQPFGG-RGLSGTG--P-KA-GG-PLYLGRLVTTAPVPP-QH-SSVHT---D-P--V--L---LDFA---*

C;cover size:485; local alignment length=485 (original info = 4GO4A	487	584.55	1.9e-71	44)
>P1;4GO4A
structureN:4GO4A: 3: : 487: : : :6.0: 
-----------------------------------------NQLYIDGRFVDAVA---GGTIDVVSPH-D-G-SLIT-RIA---------AAEAADVDLAVAAAKRAF-----P-----A--WSALG-AAERGRLLLKLADRIE--EC-SEELAQLESLNTGHPIRDS-R-GL----DVPRTAACFRYFGGMADKIEGSVI------PV------------------DAGFLNYVQRKPI-GVVAQIVPWNFPLMFTS--WKMGPALAAGNTIVIKPSEITPLSTLRIVELM----TE-VGFPKGVVNVVPGY--G----H--TAGQALAEHLDVGKIAFTGSTATGRRIVEAS-K------S------N------L------K------RIQLELGGKGANIVFED---A--N-----IEAA--VNGAAWAIFHNQGQACIAGSR-LILHK-D---------IA-DQFLERFIALAKS-IRLGD-PM-D-PETEMGPLTSALRRDRVLSYIDIAIEQ-GG-KVLAGGK-AP--------DDKALANGFYVEPTVVE---AK---PQDRVCQEEVFGPFVTVVRF--S------S--D--EEA-LAIA-NN--TEYG-LGSGLWTQ--NLARAHKMA--HAI--H--AGMCWIN--CYK-R------------------VSPGSPFGG-VGQSGYG--R-E--MG-FEAIHDYTEARSVWV-NV-D---AK--I-A--P--H---FKR----*

C;cover size:481; local alignment length=481 (original info = 5VBFA	478	584.54	1.2e-71	45)
>P1;5VBFA
structureN:5VBFA: 1: : 478: : : :6.0: 
----------------------RH------D--Y-----APLRLYIDGRFHDADG---RRTQPVVDPG-T-T-RVLG-ELP---------HATAHDIDAAVQAAHRAF-----V-----T--WRHES-PLVRSDLLRRAAALAR--ER-AETIGRHITMDQGKPLREA-I-A-----EVVSAAEQLEWHAEEGRRTYGRVV------PA---------R--------SPDVMQTVLREPI-GVCAAFSPWNFPFSQAM--HKIAAALASGCTLVLKGPEESPSAIVALAQLF----HD-AGLPPGCLNIVWGV--P----G--DVSKQLIEAPQVRKISFTGSVPVGKQLAALA-A------S------L------M------K------RMTMELGGHAPVLVCAD---A--D-----VERA--AAMLAAYKFRNAGQVCVSPTR-FFVQR-A---------AF-DRFVCAYLDAVGT-IRVGY-GL-D-AGVTMGPLAHARRVDEIDAFVADATAK-GA-QIATGGM-RL--------P----GPGHYFAPTVVLG--PT---RDTRLMNDEPFGPIVGIVPF--D------D--L--DDA-LAEA-NR--LPFG-LASYAFTT--SARNAHRIS--RAL--E--AGMVNIN--HFG-M------------------GPAEIPFGG-VKDSGFG--S-E--GG-MEAFDGYLVTKFVTQMN-----------------------------*

C;cover size:494; local alignment length=494 (original info = 1O9JA	494	584.80	2.4e-71	46)
>P1;1O9JA
structureX:1O9JA: 2: : 494: : : :2.4: 
------------LPAPLT---NIK---------I-----QHTKLFINNEWHESVS---GKTFPVFNPA-T-E-EKIC-EVE---------EADKEDVDKAVKAAREAF-----QMGS--P--WRTMD-ASERGQLIYKLADLIE--RD-RLLLATLESINAGKVFASA-YLM-----DLDYCIKALRYCAGWADKIQGRTI------PV------------------DGEFFSYTRHEPI-GVCGLIFPWNAPMILLA--CKIGPALCCGNTVIVKPAEQTPLTALHVASLI----KE-AGFPPGVVNIVPGY--G----P--TAGAAISSHMDVDKVAFTGSTEVGKMIQEAA-A------KS-----N------L------K------RVTLELGAKNPCIVFAD---A--D-----LDSA--VEFAHQGVFTNQGQSCIAASK-LFVEE-A---------IY-DEFVQRSVERAKK-YVFGN-PL-T-PGVNHGPQINKAQHNKIMELIESGKKE-GA-KLECGGG-PW--------G----NKGYFIQPTVFSN--VT---DDMRIAKEEIFGPVQQIMKF--K------S--L--DEV-IKRA-NN--TYYG-LVAGVFTK--DLDKAVTVS--SAL--Q--AGTVWVN--CYL-A------------------ASAQSPAGG-FKMSGHG--R-E--MG-EYGIHEYTEVKTVTM-KI-S---E---K-N--S-------------*

C;cover size:482; local alignment length=482 (original info = 5JRYA	477	585.03	1e-71	47)
>P1;5JRYA
structureN:5JRYA: 1: : 477: : : :6.0: 
-----------------------M------L--K-----ETYPYYLANAAVY--A---NTDLEVTDKY-S-G-KVAT-RVA---------LADAKAIDAAIGAAVDAT-----K-----P--MRELP-AYKRQAVLDHCVARFR--ER-FDELAEALCIEAGKPINDA-K-G-----EVTRLIDTFRVASEEAVRIDGEVL------NL---------EISAR----AQGYTGYTRRVPI-GPCSFISPFNFPLNLAA--HKVAPALAAGCPFVLKPASRTPVGALIIGEV----LAE-TDLPKGAFSVLPA---H----R--DGADLFTTDDRFRLLSFTGSPAVGWALKEKA-G--------------------K------K------KVVLELGGNAAAIVDAD---QLDR-----LDYV--VDRLAFGAFYQSGQSCIGVQR-ILAHA-D---------IY-DALRDKLIAKTRS-LKMGD-PK-D-PSTFVGPMISESESRRLSGWMDAAVAA-GA-KIVAGGK----------------VDGAMFEATLLEN--VG---RDQDLYRKEAFGPIAILEKF--D------R--F--DDA-LARV-ND--SDFG-LQAGVFTD--SLAHTQQAW--DEL--E--VGGVVIN--DVP-S--------F---------RVDNMPYGG-VKDSGLG--R-E--GI-RYAIEDMTEPRLLVV-RR-R--------------------------*

C;cover size:480; local alignment length=480 (original info = 2IMPA	476	582.02	2.3e-71	48)
>P1;2IMPA
structureX:2IMPA: 1: : 476: : : :2.10: 
------------------------------V--P-----VQHPMYIDGQFVT--WRG-DAWIDVVNPA-T-E-AVIS-RIP---------DGQAEDARKAIDAAERAQ-----P-----E--WEALP-AIERASWLRKISAGIR--ER-ASEISALIVEEGGKIQQLA-E-V-----EVAFTADYIDYMAEWARRYEGEII------QS---------D--------RPGENILLFKRAL-GVTTGILPWNFPFFLIA--RKMAPALLTGNTIVIKPSEFTPNNAIAFAKIV----DE-IGLPRGVFNLVLGR--G----E--TVGQELAGNPKVAMVSMTGSVSAGEKIMATA-A------K------N------I------T------KV-LELGGKAPAIVMDD---A--D-----LELA--VKAIVDSRVINSGQVCNCAER-VYVQK-G---------IY-DQFVNRLGEAMQA-VQFGN-PA-ERNDIAMGPLINAAALERVEQKVARAVEE-GA-RVAFGGK-AV--------E----GKGYYYPPTLLLD--VR---QEMSIMHEETFGPVLPVVAF--D------T--L--EDA-ISMA-ND--SDYG-LTSSIYTQ--NLNVAMKAI--KGL--K--FGETYIN--REN-F------------------EAMQGFHAG-WRKSGIG--G-A--DG-KHGLHEYLQTQVVYL-QS----------------------------*

C;cover size:491; local alignment length=491 (original info = 4I8QA	495	581.45	6.7e-71	49)
>P1;4I8QA
structureN:4I8QA: 1: : 494: : : :6.0: 
------------------------------P--I-----PRRQLYIGGEWRE--PVK-KNRIPIINPA-T-E-EIIG-DIP---------AATAEDVDIAVEAARKAI-----ARD---D--WGSTT-GAQRAKYLRAIAAKVL--EK-KSVLATLESLDSGKTLYES-A-A-----DMDDVAGCFEYYAGLAEALDSRRM------TPVNL------N--------SDSYKSYVLREPL-GVVGLITPWNYPLLMAI--WKVAPALAAGCAAILKPSELASITCLELGEIC----RE-IGLPSGALNILTGL--G----P--EAGGPLASHPHVDKISFTGSGPTGSKIMTAA-A------Q------L------V------K------PVSLALGGKSPIVVFDD---ID-N-----LDIA--AEWTLFGIFANTGQVCSATSR-LIVQE-N---------IA-SAFMDRLLKWTKN-IKISD-PL-E-EDCKLGPVVSAGQYEKVLKFISNAKSE-GA-TILCGGE-RPQH------L----KKGYYVQPTIITD--VN---TSMEIWKEEVFGPVLCVKTF--K------T--E--EQA-IELA-ND--TKYG-LGAAVMSK--DVKRCERFT--KAF--Q--TGIIWIN--CSQ-P------------------TFNELPWGG-KKRSGFG--R-D--LG-KWGLENFLNIKQVTE-YT-S-------A-E--P--L---AFYKS--*

C;cover size:487; local alignment length=487 (original info = 2VE5A	489	582.44	3.9e-71	50)
>P1;2VE5A
structureN:2VE5A: 1: : 489: : : :6.0: 
------------------------------A--RF----EEQKLYIGGRYVEASS---GATFETINPA-N-G-EVLA-KVQ---------RASREDVERAVQSAVEGQ-----K-----V--WAAMT-AMQRSRILRRAVDILR--ER-NDELAALETLDTGKPLAET-R-SV----DIVTGADVLEYYAGLVPAIEGEQI------PL------------------RETSFVYTRREPL-GVVAGIGAWNYPVQIAL--WKSAPALAAGNAMIFKPSEVTPLTALKLAEI----YTE-AGVPDGVFNVLTGS--G----R--EVGQWLTEHPLIEKISFTGGTSTGKKVMASA-SS-----S------S------L------K------EVTMELGGKSPLIIFPD---A--D-----LDRA--ADIAVMANFFSSGQVCTNGTR-VFIHR-S---------QQ-ARFEAKVLERVQR-IRLGD-PQ-D-ENTNFGPLVSFPHMESVLGYIESGKAQ-KA-RLLCGGE-RVTDGA----F----GKGAYVAPTVFTD--CR---DDMTIVREEIFGPVMSILVY--D------D--E--DEA-IRRA-ND--TEYG-LAAGVVTQ--DLARAHRAI--HRL--E--AGICWIN--TWG-E------------------SPAEMPVGG-YKQSGVG--R-E--NG-LTTLAHYTRIKSVQV-EL-G---D---Y-A--S--V---F------*

C;cover size:480; local alignment length=480 (original info = 4U3WA	485	580.38	5.7e-71	51)
>P1;4U3WA
structureN:4U3WA: 1: : 485: : : :6.0: 
---------------------------------R-----QLLRHYINGEFVA--S---GTTFPNLSPV-D-G-RKLA-DVC---------EADAALVDSAVQAAHAAQ-----K-----AG-WRDTT-PAQRAAWLHKIADGIE--AR-FDEFVAAEVADTGRPVAQA-R-TL----DIARGIANFRTFADLVRTASGEYF------ET---------HAAD-----GSELINYVTRKPL-GVIGIISPWNLPLLLFT--WKVAPALAMGNCVVAKPSEETPSSATLLAEV----MHD-VGLPPGVFNLIHG---H----GQNAAGEFLTRHPDISAITFTGESRTGSTIMKAV-A------D------G------V------K------EVSFELGGKNAAVVFAD---A--D-----FDAA--VAGVLRSSFTNAGQVCLCSER-VYVER-P---------IF-ERFVAALKEQAQA-LRVGA-PE-D-PATTMGPLISRGHRDKVLSYFRLAVEE-GA-TVVTGGG-APSFGDA---R----DDGAFVMPTIWTG--LP---DSARCVREEIFGPVCHIAPF--D------D--E--AEV-VKRV-ND--SAYG-LAASIWTT--QLARGHRVA--KQI--E--TGIVWVN--AWF-V------------------RDLRTPFGG-TKLSGLG--R-E--GG-RHSLDFYSELTNVCV-RI-A--------------------------*

C;cover size:485; local alignment length=485 (original info = 3B4WA	483	582.81	2.5e-71	52)
>P1;3B4WA
structureN:3B4WA: 1: : 483: : : :6.0: 
-----------------------S------A--T-----EYDKLFIGGKWTK--PST-SDVIEVRCPA-T-G-EYVG-KVP---------MAAAADVDAAVAAARAAF-----D-----NGPWPSTP-PHERAAVIAAAVKMLA--ER-KDLFTKLLAAETGQPPTII-E-TM----HWMGSMGAMNYFAGAADKVTWTET------RT------------------GSYGQSIVSREPV-GVVGAIVAWNVPLFLAV--NKIAPALLAGCTIVLKPAAETPLTANALAE----VFAE-VGLPEGVLSVVPG---G----I--ETGQALTSNPDIDMFTFTGSSAVGREVGRRA-A------E------M------L------K------PCTLELGGKSAAIILED---V--D-----LAAA--IPMMVFSGVMNAGQGCVNQTR-ILAPR-S---------RY-DEIVAAVTNFVTA-LPVGP-PS-D-PAAQIGPLISEKQRTRVEGYIAKGIEE-GA-RLVCGGG-RPEG------L----DNGFFIQPTVFAD--VD---NKMTIAQEEIFGPVLAIIPY--D------T--E--EDA-IAIA-ND--SVYG-LAGSVWTT--DVPKGIKIS--QQI--R--TGTYGIN--WYA--------------------FDPGSPFGG-YKNSGIG--R-E--NG-PEGVEHFTQQKSVLL-PM-G---Y---T-V----------------*

C;cover size:461; local alignment length=461 (original info = 4OGDA	455	580.17	1.5e-71	53)
>P1;4OGDA
structureN:4OGDA: 2: : 455: : : :6.0: 
-------------------------------------------------------------YQTIYPY-T-N-EVLH-TFD---------NMTDQGLADVLERAHLLY-----K-----K--WRKEDHLEERKAQLHQVANILR--RD-RDKYAEIMTKDMGKLFTEA-Q-G-----EVDLCADIADYYADKADEFLMSTP------LE------------------TDSGQAYYLKQST-GVILAVEPWNFPYYQIM--RVFAPNFIVGNPMVLKHASICPRSAQSFEEL----VLE-AGAEAGSITNLFI---S----Y--DQVSQVIADKRVVGVCLTGSERGGASIAEEA-G------K------N------L------K------KTTLELGGDDAFIILDD---A--D-----WDQL--EKVLYFSRLYNAGQVCTSSKR-FIVLD-K---------DY-DRFKELLTKVFKT-AKWGD-PM-D-PETTLAPLSSAQAKADVLDQIKLALDH-GA-ELVYGGE-AI--------D----HPGHFVMPTIIAG--LT---KDNPIYYQEIFGPVGEIYKV--S------S--E--EEA-IEVA-ND--SNYG-LGGTIFSS--NQEHAKAVA--AKI--E--TGMSFIN--SGW-T--------S----------LPELPFGG-IKHSGYG--R-E--LS-ELGFTSFVNEHLIYI-PN----------------------------*

C;cover size:484; local alignment length=484 (original info = 3K2WA	475	579.94	4.2e-71	54)
>P1;3K2WA
structureN:3K2WA: 2: : 475: : : :6.0: 
----------------------LH------F--------KNKVNFIGGQYVP--SNE-SDTIDILSPS-T-G-KVIG-EIP---------AGCKADAENALEVAQAAQ-----K-----A--WAKLT-ARTRQNMLRTFANKIR--EN-KHILAPMLVAEQGKLLSVA-E-M-----EVDVTATFIDYGCDNALTIEGDIL------PS---------D--------NQDEKIYIHKVPR-GVVVGITAWNFPLALAG--RKIGPALITGNTMVLKPTQETPLATTELGRI----AKE-AGLPDGVLNVINGT--G----S--VVGQTLCESPITKMITMTGSTVAGKQIYKTS-A------E------Y------M------T------PVMLELGGKAPMVVMDD---A--D-----LDKA--AEDALWGRFANCGQVCTCVER-LYVHA-S---------VY-DEFMAKFLPLVKG-LKVGD-PM-D-ADSQMGPKCNQREIDNIDHIVHEAIKQ-GA-TVATGG------------------KGCWYEPTVLVD--VK---QDNIVVHEETFGPILPIVKV--S------S--M--EQA-IEFC-ND--SIYG-LSAYVHTQ--SFANINQAI--SDL--E--VGEVYIN--RGM-G------------------EQHQGFHNG-WKQSGFG--G-E--DG-KFGLEQYLEKKTVYI-NE-A---E----------------------*

C;cover size:494; local alignment length=494 (original info = 1BXSA	494	578.76	1.5e-70	55)
>P1;1BXSA
structureX:1BXSA: 2: : 494: : : :2.35: 
------------VPAPLT---NL-------Q--F-----KYTKIFINNEWHSSVS---GKKFPVFNPA-T-E-EKLC-EVE---------EGDKEDVDKAVKAARQAF-----QIGS--P--WRTMD-ASERGRLLNKLADLIE--RD-RLLLATMEAMNGGKLFSNAYL-M-----DLGGCIKTLRYCAGWADKIQGRTI------PM------------------DGNFFTYTRSEPV-GVCGQIIPWNFPLLMFL--WKIGPALSCGNTVVVKPAEQTPLTALHMGSLI----KE-AGFPPGVVNIVPGY--G----P--TAGAAISSHMDVDKVAFTGSTEVGKLIKEAA-G------KS-----N------L------K------RVSLELGGKSPCIVFAD---A--D-----LDNA--VEFAHQGVFYHQGQCCIAASR-LFVEE-S---------IY-DEFVRRSVERAKK-YVLGN-PL-T-PGVSQGPQIDKEQYEKILDLIESGKKE-GA-KLECGGG-PW--------G----NKGYFIQPTVFSD--VT---DDMRIAKEEIFGPVQQIMKF--K------S--L--DDV-IKRA-NN--TFYG-LSAGIFTN--DIDKAITVS--SAL--Q--SGTVWVN--CYS-V------------------VSAQCPFGG-FKMSGNG--R-E--LG-EYGFHEYTEVKTVTI-KI-S---Q---K-N--S-------------*

C;cover size:480; local alignment length=480 (original info = 1EUHA	474	577.16	8.4e-71	56)
>P1;1EUHA
structureX:1EUHA: 1: : 474: : : :1.82: 
---------------------------------T-----KQYKNYVNGEWKL--S---ENEIKIYEPA-S-G-AELG-SVP---------AMSTEEVDYVYASAKKAQ-----P-----A--WRALS-YIERAAYLHKVADILM--RD-KEKIGAILSKEVAKGYKSA-V-S-----EVVRTAEIINYAAEEGLRMEGEVL------EG---------GSFEAA---SKKKIAVVRREPV-GLVLAISPFNYPVNLAG--SKIAPALIAGNVIAFKPPTQGSISGLLLAE----AFAE-AGLPAGVFNTITGR--G----S--EIGDYIVEHQAVNFINFTGSTGIGERIGKMA---------------G------M------R------PIMLELGGKDSAIVLED---A--D-----LELT--AKNIIAGAFGYSGQRCTAVKR-VLVME-S---------VA-DELVEKIREKVLA-LTIGN-PE-D--DADITPLIDTKSADYVEGLINDANDK-GA-TALTEIK----------------REGNLICPILFDK--VT---TDMRLAWEEPFGPVLPIIRV--T------S--V--EEA-IEIS-NK--SEYG-LQASIFTN--DFPRAFGIA--EQL--E--VGTVHIN--NKT-Q--------R---------GTDNFPFLG-AKKSGAG--I-Q--GV-KYSIEAMTTVKSVVF-DI-K--------------------------*

C;cover size:477; local alignment length=477 (original info = 3PRLA	475	574.98	1.8e-70	57)
>P1;3PRLA
structureN:3PRLA: 3: : 475: : : :6.0: 
----------------------------------------NANILRNGEWVE--SRT-GERISISAPA-S-G-VALG-SIP---------ALSQEEVNDAIQGAKDAQ-----K-----I--WKIRP-IHERVDLLYAWADLLE--ER-KEIIGELIMHEVAKPKKSA-I-G-----EVSRTADIIRHTADEALRLNGETL------KG---------DQFKGG---SSKKIALVEREPL-GVVLAISPFNYPVNLAA--AKIAPALVTGNTVVFKPATQGSLSGIKMVEA----LAD-AGAPEGIIQVVTGR--G----S--VIGDHLVEHPGIDMITFTGGTTTGERISEKA---------------K------M------I------PVVLELGGKDPAIVLDD---A--D-----LKLT--ASQIVSGAFSYSGQRCTAIKR-VFVQD-S---------VA-DQLVANIKELVEQ-LTVGS-PE-D--DADITPVIDEKSAAFIQGLIDDALEN-GA-TLLSGNK----------------RQGNLLSPTLLDD--VT---PAMRVAWEEPFGPVLPIIRV--K------D--A--NEA-ISLS-NQ--SDYG-LQASIFTK--DTDRAINIG--KHL--E--VGTVHIN--AKT-E--------R---------GPDHFPFLG-VKKSGLG--V-Q--GI-KPSLLSMTRERVTVL-NL----------------------------*

C;cover size:464; local alignment length=464 (original info = 3PQAA	456	573.17	1.3e-70	58)
>P1;3PQAA
structureN:3PQAA: 3: : 456: : : :6.0: 
----------------------------------------------------------REDMDVINPY-S-L-EVIK-KIP---------ALSREEAKEAIDTAEKYK-----E-----V--MKNLP-ITKRYNILMNIAKQIK--EK-KEELAKILAIDAGKPIKQA-R-V-----EVERSIGTFKLAAFYVKEHRDEVI------PS-------------------DDRLIFTRREPV-GIVGAITPFNFPLNLSA--HKIAPAIATGNVIVHHPSSKAPLVCIELAKIIENALKK-YNVPLGVYNLLTG---AG---E--VVGDEIVVNEKVNMISFTGSSKVGELITKKA---------------G------F------K------KIALELGGVNPNIVLKD---A--D-----LNKA--VNALIKGSFIYAGQVCISVGM-ILVDE-S---------IA-DKFIEMFVNKAKV-LNVGN-PL-D-EKTDVGPLISVEHAEWVEKVVEKAIDE-GG-KLLLGGK-R---------------DKALFYPTILE---VD---RDNILCKTETFAPVIPIIR---T------N--E--EEM-IDIA-NS--TEYG-LHSAIFTN--DINKSLKFA--ENL--E--FGGVVIN--DSS-L--------F---------RQDNMPFGG-VKKSGLG--R-E--GV-KYAMEEMSNIKTIII-SK----------------------------*

C;cover size:487; local alignment length=487 (original info = 4KNAA	487	576.55	1.9e-70	59)
>P1;4KNAA
structureN:4KNAA: 2: : 486: : : :6.0: 
-----------------------------------------TELFIDGAWVDG-A---GPVFASRNPG-T-N-ERVW-EGA---------SASADDVERAVASARRAF-----A-----A--WSALD-LDARCTIVKRFAALLV--ER-KEALATMIGRETGKPLWEA-R-T-----EVASMAAKVDISITAYHERTGEKR------AP------------------MADGVAVLRHRPH-GVVAVFGPYNFPGHLPN--GHIVPALIAGNTVVFKPSELAPGVARATVEIW----RD-AGLPAGVLNLVQG---E----K--DTGVALANHRQIDGLFFTGSSDTGTLLHKQF-G------G------RP-----E------I------VLALEMGGNNPLVVAEV---E--D-----IDAA--VHHAIQSAFLSAGQRCTCARR-ILVPR-G---------AFGDRFVARLADVASK-ITASVFDA-D-PQPFMGAVISARAASRLVAAQARLVGL-GA-SPIIEMK-QR--------D----PALGFVNAAIL-D--VT---NVRELPDEEHFGPLAQIVRY--T------D--L--DDA-IARA-ND--TAFG-LSAGLLAD--DEQAWHTFR--RAI--R--AGIVNWN--RPT-N--------G---------ASSAAPFGG-AGRSGNH--R-P--SA-YYAADYCAYPMASVE-SA-Q---L---Q-MPAS--L---SPGLH--*

C;cover size:476; local alignment length=476 (original info = 4I3WA	473	578.32	6.3e-71	60)
>P1;4I3WA
structureN:4I3WA: 2: : 473: : : :6.0: 
-----------------------------------------EPMRIAGRLVD--T---DDRVEVRYPW-N-D-TVVG-TVP---------AGRAEHAREAFAIAAAY---------------QPKLT-RYERQKILLATAEALA--AR-KEEISDVITLELGISKADS-L-Y-----EVGRAFDVFTLAGQMCIRDDGEIF------SCDLTP-----H--------GKARKIFTMREPL-TAISAITPFNHPLNMVA--HKVAPAIATNNCVVVKPTELTPMTALLLADI----LYE-AGLPPEMLSVVTGW--P----A--DIGMEMITNPHVDLVTFTGSVPVGKLIAANA---------------H------Y------K------RQVLELGGNDPLIILNDLSDD--D-----LARA--ADLAVAGATKNSGQRCTAVKR-ILCQE-S---------VA-DRFVPLVLERAKR-LRFGD-PM-D-RSTDLGTVIHEKAAALFEERVMRAAEE-GA-DILYHPG----------------RSGALLPPIVVDR--VP---HQSDLVLEETFGPIIPIVRV--P------D--D--DDATITLS-NS--TAFG-LSSGVCTN--DYRRMQKYI--AGL--K--VGTVNIW--EVP-G--------Y---------RIEMSPFGG-IKDSGNG--Y-K--EGVIEAMKSFTNVKTFSL-PW----------------------------*

C;cover size:474; local alignment length=474 (original info = 3V9IA	506	582.72	7.4e-71	61)
>P1;3V9IA
structureN:3V9IA: 20: : 504: : : :6.0: 
QG---SPERDALQKA-LK---DLK------GR-M-----EAIPCVVGDEEVW--TS--DVQYQVSPFN-H-G-HKVA-KFC---------YADKSLLNKAIEAALAAR-----K-----E--WDLKP-IADRAQIFLKAADMLSG-PR-RAEILAKTMVGQGKTVIQA-EID-----AAAELIDFFRFNAKYAVELEGP------------------------------STNSTVYRGLE-GFVAAISPFNFTAIGGN--LAGAPAL-MGNVVLWKPSDTAMLASYAVYRI----LRE-AGLPPNIIQFVPAD--G----P--LFGDTVTSSEHLCGINFTGSVPTFKHLWKQV-A------Q------N------L------DRFHTF-PRLAGECGKNFHFVHRS---A--D-----VESV--VSGTLRSAFEYGGQKCSACLR-LYVPH-S---------LW-PQIKGRLLEEHSR-IKVGD-PA-EDFGTFFSAVIDAKSFARIKKWLEHARSS-PSLTILAGGK-CD--------D----SVGYFVEPCIVES--KD---PQEPIMKEEIFGPVLSVYVY--P------DDKY--KET-LQLV-DST-TSYG-LTGAVFSQ--DKDVVQEAT--KVL--RNAAGNFYIN--DKS-T--------ILRWTSPQVIKETHKPLGD-WSYA-----------------------------------------------------------*

C;cover size:484; local alignment length=484 (original info = 3R31A	482	575.64	2.1e-70	62)
>P1;3R31A
structureN:3R31A: 1: : 482: : : :6.0: 
---------------------PLK------A--Q-----PKASHFIDGDYVEDNT---GTPFESIFPA-T-G-EMIA-KLH---------AATPAIVERAIASAKRAQ-----K-----E--WAAMS-PMARGRILKRAADIMR--ER-NDALSTLETLDTGKPIQET-IVA-----DPTSGADAFEFFGGIAPSALNGDY------IP------------------LGGDFAYTKRVPL-GVCVGIGAWNYPQQIAC--WKAAPALVAGNAMVFKPSENTPLGALKIAEIL----IE-AGLPKGLFNVIQG---D----R--DTGPLLVNHPDVAKVSLTGSVPTGRKVAAAA-A------G------H------L------K------HVTMELGGKSPMIVFDD---A--D-----IESA--VGGAMLGNFYSSGQVCSNGTR-VFVQK-K---------AK-ARFLENLKRRTEA-MILGD-PL-D-YATHLGPLVSKAQQEKVLSYIEKGKAE-GA-TLITGGG-IPNNV-----A----GEGAYVQPTVFAD--VT---DDMTIAREEIFGPVMCVLDF--D------D--E--DEV-LARA-NA--TEFG-LAGGVFTA--DLARAHRVV--DGL--E--AGTLWIN--TYN-L------------------CPVEIPFGG-SKQSGFG--R-E--NS-AAALEHYSELKTVYV-ST-G--------------------------*

C;cover size:479; local alignment length=479 (original info = 3I44A	476	571.62	5.3e-70	63)
>P1;3I44A
structureN:3I44A: 2: : 476: : : :6.0: 
------------------------------L--------NKRKFYINGLWDD--PST-PHDLYVIDPS-T-E-EACA-VIS---------LGSTRDADKAINAAKKAF-----Q-----T--WKTTS-PHERLGFVEKILEIYE--KR-SSDMAKTISMEMGAPIDMA-LNA-----QTATGSSHIRNFIKAYKEFSFQEA------LI------------------EGNEQAILHYDAI-GVVGLITPWNWPMNQVT--LKVIPALLAGCTMVLKPSEIAPLSAMLFAEI----LDE-AALPSGVFNLINGD--G----A--NVGSYLSAHPDLEMISFTGSTRAGKDISKNA-S------N------T------L------K------RVCLELGGKGANIIFAD---A--D-----ID-A--LQRGVRHCFYNSGQSCNAPTR-MLVEQ-A---------IY-DKAIKTAKDIAEK-TQVGP-GH-Q-TGNHIGPVVSKEQYDKIQDLIQSGIDE-GA-TLVTGGT-GLPMG-----M----ERGYYVRPTVFAD--VK---PHMRIFREEIFGPVLSLLPF--N------T--E--DEA-VTLA-ND--TEYG-LTNYIQSQ--DRSKCRRIA--AQV--R--SGMVEVN--GHE-L-------------------PGGSYFGG-VKFSGRA--R-E--GG-LWGIKEFLDTKAISY-W-----------------------------*

C;cover size:487; local alignment length=487 (original info = 2VROA	521	584.87	7.1e-71	64)
>P1;2VROA
structureN:2VROA: 1: : 521: : : :6.0: 
-----------------------H------M--T-----ELLKNHVAGQWIA--GT--GAGITLTDPV-T-G-VALV-RVS---------SEG-LDLARAFSFAREDGG----A-----A--LRALT-YAQRAARLADIVKLLQ--AK-RGDYYAIATANSGTTRNDS-A-V-----DIDGGIFTLSYYAKLGASLGEVHA------LRDGSAESLSKD--------RSFSAQHVLSPTR-GVALFINAFNFPSWGLW--EKAAPALLSGVPVIVKPATATAWLTQRM---VADVVDA-GILPPGALSIICG---S----S----AGLLDQIRSFDVVSFTGSADTAATLRAHP-AFV----Q------R------G------A------RLNVEADSLNSAILCAD---A--TPDTPAFDLF--IKEVVREMTVKSGQKCTAIRR-AFVPE-A---------AL-EPVLEALKAKLAK-ITVGN-PR-N-DAVRMGSLVSREQYENVLAGIAALRE--EA-VLAYDSS-AVPLIDAD--A----NIAACVAPHLFVVNDPD---NATLLHDVEVFGPVASVAPY--RVTTDTLP--E--AHA-VALA-RR--GQGS-LVASIYSN--DDAHLGRLA--LELADS--HGRVHAI--SPS-VQHSQTGHGN---------VMPMSLHGG-PGRAGGG--E-E--LG-GLRALAFYHRRSAIQ-AA-SA--A---I-G--T--L----------*

C;cover size:480; local alignment length=480 (original info = 5X5UA	476	569.80	8.8e-70	65)
>P1;5X5UA
structureN:5X5UA: 1: : 476: : : :6.0: 
------------------------------T--Y-----TDTQLLIDGEWVDAAS---GKTIDVVNPA-T-G-KPIG-RVA---------HAGIADLDRALAAAQSGF-----E-----A--WRKVP-AHERAATMRKAAALVR--ER-ADAIAQLMTQEQGKPLTEA-R-V-----EVLSAADIIEWFADEGRRVYGRIV------PP---------R--------NLGAQQTVVKEPV-GPVAAFTPWNFPVNQVV--RKLSAALATGCSFLVKAPEETPASPAALLRA----FVD-AGVPAGVIGLVYG---DP---A--EISSYLIPHPVIRKVTFTGSTPVGKQLASLA-G------L------H------M------K------RATMELGGHAPVIVAED---A--D-----VALA--VKAAGGAKFRNAGQVCISPTR-FLVHN-S---------IR-DEFTRALVKHAEG-LKVGN-GL-E-EGTTLGALANPRRLTAMASVIDNARKV-GA-SIETGGE-RI--------G----SEGNFFAPTVIAN--VP---LDADVFNNEPFGPVAAIRGF--D------K--L--EEA-IAEA-NR--LPFG-LAGYAFTR--SFANVHLLT--QRL--E--VGMLWIN--QPA-T--------P----------WPEMPFGG-VKDSGYG--S-E--GG-PEALEPYLVTKSVTV-MA----------------------------*

C;cover size:476; local alignment length=476 (original info = 6C43A	473	567.12	1.7e-69	66)
>P1;6C43A
structureN:6C43A: 2: : 473: : : :6.0: 
-----------------------------------------YQLLINGVLVD--GE--GERQSVYNPA-T-G-EVIL-EIA---------EASPAQVDAAVQAADNAF-----A-----E--WGQTT-PKARAECLLKLADSIE--QN-ALEFARLESQNCGKPLHCV-IND-----EIPAIVDVFRFFAGAARCLSGLAA------GE---------Y--------LEGHTSMIRRDPI-GVVASIAPWNYPLMMAA--WKLAPALAAGNCVVIKPSEITPLTALKLAVLAK----D--IFPPGVLNVLFGR--G----Q--TVGDVLTGHEKVRMVSLTGSIATGEHILRHT-A------P------A------I------K------RTHMELGGKAPVIVFDD---A--D-----LDAV--AQGVRTFGFYNAGQDCTAACR-IYAQR-G---------IY-DALVEKLGNAVSS-LKMGA-PE-D-ESTELGPLSSLAHLKRVTAAVEEAKALSHI-RVITGGS-QT--------E----GKGYYFAPTLLAD--AK---QEDAIVQREVFGPVVSITVF--D------D--E--DQV-LRWA-ND--SRYG-LASSVWTQ--DVGRAHRLS--ARL--Q--YGCTWIN--THF-M------------------LVSEMPHGG-QKQSGYG--K-D--MS-LYGLEDYTLVRHIMV-KH----------------------------*

C;cover size:499; local alignment length=499 (original info = 1BI9A	478	569.33	1.2e-69	67)
>P1;1BI9A
structureX:1BI9A: 4: : 478: : : :2.7: 
-------LQLLPSPTPNL---E-----------I-----KYTKIFINNEWQN--SES-GRVFPVCNPA-T-G-EQVC-EVQ---------EADKVDIDKAVQAARLAF-----SLGS--V--WRRMD-ASERGRLLDKLADLVE--RD-RATLATMESLNGGKPFLQA-FYI-----DLQGVIKTLRYYAGWADKIHGMTI------PV------------------DGDYFTFTRHEPI-GVCGQIIPWNFPLLMFT--WKIAPALCCGNTVVIKPAEQTPLSALYMGAL----IKE-AGFPPGVVNILPGY--G----P--TAGAAIASHIGIDKIAFTGSTEVGKLIQEAA-G------RS-----N------L------K------RVTLELGGKSPNIIFAD---A--D-----LDYA--VEQAHQGVFFNQGQCCTAGSR-IFVEE-S---------IY-EEFVKRSVERAKR-RIVGS-PF-D-PTTEQGPQIDKKQYNKILELIQSGVAE-GA-KLECGGK-GL--------G----RKGFFIEPTVFSN--VT---DDMRIAKEEIFGPVQEILRF--K------T--M--DEV-IERA-NN--SDFG-LVAAVFTN--DINKALMVS--SAM--Q--AGTVWIN--CY----------------------------------------------G-EFGLREYSEVKTVTV-KI-P---Q---K-N--S-------------*

C;cover size:476; local alignment length=476 (original info = 1WNDA	474	565.39	2.6e-69	69)
>P1;1WNDA
structureX:1WNDA: 3: : 474: : : :2.10: 
-----------------------------------------HKLLINGELVS--GE--GEKQPVYNPA-T-G-DVLL-EIA---------EASAEQVDAAVRAADAAF-----A-----E--WGQTT-PKVRAECLLKLADVIE--EN-GQVFAELESRNCGKPLHSA-F-ND----EIPAIVDVFRFFAGAARCLNGLAA------GE---------Y--------LEGHTSMIRRDPL-GVVASIAPWNYPLMMAA--WKLAPALAAGNCVVLKPSEITPLTALKLAELAKD------IFPAGVVNILFGR--G----K--TVGDPLTGHPKVRMVSLTGSIATGEHIISHT-A------S------S------I------K------RTHMELGGKAPVIVFDD---A--D-----IEAV--VEGVRTFGYYNAGQDCTAACR-IYAQK-G---------IY-DTLVEKLGAAVAT-LKSGA-PD-D-ESTELGPLSSLAHLERVGKAVEEAKAT-GHIKVITGGE-KR--------K----GNGYYYAPTLLAG--AL---QDDAIVQKEVFGPVVSVTPF--D------N--E--EQV-VNWA-ND--SQYG-LASSVWTK--DVGRAHRVS--ARL--Q--YGCTWVN--THF-M------------------LVSEMPHGG-QKLSGYG--K-D--MS-LYGLEDYTVVRHVMV-KH----------------------------*

C;cover size:480; local alignment length=480 (original info = 4E4GA	470	565.65	2.5e-69	70)
>P1;4E4GA
structureN:4E4GA: 2: : 470: : : :6.0: 
----------------------------------------ELGHFIDGKRVAGTS---GRVSNIFNPA-T-G-EVQG-TVA---------LASDADLAAAVESAKAAQ-----P-----K--WAATN-PQRRARV-FKFVQLLN--DN-N-ELAEL-SREHGKTIDDA-K-G-----DIVRGLEVCEFVIGIPHLQKSEFT------EG------------------AGPGIDYSIRQPV-GIGAGITPFNFPGIP-----WFAPAIACGNAFILKPSERDPSVPIRLAELI-----E-AGLPAGILNVVNG---D----K--GAVDAILTHPDIAAVSFVGSTPIARYVYGTA-A------N-------------G------K------RAQCF--GGAKNHIIPD---A--D-----LDQA--ANALIGAGYGSAGERCAISVA-VPVGE-E---------TA-NRLIDKLVP-VES-LRIGP-YT-D-EKA-DGPVVTKEAEQRIRSLIDSGIEQ-GA-KLVVDGR-DFKLQG----Y----ENGHFIGGCLFDD--VT---PD-DIYKTEIFGPVLSVVRA--R------N--Y--EEA-LSLP-KH---EYG-NGVAIYTR--DGDAARDFA--SRI--N--IG-VGVN--VPI-P--------V---------PLAYHSFGG-WKSSSFGDLN-Q--HG-TDSIKFWTRTKTITS-RW-P---SGIKD------------------*

C;cover size:504; local alignment length=504 (original info = 5UJUA	558	601.43	1.9e-72	71)
>P1;5UJUA
structureN:5UJUA: 19: : 558: : : :6.0: 
AI---ESRGYWSPFAEMP---SPK------V--Y-----GESGNADGEAAFKSHL---GKTFELDQPA-S-G-ETVG-AERSPYGVALDIRYPKSTPDALIAAAAAAQ-----R-----T--WREAG-PSAWIGVSLEILARLN--RA-SFEIAYSVMHTTGQAFMMA-F-QAGGPHAQDRALEAVAYAWDQLRRIPADAHWEKPQGKN---------P--------PLAMQKRYTIVPR-GTGLVLGCCTFPTWNGY--PGLFADLATGNTVIVKPHPGAILPLAITVRIARDVLRE-AGFDPNVVTLLATEPND----G--ALVQDLALRPEIKLIDFTGSTQNGTWLERHA---------------H------Q------A------QVYTEKAGVNQIVIDST---D--D-----LKAA--AKNIAFSLALYSGQMCTAPQN-IYVPR-DGIRTADGHASF-DEVAQAIAGAVQK-L-TGD-PA-R-SVELIGAIQN----DGVTARIDAARAV-GR-VLLDSQT-LQHPA-----F----PDARVRTPLVLQL--DV---ADREKFTQEWFGPISFVIAT--D------S--T--AQS-LDLA-GEIAAEHGALTLSVYST--ADDVIDAAH--EAA--V--RGGVALSINLTGGV--------F---------VNQSAAFSD-FHGTGAN--P-A--ANAALADAAFVANRFRVV-QSRV---H---V-A--P--K----------*

C;cover size:486; local alignment length=486 (original info = 2W8OA	480	566.21	3.4e-69	72)
>P1;2W8OA
structureN:2W8OA: 1: : 480: : : :6.0: 
----------------LA---GLSA-----A--L-----LRTDSFVGGRWLP--A---AATFPVQDPA-S-G-AALG-MVA---------DCGVREARAAVRAAYEAF-----C-----R--WREVS-AKERSSLLRKWYNLMI--QN-KDDLARIITAESGKPLKEA-H-G-----EILYSAFFLEWFSEEARRVYGDII------HT---------P--------AKDRRALVLKQPI-GVAAVITPWNFPSAMIT--RKVGAALAAGCTVVVKPAEDTPFSALALAE----LASQ-AGIPSGVYNVIPC---SRKNAK--EVGEAICTDPLVSKISFTGSTTTGKILLHHA-A------N------S------V------K------RVSMELGGLAPFIVFDS---A--N-----VDQA--VAGAMASKFRNTGQTCVCSNQ-FLVQR-G---------IH-DAFVKAFAEAMKKNLRVGN-GF-E-EGTTQGPLINEKAVEKVEKQVNDAVSK-GA-TVVTGGK-RH--------Q----LGKNFFEPTLLCN--VT---QDM-----LTFGPLAPVIKF--D------T--E--EEA-IAIA-NA--ADVG-LAGYFYSQ--DPAQIWRVA--EQL--E--VGMVGVN--EGL-I------------------SSVECPFGG-VKQSGLG--R-E--GS-KYGIDEYLELKYVCY-GG-L--------------------------*

C;cover size:476; local alignment length=476 (original info = 4DALA	464	562.11	5.6e-69	73)
>P1;4DALA
structureN:4DALA: 2: : 464: : : :6.0: 
-----------------------------------------TQLLIGSRFEA--GT--EAEEHILNPR-T-G-AGII-DLA---------EASHAQIDAAVDAAERAF-----V-----G--WSQTT-PAERSNALLKIADAIE--KE-ADEFAALEALNCGKPINAV-KND-----ELPAIIDCWRFFAGAVRNLHAPAA------GE---------Y---------LPGHTSIRRDPI-GIVGSIAPWNYPL---A--WKLAPAIGGGNTVVFKPSEQTPLTALKLARLIAD------ILPEGVVNVITGR--G----E--TVGNALINHPKVG-VSITGDIATGKKVLAAA-A------K------T------V------K------RTHLELGGKAPVIVYGD---A--D-----LEAV--VNGIRTFGYYNAGQDCTAACR-IYAEA-G---------IY-EKLVADLTSAVST-IRYNL-DD-D-TENEIGPLISRRQRDRVASFVERAADQ-KH-IEITTGGRTG--------S----DEGFFFQPTVVAG--AT---QEDEIVRREVFGPVVSVTRF--T------G--K--DDA-VAWA-ND--SDYG-LASSVWTK--DISKA-RAA--SRL--Q--YGCTWIN--THF-L--------------------TNEPHGG-IKQSGYG--K-D---S-VYALEDYTAVRHIIN-HG----------------------------*

C;cover size:475; local alignment length=475 (original info = 4QYJA	481	566.95	2.7e-69	75)
>P1;4QYJA
structureN:4QYJA: 1: : 481: : : :6.0: 
------------------------------------------QMLIGGQWVSAQS---GKTLNVYNPA-T-G-DILT-EVP---------DGDVEDVNAAVESAAATL-----RSD---T--WRRMP-PSARERILLRLADLLE--VH-GDELARLETLNNGKLLIYS-KLM-----EVGASAQWLRYMAGWATKLTGSTL------DL---------SLPLPP---EVRSRASTQRVPV-GVVAAIIPWNFPLLMAV--WKIAPALACGNTVVLKPAEETPLTALRLAEL----AME-AGLPAGALNVVTGR--G----E--TAGDALVRHPKVAKVAFTGSTEVGRIIGSAC-G------R------S------L------K------AVSLELGGKSPVIVLAD---C--D-----PQEA--AEGAAAAIFFNHGQVCTAGSR-LYVHE-S---------IY-EDVIQRLAVIGES-IVVGS-GL-E-QGVHMGPMVSKKHHENVLRHIRNGIED-GA-DLICGGT-EAP-------C----AQGFFVKPTIFAN--REK--KDIRLLSQEVFGPVLVATPF--S------D--I--AEV-VNEA-NR--SVYG-LGASIWTN--DLSAALRIN--DEL--E--AGTVWVN--THN-M------------------VDPNLPFGG-FKDSGVG--R-E--HG-AAAIEHYTTTRSLVI-AY----------------------------*

C;cover size:477; local alignment length=477 (original info = 1EZ0A	504	578.20	2.6e-70	76)
>P1;1EZ0A
structureX:1EZ0A: 2: : 492: : : :2.10: 
----------------------------------------------------------DNVFYATNAF-T-G-EALPLAFP---------VHTEVEVNQAATAAAKVA-----R-----D--FRRLN-NSKRASLLRTIASELE--AR-SDDIIARAHLETALPEVRL-T-G-----EIARTANQLRLFADVVNSGSYHQA------IL---------DTPNPTRAPLPKPDIRRQQIAL-GPVAVFGASNFPLAFSAAGGDTASALAAGCPVIVKGHTAHPGTSQIVAECIEQALKQ-EQLPQAIFTLLQGN--Q----R--ALGQALVSHPEIKAVGFTGSVGGGRALFNLA-H------E------R------PEP----I------PFYGELGAINPTFIFPS---A--M-----RAKADLADQFVASMTMGCGQFCTKPGV-VFALNTP---------ET-QAFIETAQSLIRQ-Q--------S-PSTLLTPGIRDSYQSQV---VSRGSDD-GI-DVTFSQA-----------------ESPCVASALFVT--SSENWRKHPAWEEEIFGPQSLIVVC--E------N--V--ADM-LSLS-EM--LAGS-LTATIHATEEDYPQVSQLI--PRL--EEIAGRLVFN--GWP-T--------GVE-------VGYAMVHGGPYPASTHSAST-S--VG-AEAIHRWLRPVAYQA-LP-E---S---L-L--P--D---SLKAENP*

C;query_length:511 num_of_temps:1 cover_ratio:0.97 cover:498 not_cover:13
>P1;ALDH7A1_A171V
 : : : : : : : : : 
MS---TLLINQPQYAWLK---ELG------L--R-----EENEGVYNGSWGG--R---GEVITTYCPA-N-N-EPIA-RVR---------QASVADYEETVKKAREAW-----K-----I--WADIP-APKRGEIVRQIGDALR--EK-IQVLGSLVSLEMGKILVEG-V-G-----EVQEYVDICDYAVGLSRMIGGPIL------PS---------E--------RSGHALIEQWNPV-GLVGIITAFNFPVVVYG--WNNAIAMICGNVCLWKGAPTTSLISVAVTKIIAKVLED-NKLPGAICSLTCG---G----A--DIGTAMAKDERVNLLSFTGSTQVGKQVGLMV-Q------E------R------F------G------RSLLELGGNNAIIAFED---A--D-----LSLV--VPSALFAAVGTAGQRCTTARR-LFIHE-S---------IH-DEVVNRLKKAYAQ-IRVGN-PW-D-PNVLYGPLHTKQAVSMFLGAVEEAKKE-GG-TVVYGGK-VM--------D----RPGNYVEPTIVTG--LG---HDASIAHTETFAPILYVFKF--K------N--E--EEV-FAWN-NE--VKQG-LSSSIFTK--DLGRIFRWLGPKGS--D--CGIVNVN--IPT-S--------G---------AEIGGAFGG-EKHTGGG--R-E--SG-SDAWKQYMRRSTCTI-NY-S---K---D-L--P--L---AQGIKFQ*
