C; model_eva_score=0.19, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite5.pdb1
structureX:meta_hhsuite5.pdb: 1: : 396: : : : : 
MGSSHHHHHHSSGLVPRGSHMSNDKEMRAAWISTVYNLDWPKTKNNEAKQKKEYTDLLDKLKSVGINTAVVQVRPKSDALYKSNINPWSEYLTGTQGKDPGYDPLPFLIEEAHKRGMEFHAWFNPYRITMADESIDKLPANHPAKKNPSWVVKHGNKYYYDPGLPEVRKYIVDSIAEVVQNYDIDGVHFDDYFYPGVSFNDTATYQKYGKGQNKDNWRRENVNTLLRDVKASIKSIKPNVVFGVSPAGIWRNKSSDPTGSDTSGNESYVGTYADTRAWIKQGLIDYVVPQLYWPIGLKAADYSKLVAWWANEVKGTNVDLYIGQGIYKQGQSSYGGQNIAKEIVQQVTLNRKYSEIKGSMYFSAKDIANSTSIQKDLKSLYSSSEEPVTPPSNVKV*

C; model_eva_score=0.188, tm_score=0.8195, gdt_score=0.7052, maxsub=0.6824.
>P1;meta_hhsuite7.pdb1
structureX:meta_hhsuite7.pdb: 222: : 281: : : : : 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------VNTLLRDVKASIKSIKPNVVFGVSPAGIWRNKSSDPTGSDTSGNESYVGTYADTRAWIKQ-------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 2
>P1;C00741
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMSNDKEMRAAWISTVYNLDWPKTKNNEAKQKKEYTDLLDKLKSVGINTAVVQVRPKSDALYKSNINPWSEYLTGTQGKDPGYDPLPFLIEEAHKRGMEFHAWFNPYRITMADESIDKLPANHPAKKNPSWVVKHGNKYYYDPGLPEVRKYIVDSIAEVVQNYDIDGVHFDDYFYPGVSFNDTATYQKYGKGQNKDNWRRENVNTLLRDVKASIKSIKPNVVFGVSPAGIWRNKSSDPTGSDTSGNESYVGTYADTRAWIKQGLIDYVVPQLYWPIGLKAADYSKLVAWWANEVKGTNVDLYIGQGIYKQGQSSYGGQNIAKEIVQQVTLNRKYSEIKGSMYFSAKDIANSTSIQKDLKSLYSSSEEPVTPPSNVKV*
