C; model_eva_score=0.194, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hhsuite8.pdb1
structureX:meta_hhsuite8.pdb: 1: : 396: : : : : 
MGSSHHHHHHSSGLVPRGSHMSNDKEMRAAWISTVYNLDWPKTKNNEAKQKKEYTDLLDKLKSVGINTAVVQVRPKSDALYKSNINPWSEYLTGTQGKDPGYDPLPFLIEEAHKRGMEFHAWFNPYRITMADESIDKLPANHPAKKNPSWVVKHGNKYYYDPGLPEVRKYIVDSIAEVVQNYDIDGVHFDDYFYPGVSFNDTATYQKYGKGQNKDNWRRENVNTLLRDVKASIKSIKPNVVFGVSPAGIWRNKSSDPTGSDTSGNESYVGTYADTRAWIKQGLIDYVVPQLYWPIGLKAADYSKLVAWWANEVKGTNVDLYIGQGIYKQGQSSYGGQNIAKEIVQQVTLNRKYSEIKGSMYFSAKDIANSTSIQKDLKSLYSSSEEPVTPPSNVKV*

C; model_eva_score=0.197, tm_score=0.8425, gdt_score=0.7052, maxsub=0.6756.
>P1;meta_hhsuite10.pdb1
structureX:meta_hhsuite10.pdb: 78: : 195: : : : : 
-----------------------------------------------------------------------------DALYKSNINPWSEYLTGTQGKDPGYDPLPFLIEEAHKRGMEFHAWFNPYRITMADESIDKLPANHPAKKNPSWVVKHGNKYYYDPGLPEVRKYIVDSIAEVVQNYDIDGVHFDDYFYP---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C; model_eva_score=0.19, tm_score=0.8082, gdt_score=0.6566, maxsub=0.6134.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 77: : 195: : : : : 
----------------------------------------------------------------------------SDALYKSNINPWSEYLTGTQGKDPGYDPLPFLIEEAHKRGMEFHAWFNPYRITMADESIDKLPANHPAKKNPSWVVKHGNKYYYDPGLPEVRKYIVDSIAEVVQNYDIDGVHFDDYFYP---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*

C;total number of template models = 3
>P1;C00741
 : : : : : : : : : 
MGSSHHHHHHSSGLVPRGSHMSNDKEMRAAWISTVYNLDWPKTKNNEAKQKKEYTDLLDKLKSVGINTAVVQVRPKSDALYKSNINPWSEYLTGTQGKDPGYDPLPFLIEEAHKRGMEFHAWFNPYRITMADESIDKLPANHPAKKNPSWVVKHGNKYYYDPGLPEVRKYIVDSIAEVVQNYDIDGVHFDDYFYPGVSFNDTATYQKYGKGQNKDNWRRENVNTLLRDVKASIKSIKPNVVFGVSPAGIWRNKSSDPTGSDTSGNESYVGTYADTRAWIKQGLIDYVVPQLYWPIGLKAADYSKLVAWWANEVKGTNVDLYIGQGIYKQGQSSYGGQNIAKEIVQQVTLNRKYSEIKGSMYFSAKDIANSTSIQKDLKSLYSSSEEPVTPPSNVKV*
