C; model_eva_score=0.614, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.617, tm_score=0.8693, gdt_score=0.8762, maxsub=0.8476.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.604, tm_score=0.8228, gdt_score=0.8271, maxsub=0.7695.
>P1;meta_hhsu6.pdb1
structureX:meta_hhsu6.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.605, tm_score=0.8483, gdt_score=0.8575, maxsub=0.8047.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.605, tm_score=0.8523, gdt_score=0.8668, maxsub=0.8153.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.603, tm_score=0.7947, gdt_score=0.8154, maxsub=0.7563.
>P1;meta_psiblast3.pdb1
structureX:meta_psiblast3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.603, tm_score=0.7947, gdt_score=0.8154, maxsub=0.7563.
>P1;meta_blast5.pdb1
structureX:meta_blast5.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.602, tm_score=0.8186, gdt_score=0.8201, maxsub=0.7623.
>P1;meta_multicom3.pdb1
structureX:meta_multicom3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.602, tm_score=0.8378, gdt_score=0.8435, maxsub=0.7985.
>P1;meta_ap1.pdb1
structureX:meta_ap1.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C;total number of template models = 9
>P1;C00051
 : : : : : : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*
