C; model_eva_score=0.611, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.617, tm_score=0.8790, gdt_score=0.8879, maxsub=0.8513.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.582, tm_score=0.7866, gdt_score=0.7921, maxsub=0.7290.
>P1;meta_hhsuite3.pdb1
structureX:meta_hhsuite3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C;total number of template models = 3
>P1;C00051
 : : : : : : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*
