C; model_eva_score=0.617, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.612, tm_score=0.8412, gdt_score=0.8481, maxsub=0.8039.
>P1;meta_ss6.pdb1
structureX:meta_ss6.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.61, tm_score=0.8471, gdt_score=0.8598, maxsub=0.8062.
>P1;meta_ss7.pdb1
structureX:meta_ss7.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.611, tm_score=0.8429, gdt_score=0.8411, maxsub=0.8133.
>P1;meta_ss9.pdb1
structureX:meta_ss9.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.607, tm_score=0.8814, gdt_score=0.8925, maxsub=0.8538.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.607, tm_score=0.8563, gdt_score=0.8645, maxsub=0.8154.
>P1;meta_blits6.pdb1
structureX:meta_blits6.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C;total number of template models = 6
>P1;C00051
 : : : : : : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*
