C; model_eva_score=0.617, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hg3.pdb1
structureX:meta_hg3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.614, tm_score=0.8693, gdt_score=0.8762, maxsub=0.8476.
>P1;meta_hh8.pdb1
structureX:meta_hh8.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.611, tm_score=0.8790, gdt_score=0.8879, maxsub=0.8513.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.605, tm_score=0.8182, gdt_score=0.8201, maxsub=0.7787.
>P1;meta_csiblast3.pdb1
structureX:meta_csiblast3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.603, tm_score=0.7908, gdt_score=0.7850, maxsub=0.7322.
>P1;meta_psiblast3.pdb1
structureX:meta_psiblast3.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.603, tm_score=0.7908, gdt_score=0.7850, maxsub=0.7322.
>P1;meta_blast5.pdb1
structureX:meta_blast5.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C; model_eva_score=0.603, tm_score=0.8164, gdt_score=0.8131, maxsub=0.7666.
>P1;meta_sam1.pdb1
structureX:meta_sam1.pdb: 1: : 107: : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*

C;total number of template models = 7
>P1;C00051
 : : : : : : : : : 
GIDPFTGAAAGVSAAGIEPDLTAIWQALFALPAVGRHQDFFALGGDSQLGLRMLAQLRERHGVDLPLRCLYEAPTVARLAETIVRLAAPAPSGDQDDASEYEEGVIR*
