C; model_eva_score=0.591, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.586, tm_score=0.8719, gdt_score=0.8652, maxsub=0.7924.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.58, tm_score=0.8888, gdt_score=0.8504, maxsub=0.7825.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C;total number of template models = 3
>P1;C00611
 : : : : : : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*
