C; model_eva_score=0.59, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.595, tm_score=0.8836, gdt_score=0.8681, maxsub=0.8191.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.59, tm_score=0.8748, gdt_score=0.8494, maxsub=0.7933.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.589, tm_score=0.8843, gdt_score=0.8396, maxsub=0.8197.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.574, tm_score=0.8263, gdt_score=0.7510, maxsub=0.7000.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.573, tm_score=0.8471, gdt_score=0.7628, maxsub=0.7441.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.565, tm_score=0.8884, gdt_score=0.8297, maxsub=0.7831.
>P1;meta_ff6.pdb1
structureX:meta_ff6.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.546, tm_score=0.9299, gdt_score=0.8287, maxsub=0.8303.
>P1;meta_ff7.pdb1
structureX:meta_ff7.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.548, tm_score=0.8875, gdt_score=0.7992, maxsub=0.7640.
>P1;meta_ff2.pdb1
structureX:meta_ff2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.544, tm_score=0.8651, gdt_score=0.7854, maxsub=0.7432.
>P1;meta_ff5.pdb1
structureX:meta_ff5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C;total number of template models = 10
>P1;C00611
 : : : : : : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*
