C; model_eva_score=0.595, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.592, tm_score=0.9135, gdt_score=0.8917, maxsub=0.8395.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.592, tm_score=0.9208, gdt_score=0.8829, maxsub=0.8494.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.59, tm_score=0.8836, gdt_score=0.8681, maxsub=0.8191.
>P1;meta_com3.pdb1
structureX:meta_com3.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.59, tm_score=0.9191, gdt_score=0.8750, maxsub=0.8421.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.59, tm_score=0.8915, gdt_score=0.8701, maxsub=0.8369.
>P1;meta_prc3.pdb1
structureX:meta_prc3.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.586, tm_score=0.9124, gdt_score=0.8839, maxsub=0.8333.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.588, tm_score=0.9141, gdt_score=0.8671, maxsub=0.8339.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.574, tm_score=0.8876, gdt_score=0.7992, maxsub=0.7715.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.573, tm_score=0.9174, gdt_score=0.8248, maxsub=0.8137.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.558, tm_score=0.9075, gdt_score=0.8169, maxsub=0.8098.
>P1;meta_ff4.pdb1
structureX:meta_ff4.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.546, tm_score=0.8652, gdt_score=0.7805, maxsub=0.7447.
>P1;meta_ff7.pdb1
structureX:meta_ff7.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.548, tm_score=0.8784, gdt_score=0.7933, maxsub=0.7606.
>P1;meta_ff2.pdb1
structureX:meta_ff2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.544, tm_score=0.8927, gdt_score=0.7982, maxsub=0.7772.
>P1;meta_ff5.pdb1
structureX:meta_ff5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.541, tm_score=0.8826, gdt_score=0.7677, maxsub=0.7425.
>P1;meta_ff10.pdb1
structureX:meta_ff10.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.542, tm_score=0.8790, gdt_score=0.7844, maxsub=0.7665.
>P1;meta_ff3.pdb1
structureX:meta_ff3.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C;total number of template models = 16
>P1;C00611
 : : : : : : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*
