C; model_eva_score=0.592, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com4.pdb1
structureX:meta_com4.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.595, tm_score=0.9135, gdt_score=0.8917, maxsub=0.8395.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.592, tm_score=0.8971, gdt_score=0.8533, maxsub=0.8211.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.59, tm_score=0.9015, gdt_score=0.8661, maxsub=0.8124.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.586, tm_score=0.9485, gdt_score=0.9104, maxsub=0.8793.
>P1;meta_com5.pdb1
structureX:meta_com5.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.588, tm_score=0.8869, gdt_score=0.8573, maxsub=0.8075.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.575, tm_score=0.8592, gdt_score=0.7844, maxsub=0.7474.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.574, tm_score=0.8855, gdt_score=0.8022, maxsub=0.7799.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.573, tm_score=0.8640, gdt_score=0.7795, maxsub=0.7508.
>P1;meta_com1.pdb1
structureX:meta_com1.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.558, tm_score=0.8642, gdt_score=0.8051, maxsub=0.7394.
>P1;meta_ff4.pdb1
structureX:meta_ff4.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.541, tm_score=0.8782, gdt_score=0.7549, maxsub=0.7344.
>P1;meta_ff10.pdb1
structureX:meta_ff10.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C; model_eva_score=0.542, tm_score=0.9209, gdt_score=0.8199, maxsub=0.8416.
>P1;meta_ff3.pdb1
structureX:meta_ff3.pdb: 1: : 254: : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*

C;total number of template models = 12
>P1;C00611
 : : : : : : : : : 
MGHHHHHHHHHHSSGLEVLFQGPSGHMRDTQRAEAVMEAEYERSEALLANMLPGSIAERLKSSSRSVIADKYDEVSVLFADIVGFTERASTTTPADLVRFLNRLYGAFDELVDKHGLEKIKVSGDSYMVVSGVPRARPDHAFALADFALDMANVAAALKDPHGDPVPLRMGMACGPVVAGVVGSRRFFYDVWGDAVNVASRMESTDSVGRIQVPEAMYERLKNEFVLQERGRIEVKGKGVMRTWYLIGRKADEE*
