C;cover size:234; local alignment length=234 (original info = e3e6jA1	219	341.83	2.9e-55	210	87	100.00)
>P1;e3e6jA1
structureX:e3e6jA1: 10: : 219: : : : : 
---------------SGTTVDCRSKRHASVPA-GIPTNAQILYLHDNQITKLEPGVFDSLINLKELYLGSNQLGALPVGVFDSLTQLTVLDLG------------------------TNQLTVLPSAVFDRLVHLKELFMCCNKLTELPR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLTHAYLFGNPWDCECRDIMYLRNWVADHTSIAMRWDGKAVNDPDSAKCAGTNTPVRAVTEASTSPSKCP*

C;cover size:230; local alignment length=230 (original info = e3rfjA1	229	299.89	4e-48	225	51	100.00)
>P1;e3rfjA1
structureX:e3rfjA1: 3: : 229: : : : : 
------------------QIIANNSDIKSVQGIQYLPNVRYLALGGNKLHDIS--ALKELTNLTYLILTGNQLQSLPNGVFDKLTNLKELVLVENQLQSLPDGVFDKLTNLTYLYLYHNQLQSLPKGVFDKLTNLTRLDLDNNQLQSLPEGVFDKLTQLKQLSLNDNQLKSVPDGVFDRLTSLTHIWLLNNPWDCACSDILYLSRWISQHPGLVF---GYLNLDPDSARCSGTNTPVRAVTEASTSPSKC-*

C;query_length:249 num_of_temps:1 cover_ratio:0.94 cover:234 not_cover:15
>P1;2017-10-14_00000086_1_71
 : : : : : : : : : 
HHHHHHGGCPSQCSCSGTTVNCKSKSLASVPA-GIPTTTRVLYLNDNQITKLEPGVFDRLVNLQTLWLNNNQLTSLPAGLFDSLTQLTILALDSNQLQALPVGVFGRLVDLQQLYLGSNQLSALPSAVFDRLVHLKELLMCCNKLTELPR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLTHAYLFGNPWDCECRDIMYLRNWVADHTSIVMRWDGKAVNDPDSAKCAGTNTPVRAVTEASTSPSKCP*
