C;cover size:234; local alignment length=234 (original info = e4k5uB1	218	336.41	2e-54	210	69	100.00)
>P1;e4k5uB1
structureX:e4k5uB1: 9: : 218: : : : : 
---------------SGTEVNCAGKSLASVPAGIPTTTRVLYLNSNQITKLEPGVFDRLANLRELHLWGNQLVSLPPGVFDNLANLEKLWLNSNQLTSLPAGLFDRLVNLEHLGLCCMKLTELPSGAFDKLTRLKQL------------------------GLDQNQLKSIPDGAFARLPSLTHVWLHTNPWDCQCTDILYLSGWVAQHSSIVG-EGWP-WRHSPDSAKCSGTNTPVRAVTEASTSPSKCP*

C;cover size:233; local alignment length=233 (original info = e3m18A1	245	334.94	2.8e-53	231	45	100.00)
>P1;e3m18A1
structureX:e3m18A1: 13: : 245: : : : : 
---------------GKKEVDCQGKSLDSVPSGIPADTEKLDLQSTGLATLSDATFRGLTKLTWLNLDYNQLQTLSAGVFDDLTELGTLGLANNQLASLPLGVFDHLTQLDKLYLGGNQLKSLPSGVFDRLTKLKELRLNTNQLQSIPAGAFDKLTNLQTLSLSTNQLQSVPHGAFDRLGKLQTITLFGNQFDCSRCETLYLSQWIRENSNKVKDGTGQNLHESPDGVTCSD-GKVVRTVTNE-TLKYEC-*

C;query_length:249 num_of_temps:1 cover_ratio:0.94 cover:234 not_cover:15
>P1;2017-10-14_00000086_1_71
 : : : : : : : : : 
HHHHHHGGCPSQCSCSGTTVNCKSKSLASVPAGIPTTTRVLYLNDNQITKLEPGVFDRLVNLQTLWLNNNQLTSLPAGLFDSLTQLTILALDSNQLQALPVGVFGRLVDLQQLYLGSNQLSALPSAVFDRLVHLKELLMCCNKLTELPR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLTHAYLFGNPWDCECRDIMYLRNWVADHTSIVMRWDGK-AVNDPDSAKCAGTNTPVRAVTEASTSPSKCP*
