C;cover size:230; local alignment length=230 (original info = e3rfjA1	229	299.89	4e-48	225	51	100.00)
>P1;e3rfjA1
structureX:e3rfjA1: 3: : 229: : : : : 
------------------QIIANNSDIKSVQGIQYLPNVRYLALGGNKLHDIS--ALKELTNLTYLILTGNQLQSLPNGVFDKLTNLKELVLVENQLQSLPDGVFDKLTNLTYLYLYHNQLQSLPKGVFDKLTNLTRLDLDNNQLQSLPEGVFDKLTQLKQLSLNDNQLKSVPDGVFDRLTSLTHIWLLNNPWDCACSDILYLSRWISQHPGLVF---GYLNLDPDSARCSGTNTPVRAVTEASTSPSKC-*

C;cover size:234; local alignment length=234 (original info = e3twiD1	168	247.73	1.7e-41	160	70	100.00)
>P1;e3twiD1
structureX:e3twiD1: 9: : 168: : : : : 
---------------SGTTVNCQERSLASVPA-GIPTTTQVLHLYINQITKLEPGVFDSLTQLTYLNLAVNQLTALPVGVFDKLTKLTHLALHINQLK------------------------------------------------------------------------SIPMGVFDNLKSLTHIYLFNNPWDCECSDILYLKNWIVQHASIVNPLG---NGGVDNVKCSGTNTPVRAVTEASTSPSKCP*

C;query_length:249 num_of_temps:1 cover_ratio:0.92 cover:230 not_cover:19
>P1;2017-10-14_00000086_1_71
 : : : : : : : : : 
HHHHHHGGCPSQCSCSGTTVNCKSKSLASVPA-GIPTTTRVLYLNDNQITKLEPGVFDRLVNLQTLWLNNNQLTSLPAGLFDSLTQLTILALDSNQLQALPVGVFGRLVDLQQLYLGSNQLSALPSAVFDRLVHLKELLMCCNKLTELPR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLTHAYLFGNPWDCECRDIMYLRNWVADHTSIVMRWDGKAVNDPDSAKCAGTNTPVRAVTEASTSPSKCP*
