C;cover size:234; local alignment length=234 (original info = e3e6jA1	219	341.83	2.9e-55	210	87	100.00)
>P1;e3e6jA1
structureX:e3e6jA1: 10: : 219: : : : : 
---------------SGTTVDCRSKRHASVPAGIPTNAQILYLHDNQITKLEPGVFDSLINLKELYLGSNQLGALPVGVFDSLTQLTVLDLG------------------------------------------------TNQLTVLPSAVFDRLVHLKELFMCCNKLTEL--PR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLT----HAYLFGNPWDCECRDIMYLRNWVADHTSIAMRWDGK-AVNDPDSAKCAGTNTPVRAVTEASTSPSKCP*

C;cover size:234; local alignment length=234 (original info = e4k5uB1	218	336.41	2e-54	210	69	100.00)
>P1;e4k5uB1
structureX:e4k5uB1: 9: : 218: : : : : 
---------------SGTEVNCAGKSLASVPAGIPTTTRVLYLNSNQITKLEPGVFDRLANLRELHLWGNQLVSLPPGVFDNLANLEKLWLNSNQLTSLP------------------------AGLFDRLVNLEHLGLCCMKLTELPSGAFDKLTRLKQL--------------------------GLDQNQLKSIPDGAFARLPSLT----HVWLHTNPWDCQCTDILYLSGWVAQHSSIVG-EGWP-WRHSPDSAKCSGTNTPVRAVTEASTSPSKCP*

C;cover size:234; local alignment length=234 (original info = e2o6qA1	270	302.73	1.9e-47	226	41	100.00)
>P1;e2o6qA1
structureX:e2o6qA1: 17: : 267: : : : : 
---------------NKNSVDCSSKKLTAIPSNIPADTKKLDLQSNKLSSLPSKAFHRLTKLRLLYLNDNKLQTLPAGIFKELKNLETLWVTDNKLQALPIGVFDQLVNLAELRLDRNQLKSLPPRVFDSLTKLTYLSLGYNELQSLPKGVFDKLTSLKELRLYNNQLKRV--PEGAFDKLTELKTLKLDNNQLKRVPEGAFDSLEKLK----MLQLQENPWDCTCNGIIYMAKWLKKKADEG--------LGGVDTAGCEKGGKAVLEITEKDAA-SDCV*

C;cover size:233; local alignment length=233 (original info = e2r9uA1	174	255.86	1.1e-42	162	77	100.00)
>P1;e2r9uA1
structureX:e2r9uA1: 13: : 174: : : : : 
---------------DQTLVNCQNIRLASVPAGIPTDKQRLWLNNNQITKLEPGVFDHLVNLQQLYFNSNKLTAIPTGVFDKLTQLTQLDLNDNHLKSIP--------------------------------------------------------------------------------------------------RGAFDNLKSLT----HIYLYNNPWDCECRDIMYLRNWVADHTSIVMRWDGK-AVNDPDSAKCAGTNTPVRAVTEASTSPSKC-*

C;cover size:177; local alignment length=177 (original info = e3t6qA2	250	233.27	5.8e-37	177	21	99.97)
>P1;e3t6qA2
structureX:e3t6qA2: 8: : 187: : : : : 
---------------VNKTYNCENLGLNEIPGTLPNSTECLEFSFNVLPTIQNTTFSRLINLTFLDLTRCQIYWIHEDTFQSQHRLDTLVLTANPLIFMA------------------------ETALSGPKALKHLFFIQTGISSIDFIPLHNQKTLESLYLGSNHISSI--KLPKGFPTEKLKVLDFQNNAIHYLSKEDMSSLQQATNL--SLNLNGNDIA----------------------------------------------------------*

C;cover size:233; local alignment length=233 (original info = e3m18A1	245	334.94	2.8e-53	231	45	100.00)
>P1;e3m18A1
structureX:e3m18A1: 13: : 245: : : : : 
---------------GKKEVDCQGKSLDSVPSGIPADTEKLDLQSTGLATLSDATFRGLTKLTWLNLDYNQLQTLSAGVFDDLTELGTLGLANNQLASLP------------------------LGVFDHLTQLDKLYLGGNQLKSLPSGVFDRLTKLKELRLNTNQLQSI--PAGAFDKLTNLQTLSLSTNQLQSVPHGAFDRLGKLQ----TITLFGNQFDCSRCETLYLSQWIRENSNKVKDGTGQNLHESPDGVTCSD-GKVVRTVTNE-TLKYEC-*

C;cover size:194; local alignment length=194 (original info = e2v9tB1	210	264.58	7.2e-43	170	31	100.00)
>P1;e2v9tB1
structureX:e2v9tB1: 12: : 181: : : : : 
---------------SNNIVDCRGKGLTEIPTNLPETITEIRLEQNTIKVIPPGAFSPYKKLRRIDLSNNQISELAPDAFQGLRSLNSLVLYGNKITELP------------------------KSLFEGLFSLQLLLLNANKINCLRVDAFQDLHNLN--------------------------LLSLYDNKLQTIAKGTFSPLRAIQ----TMHLAQNPFICDCH-LKWLADYLHTNP-----------------------------------------*

C;cover size:177; local alignment length=177 (original info = e2z64A1	264	232.50	1.5e-36	177	27	99.97)
>P1;e2z64A1
structureX:e2z64A1: 7: : 189: : : : : 
---------------PNITYQCMDQKLSKVPDDIPSSTKNIDLSFNPLKILKSYSFSNFSELQWLDLSRCEIETIEDKAWHGLHHLSNLILTGNPIQSFS------------------------PGSFSGLTSLENLVAVETKLASLESFPIGQLITLKKLNVAHNFIHSCKLPA-YFSNLTNLVHVDLSYNYIQTITVNDLQFLRENPQVNLSLDMSLNPID----------------------------------------------------------*

C;cover size:224; local alignment length=224 (original info = e2o6rA1	177	253.43	4.2e-42	167	49	100.00)
>P1;e2o6rA1
structureX:e2o6rA1: 8: : 174: : : : : 
---------------SGTEIRCNSKGLTSVPTGIPSSATRLELESNKLQSLPHGVFDKLTQLTKLSLSQNQIQSLPDGVFDKLTKLTILYL------------------------------------------------HENKLQSLPNGVFDKLTQLKELALDTNQLKSV--P------------------------DGIFDRLTSLQ----KIWLHTNPWDCSCPRIDYLSRWLNKNSQK-----------EQGSAKCSGSGKPVRSII----------*

C;query_length:249 num_of_temps:1 cover_ratio:0.94 cover:234 not_cover:15
>P1;2017-10-14_00000086_1_71
 : : : : : : : : : 
HHHHHHGGCPSQCSCSGTTVNCKSKSLASVPAGIPTTTRVLYLNDNQITKLEPGVFDRLVNLQTLWLNNNQLTSLPAGLFDSLTQLTILALDSNQLQALP------------------------VGVFGRLVDLQQLYLGSNQLSALPSAVFDRLVHLKELLMCCNKLTEL--PR-GIERLTHLTHLALDQNQLKSIPHGAFDRLSSLT----HAYLFGNPWDCECRDIMYLRNWVADHTSIVMRWDGK-AVNDPDSAKCAGTNTPVRAVTEASTSPSKCP*
