C; model_eva_score=0.777, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.78, tm_score=0.9392, gdt_score=0.9257, maxsub=0.8993.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.778, tm_score=0.9393, gdt_score=0.9127, maxsub=0.8890.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.776, tm_score=0.9190, gdt_score=0.8915, maxsub=0.8615.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.777, tm_score=0.9563, gdt_score=0.9351, maxsub=0.9187.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.771, tm_score=0.9073, gdt_score=0.8927, maxsub=0.8607.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.77, tm_score=0.9021, gdt_score=0.8785, maxsub=0.8561.
>P1;meta_hmmer5.pdb1
structureX:meta_hmmer5.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.764, tm_score=0.8933, gdt_score=0.8597, maxsub=0.8311.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.763, tm_score=0.9166, gdt_score=0.8892, maxsub=0.8600.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.759, tm_score=0.8982, gdt_score=0.8703, maxsub=0.8333.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.751, tm_score=0.8861, gdt_score=0.8538, maxsub=0.8240.
>P1;meta_ff8.pdb1
structureX:meta_ff8.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.743, tm_score=0.8860, gdt_score=0.8538, maxsub=0.8183.
>P1;meta_compro2.pdb1
structureX:meta_compro2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C;total number of template models = 12
>P1;C00681
 : : : : : : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*
