C; model_eva_score=0.778, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.777, tm_score=0.9393, gdt_score=0.9127, maxsub=0.8890.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.78, tm_score=0.9344, gdt_score=0.9222, maxsub=0.9049.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.776, tm_score=0.9126, gdt_score=0.8903, maxsub=0.8545.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.777, tm_score=0.9204, gdt_score=0.8950, maxsub=0.8721.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.769, tm_score=0.9001, gdt_score=0.8667, maxsub=0.8409.
>P1;meta_prc4.pdb1
structureX:meta_prc4.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.764, tm_score=0.9117, gdt_score=0.8809, maxsub=0.8491.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.763, tm_score=0.9264, gdt_score=0.8915, maxsub=0.8649.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.759, tm_score=0.9042, gdt_score=0.8715, maxsub=0.8340.
>P1;meta_prc5.pdb1
structureX:meta_prc5.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.751, tm_score=0.9000, gdt_score=0.8656, maxsub=0.8377.
>P1;meta_ff8.pdb1
structureX:meta_ff8.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C;total number of template models = 10
>P1;C00681
 : : : : : : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*
