C; model_eva_score=0.78, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.777, tm_score=0.9392, gdt_score=0.9257, maxsub=0.8993.
>P1;meta_com2.pdb1
structureX:meta_com2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.778, tm_score=0.9344, gdt_score=0.9222, maxsub=0.9049.
>P1;meta_hh1.pdb1
structureX:meta_hh1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.776, tm_score=0.9172, gdt_score=0.8950, maxsub=0.8581.
>P1;meta_multicom7.pdb1
structureX:meta_multicom7.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.777, tm_score=0.9325, gdt_score=0.9151, maxsub=0.9002.
>P1;meta_prc2.pdb1
structureX:meta_prc2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.772, tm_score=0.9066, gdt_score=0.8844, maxsub=0.8607.
>P1;meta_hmmer4.pdb1
structureX:meta_hmmer4.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.771, tm_score=0.9184, gdt_score=0.8998, maxsub=0.8646.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.771, tm_score=0.8992, gdt_score=0.8774, maxsub=0.8555.
>P1;meta_hmmer3.pdb1
structureX:meta_hmmer3.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.764, tm_score=0.8897, gdt_score=0.8597, maxsub=0.8340.
>P1;meta_hhsuite2.pdb1
structureX:meta_hhsuite2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.763, tm_score=0.8940, gdt_score=0.8656, maxsub=0.8369.
>P1;meta_hhsuite1.pdb1
structureX:meta_hhsuite1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.743, tm_score=0.8870, gdt_score=0.8561, maxsub=0.8254.
>P1;meta_compro2.pdb1
structureX:meta_compro2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C;total number of template models = 11
>P1;C00681
 : : : : : : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*
