C; model_eva_score=0.78, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_prc1.pdb1
structureX:meta_prc1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.774, tm_score=0.9192, gdt_score=0.9033, maxsub=0.8793.
>P1;meta_hg1.pdb1
structureX:meta_hg1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.771, tm_score=0.8898, gdt_score=0.8679, maxsub=0.8361.
>P1;meta_hg2.pdb1
structureX:meta_hg2.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.766, tm_score=0.8857, gdt_score=0.8597, maxsub=0.8342.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C; model_eva_score=0.753, tm_score=0.8977, gdt_score=0.8644, maxsub=0.8305.
>P1;meta_blits1.pdb1
structureX:meta_blits1.pdb: 1: : 212: : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*

C;total number of template models = 5
>P1;C00681
 : : : : : : : : : 
MEQQPAAAEPEVPAGLGLTAAEYAELQPTVEAYHRYAVGPGQCSSLVAQRIEAPAAAVWAIVRRFDCPQVYKHFIRSCALRPDPDAGDELRPGRLREVSVISGLPASTSTERLDLLDDARRAFGFTITGGEHRLANYRSVTTVSELAPAAPAKICTVVLESYVVDVPEGNSEEDTRLFADTVVRLNLQKLKSLAEANATSAAAQATPPPQAE*
