C; model_eva_score=0.68, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C; model_eva_score=0.667, tm_score=0.8766, gdt_score=0.8333, maxsub=0.7990.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C;total number of template models = 2
>P1;C00521
 : : : : : : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*
