C; model_eva_score=0.684, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hh2.pdb1
structureX:meta_hh2.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C; model_eva_score=0.678, tm_score=0.9299, gdt_score=0.8879, maxsub=0.8608.
>P1;meta_hh3.pdb1
structureX:meta_hh3.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C; model_eva_score=0.667, tm_score=0.9044, gdt_score=0.8581, maxsub=0.8237.
>P1;meta_hh6.pdb1
structureX:meta_hh6.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C; model_eva_score=0.667, tm_score=0.8996, gdt_score=0.8512, maxsub=0.8198.
>P1;meta_hh5.pdb1
structureX:meta_hh5.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C; model_eva_score=0.664, tm_score=0.9344, gdt_score=0.8780, maxsub=0.8623.
>P1;meta_hh4.pdb1
structureX:meta_hh4.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C; model_eva_score=0.645, tm_score=0.8973, gdt_score=0.8313, maxsub=0.7942.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 252: : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*

C;total number of template models = 6
>P1;C00521
 : : : : : : : : : 
HTRMFSVWVNGVDQGDGQNVYIRTPPNTDPIKDLASPALACNVKGGEPVPQFVSASAGDKLTFEWYRVKRGDDIIDPSHSGPITTWIAAFTSPTMDGTGPVWSKIHEEGYDASTKSWAVDKLIANKGMWDFTLPSQLKPGKYMLRQEIVAHHESDATFDKNPKRGAQFYPSCVQVDVKGVGGDAVPDQAFDFNKGYKYSDPGIAFDMYTDFDSYPIPGPPVWDAQDEGCCFIDGVDTTSVKEVVKQIICVLK*
