C;cover size:74; local alignment length=74 (original info = 1V54H	79	154.73	6.3e-27	0)
>P1;1V54H
structureX:1V54H: 3: : 79: : : :1.80: 
-------------------------------------KNYQTAPFDSRFPNQNQTRNCWQNYLDFHRCEKAMTAKGGDVSVCEWYRRVYKSLCPISWVSTWDDRRAEGTFPGKI--------------*

C;query_length:125 num_of_temps:1 cover_ratio:0.59 cover:74 not_cover:51
>P1;C0022
 : : : : : : : : : 
MGPGGPLLSPSRGFLLCKTGWHSNRLLGDCGPHTPVSTALSFIAVGMAAPSMKERQVCWGARDEYWKCLDE---NLEDASQCKKLRSSFESSCPQQWIKYFDKRRDYLKFKEKFEAGQFEPSETTAKS*
