C;cover size:0; local alignment length=0 (original info = 2Y69H 0 0 0.001694 0)
>P1;2Y69H
structureN:2Y69H: 1: : 86: : : :6.0:
MAEDIQAKIKNYQTAPFDSRFPNQN-----------------------------------------------------QTRNCWQNYLDFHRCEKAMTAKGGDVSVCEWYRRVYKSLCPISWVSTWDDRRAEGTFPGKI--------------*

C;query_length:125
>P1;C0022
 : : : : : : : : :
-------------------------MGPGGPLLSPSRGFLLCKTGWHSNRLLGDCGPHTPVSTALSFIAVGMAAPSMKERQVCWGARDEYWKCLDEN---LEDASQCKKLRSSFESSCPQQWIKYFDKRRDYLKFKEKFEAGQFEPSETTAKS*
