C;template
>P1;2DYSU
structureX:2DYSU: : : : : : : : 
-----------------------------------KIKNYQTAPFDSRFPNQNQTRNCWQNYLDFHRCEKAMTAKGGDVSVCEWYRRVYKSLCPISWVSTWDDRRAEGTFPGKI--------------*

C;query
>P1;C0022
 : : : : : : : : : 
MGPGGPLLSPSRGFLLCKTGWHSNRLLGDCGPHTPVSTALSFIAVGMAAPSMKERQVCWGARDEYWKCLDENL---EDASQCKKLRSSFESSCPQQWIKYFDKRRDYLKFKEKFEAGQFEPSETTAKS*
