C; model_eva_score=0.447, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.448, tm_score=0.8938, gdt_score=0.8159, maxsub=0.8027.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.446, tm_score=0.9549, gdt_score=0.9328, maxsub=0.9147.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.45, tm_score=0.9184, gdt_score=0.8433, maxsub=0.8595.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.444, tm_score=0.8930, gdt_score=0.8134, maxsub=0.8009.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.443, tm_score=0.8714, gdt_score=0.7811, maxsub=0.7743.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.442, tm_score=0.9546, gdt_score=0.9117, maxsub=0.9024.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.439, tm_score=0.9571, gdt_score=0.9104, maxsub=0.9137.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.44, tm_score=0.8655, gdt_score=0.7786, maxsub=0.7570.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.437, tm_score=0.8739, gdt_score=0.7724, maxsub=0.7717.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.433, tm_score=0.8183, gdt_score=0.7077, maxsub=0.6615.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.424, tm_score=0.9029, gdt_score=0.8221, maxsub=0.8072.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.414, tm_score=0.8349, gdt_score=0.7090, maxsub=0.6996.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.417, tm_score=0.8334, gdt_score=0.7152, maxsub=0.6925.
>P1;meta_muster9.pdb1
structureX:meta_muster9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.41, tm_score=0.8146, gdt_score=0.7015, maxsub=0.6591.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.391, tm_score=0.8138, gdt_score=0.7040, maxsub=0.6568.
>P1;meta_compro2.pdb1
structureX:meta_compro2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C;total number of template models = 16
>P1;C00591
 : : : : : : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*
