C; model_eva_score=0.448, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.45, tm_score=0.9580, gdt_score=0.9303, maxsub=0.9129.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.446, tm_score=0.8973, gdt_score=0.8197, maxsub=0.8092.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.447, tm_score=0.8938, gdt_score=0.8159, maxsub=0.8027.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.444, tm_score=0.9584, gdt_score=0.9391, maxsub=0.9154.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.443, tm_score=0.9316, gdt_score=0.8881, maxsub=0.8777.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.442, tm_score=0.8719, gdt_score=0.7736, maxsub=0.7554.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.439, tm_score=0.8673, gdt_score=0.7687, maxsub=0.7573.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.44, tm_score=0.9455, gdt_score=0.9092, maxsub=0.8946.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.437, tm_score=0.8846, gdt_score=0.7861, maxsub=0.7843.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.433, tm_score=0.8679, gdt_score=0.7637, maxsub=0.7450.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.424, tm_score=0.8295, gdt_score=0.7177, maxsub=0.6826.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.414, tm_score=0.8408, gdt_score=0.7226, maxsub=0.7067.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.416, tm_score=0.8667, gdt_score=0.7612, maxsub=0.7553.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.416, tm_score=0.8667, gdt_score=0.7612, maxsub=0.7553.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.417, tm_score=0.8183, gdt_score=0.7152, maxsub=0.6665.
>P1;meta_muster9.pdb1
structureX:meta_muster9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.377, tm_score=0.8070, gdt_score=0.7027, maxsub=0.6428.
>P1;meta_blits9.pdb1
structureX:meta_blits9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C;total number of template models = 17
>P1;C00591
 : : : : : : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*
