C; model_eva_score=0.446, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.448, tm_score=0.8973, gdt_score=0.8197, maxsub=0.8092.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.45, tm_score=0.9272, gdt_score=0.8607, maxsub=0.8725.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.447, tm_score=0.9549, gdt_score=0.9328, maxsub=0.9147.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.444, tm_score=0.8973, gdt_score=0.8159, maxsub=0.8118.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.443, tm_score=0.8876, gdt_score=0.8022, maxsub=0.7980.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.442, tm_score=0.9163, gdt_score=0.8346, maxsub=0.8399.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.439, tm_score=0.9353, gdt_score=0.8781, maxsub=0.8757.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.44, tm_score=0.8672, gdt_score=0.7637, maxsub=0.7555.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.437, tm_score=0.9012, gdt_score=0.8097, maxsub=0.8214.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.424, tm_score=0.8942, gdt_score=0.8221, maxsub=0.8000.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.418, tm_score=0.8338, gdt_score=0.7201, maxsub=0.7087.
>P1;meta_hhsuite4.pdb1
structureX:meta_hhsuite4.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.414, tm_score=0.8565, gdt_score=0.7351, maxsub=0.7288.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.417, tm_score=0.8247, gdt_score=0.7139, maxsub=0.6865.
>P1;meta_muster9.pdb1
structureX:meta_muster9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.41, tm_score=0.8021, gdt_score=0.7002, maxsub=0.6397.
>P1;meta_sam2.pdb1
structureX:meta_sam2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C;total number of template models = 15
>P1;C00591
 : : : : : : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*
