C; model_eva_score=0.444, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.448, tm_score=0.9584, gdt_score=0.9391, maxsub=0.9154.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.446, tm_score=0.8973, gdt_score=0.8159, maxsub=0.8118.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.447, tm_score=0.8930, gdt_score=0.8134, maxsub=0.8009.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.45, tm_score=0.9485, gdt_score=0.9216, maxsub=0.8982.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.443, tm_score=0.9355, gdt_score=0.9154, maxsub=0.8858.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.442, tm_score=0.8663, gdt_score=0.7649, maxsub=0.7419.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.439, tm_score=0.8779, gdt_score=0.7799, maxsub=0.7710.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.44, tm_score=0.9427, gdt_score=0.9167, maxsub=0.8872.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.437, tm_score=0.8963, gdt_score=0.8109, maxsub=0.8132.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.433, tm_score=0.8184, gdt_score=0.7139, maxsub=0.6591.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.424, tm_score=0.8277, gdt_score=0.7139, maxsub=0.6789.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.414, tm_score=0.8436, gdt_score=0.7326, maxsub=0.7122.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.416, tm_score=0.8534, gdt_score=0.7488, maxsub=0.7394.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.416, tm_score=0.8534, gdt_score=0.7488, maxsub=0.7394.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C;total number of template models = 15
>P1;C00591
 : : : : : : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*
