C; model_eva_score=0.45, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_hs3.pdb1
structureX:meta_hs3.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.448, tm_score=0.9580, gdt_score=0.9303, maxsub=0.9129.
>P1;meta_hs1.pdb1
structureX:meta_hs1.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.446, tm_score=0.9272, gdt_score=0.8607, maxsub=0.8725.
>P1;meta_hs6.pdb1
structureX:meta_hs6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.447, tm_score=0.9184, gdt_score=0.8433, maxsub=0.8595.
>P1;meta_hs8.pdb1
structureX:meta_hs8.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.444, tm_score=0.9485, gdt_score=0.9216, maxsub=0.8982.
>P1;meta_hs2.pdb1
structureX:meta_hs2.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.443, tm_score=0.9418, gdt_score=0.8955, maxsub=0.8941.
>P1;meta_hs5.pdb1
structureX:meta_hs5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.442, tm_score=0.8900, gdt_score=0.7948, maxsub=0.7951.
>P1;meta_hs9.pdb1
structureX:meta_hs9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.439, tm_score=0.8838, gdt_score=0.7799, maxsub=0.7906.
>P1;meta_hs10.pdb1
structureX:meta_hs10.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.44, tm_score=0.9399, gdt_score=0.8806, maxsub=0.8762.
>P1;meta_hs4.pdb1
structureX:meta_hs4.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.437, tm_score=0.9151, gdt_score=0.8259, maxsub=0.8449.
>P1;meta_hs7.pdb1
structureX:meta_hs7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.433, tm_score=0.8442, gdt_score=0.7376, maxsub=0.7120.
>P1;meta_hhsuite6.pdb1
structureX:meta_hhsuite6.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.424, tm_score=0.8514, gdt_score=0.7450, maxsub=0.7231.
>P1;meta_center0.pdb1
structureX:meta_center0.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.414, tm_score=0.8615, gdt_score=0.7575, maxsub=0.7449.
>P1;meta_hh7.pdb1
structureX:meta_hh7.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.416, tm_score=0.8359, gdt_score=0.7214, maxsub=0.7127.
>P1;meta_hg5.pdb1
structureX:meta_hg5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.416, tm_score=0.8359, gdt_score=0.7214, maxsub=0.7127.
>P1;meta_ss5.pdb1
structureX:meta_ss5.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C; model_eva_score=0.417, tm_score=0.8250, gdt_score=0.7177, maxsub=0.6792.
>P1;meta_muster9.pdb1
structureX:meta_muster9.pdb: 1: : 201: : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*

C;total number of template models = 16
>P1;C00591
 : : : : : : : : : 
RAPPQFVVRPRDQIVAQGRTVTFPCETKGNPQPAVFWQKEGSQNLLFPNQPQQPNSRCSVSPTGDLTITNIQRSDAGYYICQALTVAGSILAKAQLEVTDVLTDRPPPIILQGPAMQTLAVDGTALLKCKATGDPLPVISWLKEGFTFPGRDPRATIQEQGTLQIKNLRISDTGTYTCVATSSSGETSWSAVLDVTESGKL*
