C; model_eva_score=0.114, tm_score=1, gdt_score=1, maxsub=1.
>P1;meta_rapt4.pdb1
structureX:meta_rapt4.pdb: 1: : 122: : : : : 
QDLQATEANCTVLSVQQIGEVFECTFTCGADCRGTSQYPCVQVYVNNSESNSRALLHSDEHQLLTNPKCSYIPPCKRENQKNLESVMNWQQYWKDEIGSQPFTCYFNQHQRPDDVLLHRTHD*

C; model_eva_score=0.114, tm_score=0.7677, gdt_score=0.7480, maxsub=0.6784.
>P1;meta_rapt1.pdb1
structureX:meta_rapt1.pdb: 1: : 122: : : : : 
QDLQATEANCTVLSVQQIGEVFECTFTCGADCRGTSQYPCVQVYVNNSESNSRALLHSDEHQLLTNPKCSYIPPCKRENQKNLESVMNWQQYWKDEIGSQPFTCYFNQHQRPDDVLLHRTHD*

C; model_eva_score=0.114, tm_score=0.7084, gdt_score=0.7254, maxsub=0.6038.
>P1;meta_rapt2.pdb1
structureX:meta_rapt2.pdb: 1: : 122: : : : : 
QDLQATEANCTVLSVQQIGEVFECTFTCGADCRGTSQYPCVQVYVNNSESNSRALLHSDEHQLLTNPKCSYIPPCKRENQKNLESVMNWQQYWKDEIGSQPFTCYFNQHQRPDDVLLHRTHD*

C;total number of template models = 3
>P1;C00691
 : : : : : : : : : 
QDLQATEANCTVLSVQQIGEVFECTFTCGADCRGTSQYPCVQVYVNNSESNSRALLHSDEHQLLTNPKCSYIPPCKRENQKNLESVMNWQQYWKDEIGSQPFTCYFNQHQRPDDVLLHRTHD*
